objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sales_Office__c</fullName>
        <label>Sales Office</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>K010</fullName>
                    <label>K010-ShangHai</label>
                </value>
                <value>
                    <fullName>K020</fullName>
                    <label>K020-BeiJing</label>
                </value>
                <value>
                    <fullName>K030</fullName>
                    <label>K030-ShenZhen</label>
                </value>
                <value>
                    <fullName>K040</fullName>
                    <label>K040-GuangZhou</label>
                </value>
                <value>
                    <fullName>K050</fullName>
                    <label>K050-ChengDu</label>
                </value>
                <value>
                    <fullName>K060</fullName>
                    <isActive>false</isActive>
                    <label>K060-DaLian</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Promotion__c.object
<CustomObject>
    <fields>
        <fullName>CN_End_Date__c</fullName>
        <label>End Date(Planned End Date)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Promotion_Type__c</fullName>
        <label>Promotion Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>Bundle sells</fullName>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                </value>
                <value>
                    <fullName>Gifting</fullName>
                </value>
                <value>
                    <fullName>买满就减</fullName>
                    <isActive>false</isActive>
                    <label>买满就减</label>
                </value>
                <value>
                    <fullName>买送</fullName>
                    <isActive>false</isActive>
                    <label>买送</label>
                </value>
                <value>
                    <fullName>会员促销</fullName>
                    <isActive>false</isActive>
                    <label>会员促销</label>
                </value>
                <value>
                    <fullName>免费试吃</fullName>
                    <isActive>false</isActive>
                    <label>免费试吃</label>
                </value>
                <value>
                    <fullName>免费送</fullName>
                    <isActive>false</isActive>
                    <label>免费送</label>
                </value>
                <value>
                    <fullName>凭**换取</fullName>
                    <isActive>false</isActive>
                    <label>凭**换取</label>
                </value>
                <value>
                    <fullName>加***元多一件</fullName>
                    <isActive>false</isActive>
                    <label>加***元多一件</label>
                </value>
                <value>
                    <fullName>打折</fullName>
                    <isActive>false</isActive>
                    <label>打折</label>
                </value>
                <value>
                    <fullName>折上折</fullName>
                    <isActive>false</isActive>
                    <label>折上折</label>
                </value>
                <value>
                    <fullName>抽奖</fullName>
                    <isActive>false</isActive>
                    <label>抽奖</label>
                </value>
                <value>
                    <fullName>换购</fullName>
                    <isActive>false</isActive>
                    <label>换购</label>
                </value>
                <value>
                    <fullName>特价</fullName>
                    <isActive>false</isActive>
                    <label>特价</label>
                </value>
                <value>
                    <fullName>秒杀</fullName>
                    <isActive>false</isActive>
                    <label>秒杀</label>
                </value>
                <value>
                    <fullName>送券</fullName>
                    <isActive>false</isActive>
                    <label>送券</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sales_Office__c</fullName>
        <label>Sales Office</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>K010</fullName>
                    <label>K010-ShangHai</label>
                </value>
                <value>
                    <fullName>K020</fullName>
                    <label>K020-BeiJing</label>
                </value>
                <value>
                    <fullName>K030</fullName>
                    <label>K030-ShenZhen</label>
                </value>
                <value>
                    <fullName>K040</fullName>
                    <label>K040-GuangZhou</label>
                </value>
                <value>
                    <fullName>K050</fullName>
                    <label>K050-ChengDu</label>
                </value>
                <value>
                    <fullName>K060</fullName>
                    <label>K060-DaLian</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Start_Date__c</fullName>
        <label>Start Date(Planned Start Date)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KA</fullName>
                </value>
                <value>
                    <fullName>DS</fullName>
                </value>
                <value>
                    <fullName>WS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <label>Customer Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BAPA</fullName>
                </value>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Coffee/Tea Shop</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
                <value>
                    <fullName>Retailor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Promotion_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CN_Promotion__c</fullName>
        <label>Promotion</label>
        <referenceTo>CN_Promotion__c</referenceTo>
        <relationshipLabel>Promotion Line Items</relationshipLabel>
        <relationshipName>Promotion_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promotion Line Item</label>
    <nameField>
        <displayFormat>PLI-{0000000000}</displayFormat>
        <label>Promotion Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Promotion_Member__c.object
<CustomObject>
    <fields>
        <fullName>CN_Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>CN_Promotion__c</referenceTo>
        <relationshipLabel>Promotion Members</relationshipLabel>
        <relationshipName>Promotion_Members2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion Member</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Promotion Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Quote_To_Promotion__c.object
<CustomObject>
    <fields>
        <fullName>CN_Promotion_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promotion Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CN_Promotion_Member__c.CN_IsPublished__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CN_Promotion_Member__c</referenceTo>
        <relationshipLabel>Quote To Promotions</relationshipLabel>
        <relationshipName>Quote_To_Promotions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Quote To Promotion</label>
    <nameField>
        <displayFormat>QTP-{000000}</displayFormat>
        <label>Quote To Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote To Promotions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>CN_Pricing_Unit__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Pricing Unit</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_Unit_of_Measure__c</fullName>
        <label>UoM</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CAR</fullName>
                </value>
                <value>
                    <fullName>EA</fullName>
                </value>
                <value>
                    <fullName>KG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CN_SKU_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>CN_Pricing_Unit__c</fullName>
        <label>Pricing Unit</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_Unit_of_Measure__c</fullName>
        <label>UoM</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Talend_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Change_Request_Endpoint__c</fullName>
        <label>Change Request Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Update_Endpoint__c</fullName>
        <label>Sales Order Update Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Sanbox_Change_Request_Endpoint__c</fullName>
        <label>Sanbox Change Request Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Sanbox_Sales_Order_Update_Endpoint__c</fullName>
        <label>Sanbox Sales Order Update Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Sandbox_Password__c</fullName>
        <label>Sandbox Password</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sandbox_Send_To_Account_Endpoint__c</fullName>
        <label>Sandbox Send to Account Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Sandbox_User_Name__c</fullName>
        <label>Sandbox User Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Account_Endpoint__c</fullName>
        <label>Send to Account Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Talend Setting</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CN_Sales_Office__c</fullName>
        <label>Sales Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CN_Quote_Send_To_SAP_LC_Ctrl_Test.cls
/**************************************************************************************************
 * Name           : CN_Quote_Send_To_SAP_LC_Ctrl_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Qiu Chen
 * Create Date    : 2021-06-07
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_Quote_Send_To_SAP_LC_Ctrl_Test {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }
    @isTest
    private static void controllerTest_200() {
        TestDataFactory testDataFactory = new TestDataFactory();
        List<Account> accFactroy_List = TestDataFactory.makeFactoryAccount();
        List<Product2> productList = [Select Id,name, CN_SKU_Code__c From Product2 LIMIT 1];
        Talend_Setting__c talendSetting = new Talend_Setting__c();
        talendSetting.Change_Request_Endpoint__c = 'http://127.0.0.1/CR/400';
        talendSetting.Password__c = 'password';
        talendSetting.Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/400';
        talendSetting.Sanbox_Change_Request_Endpoint__c = 'http://127.0.0.1/CR/400';
        talendSetting.Sanbox_Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/400';
        talendSetting.Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/404';
        talendSetting.Sandbox_Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/200';
        talendSetting.Sandbox_Password__c = 'password';
        talendSetting.Sandbox_Send_To_Account_Endpoint__c = 'http://127.0.0.1/ACC/400';
        talendSetting.Sandbox_User_Name__c = 'Name';
        talendSetting.Send_to_Account_Endpoint__c = 'http://127.0.0.1/ACC/400';
        talendSetting.User_Name__c = 'Name';
        talendSetting.Quote_Endpoint__c = 'http://127.0.0.1/Quote/200?ProductCode=' + productList[0].CN_SKU_Code__c + '&IsSuccess=S';
        talendSetting.Sandbox_Quote_Endpoint__c = 'http://127.0.0.1/Quote/200?ProductCode=' + productList[0].CN_SKU_Code__c + '&IsSuccess=S';
        insert talendSetting;

        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, User> lastNameUserMap = new Map<String, User>();
        for(User usr: userList) {
            lastNameUserMap.put(usr.LastName, usr);
        }

        User cce = lastNameUserMap.get('CCE1_KA');
        User salesRep = lastNameUserMap.get('Sales1');
        Account acc_factory = [SELECT Id,Name FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];
        testDataFactory.approveAccount(acc_factory);
        Id cnQuoteRTId = Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get(Constants.CN_Quote_RT_API_NAME).getRecordTypeId();

        PricebookEntry pbEntry = [Select Id,Product2Id, CN_Pricing_Unit__c, CN_Unit_of_Measure__c From PricebookEntry Where Pricebook2Id =: Test.getStandardPricebookId() And Product2Id  =: productList[0].Id];

        CN_Promotion__c promotion = new CN_Promotion__c(
            Name = 'TestPromotion',
            CN_Start_Date__c = Date.today().addMonths(3),
            CN_End_Date__c = Date.today().addMonths(3).addDays(13),
            CN_Promotion_Type__c = 'Discount',
            Channel__c = 'KA',
            CN_Status__c = 'Planned',
            Customer_Category__c = 'BAPA',
            CN_Sales_Office__c = 'K010'
        );

        CN_Promotion_Member__c pm = new CN_Promotion_Member__c ();
        Opportunity opp = new Opportunity();
        Quote q = new Quote ();

        System.runAs(cce) {
            insert promotion;

            promotion.CN_Status__c = Constants.CN_PROMOTION_STATUS_READY;
            try {
                update promotion;
            } catch (Exception e) {}

            CN_Promotion_Line_Item__c pli = new CN_Promotion_Line_Item__c(
                CN_Promotion__c = promotion.Id,
                CN_Product__c = productList[0].Id,
                CN_Promotion_Price__c = 99.9
            );
            insert pli;

            CN_Promotion_Generate_ProMember_LC_Ctrl.generateProMember(promotion.Id);

            pm = new CN_Promotion_Member__c(
                CN_Promotion__c = promotion.Id,
                CN_Account__c = acc_factory.Id
            );
            insert pm;

            promotion.CN_Status__c = Constants.CN_PROMOTION_STATUS_READY;
            update promotion;
            CN_Promotion_Publish_LC_Ctrl.prmtPublish(promotion.Id);
        }

        System.runAs(salesRep) {

            opp = testDataFactory.makeOpp(acc_factory);
            insert opp;

            Opportunity opp_update = new Opportunity();
            opp_update.Id = opp.Id;
            opp_update.Pricebook2Id = Test.getStandardPricebookId();
            update opp_update;

            OpportunityLineItem oppItem = new OpportunityLineItem(
                OpportunityId = opp.Id,
                Product2Id  = productList[0].Id
            );
            insert oppItem;

            q = new Quote(
                Name = 'Quote Name',
                CN_Effective_Date__c = Date.Today()+1,
                ExpirationDate = Date.Today() + 7,
                OpportunityId = opp.Id,
                Pricebook2Id  = Test.getStandardPricebookId()
            );
            insert q;
        }

        CN_Quote_To_Promotion__c quoteToPromo = new CN_Quote_To_Promotion__c(
            CN_Quote__c = q.Id,
            CN_Promotion_Member__c = pm.Id
        );
        insert quoteToPromo;

        QuoteLineItem quoteItem = new QuoteLineItem(
            QuoteId = q.Id,
            Product2Id = productList[0].Id,
            Quantity = 2,
            UnitPrice = 12,
            PricebookEntryId = pbEntry.Id
        );
        insert quoteItem;

        q.Status = 'Approved';
        update q;

        quoteItem.CN_Customer_Acceptance__c = 'Accepted';
        quoteItem.CN_Finance_Acceptance__c = 'Accepted';
        update quoteItem;

        CN_Quote_Send_To_SAP_LC_Ctrl.getQuoteInfoAndCheckEditPermisison(q.Id);
        Test.startTest();
        Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
        

        CN_Quote_Send_To_SAP_LC_Ctrl.sendQuote(q.Id);

        try {
            CN_Quote_Send_To_SAP_LC_Ctrl.getQuoteInfoAndCheckEditPermisison('');
        } catch (Exception e) {
            
        }
        try {
            CN_Quote_Send_To_SAP_LC_Ctrl.getQuoteInfoAndCheckEditPermisison('001000000000000');
        } catch (Exception e) {
            
        }
        try {
            CN_Quote_Send_To_SAP_LC_Ctrl.sendQuote('');
        } catch (Exception e) {
            
        }
        try {
            CN_Quote_Send_To_SAP_LC_Ctrl.sendQuote('001000000000000');
        } catch (Exception e) {
            
        }
        Test.stopTest();
    }

    @isTest
    private static void controllerTest_200_Failed() {
        TestDataFactory testDataFactory = new TestDataFactory();
        List<Account> accFactroy_List = TestDataFactory.makeFactoryAccount();
        List<Product2> productList = [Select Id,name, CN_SKU_Code__c From Product2 LIMIT 1];
        Talend_Setting__c talendSetting = new Talend_Setting__c();
        talendSetting.Change_Request_Endpoint__c = 'http://127.0.0.1/CR/400';
        talendSetting.Password__c = 'password';
        talendSetting.Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/400';
        talendSetting.Sanbox_Change_Request_Endpoint__c = 'http://127.0.0.1/CR/400';
        talendSetting.Sanbox_Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/400';
        talendSetting.Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/404';
        talendSetting.Sandbox_Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/200';
        talendSetting.Sandbox_Password__c = 'password';
        talendSetting.Sandbox_Send_To_Account_Endpoint__c = 'http://127.0.0.1/ACC/400';
        talendSetting.Sandbox_User_Name__c = 'Name';
        talendSetting.Send_to_Account_Endpoint__c = 'http://127.0.0.1/ACC/400';
        talendSetting.User_Name__c = 'Name';
        talendSetting.Quote_Endpoint__c = 'http://127.0.0.1/Quote/200?ProductCode=' + productList[0].CN_SKU_Code__c + '&IsSuccess=E';
        talendSetting.Sandbox_Quote_Endpoint__c = 'http://127.0.0.1/Quote/200?ProductCode=' + productList[0].CN_SKU_Code__c + '&IsSuccess=E';
        insert talendSetting;

        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, User> lastNameUserMap = new Map<String, User>();
        for(User usr: userList) {
            lastNameUserMap.put(usr.LastName, usr);
        }

        User cce = lastNameUserMap.get('CCE1_KA');
        User salesRep = lastNameUserMap.get('Sales1');
        Account acc_factory = [SELECT Id,Name FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];
        testDataFactory.approveAccount(acc_factory);
        Id cnQuoteRTId = Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get(Constants.CN_Quote_RT_API_NAME).getRecordTypeId();

        PricebookEntry pbEntry = [Select Id,Product2Id, CN_Pricing_Unit__c, CN_Unit_of_Measure__c From PricebookEntry Where Pricebook2Id =: Test.getStandardPricebookId() And Product2Id  =: productList[0].Id];

        CN_Promotion__c promotion = new CN_Promotion__c(
            Name = 'TestPromotion',
            CN_Start_Date__c = Date.today().addMonths(3),
            CN_End_Date__c = Date.today().addMonths(3).addDays(13),
            CN_Promotion_Type__c = 'Discount',
            Channel__c = 'KA',
            CN_Status__c = 'Planned',
            Customer_Category__c = 'BAPA',
            CN_Sales_Office__c = 'K010'
        );

        CN_Promotion_Member__c pm = new CN_Promotion_Member__c ();
        Opportunity opp = new Opportunity();
        Quote q = new Quote ();

        System.runAs(cce) {
            insert promotion;

            promotion.CN_Status__c = Constants.CN_PROMOTION_STATUS_READY;
            try {
                update promotion;
            } catch (Exception e) {}

            CN_Promotion_Line_Item__c pli = new CN_Promotion_Line_Item__c(
                CN_Promotion__c = promotion.Id,
                CN_Product__c = productList[0].Id,
                CN_Promotion_Price__c = 99.9
            );
            insert pli;

            CN_Promotion_Generate_ProMember_LC_Ctrl.generateProMember(promotion.Id);

            pm = new CN_Promotion_Member__c(
                CN_Promotion__c = promotion.Id,
                CN_Account__c = acc_factory.Id
            );
            insert pm;

            promotion.CN_Status__c = Constants.CN_PROMOTION_STATUS_READY;
            update promotion;
            CN_Promotion_Publish_LC_Ctrl.prmtPublish(promotion.Id);
        }

        System.runAs(salesRep) {

            opp = testDataFactory.makeOpp(acc_factory);
            insert opp;

            Opportunity opp_update = new Opportunity();
            opp_update.Id = opp.Id;
            opp_update.Pricebook2Id = Test.getStandardPricebookId();
            update opp_update;

            OpportunityLineItem oppItem = new OpportunityLineItem(
                OpportunityId = opp.Id,
                Product2Id  = productList[0].Id
            );
            insert oppItem;

            q = new Quote(
                Name = 'Quote Name',
                CN_Effective_Date__c = Date.Today()+1,
                ExpirationDate = Date.Today() + 7,
                OpportunityId = opp.Id,
                Pricebook2Id  = Test.getStandardPricebookId()
            );
            insert q;
        }

        CN_Quote_To_Promotion__c quoteToPromo = new CN_Quote_To_Promotion__c(
            CN_Quote__c = q.Id,
            CN_Promotion_Member__c = pm.Id
        );
        insert quoteToPromo;

        QuoteLineItem quoteItem = new QuoteLineItem(
            QuoteId = q.Id,
            Product2Id = productList[0].Id,
            Quantity = 2,
            UnitPrice = 12,
            PricebookEntryId = pbEntry.Id
        );
        insert quoteItem;

        q.Status = 'Approved';
        update q;

        quoteItem.CN_Customer_Acceptance__c = 'Accepted';
        quoteItem.CN_Finance_Acceptance__c = 'Accepted';
        update quoteItem;

        CN_Quote_Send_To_SAP_LC_Ctrl.getQuoteInfoAndCheckEditPermisison(q.Id);
        Test.startTest();
        Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
        

        CN_Quote_Send_To_SAP_LC_Ctrl.sendQuote(q.Id);

        try {
            CN_Quote_Send_To_SAP_LC_Ctrl.getQuoteInfoAndCheckEditPermisison('');
        } catch (Exception e) {
            
        }
        try {
            CN_Quote_Send_To_SAP_LC_Ctrl.getQuoteInfoAndCheckEditPermisison('001000000000000');
        } catch (Exception e) {
            
        }
        try {
            CN_Quote_Send_To_SAP_LC_Ctrl.sendQuote('');
        } catch (Exception e) {
            
        }
        try {
            CN_Quote_Send_To_SAP_LC_Ctrl.sendQuote('001000000000000');
        } catch (Exception e) {
            
        }
        Test.stopTest();
    }
}