objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Billing_Block__c</fullName>
        <label>Billing Block</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>01    Calculation Missing</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>02    Compl Confirm Missng</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>03    Prices Incomplete</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>04    Check Terms of Paymt</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>05    Check Terms of Dlv</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>08    Check Credit Memo</label>
                </value>
                <value>
                    <fullName>09</fullName>
                    <label>09    Check Debit Memo</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10-YH Rejected by Customer</label>
                </value>
                <value>
                    <fullName>S0</fullName>
                    <label>S0-Overdue Payment</label>
                </value>
                <value>
                    <fullName>S1</fullName>
                    <label>S1-Credit Limit</label>
                </value>
                <value>
                    <fullName>S2</fullName>
                    <label>S2-Food License Lack</label>
                </value>
                <value>
                    <fullName>S3</fullName>
                    <label>S3-Addr. certif. Lack</label>
                </value>
                <value>
                    <fullName>S4</fullName>
                    <label>S4-Others License Lack</label>
                </value>
                <value>
                    <fullName>S5</fullName>
                    <label>S5-Missing Order</label>
                </value>
                <value>
                    <fullName>S6</fullName>
                    <label>S6-Obsolete</label>
                </value>
                <value>
                    <fullName>S7</fullName>
                    <label>S7-Inactive SF</label>
                </value>
                <value>
                    <fullName>S8</fullName>
                    <label>S8-Legal Case</label>
                </value>
                <value>
                    <fullName>YH</fullName>
                    <isActive>false</isActive>
                    <label>YH Rejected by Customer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Block_Sales_Support__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Block Sales Support</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Delivery_Block__c</fullName>
        <label>Delivery Block</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>01 Credit limit</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>02 Waitting confirm</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>03 Bottleneck material</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>04 Export papers missng</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>05 Check free of ch.dlv</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>06 No printing</label>
                </value>
                <value>
                    <fullName>07</fullName>
                    <label>07 Change in quantity</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>08 Kanban Delivery</label>
                </value>
                <value>
                    <fullName>09</fullName>
                    <label>09 JIT delivery (PDS)</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10 Not achieve MOQ</label>
                </value>
                <value>
                    <fullName>S0</fullName>
                    <label>S0-Overdue Payment</label>
                </value>
                <value>
                    <fullName>S1</fullName>
                    <label>S1-Credit Limit</label>
                </value>
                <value>
                    <fullName>S2</fullName>
                    <label>S2-Food License Lack</label>
                </value>
                <value>
                    <fullName>S3</fullName>
                    <label>S3-Addr. certif. Lack</label>
                </value>
                <value>
                    <fullName>S4</fullName>
                    <label>S4-Others License Lack</label>
                </value>
                <value>
                    <fullName>S5</fullName>
                    <label>S5-Missing Order</label>
                </value>
                <value>
                    <fullName>S6</fullName>
                    <label>S6-Obsolete</label>
                </value>
                <value>
                    <fullName>S7</fullName>
                    <label>S7-Inactive SF</label>
                </value>
                <value>
                    <fullName>S8</fullName>
                    <label>S8-Legal Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Order_Block__c</fullName>
        <label>Order Block</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>01    Overall block</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>02    All free of charge</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>03    Test block</label>
                </value>
                <value>
                    <fullName>99</fullName>
                    <label>99    test (e)</label>
                </value>
                <value>
                    <fullName>S0</fullName>
                    <label>S0-Overdue Payment</label>
                </value>
                <value>
                    <fullName>S1</fullName>
                    <label>S1-Credit Limit</label>
                </value>
                <value>
                    <fullName>S2</fullName>
                    <label>S2-Food License Lack</label>
                </value>
                <value>
                    <fullName>S3</fullName>
                    <label>S3-Addr. certif. Lack</label>
                </value>
                <value>
                    <fullName>S4</fullName>
                    <label>S4-Others License Lack</label>
                </value>
                <value>
                    <fullName>S5</fullName>
                    <label>S5-Missing Order</label>
                </value>
                <value>
                    <fullName>S6</fullName>
                    <label>S6-Obsolete</label>
                </value>
                <value>
                    <fullName>S7</fullName>
                    <label>S7-Inactive SF</label>
                </value>
                <value>
                    <fullName>S8</fullName>
                    <label>S8-Legal Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_API_Call_Logger__c.object
<CustomObject>
    <description>API Call Log</description>
    <label>API Call Logger</label>
    <nameField>
        <displayFormat>INF-{YYYYMMDD}{0000}</displayFormat>
        <label>API Call Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Call Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Talend_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Talend Setting</label>
</CustomObject>

classes/CN_Account_Inactive_To_Mg_Callout.cls
/*
 * ************************************************************************************************
 * Name : CN_Account_Inactive_To_Mg_Callout
 * Object :
 * Requirement :AC-018
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2023/4/7
 * Modify History :
 * ************************************************************************************************
 */
public class CN_Account_Inactive_To_Mg_Callout {

	public static Map<String,Account> upsertInactiveToMg(List<Account> accounts,List<CN_API_Call_Logger__c> listLog){

		//handleDataList
		List<Map<String, Object>> maps = handleData(accounts);

		//Necessary parameters for assembly request
		Talend_Setting__c setting = Talend_Setting__c.getInstance();
		Http http = new Http();
		HttpRequest request = CN_HelperClass_WS.createHttpRequestHelper(
				setting.Sandbox_MG_Update_Company_Status__c,
				setting.MG_Update_Company_Status__c);

		Map<String,Account> sendSuccessMap = new Map<String,Account>();
		for(Map<String,Object> param:maps){
			CN_HelperClass_WS.WS_Log log = new CN_HelperClass_WS.WS_Log();
			try{
				String body = JSON.serialize(param);
				log.SetRequest(body);
				System.debug(body);
				request.setBody(body);
				HttpResponse response = http.send(request);

				log.SetResponse(response.getBody());
				System.debug(response.getBody());

				// Parse the JSON response
				Integer resCode = response.getStatusCode();
				String errorMsg = '';
				String errorMessage = '';
				if(resCode == 200) {
					System.debug(response.getBody());
					Integer  code = CN_HelperClass_WS.getRetDataCode(response.getBody());
					if(code == 1) {
						Account account = new Account();
						account.Id = String.valueOf(param.get('MAP_ID'));
						sendSuccessMap.put(account.Id, account);
					}
				}else if(resCode == 503) {
					System.debug(resCode + ':' + Json.serialize(response.getBody()));
				}else {
					if(resCode == 500) {
						errorMessage = 'Server Error';
					} else if(resCode == 404) {
						errorMessage = 'API Path Error';
					}
					errorMsg = resCode + ':' + errorMessage + ':' +  Json.serialize(response.getBody());
				}
				System.debug(errorMsg);
				log.SetResult(resCode, Json.serialize(response.getBody()), errorMessage);
				listLog.add(log.getLog());
			}catch (Exception e){
				log.SetResult(0, '', e.getMessage());
				listLog.add(log.getLog());
			}

		}

		return sendSuccessMap;
	}

	private static List<Map<String, Object>> handleData(List<Account> accounts) {
		List<Map<String,Object>> maps = new List<Map<String,Object>>();
		for(Account account : accounts){
			Map<String,Object> mapItem= new Map<String,Object>();
			mapItem.put('MAP_ID',account.Id);
			mapItem.put('account_id',account.CN_MG_Account_ID__c);
			mapItem.put('inactive',account.CN_Inactive__c?'1':'0');
			mapItem.put('billing_block',account.CN_Billing_Block__c);
			mapItem.put('delivery_block',account.CN_Delivery_Block__c);
			mapItem.put('order_block',account.CN_Order_Block__c);
			mapItem.put('block_sales_support',account.CN_Block_Sales_Support__c);
			mapItem.put('closed',account.CN_Closed__c);
			maps.add(mapItem);
		}
		return maps;
	}
}