objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Chef_Request__c.object
<CustomObject>
    <fields>
        <fullName>CN_Application_Type_Selling__c</fullName>
        <inlineHelpText>e.g. mousse cake, cream cake, tiramisu</inlineHelpText>
        <label>Application Type Selling</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Competitor_Brands__c</fullName>
        <inlineHelpText>What competitor brands customer is buying?</inlineHelpText>
        <label>Competitor Brands</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Cost_Limit__c</fullName>
        <inlineHelpText>e.g. drink cost 20%, dessert cost 30%</inlineHelpText>
        <label>Cost Limit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Demo_End_Date__c</fullName>
        <label>Demo End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Demo_Start_Date__c</fullName>
        <label>Demo Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Event_Location__c</fullName>
        <label>Event Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SH Chef Studio</fullName>
                </value>
                <value>
                    <fullName>SH R&amp;D Center</fullName>
                </value>
                <value>
                    <fullName>BJ Chef Studio</fullName>
                </value>
                <value>
                    <fullName>SZ Chef Studio</fullName>
                </value>
                <value>
                    <fullName>The Third Party</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Event_Theme__c</fullName>
        <label>Event Theme</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Key_Products_to_Push__c</fullName>
        <inlineHelpText>Please input SKUs or brands.</inlineHelpText>
        <label>Key Products to Push</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CN_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.StageName</field>
                <operation>equals</operation>
                <value>Proposal/Demo/Sample, Quote/Negotiation, Closed Won</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Chef Requests</relationshipLabel>
        <relationshipName>Chef_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Price_Positioning__c</fullName>
        <inlineHelpText>e.g. Average price of one drink is 32 RMB, average price of a cake is 48 RMB.</inlineHelpText>
        <label>Price Positioning(Customer price)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Chef Request</label>
    <nameField>
        <displayFormat>CDR-{0000000000}</displayFormat>
        <label>Chef Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chef Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Chefs_Assigned__c.object
<CustomObject>
    <fields>
        <fullName>CN_Chef_Request__c</fullName>
        <label>Chef Request</label>
        <referenceTo>CN_Chef_Request__c</referenceTo>
        <relationshipLabel>Chefs Assigneds</relationshipLabel>
        <relationshipName>Chefs_Assigneds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Chef_Role__c</fullName>
        <label>Chef Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Leading Chef</fullName>
                </value>
                <value>
                    <fullName>Supporting Chef</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Chef_Work_End_Date__c</fullName>
        <label>Chef Work End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Chef_Work_Start_Date__c</fullName>
        <label>Chef Work Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Chef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chef</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>CN Chef,CN Chef Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Chefs_Assigneds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Confirmed__c</fullName>
        <formula>CN_Chef_Request__r.CN_Confirmed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Event_Location__c</fullName>
        <formula>TEXT(CN_Chef_Request__r.CN_Event_Location__c)</formula>
        <label>Event Location</label>
        <type>Text</type>
    </fields>
    <label>Chefs Assigned</label>
    <nameField>
        <displayFormat>CA-{0000000000}</displayFormat>
        <label>Chefs Assigned ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chefs Assigneds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Chef_Req_Assign_Approver_Handler_Test.cls
/**************************************************************************************************
 * Name           : CN_Chef_Request_Assign_Approver_Handler_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Qiu Chen
 * Create Date    : 2021-06-07
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_Chef_Req_Assign_Approver_Handler_Test {

    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }

    @isTest
    private static void handleBeforeInsertTest() {
        TestDataFactory testFactory = new TestDataFactory();
        List<Account> accListFactory = testFactory.makeFactoryAccount();
        List<User> userList = [SELECT Id, LastName FROM User WHERE lastName in ('Sales1', 'Sales3', 'ChefManager', 'Chef')];
        Map<String, User> lastNameUserMap = new Map<String, User>();
        for(User usr: userList) {
            lastNameUserMap.put(usr.LastName, usr);
        }
        User salesRep = lastNameUserMap.get('Sales1');
        User salesRep3 = lastNameUserMap.get('Sales3');
        User chefManager = lastNameUserMap.get('ChefManager');
        User chef = lastNameUserMap.get('Chef');
        Account acc_factory = [SELECT Id,Name FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];
        Id chef1on1RTId = Schema.SObjectType.CN_Chef_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CHEF_REQUEST_1ON1_NEW_RT_API_NAME).getRecordTypeId();
        
        CN_Chef_Request__c cr = new CN_Chef_Request__c(
            CN_Event_Location__c = 'SH Chef Studio',
            CN_Event_Theme__c = 'Test Chef Request',
            CN_Demo_Start_Date__c = Date.today().addMonths(3),
            CN_Demo_End_Date__c = Date.today().addMonths(3).addDays(13),
            CN_Price_Positioning__c = '1',
            CN_Cost_Limit__c = '1',
            CN_Competitor_Brands__c = '1',
            CN_Application_Type_Selling__c = '1',
            CN_Key_Products_to_Push__c = '1',
            RecordTypeId = chef1on1RTId
        );

        System.runAs(salesRep) {
            Opportunity opp = testFactory.makeOpp(acc_factory);
            insert opp;

            cr.CN_Opportunity__c = opp.Id;
            insert cr;

            CN_Chef_Request__c crUpdate = new CN_Chef_Request__c(
                Id = cr.Id,
                ownerId = salesRep3.Id,
                CN_Status__c = Constants.CN_CHEF_REQUEST_STATUS_READY_FOR_APPROVAL
            );
            update crUpdate;
            
        }
        System.runAs(salesRep3) {
            CN_Chef_Request__c crUpdate = new CN_Chef_Request__c(
                Id = cr.Id,
                CN_Status__c = Constants.CN_CHEF_REQUEST_STATUS_APPROVALED
            );
            update crUpdate;
        }
        System.runAs(chefManager) {
            CN_Chefs_Assigned__c ca = new CN_Chefs_Assigned__c(
                CN_Chef_Request__c = cr.Id,
                CN_Chef__c = chef.Id,
                CN_Chef_Role__c	= 'Leading Chef',
                CN_Chef_Work_Start_Date__c = Date.today().addMonths(3),
                CN_Chef_Work_End_Date__c = Date.today().addMonths(3).addDays(13)
            );
            insert ca;

            CN_Chef_Request__c crUpdate = new CN_Chef_Request__c(
                Id = cr.Id,
                CN_Confirmed__c = true
            );
            update crUpdate;
            
            try {
                delete ca;
            } catch (Exception e) {
                
            }

            crUpdate.CN_Confirmed__c = false;
            update crUpdate;
        }
        System.runAs(salesRep3) {
            CN_Chef_Request__c crUpdate = new CN_Chef_Request__c(
                Id = cr.Id
            );
            try {
                delete crUpdate;
            } catch (Exception e) {
                
            }
        }
    }
}