objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Billing_Contact_Name_CN_First_Name__c</fullName>
        <label>Billing Contact Name(CN)-First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Billing_Contact_Name_CN_Last_Name__c</fullName>
        <label>Billing Contact Name(CN)-Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Billing_Contact_Name_EN__c</fullName>
        <label>Billing Contact Name(EN)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Billing_Department_of_Contact_Person__c</fullName>
        <label>Billing Department of Contact Person</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0001</fullName>
                    <label>0001-Purchasing Dept</label>
                </value>
                <value>
                    <fullName>0002</fullName>
                    <label>0002-Sales Dept</label>
                </value>
                <value>
                    <fullName>0003</fullName>
                    <label>0003-Administration Dept</label>
                </value>
                <value>
                    <fullName>0004</fullName>
                    <label>0004-Production Dept</label>
                </value>
                <value>
                    <fullName>0005</fullName>
                    <label>0005-QA Dept</label>
                </value>
                <value>
                    <fullName>0006</fullName>
                    <label>0006-Secretary&apos;s Office</label>
                </value>
                <value>
                    <fullName>0007</fullName>
                    <label>0007-Financial Dept</label>
                </value>
                <value>
                    <fullName>0008</fullName>
                    <label>0008-Legal Dept</label>
                </value>
                <value>
                    <fullName>0009</fullName>
                    <label>0009-Human Resources Dept</label>
                </value>
                <value>
                    <fullName>0010</fullName>
                    <label>0010-General Affairs Dept</label>
                </value>
                <value>
                    <fullName>0011</fullName>
                    <label>0011-Sales Promotion Dept</label>
                </value>
                <value>
                    <fullName>0012</fullName>
                    <label>0012-International Dept</label>
                </value>
                <value>
                    <fullName>0013</fullName>
                    <label>0013-Export Dept</label>
                </value>
                <value>
                    <fullName>0014</fullName>
                    <label>0014-Import Dept</label>
                </value>
                <value>
                    <fullName>0015</fullName>
                    <label>0015-Public Relation Dept</label>
                </value>
                <value>
                    <fullName>0016</fullName>
                    <label>0016-Advertising Dept</label>
                </value>
                <value>
                    <fullName>0017</fullName>
                    <label>0017-Planning Dept</label>
                </value>
                <value>
                    <fullName>0018</fullName>
                    <label>0018-R&amp;D Dept</label>
                </value>
                <value>
                    <fullName>0019</fullName>
                    <label>0019-Product Dev. Dept</label>
                </value>
                <value>
                    <fullName>0020</fullName>
                    <label>0020-Food &amp; Beverage Dept</label>
                </value>
                <value>
                    <fullName>0021</fullName>
                    <label>0021-Service Dept</label>
                </value>
                <value>
                    <fullName>0022</fullName>
                    <label>0022-Technical Support</label>
                </value>
                <value>
                    <fullName>0023</fullName>
                    <label>0023-IT Dept</label>
                </value>
                <value>
                    <fullName>0024</fullName>
                    <label>0024-Logistics Dept</label>
                </value>
                <value>
                    <fullName>0025</fullName>
                    <label>0025-Cold Kitchen</label>
                </value>
                <value>
                    <fullName>0026</fullName>
                    <label>0026-Hot Kitchen</label>
                </value>
                <value>
                    <fullName>0027</fullName>
                    <label>0027-Banquet Kitchen</label>
                </value>
                <value>
                    <fullName>0028</fullName>
                    <label>0028-Pastry</label>
                </value>
                <value>
                    <fullName>0029</fullName>
                    <label>0029-Backery</label>
                </value>
                <value>
                    <fullName>0030</fullName>
                    <label>0030-Bar</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Billing_Email__c</fullName>
        <label>Billing Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CN_Billing_Mobile_Phone__c</fullName>
        <inlineHelpText>Please enter the number in the format of 1XXXXXXXXXX or XXX-XXXXXXXX (X is number).</inlineHelpText>
        <label>Billing Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CN_Billing_Phone_Number__c</fullName>
        <inlineHelpText>Please enter the number in the format of 1XXXXXXXXXX or XXX-XXXXXXXX (X is number).</inlineHelpText>
        <label>Billing Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CN_Contact_Name_EN__c</fullName>
        <label>Contact Name(EN)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Purchasing_Contact_Name_CN_First_Name__c</fullName>
        <label>Purchasing Contact Name(CN)-First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Purchasing_Contact_Name_CN_Last_Name__c</fullName>
        <label>Purchasing Contact Name(CN)-Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Purchasing_Contact_Name_EN__c</fullName>
        <label>Purchasing Contact Name(EN)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Purchasing_Department_of_Contact__c</fullName>
        <label>Purchasing Department of Contact Person</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0001</fullName>
                    <label>0001-Purchasing Dept</label>
                </value>
                <value>
                    <fullName>0002</fullName>
                    <label>0002-Sales Dept</label>
                </value>
                <value>
                    <fullName>0003</fullName>
                    <label>0003-Administration Dept</label>
                </value>
                <value>
                    <fullName>0004</fullName>
                    <label>0004-Production Dept</label>
                </value>
                <value>
                    <fullName>0005</fullName>
                    <label>0005-QA Dept</label>
                </value>
                <value>
                    <fullName>0006</fullName>
                    <label>0006-Secretary&apos;s Office</label>
                </value>
                <value>
                    <fullName>0007</fullName>
                    <label>0007-Financial Dept</label>
                </value>
                <value>
                    <fullName>0008</fullName>
                    <label>0008-Legal Dept</label>
                </value>
                <value>
                    <fullName>0009</fullName>
                    <label>0009-Human Resources Dept</label>
                </value>
                <value>
                    <fullName>0010</fullName>
                    <label>0010-General Affairs Dept</label>
                </value>
                <value>
                    <fullName>0011</fullName>
                    <label>0011-Sales Promotion Dept</label>
                </value>
                <value>
                    <fullName>0012</fullName>
                    <label>0012-International Dept</label>
                </value>
                <value>
                    <fullName>0013</fullName>
                    <label>0013-Export Dept</label>
                </value>
                <value>
                    <fullName>0014</fullName>
                    <label>0014-Import Dept</label>
                </value>
                <value>
                    <fullName>0015</fullName>
                    <label>0015-Public Relation Dept</label>
                </value>
                <value>
                    <fullName>0016</fullName>
                    <label>0016-Advertising Dept</label>
                </value>
                <value>
                    <fullName>0017</fullName>
                    <label>0017-Planning Dept</label>
                </value>
                <value>
                    <fullName>0018</fullName>
                    <label>0018-R&amp;D Dept</label>
                </value>
                <value>
                    <fullName>0019</fullName>
                    <label>0019-Product Dev. Dept</label>
                </value>
                <value>
                    <fullName>0020</fullName>
                    <label>0020-Food &amp; Beverage Dept</label>
                </value>
                <value>
                    <fullName>0021</fullName>
                    <label>0021-Service Dept</label>
                </value>
                <value>
                    <fullName>0022</fullName>
                    <label>0022-Technical Support</label>
                </value>
                <value>
                    <fullName>0023</fullName>
                    <label>0023-IT Dept</label>
                </value>
                <value>
                    <fullName>0024</fullName>
                    <label>0024-Logistics Dept</label>
                </value>
                <value>
                    <fullName>0025</fullName>
                    <label>0025-Cold Kitchen</label>
                </value>
                <value>
                    <fullName>0026</fullName>
                    <label>0026-Hot Kitchen</label>
                </value>
                <value>
                    <fullName>0027</fullName>
                    <label>0027-Banquet Kitchen</label>
                </value>
                <value>
                    <fullName>0028</fullName>
                    <label>0028-Pastry</label>
                </value>
                <value>
                    <fullName>0029</fullName>
                    <label>0029-Backery</label>
                </value>
                <value>
                    <fullName>0030</fullName>
                    <label>0030-Bar</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Purchasing_Email__c</fullName>
        <label>Purchasing Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CN_Purchasing_Mobile_Phone__c</fullName>
        <inlineHelpText>Please enter the number in the format of 1XXXXXXXXXX or XXX-XXXXXXXX (X is number).</inlineHelpText>
        <label>Purchasing Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CN_Purchasing_Phone_Number__c</fullName>
        <inlineHelpText>Please enter the number in the format of 1XXXXXXXXXX or XXX-XXXXXXXX (X is number).</inlineHelpText>
        <label>Purchasing Phone Number</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CN_Contact_Name_EN__c</fullName>
        <label>Contact Name(EN)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Account_Generate_Contact_Handler.cls
/**************************************************************************************************
 * Name           : CN_Account_Generate_Contact_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Qiu Chen
 * Create Date    : 2021-04-29
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_Account_Generate_Contact_Handler implements Triggers.Handler {
   public void handle() {
        //if(Trigger.isAfter && Trigger.isInsert) {
        //    handleAfterInsert();
        //}            
    }
/*     public void handleAfterInsert() {
        List<Contact> conList = new List<Contact>();
        Id newDirectRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.CN_Account_RT_API_NAME_NEW_DIRECT).getRecordTypeId();
        Id newInDirectRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.CN_Account_RT_API_NAME_NEW_INDIRECT).getRecordTypeId();
        List<Account> directAccList = new List<Account>();
        List<Account> inDirectAccList = new List<Account>();
        for(Account acc : (List<Account>)Trigger.New) {
            if(acc.RecordTypeId == newDirectRTId) {
                directAccList.add(acc);
            } else if(acc.RecordTypeId == newInDirectRTId) {
                inDirectAccList.add(acc);
            }
        }
        if(directAccList.size() > 0) {
        	List<Contact> directConList = new List<Contact>();
            directConList = generateContactsForDirectAccount(directAccList);
            if(directConList.size() > 0) {
				conList.addAll(directConList);
            }
        }
        if(inDirectAccList.size() > 0) {
        	List<Contact> inDirectConList = new List<Contact>();
            inDirectConList = generateContactsForInDirectAccount(inDirectAccList);
            if(inDirectConList.size() > 0) {
				conList.addAll(inDirectConList);
            }
        }
        if(conList.size() > 0) {
            insert conList;
        }
    }
    
    public List<Contact> generateContactsForDirectAccount(List<Account> accList) {
        List<Contact> conList = new List<Contact>();
        for(Account acc : accList) {
            if(acc.CN_Billing_Contact_Name_CN_First_Name__c == acc.CN_Purchasing_Contact_Name_CN_First_Name__c
              	&& acc.CN_Billing_Contact_Name_CN_Last_Name__c == acc.CN_Purchasing_Contact_Name_CN_Last_Name__c
                && acc.CN_Billing_Contact_Name_EN__c == acc.CN_Purchasing_Contact_Name_EN__c
                && acc.CN_Billing_Department_of_Contact_Person__c == acc.CN_Purchasing_Department_of_Contact__c
                && acc.CN_Billing_Mobile_Phone__c == acc.CN_Purchasing_Mobile_Phone__c
                && acc.CN_Billing_Email__c == acc.CN_Purchasing_Email__c
                && acc.CN_Billing_Phone_Number__c == acc.CN_Purchasing_Phone_Number__c) {
                	Contact con = new Contact(
                    	AccountId = acc.Id,
                        FirstName = acc.CN_Billing_Contact_Name_CN_First_Name__c,
                        LastName = acc.CN_Billing_Contact_Name_CN_Last_Name__c,
                        CN_Contact_Name_EN__c = acc.CN_Billing_Contact_Name_EN__c,
                        CN_Department_Of_Contact_Person__c = acc.CN_Billing_Department_of_Contact_Person__c,
                        CN_Contact_Type__c = '01;02',
                        Phone = acc.CN_Billing_Phone_Number__c,
                        MobilePhone = acc.CN_Billing_Mobile_Phone__c
                    );
                    conList.add(con);
                } else {
                	Contact billingCon = new Contact(
                    	AccountId = acc.Id,
                        FirstName = acc.CN_Billing_Contact_Name_CN_First_Name__c,
                        LastName = acc.CN_Billing_Contact_Name_CN_Last_Name__c,
                        CN_Contact_Name_EN__c = acc.CN_Billing_Contact_Name_EN__c,
                        CN_Department_Of_Contact_Person__c = acc.CN_Billing_Department_of_Contact_Person__c,
                        CN_Contact_Type__c = '01',
                        Phone = acc.CN_Billing_Phone_Number__c,
                        MobilePhone = acc.CN_Billing_Mobile_Phone__c,
                        Email = acc.CN_Billing_Email__c
                    );
                    conList.add(billingCon);
                	Contact purchasingCon = new Contact(
                    	AccountId = acc.Id,
                        FirstName = acc.CN_Purchasing_Contact_Name_CN_First_Name__c,
                        LastName = acc.CN_Purchasing_Contact_Name_CN_Last_Name__c,
                        CN_Contact_Name_EN__c = acc.CN_Purchasing_Contact_Name_EN__c,
                        CN_Department_Of_Contact_Person__c = acc.CN_Purchasing_Department_of_Contact__c,
                        CN_Contact_Type__c = '02',
                        Phone = acc.CN_Purchasing_Phone_Number__c,
                        MobilePhone = acc.CN_Purchasing_Mobile_Phone__c,
                        Email = acc.CN_Purchasing_Email__c
                    );
                    conList.add(purchasingCon);
                }
        }
        return conList;
    }
    public List<Contact> generateContactsForInDirectAccount(List<Account> accList) {
        List<Contact> conList = new List<Contact>();
		for(Account acc : accList) {
            Contact con = new Contact(
                AccountId = acc.Id,
                FirstName = acc.CN_Contact_Name_CN_First_Name__c,
                LastName = acc.CN_Contact_Name_CN_Last_Name__c,
                CN_Contact_Name_EN__c = acc.CN_Contact_Name_EN__c,
                CN_Department_Of_Contact_Person__c = acc.CN_Department_of_Contact_Person__c,
                CN_Contact_Type__c = '04',
                Phone = acc.CN_Contact_Phone_Number__c,
                MobilePhone = acc.CN_Contact_Mobile_Phone__c
            );
            conList.add(con);
        }
        return conList;
    }*/
}