objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Sales_Performance__c.object
<CustomObject>
    <fields>
        <fullName>CN_Customer_Owner__c</fullName>
        <formula>CN_Customer__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Performance</relationshipLabel>
        <relationshipName>Sales_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Is_Customer_Owner_Changed__c</fullName>
        <formula>AND(CN_Customer__r.OwnerId !=  OwnerId, RecordType.DeveloperName = &apos;CN_Sales_Performance&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Customer Owner Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Material_SAP__c</fullName>
        <description>MATNR</description>
        <label>Material</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Performance</label>
    <nameField>
        <displayFormat>SP-{000000000}</displayFormat>
        <label>Sales Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Performance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CN_SKU_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CN_SalesPerfor_Populate_Owner_Batch_Test.cls
/**************************************************************************************************
 * Name           : CN_SalesPerfor_Populate_Owner_Batch_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Kealsalas Qiu
 * Create Date    : 2021-10-12
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_SalesPerfor_Populate_Owner_Batch_Test {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }

    @isTest
    private static void CN_SalesPerfor_Populate_Owner_Batch_Test() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();

        Account acc_factory = [SELECT Id FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];

        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }

        Id SalesPerforRTId = Schema.SObjectType.CN_Sales_Performance__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_SP_RT_API_NAME_PERFORMANCE).getRecordTypeId();
        List<Product2> SKUList = [SELECT Id, Name, CN_SKU_Code__c FROM Product2];

        Test.startTest();

        CN_Sales_Performance__c sp = new CN_Sales_Performance__c(
            CN_Material_SAP__c = SKUList[0].CN_SKU_Code__c,
            RecordTypeId = SalesPerforRTId,
            CN_Customer__c = acc_factory.Id
        );
        insert sp;
        
        acc_factory.ownerId = lastNameUserIdMap.get('Sales2');
        update acc_factory;

        CN_Sales_Performance__c sp1 = [Select Id,CN_Is_Customer_Owner_Changed__c,CN_Customer_Owner__c,Owner.Name, CN_Customer__r.Owner.Name,RecordType.DeveloperName From CN_Sales_Performance__c];
        System.debug(sp1.Owner.Name);
        System.debug(sp1.CN_Customer__r.Owner.Name);
        System.debug(sp1.RecordType.DeveloperName);
        System.debug(sp1.CN_Is_Customer_Owner_Changed__c);
        CN_SalesPerfor_Populate_Owner_SCH sch = new CN_SalesPerfor_Populate_Owner_SCH();
        System.schedule('CN_SalesPerfor_Populate_Owner_SCH' + Datetime.now(), '20 30 8 10 2 ?', sch);

        Test.stopTest();
    }
}