objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Numbers_of_Ship_to_Party__c</fullName>
        <label>Numbers of Ship-to Party</label>
        <summaryFilterItems>
            <field>CN_Ship_to_Party__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Ship to Party</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CN_Ship_to_Party__c.CN_Contact_Name__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CN_Ship_to_Party__c.CN_Telephone__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CN_Ship_to_Party__c.CN_Mobile_Phone__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CN_Ship_to_Party__c.CN_Customer_Name__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>CN_Ship_to_Party__c.CN_Sold_To_Party_Customer__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CN_Upload_Bank_Information_FaPiao_No__c</fullName>
        <label>Upload Bank Information/FaPiao No.</label>
        <summaryFilterItems>
            <field>CN_Document__c.CN_Document_Type__c</field>
            <operation>equals</operation>
            <value>Fapiao Information</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CN_Document__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CN Document</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CN_Document__c.CN_Is_File_Upload__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>CN_Document__c.CN_Account__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CN_Upload_Business_License_No__c</fullName>
        <label>Upload Business License No.</label>
        <summaryFilterItems>
            <field>CN_Document__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CN Document</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CN_Document__c.CN_Document_Type__c</field>
            <operation>equals</operation>
            <value>Business License</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CN_Document__c.CN_Is_File_Upload__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>CN_Document__c.CN_Account__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CN_Upload_Contract_No__c</fullName>
        <label>Upload Contract No.</label>
        <summaryFilterItems>
            <field>CN_Document__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CN Document</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CN_Document__c.CN_Document_Type__c</field>
            <operation>equals</operation>
            <value>Contract</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CN_Document__c.CN_Is_File_Upload__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>CN_Document__c.CN_Account__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CN_Upload_Hygiene_Certificate_No__c</fullName>
        <label>Upload Hygiene Certificate No.</label>
        <summaryFilterItems>
            <field>CN_Document__c.CN_Document_Type__c</field>
            <operation>equals</operation>
            <value>Hygiene Certificate</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CN_Document__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CN Document</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CN_Document__c.CN_Is_File_Upload__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>CN_Document__c.CN_Account__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Account_Prevent_Edit_Field__mdt.object
<CustomObject>
    <description>This metadata to store the fields of account that is allowed to edit while the account has been approved.</description>
    <fields>
        <fullName>Allow_Edit_Profile__c</fullName>
        <description>The Profiles allowed to edit the field;
Input with &quot;Profile A;ProfileB&quot;</description>
        <label>Allow Edit Profile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CN Account Prevent Edit Field</label>
    <pluralLabel>CN Account Prevent Edit Fields</pluralLabel>
</CustomObject>

classes/CN_Account_Prevent_Edit_Approved_Handler.cls
/**************************************************************************************************
 * Name           : CN_Account_Prevent_Edit_Approved_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Du Dezheng
 * Create Date    : 2021-11-30
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_Account_Prevent_Edit_Approved_Handler implements Triggers.Handler {
    public void handle() {
        if(Trigger.isBefore && Trigger.isUpdate) {
            handleBeforeUpdate();
        }
    }

    public void handleBeforeUpdate() {
        Map<String, Schema.SObjectField> mfields = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap();
        List<CN_Account_Prevent_Edit_Field__mdt> accFieldsMDTList =  CN_Account_Prevent_Edit_Field__mdt.getAll().values();
        
        Map<String,String> fieldNameProfileNameMap = new Map<String,String>();
        Set<String> allFields = new Set<String>();
        Set<String> allowedEditFields = new Set<String>();
        
        
        for(String fieldName: mfields.keySet()) {
            Schema.DescribeFieldResult fResult = mfields.get(fieldName).getDescribe();
            if(fResult.isCustom() && fResult.isUpdateable()) {
                allFields.add(fieldName);
            }
            /*
            if(fResult.isCustom() && !fResult.isCalculated() && fResult.isUpdateable()) {
                allFields.add(fieldName);
            }
			*/
        }
        allFields.add('cn_upload_bank_information_fapiao_no__c');
        allFields.add('cn_upload_business_license_no__c');
        allFields.add('cn_upload_contract_no__c');
        allFields.add('cn_upload_hygiene_certificate_no__c');
        allFields.add('cn_numbers_of_ship_to_party__c');
        allFields.add('name');
        allFields.add('ownerid');
        allFields.add('recordtypeid');
        allFields.add('description');
        
        for(CN_Account_Prevent_Edit_Field__mdt accFieldsMDT : accFieldsMDTList){
            //这里不填的话一定是空吗
            
            
            if(accFieldsMDT.Allow_Edit_Profile__c==null){
                allowedEditFields.add(accFieldsMDT.Field_Name__c.toLowerCase()); //如果有profile的不加到任何条件都通过的里面，需要进一步判断profile是否符合
            }else{
                fieldNameProfileNameMap.put(accFieldsMDT.Field_Name__c.toLowerCase(), accFieldsMDT.Allow_Edit_Profile__c);
            }
        }
        //有没有要加进去的标准字段
       
		system.debug('allowedEditFields:	'+ allowedEditFields);
        for(Account acc: (List<Account>)Trigger.new) {
            Account oldAcc = (Account)Trigger.oldMap.get(acc.Id);
            if(Constants.CN_ACCOUNT_ACCOUNT_STATUS_APPROVED.equals(acc.CN_Account_Status__c) && Constants.CN_ACCOUNT_ACCOUNT_STATUS_APPROVED.equals(oldAcc.CN_Account_Status__c)) {
                if(checkFieldsChanged(allFields,allowedEditFields, acc, oldAcc,fieldNameProfileNameMap)) {
                    acc.addError(System.Label.CN_Account_Prevent_Edit_Approved_MSG);
                }
            } 
        }

    }

    public Boolean checkFieldsChanged(Set<String> fields,Set<String> allowedEditFields, Account newAcc, Account oldAcc,Map<String,String> fieldNameProfileNameMap) {
        Boolean isChanged = true;
        
        List<Profile> profileList = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
        String myProflieName = profileList[0].Name;
        
        for(String field: fields) {
            if(newAcc.get(field) != oldAcc.get(field)) {
                if(allowedEditFields.contains(field)){
                    system.debug('field:    ' + field);
                    isChanged = false;
                	break;
                }else if(fieldNameProfileNameMap.get(field)!=null && (fieldNameProfileNameMap.get(field).contains(myProflieName) || myProflieName.equals(Constants.CN_PROFILE_NAME_INTEGRATION))){
                    system.debug('field(myProflieName):    ' + field);
                    isChanged = false;
                	break;
                }
            }
        }
        return isChanged;
    }
}