objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Business_Unit__c</fullName>
        <formula>CN_Business_Unit_UI__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_City_Code__c</fullName>
        <formula>CN_City_CN__r.CN_City_Code__c</formula>
        <label>City Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sales_Team__c</fullName>
        <formula>CN_Sales_Team_UI__r.CN_Sales_Team_Code__c</formula>
        <label>Sales Team</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>CN_Complaint</fullName>
        <active>true</active>
        <businessProcess>CN_Support_Process</businessProcess>
        <label>CN_Complaint</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Business_Unit__c.object
<CustomObject>
    <fields>
        <fullName>CN_Business_Unit_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Business Unit Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_City__c.object
<CustomObject>
    <fields>
        <fullName>CN_City_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>City Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Province__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province</label>
        <referenceTo>CN_Province__c</referenceTo>
        <relationshipLabel>Citys (Province)</relationshipLabel>
        <relationshipName>Citys1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Citys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Province__c.object
<CustomObject>
    <fields>
        <fullName>Province_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Province Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Province</label>
    <nameField>
        <label>Province Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provinces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>CN_Sold_To_Account_Name__c</fullName>
        <label>Sold-To Party</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Order</relationshipLabel>
        <relationshipName>Sales_Order</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Up_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Sales Order Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Sales_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>CN_Order_Number__c</fullName>
        <label>Sales Order Number</label>
        <referenceTo>CN_Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Item</relationshipLabel>
        <relationshipName>Sales_Order_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Up_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Item Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Order Item</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Sales Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Sales_Team__c.object
<CustomObject>
    <fields>
        <fullName>CN_Business_Unit_Code__c</fullName>
        <formula>CN_Business_Unit__r.CN_Business_Unit_Code__c</formula>
        <label>Business Unit Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Business_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Unit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The business unit you choose must have business unit Code.</errorMessage>
            <filterItems>
                <field>CN_Business_Unit__c.CN_Business_Unit_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_Business_Unit__c</referenceTo>
        <relationshipLabel>Sales Teams</relationshipLabel>
        <relationshipName>Sales_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Sales_Team_Code__c</fullName>
        <externalId>true</externalId>
        <label>Sales Team Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <label>Sales Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CN_Sales_Team__c</fullName>
        <label>Sales Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CN_Complaint_Resolved_LC_Ctrl_Test.cls
@isTest
public class CN_Complaint_Resolved_LC_Ctrl_Test {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }

    @isTest
    private static void updateStatusToResolved() {
        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }
        
        Id complaintRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CN_Complaint').getRecordTypeId();
        User salesRep = New User(Id = lastNameUserIdMap.get('Sales1'));
        User QA = New User(Id = lastNameUserIdMap.get('QA'));
        User CS = New User(Id = lastNameUserIdMap.get('CS'));
        User FQ = New User(Id = lastNameUserIdMap.get('Food Quality'));
        User FinanceAR = New User(Id = lastNameUserIdMap.get('FinanceAR'));
        Id caseRtId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(Constants.CN_RECORD_TYPE_Non_Product).getRecordTypeId();

        CN_Province__c province = [SELECT Id FROM CN_Province__c WHERE Province_Code__c = '010'][0];
        CN_City__c city = [SELECT Id FROM CN_City__c WHERE CN_City_Code__c = '010'][0];
        CN_Business_Unit__c businessUnit = [SELECT Id FROM CN_Business_Unit__c WHERE CN_Business_Unit_Code__c = '0000900001'][0];
        CN_Sales_Team__c salesTeam = [SELECT Id FROM CN_Sales_Team__c WHERE CN_Sales_Team_Code__c = '0000901001'][0];
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();
        System.runAs(salesRep) {
            Account acc = [select Id from Account limit 1];
       

            CN_Sales_Order__c  order = new CN_Sales_Order__c();
            order.CN_Sold_To_Account_Name__c = acc.Id;
            order.CN_Up_Code__c = '0000' + 1;
            insert order;

            List<CN_Sales_Order_Item__c> orderItemList = new List<CN_Sales_Order_Item__c>();
            CN_Sales_Order_Item__c orderItem1 = new CN_Sales_Order_Item__c();
            orderItem1.CN_Order_Number__c = order.Id;
            orderItem1.CN_Up_Code__c = '0000' + 1 + '1';
            orderItemList.add(orderItem1);

            CN_Sales_Order_Item__c orderItem2 = new CN_Sales_Order_Item__c();
            orderItem2.CN_Order_Number__c = order.Id;
            orderItem2.CN_Up_Code__c = '0000' + 1 + '2';
            orderItemList.add(orderItem2);
        
            insert orderItemList;
        }
        System.runAs(CS) {
            Case casetest3 = new Case();
            casetest3.CN_MG_Case_Id__c = '3';
            casetest3.Status = 'New';
            Account account = [select Id from Account limit 1];
            casetest3.AccountId = account.Id;
            insert casetest3;

            Case casetest8 = new Case();
            casetest8.CN_MG_Case_Id__c = '8';
            casetest8.Status = 'New';
            insert casetest8;

            Case casetest1 = new Case();
            casetest1.CN_MG_Case_Id__c = '1';
            casetest1.Status = 'New';
            casetest1.CN_Need_Send_MG_Flag__c = 1;
          
            casetest1.CN_Actual_Return_Consistent_Status__c = true;
            casetest1.CN_CS_Feedback__c = 'test';
            insert casetest1;

            Case casetest2 = new Case();
            casetest2.CN_MG_Case_Id__c = '2';
            casetest2.Status = 'Accepted';
            casetest2.CN_Need_Send_MG_Flag__c = 1;
            casetest2.CN_Actual_Return_Consistent_Status__c = true;
            casetest2.CN_CS_Feedback__c = 'test';
            casetest2.CN_Submitter__c = CS.Id;
            casetest2.Origin = 'E-Commerce';
            insert casetest2;
            
            
        }

        Test.startTest();
        try{
            System.runAs(QA){
            CN_Complaint_Resolved_LC_Ctrl.updateStatusToResolved('','1111','','123123');
            }
        }catch(Exception e){}
        try{
            List<Case> cases = [select Id,CaseNumber,CN_MG_Case_Id__c,Status,CN_Actual_Return_Consistent_Status__c,CN_CS_Feedback__c from Case WHERE CN_MG_Case_Id__c = '2'];

            System.runAs(QA){
            CN_Complaint_Resolved_LC_Ctrl.updateStatusToResolved(cases[0].Id,'1111','','123123');
            }
        }catch(Exception e){}

        try{
        System.runAs(CS) {
            List<Case> cases = [select Id,CaseNumber,CN_MG_Case_Id__c,Status,CN_Actual_Return_Consistent_Status__c,CN_CS_Feedback__c from Case WHERE CN_MG_Case_Id__c = '1'];
            cases[0].CN_Submitter__c = CS.Id;
            cases[0].Status = 'Accepted';
            update(cases[0]);
            
            CN_Complaint_Resolved_LC_Ctrl.getInitInfo(cases[0].Id);
            CN_Complaint_Resolved_LC_Ctrl.updateStatusToResolved(cases[0].Id,'1111','Supply Chain','123123');
        }}catch(Exception e){}
        try{System.runAs(QA) {
            List<Case> cases = [select Id,CaseNumber,CN_MG_Case_Id__c,Status,CN_Actual_Return_Consistent_Status__c,CN_CS_Feedback__c from Case WHERE CN_MG_Case_Id__c = '2'];
            
            CN_Complaint_Resolved_LC_Ctrl.getInitInfo(cases[0].Id);
            CN_Complaint_Resolved_LC_Ctrl.updateStatusToResolved(cases[0].Id,'1111','Brand Quality','123123');
        }}catch(Exception e){}

        try{
            System.runAs(CS){
            List<Case> cases = [select Id,CaseNumber,CN_MG_Case_Id__c,Status,CN_Actual_Return_Consistent_Status__c,CN_CS_Feedback__c from Case WHERE CN_MG_Case_Id__c = '2'];
            CN_Complaint_Resolved_LC_Ctrl.updateStatusToResolved(cases[0].Id,'1111','','123123');
            }
        }catch(Exception e){}

        try{
            System.runAs(CS) {
                List<Case> cases = [select Id,CaseNumber,CN_MG_Case_Id__c,Status,CN_Actual_Return_Consistent_Status__c,CN_CS_Feedback__c from Case WHERE CN_MG_Case_Id__c = '8'];
                CN_Complaint_Resolved_LC_Ctrl.updateStatusToResolved(cases[0].Id,'Return','Brand Quality','Return');
                cases[0].Status = 'Accepted';
                update(cases[0]);
                cases[0].CN_Submitter__c = null;
                update(cases[0]);

                CN_Complaint_Resolved_LC_Ctrl.getInitInfo(cases[0].Id);
                CN_Complaint_Resolved_LC_Ctrl.updateStatusToResolved(cases[0].Id,'Return','Brand Quality','Return');
        }}catch(Exception e){}

        Test.stopTest();
    }
}