objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>2 OR (1 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.CN_Group_Name__c</field>
                <operation>equals</operation>
                <valueField>CN_Brand__c.CN_Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>CN_Brand__c.CN_Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CN_Brand__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CN_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>GOURMET &amp; GROCERY</fullName>
                </value>
                <value>
                    <fullName>PASTRY</fullName>
                </value>
                <value>
                    <fullName>Chef Studio Pastry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Chef_Request__c.object
<CustomObject>
    <fields>
        <fullName>CN_Application_Type_Selling__c</fullName>
        <inlineHelpText>e.g. mousse cake, cream cake, tiramisu</inlineHelpText>
        <label>Application Type Selling</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Competitor_Brands__c</fullName>
        <inlineHelpText>What competitor brands customer is buying?</inlineHelpText>
        <label>Competitor Brands</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Cost_Limit__c</fullName>
        <inlineHelpText>e.g. drink cost 20%, dessert cost 30%</inlineHelpText>
        <label>Cost Limit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Demo_End_Date__c</fullName>
        <label>Demo End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Demo_Start_Date__c</fullName>
        <label>Demo Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Event_Location__c</fullName>
        <label>Event Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SH Chef Studio</fullName>
                </value>
                <value>
                    <fullName>SH R&amp;D Center</fullName>
                </value>
                <value>
                    <fullName>BJ Chef Studio</fullName>
                </value>
                <value>
                    <fullName>SZ Chef Studio</fullName>
                </value>
                <value>
                    <fullName>The Third Party</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Event_Theme__c</fullName>
        <label>Event Theme</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Key_Products_to_Push__c</fullName>
        <inlineHelpText>Please input SKUs or brands.</inlineHelpText>
        <label>Key Products to Push</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CN_MKT_CCE_PIC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MKT/CCE PIC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Chef_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.StageName</field>
                <operation>equals</operation>
                <value>Proposal/Demo/Sample, Quote/Negotiation, Closed Won</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Chef Requests</relationshipLabel>
        <relationshipName>Chef_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Price_Positioning__c</fullName>
        <inlineHelpText>e.g. Average price of one drink is 32 RMB, average price of a cake is 48 RMB.</inlineHelpText>
        <label>Price Positioning(Customer price)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>GOURMET &amp; GROCERY</fullName>
                </value>
                <value>
                    <fullName>PASTRY</fullName>
                </value>
                <value>
                    <fullName>Chef Studio Pastry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Chef Request</label>
    <nameField>
        <displayFormat>CDR-{0000000000}</displayFormat>
        <label>Chef Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chef Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Chefs_Assigned__c.object
<CustomObject>
    <fields>
        <fullName>CN_Chef_Request__c</fullName>
        <label>Chef Request</label>
        <referenceTo>CN_Chef_Request__c</referenceTo>
        <relationshipLabel>Chefs Assigneds</relationshipLabel>
        <relationshipName>Chefs_Assigneds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Chef_Role__c</fullName>
        <label>Chef Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Leading Chef</fullName>
                </value>
                <value>
                    <fullName>Supporting Chef</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Chef_Work_End_Date__c</fullName>
        <label>Chef Work End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Chef_Work_Start_Date__c</fullName>
        <label>Chef Work Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Chef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chef</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>CN Chef,CN Chef Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Chefs_Assigneds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Confirmed__c</fullName>
        <formula>CN_Chef_Request__r.CN_Confirmed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Event_Location__c</fullName>
        <formula>TEXT(CN_Chef_Request__r.CN_Event_Location__c)</formula>
        <label>Event Location</label>
        <type>Text</type>
    </fields>
    <label>Chefs Assigned</label>
    <nameField>
        <displayFormat>CA-{0000000000}</displayFormat>
        <label>Chefs Assigned ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chefs Assigneds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Demo_Report__c.object
<CustomObject>
    <fields>
        <fullName>CN_Chef_Request__c</fullName>
        <label>Chef Request</label>
        <referenceTo>CN_Chef_Request__c</referenceTo>
        <relationshipLabel>Demo Reports</relationshipLabel>
        <relationshipName>Demo_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>CN_Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_Event_Theme__c</fullName>
        <formula>CN_Chef_Request__r.CN_Event_Theme__c</formula>
        <label>Event Theme</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Number_of_People__c</fullName>
        <label>Number of People</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_Number_of_Recipes__c</fullName>
        <label>Number of Recipes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_SAP_Concur_Travel_Cost__c</fullName>
        <label>SAP Concur Travel Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Sales_Attendance__c</fullName>
        <label>Sales Attendance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Demo Report</label>
    <nameField>
        <displayFormat>DR-{0000000000}</displayFormat>
        <label>Demo Report Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Demo_Used_Product__c.object
<CustomObject>
    <fields>
        <fullName>CN_Demo_Report__c</fullName>
        <label>Demo Report</label>
        <referenceTo>CN_Demo_Report__c</referenceTo>
        <relationshipLabel>Demo Used Products</relationshipLabel>
        <relationshipName>Demo_Used_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Demo Used Products</relationshipLabel>
        <relationshipName>Demo_Used_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Demo Used Product</label>
    <nameField>
        <displayFormat>DRP-{0000000000}</displayFormat>
        <label>Demo Used Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Used Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Demo_Report_Copy_Handler_Test.cls
/**************************************************************************************************
 * Name           : CN_Demo_Report_Copy_Handler_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Qiu Chen
 * Create Date    : 2021-10-11
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_Demo_Report_Copy_Handler_Test {

    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }

    @isTest
    private static void handleDemoReportForAccountTest() {
        TestDataFactory testFactory = new TestDataFactory();
        List<Account> accListFactory = testFactory.makeFactoryAccount();
        List<User> userList = [SELECT Id, LastName FROM User WHERE lastName in ('Sales1', 'Sales3', 'ChefManager', 'Chef')];
        Map<String, User> lastNameUserMap = new Map<String, User>();
        for(User usr: userList) {
            lastNameUserMap.put(usr.LastName, usr);
        }
        User salesRep = lastNameUserMap.get('Sales1');
        User chefManager = lastNameUserMap.get('ChefManager');
        User chef = lastNameUserMap.get('Chef');

        List<Product2> SKUList = [SELECT Id, Name FROM Product2];

        Account acc_factory = [SELECT Id,Name FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];
        Id chef1on1RTId = Schema.SObjectType.CN_Chef_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CHEF_REQUEST_1ON1_NEW_RT_API_NAME).getRecordTypeId();
        CN_Chef_Request__c cr = new CN_Chef_Request__c(
            CN_Event_Location__c = 'SH Chef Studio',
            CN_Event_Theme__c = 'Test Chef Request',
            CN_Demo_Start_Date__c = Date.today().addMonths(3),
            CN_Demo_End_Date__c = Date.today().addMonths(3).addDays(13),
            CN_Price_Positioning__c = '1',
            CN_Cost_Limit__c = '1',
            CN_Competitor_Brands__c = '1',
            CN_Application_Type_Selling__c = '1',
            CN_Key_Products_to_Push__c = '1',
            RecordTypeId = chef1on1RTId
        );
        Test.startTest();
        System.runAs(salesRep) {
            Opportunity opp = testFactory.makeOpp(acc_factory);
            insert opp;

            cr.CN_Opportunity__c = opp.Id;
            insert cr;

            CN_Chef_Request__c crUpdate = new CN_Chef_Request__c(
                Id = cr.Id,
                CN_Status__c = Constants.CN_CHEF_REQUEST_STATUS_APPROVALED
            );
            update crUpdate;
        }
        System.runAs(chefManager) {
            CN_Chefs_Assigned__c ca = new CN_Chefs_Assigned__c(
                CN_Chef_Request__c = cr.Id,
                CN_Chef__c = chef.Id,
                CN_Chef_Role__c	= 'Leading Chef',
                CN_Chef_Work_Start_Date__c = Date.today().addMonths(3),
                CN_Chef_Work_End_Date__c = Date.today().addMonths(3).addDays(13)
            );
            insert ca;

            CN_Chef_Request__c crUpdate = new CN_Chef_Request__c(
                Id = cr.Id,
                CN_Confirmed__c = true
            );
            update crUpdate;
        }

        System.runAs(chef) {
            CN_Demo_Report__c dr = new CN_Demo_Report__c(
                CN_Chef_Request__c = cr.Id,
                CN_Number_of_People__c = 10,
                CN_Sales_Attendance__c = 'Yes',
                CN_Number_of_Recipes__c = 99.99,
                CN_Comments__c = 'Test',
                CN_SAP_Concur_Travel_Cost__c = 9.9
            );
            insert dr;

            CN_Demo_Used_Product__c dup = new CN_Demo_Used_Product__c(
                CN_Demo_Report__c = dr.Id,
                CN_Product__c = SKUList[0].Id
            );
            insert dup;

            dup.CN_Product__c = SKUList[1].Id;
            update dup;

            CN_Demo_Used_Product__c dup1 = new CN_Demo_Used_Product__c(
                CN_Demo_Report__c = dr.Id,
                CN_Product__c = SKUList[0].Id
            );
            insert dup1;
            
            delete dr;
        }
        Test.stopTest();
    }

    @isTest
    private static void handleDemoReportForCampaignTest() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeCustomSetting();
        List<User> userList = [SELECT Id, LastName FROM User WHERE lastName in ('Sales1', 'Sales3', 'ChefManager', 'Chef', 'CCE1_KA')];
        Map<String, User> lastNameUserMap = new Map<String, User>();
        for(User usr: userList) {
            lastNameUserMap.put(usr.LastName, usr);
        }
        User salesRep = lastNameUserMap.get('Sales1');
        User chefManager = lastNameUserMap.get('ChefManager');
        User chef = lastNameUserMap.get('Chef');
        User cce = lastNameUserMap.get('CCE1_KA');

        Id demoRTId = Schema.SObjectType.CN_Chef_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CHEF_REQUEST_RT_NAME_MKT_DEMO).getRecordTypeId();
        Id mktDevRTId = Schema.SObjectType.CN_Chef_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CHEF_REQUEST_RT_NAME_MKT_DEV).getRecordTypeId();
        CN_Chef_Request__c cr = new CN_Chef_Request__c(
            CN_MKT_CCE_PIC__c = cce.Id,
            CN_Product_Category__c = 'Dairy',
            CN_Brand__c = '5J',
            CN_Key_Products_to_Push__c = 'Test',
            CN_Event_Type__c = 'Public Demo',
            CN_Event_Theme__c = 'CN_Event_Theme__c',
            CN_Event_Location__c = 'SH Chef Studio',
            CN_Demo_Start_Date__c = Date.today().addMonths(3),
            CN_Demo_End_Date__c = Date.today().addMonths(3).addDays(13),
            CN_Event_Location_Start_Date__c = Date.today().addMonths(3),
            CN_Event_Location_Start_Date_AM_PM__c = 'AM',
            CN_Event_Location_End_Date__c = Date.today().addMonths(3).addDays(13),
            CN_Event_Location_End_Date_AM_PM__c = 'PM',
            RecordTypeId = demoRTId
        );
        Test.startTest();
        System.runAs(cce) {
            Campaign cam = testFactory.makeCampaign();
            insert cam;

            cr.CN_Campaign__c = cam.Id;
            insert cr;

            CN_Chef_Request__c cr1 = [SELECT Id, RecordTypeId FROM CN_Chef_Request__c WHERE id =: cr.Id];
            System.assertEquals(cr1.RecordTypeId, demoRTId);

            CN_Chef_Request__c crUpdate = new CN_Chef_Request__c(
                Id = cr.Id,
                CN_Status__c = Constants.CN_CHEF_REQUEST_STATUS_APPROVALED
            );
            update crUpdate;
        }
        System.runAs(chefManager) {
            CN_Chefs_Assigned__c ca = new CN_Chefs_Assigned__c(
                CN_Chef_Request__c = cr.Id,
                CN_Chef__c = chef.Id,
                CN_Chef_Role__c	= 'Leading Chef',
                CN_Chef_Work_Start_Date__c = Date.today().addMonths(3),
                CN_Chef_Work_End_Date__c = Date.today().addMonths(3).addDays(13)
            );
            insert ca;

            CN_Chef_Request__c crUpdate = new CN_Chef_Request__c(
                Id = cr.Id,
                CN_Confirmed__c = true
            );
            update crUpdate;
        }
        CN_Demo_Report__c dr = new CN_Demo_Report__c(
            CN_Chef_Request__c = cr.Id,
            CN_Number_of_People__c = 10,
            CN_Sales_Attendance__c = 'Yes',
            CN_Number_of_Recipes__c = 99.99,
            CN_Comments__c = 'Test',
            CN_SAP_Concur_Travel_Cost__c = 9.9
        );
        System.runAs(chef) {
            insert dr;
            System.assertEquals(dr.CN_Chef_Request__c, cr.Id);
        }
        System.runAs(chefManager) {
            try {
                delete dr;
            } catch (Exception e) {
                
            }
        }
        System.runAs(chef) {
            delete dr;
        }

        Test.stopTest();
    }
}