objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Order_Reason__c.object
<CustomObject>
    <label>Order Reason</label>
    <nameField>
        <label>Order Reason  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Reason</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Sample_Product__c.object
<CustomObject>
    <fields>
        <fullName>CN_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sample Products</relationshipLabel>
        <relationshipName>Sample_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Quantity_Needed__c</fullName>
        <label>Quantity Needed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_Sample_Needed_Date__c</fullName>
        <formula>CN_Sample_Request__r.CN_Sample_Needed_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sample Needed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Sample_Request__c</fullName>
        <label>Sample Request</label>
        <referenceTo>CN_Sample_Request__c</referenceTo>
        <relationshipLabel>Sample Products</relationshipLabel>
        <relationshipName>Sample_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Status_of_Delivery__c</fullName>
        <label>Status of Delivery</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Done</fullName>
                </value>
                <value>
                    <fullName>Out of Stock</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sample Product</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Sample Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Sample_Request__c.object
<CustomObject>
    <fields>
        <fullName>CN_Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.StageName</field>
                <operation>equals</operation>
                <value>Proposal/Demo/Sample</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sample Requests</relationshipLabel>
        <relationshipName>Sample_RequestS_FeedbackS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Order_Reason__c</fullName>
        <label>Order Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Product Penetration</fullName>
                </value>
                <value>
                    <fullName>Chef Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Order_Reason_for_Wholepack__c</fullName>
        <label>Order Reason for Wholepack</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>811 Customer Sample</fullName>
                    <default>true</default>
                    <label>811 Customer Sample</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Order_Type_for_Wholepack__c</fullName>
        <label>Order Type for Wholepack</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ZFD1 Sample for Customer</fullName>
                </value>
                <value>
                    <fullName>ZFD3 - BPP sample</fullName>
                </value>
                <value>
                    <fullName>ZFD3 -BPP sample</fullName>
                    <isActive>false</isActive>
                    <label>ZFD3 -BPP sample</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sample_Delivery_Method__c</fullName>
        <label>Sample Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Include in the delivery tomorrow</fullName>
                </value>
                <value>
                    <fullName>Deliver to Office</fullName>
                </value>
                <value>
                    <fullName>Self Pick-up</fullName>
                </value>
                <value>
                    <fullName>Sales to pick up</fullName>
                </value>
                <value>
                    <fullName>Express Delivery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sample_Needed_Date__c</fullName>
        <label>Sample Needed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Sample_Request_Status__c</fullName>
        <label>Sample Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>SR-{000000000}</displayFormat>
        <label>Sample Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CN_SR_Populate_Fields_Handler_Test.cls
/**************************************************************************************************
 * Name           : CN_SR_Populate_Fields_Handler_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Qiu Chen
 * Create Date    : 2021-10-12
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_SR_Populate_Fields_Handler_Test {

    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }

    @isTest
    private static void CN_SR_Populate_Fields_HandlerTest() {
        TestDataFactory testFactory = new TestDataFactory();
        List<Account> accListFactory = testFactory.makeFactoryAccount();
        List<User> userList = [SELECT Id, LastName FROM User WHERE lastName in ('Sales1', 'Sales3', 'ChefManager', 'Chef', 'CCE1_KA')];
        Map<String, User> lastNameUserMap = new Map<String, User>();
        for(User usr: userList) {
            lastNameUserMap.put(usr.LastName, usr);
        }
        User salesRep = lastNameUserMap.get('Sales1');

        Id repackRTId = Schema.SObjectType.CN_Sample_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_SR_OFFICE_REPACK_RT_API_NAME).getRecordTypeId();
        Id wholepackRTId = Schema.SObjectType.CN_Sample_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_SR_WHOLE_PACK_RT_API_NAME).getRecordTypeId();
        Account acc_factory = [SELECT Id,Name FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];
        List<Product2> SKUList = [SELECT Id, Name FROM Product2];

        CN_Sample_Request__c sr = new CN_Sample_Request__c(
            CN_Sample_Delivery_Method__c = 'Self Pick-up',
            CN_Sample_Request_Status__c = 'New',
            CN_Order_Type_for_Wholepack__c = 'ZFD1 Sample for Customer',
            CN_Order_Reason__c = 'Product Penetration',
            CN_Order_Reason_for_Wholepack__c = '811 Customer Sample',
            CN_Sample_Needed_Date__c = Date.today().addMonths(3),
            RecordTypeId = wholepackRTId
        );
        Test.startTest();

        System.runAs(salesRep) {
            Opportunity opp = testFactory.makeOpp(acc_factory);
            insert opp;

            Opportunity opp1 = testFactory.makeOpp(acc_factory);
            insert opp1;

            sr.CN_Opportunity_Name__c = opp.Id;
            insert sr;
            
            CN_Sample_Product__c sp = new CN_Sample_Product__c(
                CN_Sample_Request__c = sr.Id,
                CN_Product__c = SKUList[0].Id,
                CN_Quantity_Needed__c = 9
            );
            insert sp;

            sr.CN_Sample_Request_Status__c = Constants.CN_SR_STATUS_READY;
            sr.CN_Opportunity_Name__c = opp1.Id;
            update sr;

            sr.CN_Sample_Request_Status__c = Constants.CN_SR_STATUS_APPROVED;
            update sr;

            sp.CN_Status_of_Delivery__c = 'Done';
            update sp;

            try {
                delete sr;
            } catch (Exception e) {
                
            }

            try {
                delete sp;
            } catch (Exception e) {
                
            }
        }

        Test.stopTest();
    }
}