objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Source__c</fullName>
        <label>Account Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Recommend</fullName>
                </value>
                <value>
                    <fullName>Cold Visit</fullName>
                </value>
                <value>
                    <fullName>Public Demo</fullName>
                </value>
                <value>
                    <fullName>Brand Activity</fullName>
                </value>
                <value>
                    <fullName>Expositions</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Social Media Network</fullName>
                </value>
                <value>
                    <fullName>Marketing Campaign</fullName>
                </value>
                <value>
                    <fullName>Digital Campaign</fullName>
                </value>
                <value>
                    <fullName>Bakery China</fullName>
                </value>
                <value>
                    <fullName>CIIE</fullName>
                </value>
                <value>
                    <fullName>FHC</fullName>
                </value>
                <value>
                    <fullName>Other Trade show</fullName>
                </value>
                <value>
                    <fullName>Sponsorship Event</fullName>
                </value>
                <value>
                    <fullName>Customer Service Hotline</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Ship_to_Party__c.object
<CustomObject>
    <fields>
        <fullName>CN_UP_Code__c</fullName>
        <externalId>true</externalId>
        <label>UP code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Ship to Party</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Ship to Party Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ship to Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_ShipTo_Upsert_To_Mg_Test.cls
/*
 * ************************************************************************************************
 * Name : CN_ShipTo_Upsert_To_Mg_Test
 * Description :
 * Object :
 * Requirement :
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2023/12/29
 * Modify History :
 * ************************************************************************************************
 */
@IsTest
public class CN_ShipTo_Upsert_To_Mg_Test {

	@TestSetup
	static void makeData(){
		TestDataFactory.makeBaseData();
	}

	@IsTest
	private static void handleUpdate() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		testFactory.makeTalendSetting();
		Account account = [SELECT Id FROM Account WHERE CN_MG_Account_ID__c = '1'];
		account.CN_Account_Source__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		update account;
		CN_Ship_to_Party__c shipToParty = [SELECT Id FROM CN_Ship_to_Party__c WHERE CN_ShipTo_Address_ID__c = '1'];
		shipToParty.CN_Need_Send_MG__c = true;
		shipToParty.CN_UP_Code__c = 'UPTEST';
		update shipToParty;

		Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
		Database.executeBatch(new CN_ShipTo_Upsert_To_Mg_Batch());
	}

	@IsTest
	private static void handleUpdate503() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		testFactory.makeTalendSetting();
		Account account = [SELECT Id FROM Account WHERE CN_MG_Account_ID__c = '1'];
		account.CN_Account_Source__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		update account;
		CN_Ship_to_Party__c shipToParty = [SELECT Id FROM CN_Ship_to_Party__c WHERE CN_ShipTo_Address_ID__c = '1'];
		shipToParty.CN_Need_Send_MG__c = true;
		shipToParty.CN_UP_Code__c = 'UPTEST';
		shipToParty.CN_ShipTo_Address_ID__c = '503';
		update shipToParty;

		Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
		Database.executeBatch(new CN_ShipTo_Upsert_To_Mg_Batch());
	}

	@IsTest
	private static void handleUpdate500() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		testFactory.makeTalendSetting();
		Account account = [SELECT Id FROM Account WHERE CN_MG_Account_ID__c = '1'];
		account.CN_Account_Source__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		update account;
		CN_Ship_to_Party__c shipToParty = [SELECT Id FROM CN_Ship_to_Party__c WHERE CN_ShipTo_Address_ID__c = '1'];
		shipToParty.CN_Need_Send_MG__c = true;
		shipToParty.CN_UP_Code__c = 'UPTEST';
		shipToParty.CN_ShipTo_Address_ID__c = '500';
		update shipToParty;

		Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
		Database.executeBatch(new CN_ShipTo_Upsert_To_Mg_Batch());
	}

	@IsTest
	private static void handleUpdate404() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		testFactory.makeTalendSetting();
		Account account = [SELECT Id FROM Account WHERE CN_MG_Account_ID__c = '1'];
		account.CN_Account_Source__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		update account;
		CN_Ship_to_Party__c shipToParty = [SELECT Id FROM CN_Ship_to_Party__c WHERE CN_ShipTo_Address_ID__c = '1'];
		shipToParty.CN_Need_Send_MG__c = true;
		shipToParty.CN_UP_Code__c = 'UPTEST';
		shipToParty.CN_ShipTo_Address_ID__c = '404';
		update shipToParty;

		Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
		Database.executeBatch(new CN_ShipTo_Upsert_To_Mg_Batch());
	}

	@IsTest
	private static void handleUpdateErr() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		testFactory.makeTalendSetting();
		Account account = [SELECT Id FROM Account WHERE CN_MG_Account_ID__c = '1'];
		account.CN_Account_Source__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		update account;
		CN_Ship_to_Party__c shipToParty = [SELECT Id FROM CN_Ship_to_Party__c WHERE CN_ShipTo_Address_ID__c = '1'];
		shipToParty.CN_Need_Send_MG__c = true;
		shipToParty.CN_UP_Code__c = 'UPTEST';
		shipToParty.CN_ShipTo_Address_ID__c = 'Err';
		update shipToParty;

		Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
		Database.executeBatch(new CN_ShipTo_Upsert_To_Mg_Batch());
	}

	@IsTest
	private static void handleSCHTest() {
		System.schedule('CN_ShipTo_Upsert_To_Mg_SCH', '0 0 * * * ?', new CN_ShipTo_Upsert_To_Mg_SCH());
	}
}