objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Approve_Aging_Trigger_Datetime__c</fullName>
        <label>Approve Aging Trigger Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CN_Approve_Step__c</fullName>
        <label>Approve Step</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Step1</fullName>
                </value>
                <value>
                    <fullName>Step2</fullName>
                </value>
                <value>
                    <fullName>Step3</fullName>
                </value>
                <value>
                    <fullName>Step4</fullName>
                </value>
                <value>
                    <fullName>Step5</fullName>
                </value>
                <value>
                    <fullName>Step6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales MDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_Approver1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesale Channel Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_Approver2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_Approver3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Approver_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_Approver4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Approver_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_Approver5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Current_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CN_Current_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Approval_Aging_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>CN_Approval_Aging_Setting_Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_Approval_Aging_Setting_Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Approval_Aging_Setting_Step__c</fullName>
        <label>Step</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approval Aging Setting</label>
    <pluralLabel>Approval Aging Settings</pluralLabel>
</CustomObject>

classes/CN_Account_Approve_Aging_Handler.cls
/**************************************************************************************************
 * Name           : CN_Account_Approve_Aging_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Du Dezheng
 * Create Date    : 2021-05-07
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_Account_Approve_Aging_Handler implements Triggers.Handler{
    
	public void handle() {
        if(Trigger.isBefore && Trigger.IsUpdate) {
            handleBeforeUpdate();
        }
    }
    
    public void handleBeforeUpdate() {
        Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.CN_Account_RT_API_NAME_EDIT_DIRECT).getRecordTypeId();
        List<Account> accList = new List<Account>();
        for(Account acc : (List<Account>)Trigger.New) {          
            if(acc.recordTypeId == accRTId && Constants.CN_ACCOUNT_ACCOUNT_STATUS_SUBMITTED_FOR_APPROVAL.equals(acc.CN_Account_Status__c) && String.isNotBlank(acc.CN_Approve_Step__c) && acc.CN_Approve_Step__c <> ((Account)Trigger.oldMap.get(acc.Id)).CN_Approve_Step__c ){
                accList.add(acc);
            }
        }
        if(acclist.size() > 0){
            updateTriggerTimeAndApprover(accList);
        }        
    }
    
    public void updateTriggerTimeAndApprover(List<Account> accList){
        for(Account acc : accList){
            Integer hours = NUll;
            
            Map<String,Id> ApproveStepStringApproverIdMap = new Map<String,Id>();
            ApproveStepStringApproverIdMap.put('step1',acc.CN_Approver_1__c);
            ApproveStepStringApproverIdMap.put('step2',acc.CN_Approver_2__c);
            ApproveStepStringApproverIdMap.put('step3',acc.CN_Approver_3__c);
            ApproveStepStringApproverIdMap.put('step4',acc.CN_Approver_4__c);
            ApproveStepStringApproverIdMap.put('step5',acc.CN_Approver_5__c);

            Integer str_Approve_Step_num = Integer.valueOf(acc.CN_Approve_Step__c.Right(1));
            for(Integer n=str_Approve_Step_num;n<=5;n++){
                if(String.isNotBlank(ApproveStepStringApproverIdMap.get('step'+n))){
                    acc.CN_Current_Approver__c = ApproveStepStringApproverIdMap.get('step'+ n);
                    acc.CN_Approve_Step__c = 'step'+n;
                    break;
                }else if(n==5){
                    return;
                }
            }
            
            List<CN_Approval_Aging_Setting__mdt> approvalAgingSettings =  CN_Approval_Aging_Setting__mdt.getAll().values();
            for(CN_Approval_Aging_Setting__mdt approvalAgingSetting : approvalAgingSettings){
                if(approvalAgingSetting.CN_Approval_Aging_Setting_Step__c == acc.CN_Approve_Step__c && 'Account'.equals(approvalAgingSetting.CN_Approval_Aging_Setting_Object__c)){
                	hours = (Integer)approvalAgingSetting.CN_Approval_Aging_Setting_Hours__c;
                    break;
                }
            }
            
            if(hours <> null){
                acc.CN_Approve_Aging_Trigger_Datetime__c = Untils.calculateBusinessTime(DateTime.now(),hours,Constants.CN_BUSINESS_HOURS_NAME);
            }else{
                acc.AddError(system.Label.CN_Account_CustomLabel_Hour_Is_NULL);
            }
        }
    }
}