objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>2 OR (1 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.CN_Group_Name__c</field>
                <operation>equals</operation>
                <valueField>CN_Brand__c.CN_Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>CN_Brand__c.CN_Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CN_Brand__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CN_Brand__c</fullName>
        <label>Brand</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>5J</fullName>
                </value>
                <value>
                    <fullName>Adamance</fullName>
                </value>
                <value>
                    <fullName>ANTICHICOLLI</fullName>
                </value>
                <value>
                    <fullName>BARNIER OLIVES</fullName>
                </value>
                <value>
                    <fullName>BASTIDES</fullName>
                </value>
                <value>
                    <fullName>BEAUFOR</fullName>
                </value>
                <value>
                    <fullName>Beillevaire</fullName>
                </value>
                <value>
                    <fullName>BERETTA</fullName>
                </value>
                <value>
                    <fullName>BEYONG MEAT</fullName>
                </value>
                <value>
                    <fullName>Cabrifin</fullName>
                </value>
                <value>
                    <fullName>CAPRICE DES DIEUX</fullName>
                </value>
                <value>
                    <fullName>CAVIAR &amp; TRADITIONS</fullName>
                </value>
                <value>
                    <fullName>Chateau d&apos;Estoublon</fullName>
                </value>
                <value>
                    <fullName>Chef Studio OIL</fullName>
                </value>
                <value>
                    <fullName>Chef Studio Pastry</fullName>
                </value>
                <value>
                    <fullName>COEUR DE LION</fullName>
                </value>
                <value>
                    <fullName>CORMAN</fullName>
                </value>
                <value>
                    <fullName>DOBLA</fullName>
                </value>
                <value>
                    <fullName>DODONI</fullName>
                </value>
                <value>
                    <fullName>Elle &amp; Vire</fullName>
                </value>
                <value>
                    <fullName>FERMES DE LA TREMBLAYE</fullName>
                </value>
                <value>
                    <fullName>Giovanni Ferrari</fullName>
                </value>
                <value>
                    <fullName>ILE DE FRANCE</fullName>
                </value>
                <value>
                    <fullName>IRCA</fullName>
                </value>
                <value>
                    <fullName>Joyhana</fullName>
                </value>
                <value>
                    <fullName>LE RUSTIQUE</fullName>
                </value>
                <value>
                    <fullName>Lescure</fullName>
                </value>
                <value>
                    <fullName>Liberty Lane</fullName>
                </value>
                <value>
                    <fullName>LOSTE TRADI-FRANCE</fullName>
                </value>
                <value>
                    <fullName>Milkana</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Channel__c</fullName>
        <label>Channel</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KA</fullName>
                </value>
                <value>
                    <fullName>WS</fullName>
                </value>
                <value>
                    <fullName>DS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Customer_Category__c</fullName>
        <label>Customer Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BAPA</fullName>
                </value>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Coffee/Tea Shop</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
                <value>
                    <fullName>Retailor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Execution_Type__c</fullName>
        <label>Execution Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public Demonstration</fullName>
                </value>
                <value>
                    <fullName>VIP Class</fullName>
                </value>
                <value>
                    <fullName>1on1</fullName>
                </value>
                <value>
                    <fullName>VIP Dinner</fullName>
                </value>
                <value>
                    <fullName>Tasting</fullName>
                </value>
                <value>
                    <fullName>On-Site Order</fullName>
                </value>
                <value>
                    <fullName>Livestreaming</fullName>
                </value>
                <value>
                    <fullName>Solution Development</fullName>
                </value>
                <value>
                    <fullName>Short Video</fullName>
                </value>
                <value>
                    <fullName>WeChat</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>GOURMET &amp; GROCERY</fullName>
                </value>
                <value>
                    <fullName>PASTRY</fullName>
                </value>
                <value>
                    <fullName>Chef Studio Pastry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Product_Type__c</fullName>
        <label>Product Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CHEESE</fullName>
                </value>
                <value>
                    <fullName>BUTTER</fullName>
                </value>
                <value>
                    <fullName>CREAM</fullName>
                </value>
                <value>
                    <fullName>COLD CUTS &amp; MEAT</fullName>
                </value>
                <value>
                    <fullName>FOIS GRAS</fullName>
                </value>
                <value>
                    <fullName>GROCERY</fullName>
                </value>
                <value>
                    <fullName>CHOCOLATE &amp; DECORATION</fullName>
                </value>
                <value>
                    <fullName>PUREE</fullName>
                </value>
                <value>
                    <fullName>PRE MIX</fullName>
                </value>
                <value>
                    <fullName>VALUE - ADDED</fullName>
                </value>
                <value>
                    <fullName>FROZEN PASTRY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>CN_Campaign</fullName>
        <active>true</active>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_API_Call_Logger__c.object
<CustomObject>
    <description>API Call Log</description>
    <label>API Call Logger</label>
    <nameField>
        <displayFormat>INF-{YYYYMMDD}{0000}</displayFormat>
        <label>API Call Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Call Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CN_Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CN_Campaign_Upsert_To_Mg_Handler_Test.cls
/*
 * ************************************************************************************************
 * Name : CN_Campaign_Upsert_To_Mg_Handler_Test
 * Object :
 * Requirement : ET-001
 * Target :
 * Refer classes :
 * Author : Zhang zhihao
 * Create Date : 2024/4/1
 * Modify History :
 * ************************************************************************************************
 */
@isTest
public class CN_Campaign_Upsert_To_Mg_Handler_Test {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }
    @isTest
    private static void campaignToTigerTest200(){
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeTalendSetting();
        testFactory.makeFactoryAccount();
        Account acc_factory = [SELECT Id, Name FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];
        Contact con_factory = [SELECT Id, Name FROM Contact WHERE AccountId =: acc_factory.Id];

        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }
        User marketingRep = New User(Id = lastNameUserIdMap.get('Marketing1'));

        List<Product2> SKUList = [SELECT Id FROM Product2];

        Campaign cam = testFactory.makeCampaign();
        insert cam;
        cam.Name = '200';
        update cam;
        List<Campaign> camps = new List<Campaign>();
        Campaign camTest = new Campaign();
        Id camRTId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('CN_Campaign').getRecordTypeId();
        camTest.RecordTypeId = camRTId;
        camTest.Name = '200';
        camTest.Status = 'Planned';
        camTest.Type = 'Corporate Event';
        camTest.StartDate = Date.today().addMonths(3);
        camTest.EndDate = Date.today().addMonths(3).addDays(13);
        camTest.CN_Execution_Type__c = 'Public Demonstration';
        camTest.CN_Channel__c = 'KA';
        camTest.CN_Customer_Category__c = 'BAPA';
        camTest.CN_Product_Category__c = 'Dairy';
        camTest.CN_Product_Type__c = 'CHEESE';
        camTest.CN_Brand__c = '5J';
        insert camTest;
        Test.startTest();
        List<CN_API_Call_Logger__c> listLog = new List<CN_API_Call_Logger__c>();
        camps.add(camTest);
        CN_Campaign_Upsert_To_Mg_Callout.sendMgCampaign(camps,listLog);
        Test.setMock(HttpCalloutMock.class, new TestHttpMock());
        Test.stopTest();

    }



    @isTest
    private static void timedTask(){
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeTalendSetting();
        testFactory.makeFactoryAccount();
        List<Campaign> camps = new List<Campaign>();
        Campaign camTest = new Campaign();
        Id camRTId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('CN_Campaign').getRecordTypeId();
        camTest.RecordTypeId = camRTId;
        camTest.Name = '200';
        camTest.Status = 'Planned';
        camTest.Type = 'Corporate Event';
        camTest.StartDate = Date.today().addMonths(3);
        camTest.EndDate = Date.today().addMonths(3).addDays(13);
        camTest.CN_Execution_Type__c = 'Public Demonstration';
        camTest.CN_Channel__c = 'KA';
        camTest.CN_Customer_Category__c = 'BAPA';
        camTest.CN_Product_Category__c = 'Dairy';
        camTest.CN_Product_Type__c = 'CHEESE';
        camTest.CN_Brand__c = '5J';
        insert camTest;

        update camTest;
        
        Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
		Database.executeBatch(new CN_Campaign_Upsert_To_Mg_Batch());

    }
}