objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Sales_Team_UI__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Please search for KA/DS/WS.</inlineHelpText>
        <label>Sales Team</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>2 OR (1 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.CN_Business_Unit_UI__c</field>
                <operation>equals</operation>
                <valueField>CN_Sales_Team__c.CN_Business_Unit__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>CN_Sales_Team__c.CN_Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CN_Sales_Team__c</referenceTo>
        <relationshipLabel>SalesTeams</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Approve_Process_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CN_Finance_MDM_UserId__c</fullName>
        <label>Finance MDM User ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CN Approve Process Settings</label>
</CustomObject>

objects/CN_Sales_Team__c.object
<CustomObject>
    <label>Sales Team</label>
    <nameField>
        <label>Sales Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>CN_Customer_Code__c</fullName>
        <formula>Opportunity.Account.CN_Customer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Quote_Finance_Notice_LC_Ctrl.cls
/**************************************************************************************************
* Name           : CN_Quote_Finance_Notice_LC_Ctrl
* Object         : 
* Requirement    : 
* Target         : 
* Refer classes  :
* Author         : Wan Houchen
* Create Date    : 2021-10-29
* Modify History : 
**************************************************************************************************/
public without sharing class CN_Quote_Finance_Notice_LC_Ctrl {
    
    @AuraEnabled
    public static void sendNotifyEmail(String QuoteId){
        system.debug('QuoteId==>'+QuoteId);
        try {
            CN_Approve_Process_Settings__c settings = CN_Approve_Process_Settings__c.getInstance();            
            String recipientId = settings.CN_Finance_MDM_UserId__c;
            Quote qu = [Select Id,CN_Finance_Notify_DateTime__c,Opportunity.Account.CN_Customer_Code__c,Opportunity.Account.CN_Sales_Team_UI__r.Name,Opportunity.Account.Name From Quote Where Id = :QuoteId];
            system.debug('quote==>'+qu);
            EmailTemplate template = [Select Id, DeveloperName from EmailTemplate Where DeveloperName = 'CN_Quote_Notify_Finance' limit 1];
            
            Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(template.Id,recipientId,QuoteId);
            String CNsubject = '请在SAP中维护SKU报价 for - '+ qu.Opportunity.Account.CN_Customer_Code__c +' – '+ qu.Opportunity.Account.CN_Sales_Team_UI__r.Name +' - '+ qu.Opportunity.Account.Name;
            String ENsubject = 'Please Maintain SKU Quote Price in SAP for customer - '+ qu.Opportunity.Account.CN_Customer_Code__c +' – '+ qu.Opportunity.Account.CN_Sales_Team_UI__r.Name +' - '+ qu.Opportunity.Account.Name;
            system.debug('CNsubject==>'+CNsubject);
            email.setSubject(CNsubject+'/'+ENsubject);
            email.setSaveAsActivity(false);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
            qu.CN_Finance_Notify_DateTime__c = system.now();
            update qu;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}