objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Source__c</fullName>
        <label>Account Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Recommend</fullName>
                </value>
                <value>
                    <fullName>Cold Visit</fullName>
                </value>
                <value>
                    <fullName>Public Demo</fullName>
                </value>
                <value>
                    <fullName>Brand Activity</fullName>
                </value>
                <value>
                    <fullName>Expositions</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Social Media Network</fullName>
                </value>
                <value>
                    <fullName>Marketing Campaign</fullName>
                </value>
                <value>
                    <fullName>Digital Campaign</fullName>
                </value>
                <value>
                    <fullName>Bakery China</fullName>
                </value>
                <value>
                    <fullName>CIIE</fullName>
                </value>
                <value>
                    <fullName>FHC</fullName>
                </value>
                <value>
                    <fullName>Other Trade show</fullName>
                </value>
                <value>
                    <fullName>Sponsorship Event</fullName>
                </value>
                <value>
                    <fullName>Customer Service Hotline</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_City_CN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City(CN)</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>CN_City__c.CN_Province__c</field>
                <operation>equals</operation>
                <valueField>$Source.CN_Province_CN__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_City__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Customer_Type__c</fullName>
        <defaultValue>&quot;0001-Sold to party&quot;</defaultValue>
        <label>Customer Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0001</fullName>
                    <label>0001-Sold to party</label>
                </value>
                <value>
                    <fullName>0002</fullName>
                    <label>0002-Goods Receipt</label>
                </value>
                <value>
                    <fullName>CPDA</fullName>
                    <label>CPDA-Onetime Customer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Delivery_Plant__c</fullName>
        <label>Delivery Plant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P011</fullName>
                    <label>P011-SINODIS ShangHai External-西诺迪斯（上海） 外部</label>
                </value>
                <value>
                    <fullName>P020</fullName>
                    <label>P020-SINODIS BeiJing-西诺迪斯（北京）</label>
                </value>
                <value>
                    <fullName>P040</fullName>
                    <label>P040-SINODIS GuangZhou-西诺迪斯（广州）</label>
                </value>
                <value>
                    <fullName>P050</fullName>
                    <label>P050-SINODIS Chengdu-西诺迪斯（成都）</label>
                </value>
                <value>
                    <fullName>P060</fullName>
                    <label>P060-SINODIS Dalian-西诺迪斯（大连）</label>
                </value>
                <value>
                    <fullName>P010</fullName>
                    <isActive>false</isActive>
                    <label>P010-SINODIS ShangHai-西诺迪斯（上海）</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Invoicing_Address_EN__c</fullName>
        <label>Delivery Address(EN)</label>
        <length>220</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Invoicing_Address_and_Phone__c</fullName>
        <inlineHelpText>address and phone</inlineHelpText>
        <label>Invoicing Address and Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Province_CN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province(CN)</label>
        <referenceTo>CN_Province__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Ship_to_Party__c.object
<CustomObject>
    <fields>
        <fullName>CN_City_CN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City(CN)</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>CN_City__c.CN_Province__c</field>
                <operation>equals</operation>
                <valueField>$Source.CN_Province_CN__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_City__c</referenceTo>
        <relationshipLabel>Ship to Parties</relationshipLabel>
        <relationshipName>Ship_to_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Customer_Type__c</fullName>
        <label>Customer Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0001</fullName>
                    <label>0001-Sold to party</label>
                </value>
                <value>
                    <fullName>0002</fullName>
                    <default>true</default>
                    <label>0002-Goods Receipt</label>
                </value>
                <value>
                    <fullName>CPDA</fullName>
                    <label>CPDA-Onetime Customer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Delivery_Address_CN__c</fullName>
        <label>Delivery Address(CN)</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Delivery_Address_EN__c</fullName>
        <label>Delivery Address (EN)</label>
        <length>220</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Delivery_Plant__c</fullName>
        <label>Delivery Plant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P011</fullName>
                    <label>P011-SINODIS ShangHai External-西诺迪斯（上海） 外部</label>
                </value>
                <value>
                    <fullName>P020</fullName>
                    <label>P020-SINODIS BeiJing-西诺迪斯（北京）</label>
                </value>
                <value>
                    <fullName>P040</fullName>
                    <label>P040-SINODIS GuangZhou-西诺迪斯（广州）</label>
                </value>
                <value>
                    <fullName>P050</fullName>
                    <label>P050-SINODIS Chengdu-西诺迪斯（成都）</label>
                </value>
                <value>
                    <fullName>P060</fullName>
                    <label>P060-SINODIS Dalian-西诺迪斯（大连）</label>
                </value>
                <value>
                    <fullName>P010</fullName>
                    <isActive>false</isActive>
                    <label>P010-SINODIS ShangHai-西诺迪斯（上海）</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Province_CN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province(CN)</label>
        <referenceTo>CN_Province__c</referenceTo>
        <relationshipLabel>Ship to Parties (Province(CN))</relationshipLabel>
        <relationshipName>Ship_to_Parties1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Sold_To_Party_Customer__c</fullName>
        <label>Sold-to Party Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5 AND 6) OR 7</booleanFilter>
            <errorMessage>You can only select Account whose Status is New.</errorMessage>
            <filterItems>
                <field>Account.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>New</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship to Party</value>
            </filterItems>
            <filterItems>
                <field>$Source.CN_Change_Request__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.CN_Change_Request__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship to Party</value>
            </filterItems>
            <filterItems>
                <field>Account.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship to Parties</relationshipLabel>
        <relationshipName>Ship_to_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ship to Party</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Ship to Party Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ship to Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_ShipTo_Send_Mg_Handler_Test.cls
/*
 * ************************************************************************************************
 * Name : CN_ShipTo_Send_Mg_Handler_Test
 * Description :
 * Object :
 * Requirement :
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2024/1/2
 * Modify History :
 * ************************************************************************************************
 */
@IsTest
public class CN_ShipTo_Send_Mg_Handler_Test {
	@TestSetup
	static void makeData(){
		TestDataFactory.makeBaseData();
	}


	@isTest
	static void testHandleBeforeInsert1() {

		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		Account acc = [SELECT Id,CN_Invoicing_Address_and_Phone__c,CN_Delivery_Plant__c,CN_Province_CN__c,CN_City_CN__c, Name,CN_Invoicing_Address_EN__c, CN_MG_Account_ID__c FROM Account WHERE CN_MG_Account_ID__c = '1'];

		CN_Ship_to_Party__c shipTo = new CN_Ship_to_Party__c(
				CN_Sold_To_Party_Customer__c = acc.Id,
				CN_Customer_Type__c = '0002',
				CN_Delivery_Address_CN__c = acc.CN_Invoicing_Address_and_Phone__c + 1,
				CN_Delivery_Plant__c = acc.CN_Delivery_Plant__c,
				CN_Province_CN__c = acc.CN_Province_CN__c,
				CN_City_CN__c = acc.CN_City_CN__c,
				CN_Delivery_Address_EN__c = acc.CN_Invoicing_Address_EN__c + 1,
				CN_ShipTo_Address_ID__c = acc.CN_MG_Account_ID__c + 1
		);
		insert shipTo;

	}

	@isTest
	static void testHandleBeforeInsert2() {

		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		Account acc = [SELECT Id,CN_Invoicing_Address_and_Phone__c,CN_Delivery_Plant__c,CN_Province_CN__c,CN_City_CN__c, Name,CN_Invoicing_Address_EN__c, CN_MG_Account_ID__c FROM Account WHERE CN_MG_Account_ID__c = '1'];
		acc.CN_Account_Source__c = 'Customer Service Hotline';
		update acc;

		CN_Ship_to_Party__c shipTo = new CN_Ship_to_Party__c(
				CN_Sold_To_Party_Customer__c = acc.Id,
				CN_Customer_Type__c = '0002',
				CN_Delivery_Address_CN__c = acc.CN_Invoicing_Address_and_Phone__c + 1,
				CN_Delivery_Plant__c = acc.CN_Delivery_Plant__c,
				CN_Province_CN__c = acc.CN_Province_CN__c,
				CN_City_CN__c = acc.CN_City_CN__c,
				CN_Delivery_Address_EN__c = acc.CN_Invoicing_Address_EN__c + 1,
				CN_ShipTo_Address_ID__c = acc.CN_MG_Account_ID__c + 1
		);
		insert shipTo;

	}

	@isTest
	static void testHandleBeforeInsert3() {

		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		Account acc = [SELECT Id,CN_Invoicing_Address_and_Phone__c,CN_Delivery_Plant__c,CN_Province_CN__c,CN_City_CN__c, Name,CN_Invoicing_Address_EN__c, CN_MG_Account_ID__c FROM Account WHERE CN_MG_Account_ID__c = '1'];
		acc.CN_Account_Source__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		update acc;

		CN_Ship_to_Party__c shipTo = new CN_Ship_to_Party__c(
				CN_Sold_To_Party_Customer__c = acc.Id,
				CN_Customer_Type__c = '0002',
				CN_Delivery_Address_CN__c = acc.CN_Invoicing_Address_and_Phone__c + 1,
				CN_Delivery_Plant__c = acc.CN_Delivery_Plant__c,
				CN_Province_CN__c = acc.CN_Province_CN__c,
				CN_City_CN__c = acc.CN_City_CN__c,
				CN_Delivery_Address_EN__c = acc.CN_Invoicing_Address_EN__c + 1,
				CN_ShipTo_Address_ID__c = acc.CN_MG_Account_ID__c + 1
		);
		insert shipTo;
	}

	@isTest
	static void testHandleBeforeUpdate1() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		Account acc = [SELECT Id,CN_Invoicing_Address_and_Phone__c,CN_Delivery_Plant__c,CN_Province_CN__c,CN_City_CN__c, Name,CN_Invoicing_Address_EN__c, CN_MG_Account_ID__c FROM Account WHERE CN_MG_Account_ID__c = '1'];
		acc.CN_Account_Source__c = null;
		update acc;

		CN_Ship_to_Party__c shipToParty =  [select id,Name  from CN_Ship_to_Party__c WHERE CN_ShipTo_Address_ID__c = '1'];
		shipToParty.CN_Delivery_Address_CN__c = 'TestUpdate';
		update shipToParty;
	}

	@isTest
	static void testHandleBeforeUpdate2() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		Account acc = [SELECT Id,CN_Invoicing_Address_and_Phone__c,CN_Delivery_Plant__c,CN_Province_CN__c,CN_City_CN__c, Name,CN_Invoicing_Address_EN__c, CN_MG_Account_ID__c FROM Account WHERE CN_MG_Account_ID__c = '1'];
		acc.CN_Account_Source__c = 'Customer Service Hotline';
		update acc;

		CN_Ship_to_Party__c shipToParty =  [select id,Name  from CN_Ship_to_Party__c WHERE CN_ShipTo_Address_ID__c = '1'];
		shipToParty.CN_Delivery_Address_CN__c = 'TestUpdate';
		update shipToParty;
	}

	@isTest
	static void testHandleBeforeUpdate3() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();

		CN_Ship_to_Party__c shipToParty =  [select id,Name  from CN_Ship_to_Party__c WHERE CN_ShipTo_Address_ID__c = '1'];
		shipToParty.CN_Delivery_Address_CN__c = 'TestUpdate';
		update shipToParty;
	}

	@isTest
	static void testHandleBeforeUpdate4() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		Account acc = [SELECT Id,CN_Invoicing_Address_and_Phone__c,CN_Delivery_Plant__c,CN_Province_CN__c,CN_City_CN__c, Name,CN_Invoicing_Address_EN__c, CN_MG_Account_ID__c FROM Account WHERE CN_MG_Account_ID__c = '1'];
		acc.CN_Account_Source__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		update acc;

		CN_Ship_to_Party__c shipToParty =  [select id,Name  from CN_Ship_to_Party__c WHERE CN_ShipTo_Address_ID__c = '1'];
		shipToParty.CN_Delivery_Address_CN__c = 'TestUpdate';
		update shipToParty;
	}
}