objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Change_Request__c</fullName>
        <label>Change Request</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Latest_CR_Sync_Error_Message__c</fullName>
        <label>Latest Change Request Sync Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_Latest_CR_Sync_Status__c</fullName>
        <label>Latest Change Request Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>No Need To Sync</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Latest_CR_Sync_Time__c</fullName>
        <label>Latest Change Request Sync Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CN_Sync_Error_Message__c</fullName>
        <label>Sync Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_Sync_Status__c</fullName>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sync_Time__c</fullName>
        <label>Sync Time</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <errorMessage>The Account should be Approved and Synchronized.</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Update Account Request, Update Contact Request, New Contact Request, Update Ship-to Request, New Ship-to Request</value>
            </filterItems>
            <filterItems>
                <field>Account.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>Account.CN_Synchronized__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Update Account Request, Update Contact Request, New Contact Request, Update Ship-to Request, New Ship-to Request</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Change_Request_Status__c</fullName>
        <label>Change Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4 OR 5</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Update Account Request, Update Contact Request, New Contact Request, Update Ship-to Request, New Ship-to Request</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.CN_Synchronized__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Update Account Request, Update Contact Request, New Contact Request, Update Ship-to Request, New Ship-to Request</value>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Change Requests (Contact)</relationshipLabel>
        <relationshipName>Change_Requests_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship to Party</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <errorMessage>The associated Account should be Approved and Synchronized.</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Update Account Request, Update Contact Request, New Contact Request, Update Ship-to Request, New Ship-to Request</value>
            </filterItems>
            <filterItems>
                <field>CN_Ship_to_Party__c.CN_Sold_To_Party_Customer__r.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>CN_Ship_to_Party__c.CN_Sold_To_Party_Customer__r.CN_Synchronized__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Update Account Request, Update Contact Request, New Contact Request, Update Ship-to Request, New Ship-to Request</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_Ship_to_Party__c</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Change_Requests_Shipto</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Sync_Error_Message__c</fullName>
        <label>Sync Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_Sync_Status__c</fullName>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>No Need To Sync</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sync_Time__c</fullName>
        <label>Sync Time</label>
        <type>DateTime</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Ship_to_Party__c.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License Name(CN)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship to Parties (Account Name)</relationshipLabel>
        <relationshipName>Ship_to_Parties2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Change_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change Request</label>
        <referenceTo>CN_Change_Request__c</referenceTo>
        <relationshipLabel>Ship to Parties</relationshipLabel>
        <relationshipName>Ship_to_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Latest_CR_Sync_Error_Message__c</fullName>
        <label>Latest Change Request Sync Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_Latest_CR_Sync_Status__c</fullName>
        <label>Latest Change Request Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>No Need To Sync</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Latest_CR_Sync_Time__c</fullName>
        <label>Latest Change Request Sync Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CN_Sync_Error_Message__c</fullName>
        <label>Sync Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_Sync_Status__c</fullName>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sync_Time__c</fullName>
        <label>Sync Time</label>
        <type>DateTime</type>
    </fields>
    <label>Ship to Party</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Ship to Party Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ship to Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Name__c</fullName>
        <formula>Account.Name</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Change_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change Request</label>
        <referenceTo>CN_Change_Request__c</referenceTo>
        <relationshipLabel>Change Request</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Latest_CR_Sync_Error_Message__c</fullName>
        <label>Latest Change Request Sync Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_Latest_CR_Sync_Status__c</fullName>
        <label>Latest Change Request Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>No Need To Sync</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Latest_CR_Sync_Time__c</fullName>
        <label>Latest Change Request Sync Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CN_Sync_Error_Message__c</fullName>
        <label>Sync Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_Sync_Status__c</fullName>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sync_Time__c</fullName>
        <label>Sync Time</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_CR_Update_Sync_Status_Handler.cls
/**************************************************************************************************
 * Name           : CN_CR_Update_Sync_Status_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Jessica
 * Create Date    : 2021-05-23
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_CR_Update_Sync_Status_Handler implements Triggers.Handler {
    public static Boolean isTriggerRun = true;
    Set<Id> accRTIdSet = new Set<Id>();
    Set<Id> conRTIdSet = new Set<Id>();
    Set<Id> shipToRTIdSet = new Set<Id>();
    Id appdUpdateAccountRTId = Schema.SObjectType.CN_Change_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CR_RT_API_NAME_APPD_UPDATE_ACCOUNT).getRecordTypeId();
    Id appdNewContactRTId = Schema.SObjectType.CN_Change_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CR_RT_API_NAME_APPD_NEW_CONTACT).getRecordTypeId();
    Id appdUpdateContactRTId = Schema.SObjectType.CN_Change_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CR_RT_API_NAME_APPD_UPDATE_CONTACT).getRecordTypeId();
    Id appdNewShipToRTId = Schema.SObjectType.CN_Change_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CR_RT_API_NAME_NEW_APPD_SHIPTO).getRecordTypeId();
    Id appdUpdateShipToRTId = Schema.SObjectType.CN_Change_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CR_RT_API_NAME_APPD_UPDATE_SHIPTO).getRecordTypeId();
    
    public void handle() {
        this.accRTIdSet.add(this.appdUpdateAccountRTId);
        this.conRTIdSet.add(this.appdNewContactRTId);
        this.conRTIdSet.add(this.appdUpdateContactRTId);
        this.shipToRTIdSet.add(this.appdNewShipToRTId);
        this.shipToRTIdSet.add(this.appdUpdateShipToRTId);

        if (Trigger.isAfter && Trigger.isUpdate) {
            if(CN_CR_Update_Sync_Status_Handler.isTriggerRun) {
                handleAfterUpdate();
            }
        }
    }
    public void handleAfterUpdate() {
        Map<Id, CN_Change_Request__c> oldCRMap = (Map<Id, CN_Change_Request__c>)Trigger.oldMap;
        Map<Id,CN_Change_Request__c> accSyncStatusMap = new Map<Id,CN_Change_Request__c>();
        Map<Id,CN_Change_Request__c> conSyncStatusMap = new Map<Id,CN_Change_Request__c>();
        Map<Id,CN_Change_Request__c> shipToSyncStatusMap = new Map<Id,CN_Change_Request__c>();

        Datetime latestAccountSyncTime = null;
        Datetime latestContactSyncTime = null;
        Datetime latestSTPSyncTime = null;
        for (CN_Change_Request__c cr : (List<CN_Change_Request__c>)Trigger.new) {
            if (
                accRTIdSet.contains(cr.RecordTypeId) ||
                 conRTIdSet.contains(cr.RecordTypeId) || 
                 shipToRTIdSet.contains(cr.RecordTypeId) &&
                 Constants.CN_CR_STATUS_APPROVED.equals(cr.CN_Change_Request_Status__c) &&
                 ( 
                     Constants.CN_CR_SYNC_STATUS_SUCCESS.equals(cr.CN_Sync_Status__c) ||
                     Constants.CN_CR_SYNC_STATUS_SENT.equals(cr.CN_Sync_Status__c) ||
                     Constants.CN_CR_SYNC_STATUS_NO_NEED_TO_SYNC.equals(cr.CN_Sync_Status__c)
                 )) {
                CN_Change_Request__c oldCRObj = null;
                if (oldCRMap.containsKey(cr.Id)) {
                    oldCRObj = (CN_Change_Request__c)oldCRMap.get(cr.Id);
                } 
                if (cr.CN_Sync_Status__c <> oldCRObj.CN_Sync_Status__c) {
                    if (cr.CN_Account_Name__c <> null) {
                        if(latestAccountSyncTime == null || latestAccountSyncTime < cr.CN_Sync_Time__c) {
                            latestAccountSyncTime = cr.CN_Sync_Time__c;
                            accSyncStatusMap.put(cr.CN_Account_Name__c, cr);
                        }
                    }
                    if (cr.CN_Contact__c <> null) {
                        if(latestContactSyncTime == null || latestContactSyncTime < cr.CN_Sync_Time__c) {
                            latestContactSyncTime = cr.CN_Sync_Time__c;
                            conSyncStatusMap.put(cr.CN_Contact__c, cr);
                        }
                    }
                    if (cr.CN_Ship_To_Party__c <> null) {
                        if(latestSTPSyncTime == null || latestSTPSyncTime < cr.CN_Sync_Time__c) {
                            latestSTPSyncTime = cr.CN_Sync_Time__c;
                            shipToSyncStatusMap.put(cr.CN_Ship_To_Party__c, cr);

                        }
                    }
                } 
            }
        }
        if (!accSyncStatusMap.isEmpty()) {
            syncAccountSyncStatus(accSyncStatusMap);
            CN_CR_Update_Sync_Status_Handler.isTriggerRun = false;
        }
        if (!conSyncStatusMap.isEmpty()) {
            syncContactSyncStatus(conSyncStatusMap);
            CN_CR_Update_Sync_Status_Handler.isTriggerRun = false;
        }
        if (!shipToSyncStatusMap.isEmpty()) {
            syncShipToSyncStatus(shipToSyncStatusMap);
            CN_CR_Update_Sync_Status_Handler.isTriggerRun = false;
        }
    }
    public void syncAccountSyncStatus(Map<Id, CN_Change_Request__c> accSyncStatusMap) {
        List<Account> accUpdateList = new List<Account>();
        for(Id accId : accSyncStatusMap.keySet()) {
            CN_Change_Request__c cr = accSyncStatusMap.get(accId);
            Account acc = new Account(
                Id = accId,
                CN_Latest_CR_Sync_Status__c = cr.CN_Sync_Status__c,
                CN_Latest_CR_Sync_Time__c = cr.CN_Sync_Time__c,
                CN_Latest_CR_Sync_Error_Message__c = cr.CN_Sync_Error_Message__c,
                CN_Change_Request__c = cr.Id
            );
            accUpdateList.add(acc);
        }
        if(accUpdateList.size() > 0) {
            Constants.CN_ACCOUNT_TRIGGER_ON = false;
            update accUpdateList;
            Constants.CN_ACCOUNT_TRIGGER_ON = true;
        }
    }
    public void syncContactSyncStatus(Map<Id, CN_Change_Request__c> conSyncStatusMap) {
        List<Contact> conUpdateList = new List<Contact>();

        for(Id conId : conSyncStatusMap.keySet()) {
            CN_Change_Request__c cr = conSyncStatusMap.get(conId);
            Contact con = new Contact();
            con.Id = conId;
            con.CN_Latest_CR_Sync_Status__c = cr.CN_Sync_Status__c;
            con.CN_Latest_CR_Sync_Time__c = cr.CN_Sync_Time__c;
            con.CN_Latest_CR_Sync_Error_Message__c = cr.CN_Sync_Error_Message__c;
            con.CN_Change_Request__c = cr.Id;
            if(cr.recordTypeId == appdNewContactRTId && Constants.CN_CR_SYNC_STATUS_SUCCESS.equals(cr.CN_Sync_Status__c)){
                con.CN_Up_Code__c = cr.CN_SAP_ID__c;
            }

            //add by leo 2023.12.10 CN_Has_CR_Need_Sync must be False when sync Contact to E-Commerce
            if(Constants.CN_CR_SYNC_STATUS_SUCCESS.equals(cr.CN_Sync_Status__c) || Constants.CN_CR_SYNC_STATUS_NO_NEED_TO_SYNC.equals(cr.CN_Sync_Status__c)){
                con.CN_Has_CR_Need_Sync__c = false;
            }
            //add by leo 2023.12.10 CN_Has_CR_Need_Sync must be False when sync Contact to E-Commerce

            conUpdateList.add(con);
        }
        if(conUpdateList.size() > 0) {
            Constants.CN_CONTACT_TRIGGER_ON = false;
            update conUpdateList;
            Constants.CN_CONTACT_TRIGGER_ON = true;
        }
    }
    public void syncShipToSyncStatus(Map<Id, CN_Change_Request__c> shipToSyncStatusMap) {
        List<CN_Ship_to_Party__c> shipToUpdateList = new List<CN_Ship_to_Party__c>();

        for(Id stpId : shipToSyncStatusMap.keyset()) {
            CN_Change_Request__c cr = shipToSyncStatusMap.get(stpId);
            CN_Ship_to_Party__c stp = new CN_Ship_to_Party__c();
            stp.Id = stpId;
            stp.CN_Latest_CR_Sync_Status__c = cr.CN_Sync_Status__c;
            stp.CN_Latest_CR_Sync_Time__c = cr.CN_Sync_Time__c;
            stp.CN_Latest_CR_Sync_Error_Message__c = cr.CN_Sync_Error_Message__c;
            stp.CN_Change_Request__c = cr.Id;
            if(cr.recordTypeId == appdNewShipToRTId && Constants.CN_CR_SYNC_STATUS_SUCCESS.equals(cr.CN_Sync_Status__c)){
                stp.CN_Up_Code__c = cr.CN_SAP_ID__c;
            }

            shipToUpdateList.add(stp);
        }
        if(shipToUpdateList.size() > 0) {
            Constants.CN_SHIPTO_TRIGGER_ON = false;
            update shipToUpdateList;
            Constants.CN_SHIPTO_TRIGGER_ON = true;
        }
    }
}