objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Approve_Step__c</fullName>
        <label>Approve Step</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Step1</fullName>
                </value>
                <value>
                    <fullName>Step2</fullName>
                </value>
                <value>
                    <fullName>Step3</fullName>
                </value>
                <value>
                    <fullName>Step4</fullName>
                </value>
                <value>
                    <fullName>Step5</fullName>
                </value>
                <value>
                    <fullName>Step6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Reference_Day__c</fullName>
        <label>Reference Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery_Day</fullName>
                    <label>Delivery Day</label>
                </value>
                <value>
                    <fullName>Fapiao_Day</fullName>
                    <label>Fapiao Day</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sync_Status__c</fullName>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Credit_Term_Application__c.object
<CustomObject>
    <fields>
        <fullName>CN_Account__c</fullName>
        <label>Sold-to Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Term Applications</relationshipLabel>
        <relationshipName>Credit_Term_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Approve_Step__c</fullName>
        <label>Approve Step</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Step1</fullName>
                </value>
                <value>
                    <fullName>Step2</fullName>
                </value>
                <value>
                    <fullName>Step3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Company_Background__c</fullName>
        <label>Company Background</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_Credit_Limit_Incl_VAT__c</fullName>
        <label>Credit Limit (incl VAT)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <formula>CN_Account__r.CN_License_Name_EN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>License Name(EN)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Nature_Of_Request__c</fullName>
        <label>Nature of Request</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Regular Customer</fullName>
                </value>
                <value>
                    <fullName>TM1 (Hotel-3month rule)</fullName>
                </value>
                <value>
                    <fullName>TM2 (BAPA-3month rule)</fullName>
                    <label>TM2(Excluding Hotel-3month rule)</label>
                </value>
                <value>
                    <fullName>NO CONTRACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Payment_Term_Negotiated__c</fullName>
        <label>Payment Term Negotiated</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>D005</fullName>
                    <label>D005-D05/5 days after delivery</label>
                </value>
                <value>
                    <fullName>D010</fullName>
                    <label>D010-D10/10 days after delivery</label>
                </value>
                <value>
                    <fullName>D015</fullName>
                    <label>D015-15 days after delivery</label>
                </value>
                <value>
                    <fullName>D020</fullName>
                    <label>D020-20 days, due net</label>
                </value>
                <value>
                    <fullName>D030</fullName>
                    <label>D030-30 days, due net</label>
                </value>
                <value>
                    <fullName>D045</fullName>
                    <label>D045-45 days, due net</label>
                </value>
                <value>
                    <fullName>D060</fullName>
                    <label>D060-60days, due net</label>
                </value>
                <value>
                    <fullName>D090</fullName>
                    <label>D090-90days, due net</label>
                </value>
                <value>
                    <fullName>M110</fullName>
                    <label>M110-10 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M115</fullName>
                    <label>M115-15 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M131</fullName>
                    <label>M131-30 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M145</fullName>
                    <label>M145-Before 15th in 2 months, due net</label>
                </value>
                <value>
                    <fullName>M231</fullName>
                    <label>M231-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>D000</fullName>
                    <isActive>false</isActive>
                    <label>D000-Payment in advance</label>
                </value>
                <value>
                    <fullName>D003-Pay immediately with Invoice</fullName>
                    <isActive>false</isActive>
                    <label>D003-Pay immediately with Invoice</label>
                </value>
                <value>
                    <fullName>D120-120 days, due net</fullName>
                    <isActive>false</isActive>
                    <label>D120-120 days, due net</label>
                </value>
                <value>
                    <fullName>M120-20 th of next month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M120-20 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M23-60 days end of month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M23-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M331-90 days end of month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M331-90 days end of month, due net</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Reasons_For_Applying_For_Credit_Term__c</fullName>
        <label>Reasons for applying for credit term</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_Reference_Day__c</fullName>
        <label>Reference Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery_Day</fullName>
                    <label>Delivery Day</label>
                </value>
                <value>
                    <fullName>Fapiao_Day</fullName>
                    <label>Fapiao Day</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Credit Term Application</label>
    <nameField>
        <displayFormat>CA{0000000000}</displayFormat>
        <label>Credit Term Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Term Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_CTA_Approve_Aging_Handler_Test.cls
/**************************************************************************************************
 * Name           : CN_CTA_Approve_Aging_Handler_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Du Dezheng
 * Create Date    : 2021-06-10
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_CTA_Approve_Aging_Handler_Test {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }
    @isTest
    private static void handleBeforeUpdateTest() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();

        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }

        User salesRep = [SELECT Id FROM User WHERE lastName = 'Sales1'][0];
        Account acc_factory = [SELECT Id FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];
        
        System.runAs(salesRep) {
            Id newDirectRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.CN_Account_RT_API_NAME_NEW_DIRECT).getRecordTypeId();
            Id editDirectRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.CN_Account_RT_API_NAME_EDIT_DIRECT).getRecordTypeId();
            Id newInDirectRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.CN_Account_RT_API_NAME_NEW_INDIRECT).getRecordTypeId();

            CN_Credit_Term_Application__c cta = new CN_Credit_Term_Application__c();
            cta.CN_Account__c = acc_factory.Id;
            cta.CN_Company_Background__c = 'company background';
            cta.CN_Nature_Of_Request__c = 'Regular Customer	';
            cta.CN_Payment_Term_Negotiated__c = 'D005';
            cta.CN_Reference_Day__c = 'Delivery_Day';
            cta.CN_Credit_Limit_Incl_VAT__c = 113.00;
            cta.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            insert cta;

            Account updateAcc = new Account();
            updateAcc.Id = acc_factory.Id;
            updateAcc.CN_Account_Status__c = Constants.CN_ACCOUNT_ACCOUNT_STATUS_READY_FOR_APPROVAL;
            update updateAcc;

            updateAcc = new Account();
            updateAcc.Id = acc_factory.Id;
            updateAcc.CN_Account_Status__c = Constants.CN_ACCOUNT_ACCOUNT_STATUS_SUBMITTED_FOR_APPROVAL;
            updateAcc.CN_Approve_Step__c = 'Step1';
            update updateAcc;

            updateAcc = new Account();
            updateAcc.Id = acc_factory.Id;
            updateAcc.CN_Account_Status__c = Constants.CN_ACCOUNT_ACCOUNT_STATUS_APPROVED;
            updateAcc.CN_Sync_Status__c = Constants.CN_ACCOUNT_SYNC_STATUS_SUCCESS;
            update updateAcc;

            Test.startTest();
            CN_Credit_Term_Application__c cta_update = new CN_Credit_Term_Application__c();
            cta_update.Id = cta.Id;
            cta_update.CN_Status__c = Constants.CN_CTA_STATUS_READY_FOR_APPROVAL;
            update cta_update;

            CN_Credit_Term_Application__c cta_update2 = new CN_Credit_Term_Application__c();
            cta_update2.Id = cta.Id;
            cta_update2.CN_Status__c = Constants.CN_CTA_STATUS_SUBMITTED_FOR_APPROVAL;
            cta_update2.CN_Approve_Step__c = 'Step1';
            update cta_update2;
            Test.stopTest();

        }
    }
}