objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Source__c</fullName>
        <label>Account Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Recommend</fullName>
                </value>
                <value>
                    <fullName>Cold Visit</fullName>
                </value>
                <value>
                    <fullName>Public Demo</fullName>
                </value>
                <value>
                    <fullName>Brand Activity</fullName>
                </value>
                <value>
                    <fullName>Expositions</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Social Media Network</fullName>
                </value>
                <value>
                    <fullName>Marketing Campaign</fullName>
                </value>
                <value>
                    <fullName>Digital Campaign</fullName>
                </value>
                <value>
                    <fullName>Bakery China</fullName>
                </value>
                <value>
                    <fullName>CIIE</fullName>
                </value>
                <value>
                    <fullName>FHC</fullName>
                </value>
                <value>
                    <fullName>Other Trade show</fullName>
                </value>
                <value>
                    <fullName>Sponsorship Event</fullName>
                </value>
                <value>
                    <fullName>Customer Service Hotline</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_City_CN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City(CN)</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>CN_City__c.CN_Province__c</field>
                <operation>equals</operation>
                <valueField>$Source.CN_Province_CN__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_City__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_City_Code__c</fullName>
        <formula>CN_City_CN__r.CN_City_Code__c</formula>
        <label>City Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Delivery_Plant__c</fullName>
        <label>Delivery Plant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P011</fullName>
                    <label>P011-SINODIS ShangHai External-西诺迪斯（上海） 外部</label>
                </value>
                <value>
                    <fullName>P020</fullName>
                    <label>P020-SINODIS BeiJing-西诺迪斯（北京）</label>
                </value>
                <value>
                    <fullName>P040</fullName>
                    <label>P040-SINODIS GuangZhou-西诺迪斯（广州）</label>
                </value>
                <value>
                    <fullName>P050</fullName>
                    <label>P050-SINODIS Chengdu-西诺迪斯（成都）</label>
                </value>
                <value>
                    <fullName>P060</fullName>
                    <label>P060-SINODIS Dalian-西诺迪斯（大连）</label>
                </value>
                <value>
                    <fullName>P010</fullName>
                    <isActive>false</isActive>
                    <label>P010-SINODIS ShangHai-西诺迪斯（上海）</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Post_Code__c</fullName>
        <label>Post Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Province_CN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province(CN)</label>
        <referenceTo>CN_Province__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Province_EN__c</fullName>
        <formula>CN_Province_CN__r.Province_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Province(EN) API</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_City__c.object
<CustomObject>
    <fields>
        <fullName>CN_City_CN__c</fullName>
        <label>City(CN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_City_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>City Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Citys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Province__c.object
<CustomObject>
    <fields>
        <fullName>CN_Province_CN__c</fullName>
        <label>Province(CN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Province_EN__c</fullName>
        <label>Province(EN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Province Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Province</label>
    <nameField>
        <label>Province Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provinces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Ship_to_Party__c.object
<CustomObject>
    <fields>
        <fullName>CN_City_CN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City(CN)</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>CN_City__c.CN_Province__c</field>
                <operation>equals</operation>
                <valueField>$Source.CN_Province_CN__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_City__c</referenceTo>
        <relationshipLabel>Ship to Parties</relationshipLabel>
        <relationshipName>Ship_to_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Customer_Name_EN__c</fullName>
        <label>Ship To Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Customer_Name__c</fullName>
        <inlineHelpText>Please input license name + store name.</inlineHelpText>
        <label>Ship To Name(CN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Delivery_Address_CN__c</fullName>
        <label>Delivery Address(CN)</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Delivery_Address_EN__c</fullName>
        <label>Delivery Address (EN)</label>
        <length>220</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Delivery_Plant__c</fullName>
        <label>Delivery Plant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P011</fullName>
                    <label>P011-SINODIS ShangHai External-西诺迪斯（上海） 外部</label>
                </value>
                <value>
                    <fullName>P020</fullName>
                    <label>P020-SINODIS BeiJing-西诺迪斯（北京）</label>
                </value>
                <value>
                    <fullName>P040</fullName>
                    <label>P040-SINODIS GuangZhou-西诺迪斯（广州）</label>
                </value>
                <value>
                    <fullName>P050</fullName>
                    <label>P050-SINODIS Chengdu-西诺迪斯（成都）</label>
                </value>
                <value>
                    <fullName>P060</fullName>
                    <label>P060-SINODIS Dalian-西诺迪斯（大连）</label>
                </value>
                <value>
                    <fullName>P010</fullName>
                    <isActive>false</isActive>
                    <label>P010-SINODIS ShangHai-西诺迪斯（上海）</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Indirect_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Indirect Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship to Parties (Indirect Account)</relationshipLabel>
        <relationshipName>Ship_to_Parties1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Mobile_Phone__c</fullName>
        <inlineHelpText>Please enter the number in the format of 1XXXXXXXXXX or XXX-XXXXXXXX or XXXX-XXXXXXXX-XXX (X is number).</inlineHelpText>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CN_Post_Code__c</fullName>
        <formula>CN_Sold_To_Party_Customer__r.CN_Post_Code__c</formula>
        <label>Post Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Province_CN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province(CN)</label>
        <referenceTo>CN_Province__c</referenceTo>
        <relationshipLabel>Ship to Parties (Province(CN))</relationshipLabel>
        <relationshipName>Ship_to_Parties1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Province_EN__c</fullName>
        <formula>CN_Province_CN__r.Province_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Province(EN) API</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sold_To_Party_Customer__c</fullName>
        <label>Sold-to Party Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5 AND 6) OR 7</booleanFilter>
            <errorMessage>You can only select Account whose Status is New.</errorMessage>
            <filterItems>
                <field>Account.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>New</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship to Party</value>
            </filterItems>
            <filterItems>
                <field>$Source.CN_Change_Request__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.CN_Change_Request__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship to Party</value>
            </filterItems>
            <filterItems>
                <field>Account.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship to Parties</relationshipLabel>
        <relationshipName>Ship_to_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Telephone__c</fullName>
        <inlineHelpText>Please enter the number in the format of 1XXXXXXXXXX or XXX-XXXXXXXX or XXXX-XXXXXXXX-XXX (X is number).</inlineHelpText>
        <label>Telephone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CN_UP_Code__c</fullName>
        <externalId>true</externalId>
        <label>UP code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Ship to Party</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Ship to Party Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ship to Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_ShipTo_Upsert_To_Mg_Batch.cls
/*
 * ************************************************************************************************
 * Name : CN_ShipTo_Upsert_To_Mg_Batch
 * Object :
 * Requirement : AC-009
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2023/4/24
 * Modify History :
 * ************************************************************************************************
 */
public class CN_ShipTo_Upsert_To_Mg_Batch  implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful{

	public Iterable<SObject> start(Database.BatchableContext bc) {
		List<CN_Ship_to_Party__c> newList = [SELECT ID,CN_ShipTo_Address_ID__c,CN_City_CN__r.CN_City_Code__c,
		CN_Contact_Name__c,CN_Customer_Name_EN__c,CN_Delivery_Address_EN__c,CN_Delivery_Address_CN__c,CN_Delivery_Plant__c,
		CN_Indirect_Account__r.CN_MG_Account_ID__c,
		CN_Mobile_Phone__c,CN_Province_CN__r.CN_Province_EN__c,CN_Province_CN__r.Province_Code__c,CN_Customer_Name__c,
		CN_Sold_To_Party_Customer__r.CN_MG_Account_ID__c,
		CN_Sold_To_Party_Customer__r.CN_Lead_MG_Contact_Id__c,
		CN_UP_Code__c,CN_Post_Code__c,
		CN_Telephone__c,CN_Inactive__c FROM CN_Ship_to_Party__c
		WHERE CN_Need_Send_MG__c = true
		AND CN_Sold_To_Party_Customer__r.CN_Account_Source__c = :Constants.CN_ACCOUNT_SOURCE_ECOMMERCE
		AND CN_UP_Code__c != null
		ORDER BY LastModifiedDate DESC
		];

		return newList;
	}

	public void execute(Database.BatchableContext bc, List<SObject> shipToList){
		List<CN_Ship_to_Party__c> sendSuccess =  CN_ShipTo_Upsert_To_Mg_Callout.upsertShipToAddress((List<CN_Ship_to_Party__c>) shipToList);
		if(sendSuccess.size() > 0){
			try {
				update sendSuccess;
			} catch (Exception e){
				CN_HelperClass_WS.WS_Log log = new CN_HelperClass_WS.WS_Log();
				log.SetResult(0,'DML Exception' + e.getMessage(),e.getStackTraceString() + e.getCause());
				log.Save();
			}
		}
	}

	public void finish(Database.BatchableContext bc) {

	}
}