objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Source__c</fullName>
        <label>Account Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Recommend</fullName>
                </value>
                <value>
                    <fullName>Cold Visit</fullName>
                </value>
                <value>
                    <fullName>Public Demo</fullName>
                </value>
                <value>
                    <fullName>Brand Activity</fullName>
                </value>
                <value>
                    <fullName>Expositions</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Social Media Network</fullName>
                </value>
                <value>
                    <fullName>Marketing Campaign</fullName>
                </value>
                <value>
                    <fullName>Digital Campaign</fullName>
                </value>
                <value>
                    <fullName>Bakery China</fullName>
                </value>
                <value>
                    <fullName>CIIE</fullName>
                </value>
                <value>
                    <fullName>FHC</fullName>
                </value>
                <value>
                    <fullName>Other Trade show</fullName>
                </value>
                <value>
                    <fullName>Sponsorship Event</fullName>
                </value>
                <value>
                    <fullName>Customer Service Hotline</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Contact_Name_EN__c</fullName>
        <label>Contact Name(EN)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Department_of_Contact_Person__c</fullName>
        <label>Department of Contact Person</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0001-Purchasing Dept</fullName>
                </value>
                <value>
                    <fullName>0002-Sales Dept</fullName>
                </value>
                <value>
                    <fullName>0003-Administration Dept</fullName>
                </value>
                <value>
                    <fullName>0004-Production Dept</fullName>
                </value>
                <value>
                    <fullName>0005-QA Dept</fullName>
                </value>
                <value>
                    <fullName>0006-Secretary&apos;s Office</fullName>
                </value>
                <value>
                    <fullName>0007-Financial Dept</fullName>
                </value>
                <value>
                    <fullName>0008-Legal Dept</fullName>
                </value>
                <value>
                    <fullName>0009-Human Resources Dept</fullName>
                </value>
                <value>
                    <fullName>0010-General Affairs Dept</fullName>
                </value>
                <value>
                    <fullName>0011-Sales Promotion Dept</fullName>
                </value>
                <value>
                    <fullName>0012-International Dept</fullName>
                </value>
                <value>
                    <fullName>0013-Export Dept</fullName>
                </value>
                <value>
                    <fullName>0014-Import Dept</fullName>
                </value>
                <value>
                    <fullName>0015-Public Relation Dept</fullName>
                </value>
                <value>
                    <fullName>0016-Advertising Dept</fullName>
                </value>
                <value>
                    <fullName>0017-Planning Dept</fullName>
                </value>
                <value>
                    <fullName>0018-R&amp;D Dept</fullName>
                </value>
                <value>
                    <fullName>0019-Product Dev. Dept</fullName>
                </value>
                <value>
                    <fullName>0020-Food &amp; Beverage Dept</fullName>
                </value>
                <value>
                    <fullName>0021-Service Dept</fullName>
                </value>
                <value>
                    <fullName>0022-Technical Support</fullName>
                </value>
                <value>
                    <fullName>0023-IT Dept</fullName>
                </value>
                <value>
                    <fullName>0024-Logistics Dept</fullName>
                </value>
                <value>
                    <fullName>0025-Cold Kitchen</fullName>
                </value>
                <value>
                    <fullName>0026-Hot Kitchen</fullName>
                </value>
                <value>
                    <fullName>0027-Banquet Kitchen</fullName>
                </value>
                <value>
                    <fullName>0028-Pastry</fullName>
                </value>
                <value>
                    <fullName>0029-Backery</fullName>
                </value>
                <value>
                    <fullName>0030-Bar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CN_Bill_To_Address__c</fullName>
        <label>Bill To Address</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Contact_Name_EN__c</fullName>
        <label>Contact Name(EN)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>01-Billing</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>02-Business</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>04-Others</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <isActive>false</isActive>
                    <label>03-Receiving</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Department_Of_Contact_Person__c</fullName>
        <label>Department of Contact Person</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0001</fullName>
                    <label>0001-Purchasing Dept</label>
                </value>
                <value>
                    <fullName>0002</fullName>
                    <label>0002-Sales Dept</label>
                </value>
                <value>
                    <fullName>0003</fullName>
                    <label>0003-Administration Dept</label>
                </value>
                <value>
                    <fullName>0004</fullName>
                    <label>0004-Production Dept</label>
                </value>
                <value>
                    <fullName>0005</fullName>
                    <label>0005-QA Dept</label>
                </value>
                <value>
                    <fullName>0006</fullName>
                    <label>0006-Secretary&apos;s Office</label>
                </value>
                <value>
                    <fullName>0007</fullName>
                    <label>0007-Financial Dept</label>
                </value>
                <value>
                    <fullName>0008</fullName>
                    <label>0008-Legal Dept</label>
                </value>
                <value>
                    <fullName>0009</fullName>
                    <label>0009-Human Resources Dept</label>
                </value>
                <value>
                    <fullName>0010</fullName>
                    <label>0010-General Affairs Dept</label>
                </value>
                <value>
                    <fullName>0011</fullName>
                    <label>0011-Sales Promotion Dept</label>
                </value>
                <value>
                    <fullName>0012</fullName>
                    <label>0012-International Dept</label>
                </value>
                <value>
                    <fullName>0013</fullName>
                    <label>0013-Export Dept</label>
                </value>
                <value>
                    <fullName>0014</fullName>
                    <label>0014-Import Dept</label>
                </value>
                <value>
                    <fullName>0015</fullName>
                    <label>0015-Public Relation Dept</label>
                </value>
                <value>
                    <fullName>0016</fullName>
                    <label>0016-Advertising Dept</label>
                </value>
                <value>
                    <fullName>0017</fullName>
                    <label>0017-Planning Dept</label>
                </value>
                <value>
                    <fullName>0018</fullName>
                    <label>0018-R&amp;D Dept</label>
                </value>
                <value>
                    <fullName>0019</fullName>
                    <label>0019-Product Dev. Dept</label>
                </value>
                <value>
                    <fullName>0020</fullName>
                    <label>0020-Food &amp; Beverage Dept</label>
                </value>
                <value>
                    <fullName>0021</fullName>
                    <label>0021-Service Dept</label>
                </value>
                <value>
                    <fullName>0022</fullName>
                    <label>0022-Technical Support</label>
                </value>
                <value>
                    <fullName>0023</fullName>
                    <label>0023-IT Dept</label>
                </value>
                <value>
                    <fullName>0024</fullName>
                    <label>0024-Logistics Dept</label>
                </value>
                <value>
                    <fullName>0025</fullName>
                    <label>0025-Cold Kitchen</label>
                </value>
                <value>
                    <fullName>0026</fullName>
                    <label>0026-Hot Kitchen</label>
                </value>
                <value>
                    <fullName>0027</fullName>
                    <label>0027-Banquet Kitchen</label>
                </value>
                <value>
                    <fullName>0028</fullName>
                    <label>0028-Pastry</label>
                </value>
                <value>
                    <fullName>0029</fullName>
                    <label>0029-Backery</label>
                </value>
                <value>
                    <fullName>0030</fullName>
                    <label>0030-Bar</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Contact_Send_Mg_Mark_Handler_Test.cls
/*
 * ************************************************************************************************
 * Name : CN_Contact_Send_Mg_Mark_Handler_Test
 * Object :
 * Requirement : CT-014 Test
 * Target :
 * Refer classes :
 * Author : ZZH
 * Create Date : 2024/1/1
 * Modify History :
 * ************************************************************************************************
 */
@isTest
public class CN_Contact_Send_Mg_Mark_Handler_Test {

    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }

    
    @isTest
    static void testHandleBeforeInsert1() {

        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();
        Account account = [SELECT Id, Name, CN_MG_Account_ID__c FROM Account WHERE CN_MG_Account_ID__c = '1'];

        Contact con = new Contact();
        con.AccountId = account.Id;
        con.CN_Contact_Type__c = '02';
        con.Title = 'CEO';
        con.CN_Department_Of_Contact_Person__c = '0001';
        con.CN_Contact_Name_EN__c = account.Name + 'Test Contact1';
        con.LastName = 'Contact1';
        con.MobilePhone = '13013001301';
        con.CN_Bill_To_Address__c = 'ABCDE1';
        con.CN_MG_Contact_ID__c = account.CN_MG_Account_ID__c;
        insert con;

    }

    @isTest
    static void testHandleBeforeInsert2() {

        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();
        Account account = [SELECT Id, Name, CN_MG_Account_ID__c FROM Account WHERE CN_MG_Account_ID__c = '1'];
        account.CN_Account_Source__c = 'Customer Service Hotline';
        update account;

        Contact con = new Contact();
        con.AccountId = account.Id;
        con.CN_Contact_Type__c = '02';
        con.Title = 'CEO';
        con.CN_Department_Of_Contact_Person__c = '0001';
        con.CN_Contact_Name_EN__c = account.Name + 'Test Contact1';
        con.LastName = 'Contact1';
        con.MobilePhone = '13013001301';
        con.CN_Bill_To_Address__c = 'ABCDE1';
        con.CN_MG_Contact_ID__c = account.CN_MG_Account_ID__c;
        insert con;

    }

    @isTest
    static void testHandleBeforeInsert3() {

        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();
        Account account = [SELECT Id, Name, CN_MG_Account_ID__c FROM Account WHERE CN_MG_Account_ID__c = '1'];
        account.CN_Account_Source__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
        update account;

        Contact con = new Contact();
        con.AccountId = account.Id;
        con.CN_Contact_Type__c = '02';
        con.Title = 'CEO';
        con.CN_Department_Of_Contact_Person__c = '0001';
        con.CN_Contact_Name_EN__c = account.Name + 'Test Contact1';
        con.LastName = 'Contact1';
        con.MobilePhone = '13013001301';
        con.CN_Bill_To_Address__c = 'ABCDE1';
        con.CN_MG_Contact_ID__c = account.CN_MG_Account_ID__c;
        insert con;

    }
    
    @isTest
    static void testHandleBeforeUpdate1() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();
        Account account = [SELECT Id, Name, CN_MG_Account_ID__c FROM Account WHERE CN_MG_Account_ID__c = '1'];
        account.CN_Account_Source__c = null;
        update account;

        Contact contact =  [select id,Name,CN_MG_Contact_Id__c  from Contact WHERE CN_MG_Contact_ID__c = '1'];
        contact.LastName = 'TestUpdate';
        contact.AccountId = account.Id;
        update contact;
    }

    @isTest
    static void testHandleBeforeUpdate2() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();
        Account account = [SELECT Id, Name, CN_MG_Account_ID__c FROM Account WHERE CN_MG_Account_ID__c = '1'];
        account.CN_Account_Source__c = 'Customer Service Hotline';
        update account;

        Contact contact =  [select id,Name,CN_MG_Contact_Id__c  from Contact WHERE CN_MG_Contact_ID__c = '1'];
        contact.LastName = 'TestUpdate';
        contact.AccountId = account.Id;
        update contact;
    }

    @isTest
    static void testHandleBeforeUpdate3() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();

        Contact contact =  [select id,Name,CN_MG_Contact_Id__c  from Contact WHERE CN_MG_Contact_ID__c = '1'];
        contact.LastName = 'TestUpdate';
        contact.AccountId = null;
        update contact;
    }

    @isTest
    static void testHandleBeforeUpdate4() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();
        Account account = [SELECT Id, Name, CN_MG_Account_ID__c FROM Account WHERE CN_MG_Account_ID__c = '1'];
        account.CN_Account_Source__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
        update account;

        Contact contact =  [select id,Name,CN_MG_Contact_Id__c  from Contact WHERE CN_MG_Contact_ID__c = '1'];
        contact.LastName = 'TestUpdate';
        contact.AccountId = account.Id;
        update contact;
    }
}