objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Billing_Block_Date__c</fullName>
        <label>Billing Block Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Billing_Block__c</fullName>
        <label>Billing Block</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>01    Calculation Missing</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>02    Compl Confirm Missng</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>03    Prices Incomplete</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>04    Check Terms of Paymt</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>05    Check Terms of Dlv</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>08    Check Credit Memo</label>
                </value>
                <value>
                    <fullName>09</fullName>
                    <label>09    Check Debit Memo</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10-YH Rejected by Customer</label>
                </value>
                <value>
                    <fullName>S0</fullName>
                    <label>S0-Overdue Payment</label>
                </value>
                <value>
                    <fullName>S1</fullName>
                    <label>S1-Credit Limit</label>
                </value>
                <value>
                    <fullName>S2</fullName>
                    <label>S2-Food License Lack</label>
                </value>
                <value>
                    <fullName>S3</fullName>
                    <label>S3-Addr. certif. Lack</label>
                </value>
                <value>
                    <fullName>S4</fullName>
                    <label>S4-Others License Lack</label>
                </value>
                <value>
                    <fullName>S5</fullName>
                    <label>S5-Missing Order</label>
                </value>
                <value>
                    <fullName>S6</fullName>
                    <label>S6-Obsolete</label>
                </value>
                <value>
                    <fullName>S7</fullName>
                    <label>S7-Inactive SF</label>
                </value>
                <value>
                    <fullName>S8</fullName>
                    <label>S8-Legal Case</label>
                </value>
                <value>
                    <fullName>YH</fullName>
                    <isActive>false</isActive>
                    <label>YH Rejected by Customer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Delivery_Block_Date__c</fullName>
        <label>Delivery Block Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Delivery_Block__c</fullName>
        <label>Delivery Block</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>01 Credit limit</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>02 Waitting confirm</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>03 Bottleneck material</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>04 Export papers missng</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>05 Check free of ch.dlv</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>06 No printing</label>
                </value>
                <value>
                    <fullName>07</fullName>
                    <label>07 Change in quantity</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>08 Kanban Delivery</label>
                </value>
                <value>
                    <fullName>09</fullName>
                    <label>09 JIT delivery (PDS)</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10 Not achieve MOQ</label>
                </value>
                <value>
                    <fullName>S0</fullName>
                    <label>S0-Overdue Payment</label>
                </value>
                <value>
                    <fullName>S1</fullName>
                    <label>S1-Credit Limit</label>
                </value>
                <value>
                    <fullName>S2</fullName>
                    <label>S2-Food License Lack</label>
                </value>
                <value>
                    <fullName>S3</fullName>
                    <label>S3-Addr. certif. Lack</label>
                </value>
                <value>
                    <fullName>S4</fullName>
                    <label>S4-Others License Lack</label>
                </value>
                <value>
                    <fullName>S5</fullName>
                    <label>S5-Missing Order</label>
                </value>
                <value>
                    <fullName>S6</fullName>
                    <label>S6-Obsolete</label>
                </value>
                <value>
                    <fullName>S7</fullName>
                    <label>S7-Inactive SF</label>
                </value>
                <value>
                    <fullName>S8</fullName>
                    <label>S8-Legal Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Is_TM_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is TM Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Order_Block_Date__c</fullName>
        <label>Order Block Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Order_Block__c</fullName>
        <label>Order Block</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>01    Overall block</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>02    All free of charge</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>03    Test block</label>
                </value>
                <value>
                    <fullName>99</fullName>
                    <label>99    test (e)</label>
                </value>
                <value>
                    <fullName>S0</fullName>
                    <label>S0-Overdue Payment</label>
                </value>
                <value>
                    <fullName>S1</fullName>
                    <label>S1-Credit Limit</label>
                </value>
                <value>
                    <fullName>S2</fullName>
                    <label>S2-Food License Lack</label>
                </value>
                <value>
                    <fullName>S3</fullName>
                    <label>S3-Addr. certif. Lack</label>
                </value>
                <value>
                    <fullName>S4</fullName>
                    <label>S4-Others License Lack</label>
                </value>
                <value>
                    <fullName>S5</fullName>
                    <label>S5-Missing Order</label>
                </value>
                <value>
                    <fullName>S6</fullName>
                    <label>S6-Obsolete</label>
                </value>
                <value>
                    <fullName>S7</fullName>
                    <label>S7-Inactive SF</label>
                </value>
                <value>
                    <fullName>S8</fullName>
                    <label>S8-Legal Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_TM_Remove_Date__c</fullName>
        <label>TM Remove Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CN_Account_TM_REPORT_Handler.cls
public without sharing class CN_Account_TM_REPORT_Handler implements Triggers.Handler {
    public void handle() {
        if(Trigger.isBefore && Trigger.isUpdate) {
            handleAfterUpdate();
        }   
    }

    public void handleAfterUpdate() {
        List<Account> accList = new List<Account>();
        for(Account acc : (List<Account>)Trigger.New) {
            Account oldAccount = (Account)Trigger.oldMap.get(acc.Id);
            if (acc.CN_Account_Status__c == 'Approved' && oldAccount.CN_Account_Status__c == 'Submitted for Approval' && acc.name.substring(0,2).equals('TM')) {
                //是否TM 客户 ： 客户审批通过时， 客户名称以TM 开头， 则是TM 客户 
                acc.CN_Is_TM_Account__c = true;
            }
            if(acc.CN_Customer_Code__c != null && oldAccount.CN_Customer_Code__c == null){
                //开户日期 ： SAP 代码生成时， 更新改日期
                acc.CN_Open_Date__c = system.today();
            }
            if(!acc.name.substring(0,2).equals('TM') && oldAccount.name.substring(0,2).equals('TM')){
                //TM变更日期 ：当客户名称 去除了 TM 开头，并审批通过时, 则更新该日期为当前日期 
                acc.CN_TM_Remove_Date__c = system.today();
            }
            if(acc.CN_Order_Block__c != null && oldAccount.CN_Order_Block__c == null){
                //Order Block  Date :  Order Block 有值时，更新成当前日期 ； Order Block 从有值更新为空时，清空
                acc.CN_Order_Block_Date__c = system.today();
            }else if(acc.CN_Order_Block__c == null && oldAccount.CN_Order_Block__c != null){
                acc.CN_Order_Block_Date__c = null;
            }
            if(acc.CN_Delivery_Block__c != null && oldAccount.CN_Delivery_Block__c == null){
                //Delivery Block Date ： Delivery Block 有值时，更新成当前日期 ； Delivery Block从有值更新为空时，清空
                acc.CN_Delivery_Block_Date__c = system.today();
            }else if(acc.CN_Delivery_Block__c == null && oldAccount.CN_Delivery_Block__c != null){
                acc.CN_Delivery_Block_Date__c = null;
            }
            if(acc.CN_Billing_Block__c != null && oldAccount.CN_Billing_Block__c == null){
                //Billing Block Date : Billing Block  有值时，更新成当前日期 ； Billing Block从有值更新为空时，清空 
                acc.CN_Billing_Block_Date__c = system.today();
            }else if(acc.CN_Billing_Block__c == null && oldAccount.CN_Billing_Block__c != null){
                acc.CN_Billing_Block_Date__c = null;
            }
        }
    }
}