objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Approve_Step__c</fullName>
        <label>Approve Step</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Step1</fullName>
                </value>
                <value>
                    <fullName>Step2</fullName>
                </value>
                <value>
                    <fullName>Step3</fullName>
                </value>
                <value>
                    <fullName>Step4</fullName>
                </value>
                <value>
                    <fullName>Step5</fullName>
                </value>
                <value>
                    <fullName>Step6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Business_Unit__c</fullName>
        <formula>CN_Business_Unit_UI__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_City_Code__c</fullName>
        <formula>CN_City_CN__r.CN_City_Code__c</formula>
        <label>City Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Reference_Day__c</fullName>
        <label>Reference Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery_Day</fullName>
                    <label>Delivery Day</label>
                </value>
                <value>
                    <fullName>Fapiao_Day</fullName>
                    <label>Fapiao Day</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sales_Team__c</fullName>
        <formula>CN_Sales_Team_UI__r.CN_Sales_Team_Code__c</formula>
        <label>Sales Team</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Business_Unit__c.object
<CustomObject>
    <fields>
        <fullName>CN_Business_Unit_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Business Unit Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_City__c.object
<CustomObject>
    <fields>
        <fullName>CN_City_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>City Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Province__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province</label>
        <referenceTo>CN_Province__c</referenceTo>
        <relationshipLabel>Citys (Province)</relationshipLabel>
        <relationshipName>Citys1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Citys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Credit_Term_Application__c.object
<CustomObject>
    <fields>
        <fullName>CN_Account__c</fullName>
        <label>Sold-to Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Term Applications</relationshipLabel>
        <relationshipName>Credit_Term_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Approve_Step__c</fullName>
        <label>Approve Step</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Step1</fullName>
                </value>
                <value>
                    <fullName>Step2</fullName>
                </value>
                <value>
                    <fullName>Step3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Business_Unit__c</fullName>
        <formula>CN_Account__r.CN_Business_Unit_UI__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Company_Background__c</fullName>
        <label>Company Background</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_Credit_Limit_Incl_VAT__c</fullName>
        <label>Credit Limit (incl VAT)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Nature_Of_Request__c</fullName>
        <label>Nature of Request</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Regular Customer</fullName>
                </value>
                <value>
                    <fullName>TM1 (Hotel-3month rule)</fullName>
                </value>
                <value>
                    <fullName>TM2 (BAPA-3month rule)</fullName>
                    <label>TM2(Excluding Hotel-3month rule)</label>
                </value>
                <value>
                    <fullName>NO CONTRACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Payment_Term_Negotiated__c</fullName>
        <label>Payment Term Negotiated</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>D005</fullName>
                    <label>D005-D05/5 days after delivery</label>
                </value>
                <value>
                    <fullName>D010</fullName>
                    <label>D010-D10/10 days after delivery</label>
                </value>
                <value>
                    <fullName>D015</fullName>
                    <label>D015-15 days after delivery</label>
                </value>
                <value>
                    <fullName>D020</fullName>
                    <label>D020-20 days, due net</label>
                </value>
                <value>
                    <fullName>D030</fullName>
                    <label>D030-30 days, due net</label>
                </value>
                <value>
                    <fullName>D045</fullName>
                    <label>D045-45 days, due net</label>
                </value>
                <value>
                    <fullName>D060</fullName>
                    <label>D060-60days, due net</label>
                </value>
                <value>
                    <fullName>D090</fullName>
                    <label>D090-90days, due net</label>
                </value>
                <value>
                    <fullName>M110</fullName>
                    <label>M110-10 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M115</fullName>
                    <label>M115-15 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M131</fullName>
                    <label>M131-30 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M145</fullName>
                    <label>M145-Before 15th in 2 months, due net</label>
                </value>
                <value>
                    <fullName>M231</fullName>
                    <label>M231-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>D000</fullName>
                    <isActive>false</isActive>
                    <label>D000-Payment in advance</label>
                </value>
                <value>
                    <fullName>D003-Pay immediately with Invoice</fullName>
                    <isActive>false</isActive>
                    <label>D003-Pay immediately with Invoice</label>
                </value>
                <value>
                    <fullName>D120-120 days, due net</fullName>
                    <isActive>false</isActive>
                    <label>D120-120 days, due net</label>
                </value>
                <value>
                    <fullName>M120-20 th of next month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M120-20 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M23-60 days end of month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M23-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M331-90 days end of month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M331-90 days end of month, due net</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Reasons_For_Applying_For_Credit_Term__c</fullName>
        <label>Reasons for applying for credit term</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_Reference_Day__c</fullName>
        <label>Reference Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery_Day</fullName>
                    <label>Delivery Day</label>
                </value>
                <value>
                    <fullName>Fapiao_Day</fullName>
                    <label>Fapiao Day</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sales_Team__c</fullName>
        <formula>CN_Account__r.CN_Sales_Team_UI__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Credit Term Application</label>
    <nameField>
        <displayFormat>CA{0000000000}</displayFormat>
        <label>Credit Term Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Term Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Province__c.object
<CustomObject>
    <fields>
        <fullName>Province_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Province Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Province</label>
    <nameField>
        <label>Province Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provinces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Sales_Team__c.object
<CustomObject>
    <fields>
        <fullName>CN_Business_Unit_Code__c</fullName>
        <formula>CN_Business_Unit__r.CN_Business_Unit_Code__c</formula>
        <label>Business Unit Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Business_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Unit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The business unit you choose must have business unit Code.</errorMessage>
            <filterItems>
                <field>CN_Business_Unit__c.CN_Business_Unit_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_Business_Unit__c</referenceTo>
        <relationshipLabel>Sales Teams</relationshipLabel>
        <relationshipName>Sales_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Sales_Team_Code__c</fullName>
        <externalId>true</externalId>
        <label>Sales Team Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <label>Sales Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CN_Sales_Team__c</fullName>
        <label>Sales Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CN_CTA_Populate_Approver_Hander_Test.cls
/**************************************************************************************************
 * Name           : CN_CTA_Populate_Approver_Hander_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Du Dezheng
 * Create Date    : 2021-06-10
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_CTA_Populate_Approver_Hander_Test {

    static List<Account> accList_factory = null;
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }
    @isTest
    private static void handleBeforeUpdateTest() {
        TestDataFactory testDataFactory = new TestDataFactory();
        accList_factory = testDataFactory.makeAccounts(18,false);
        testDataFactory.makeCustomSetting();
        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }

        User salesRep = [SELECT Id FROM User WHERE lastName = 'Sales1'][0];
        CN_Province__c province = [SELECT Id FROM CN_Province__c WHERE Province_Code__c = '010'][0];
        CN_City__c city = [SELECT Id FROM CN_City__c WHERE CN_City_Code__c = '010'][0];
        CN_Business_Unit__c businessUnit = [SELECT Id FROM CN_Business_Unit__c WHERE CN_Business_Unit_Code__c = '0000900001'][0];
        CN_Sales_Team__c salesTeam = [SELECT Id FROM CN_Sales_Team__c WHERE CN_Sales_Team_Code__c = '0000901001'][0];
        
        System.runAs(salesRep) {

            integer num_name = 0;

            List<CN_Credit_Term_Application__c> ctaList = new List<CN_Credit_Term_Application__c>();
            CN_Credit_Term_Application__c cta = new CN_Credit_Term_Application__c();
            cta.CN_Account__c = accList_factory[num_name++].Id;
            cta.CN_Company_Background__c = 'company background';
            cta.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_REGULAR;
            cta.CN_Payment_Term_Negotiated__c = 'D005';
            cta.CN_Reference_Day__c = 'Delivery_Day';
            cta.CN_Credit_Limit_Incl_VAT__c = 113.00;
            cta.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta);

            
            CN_Credit_Term_Application__c cta2 = new CN_Credit_Term_Application__c();
            cta2.CN_Account__c = accList_factory[num_name++].Id;
            cta2.CN_Company_Background__c = 'company background';
            cta2.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_REGULAR;
            cta2.CN_Payment_Term_Negotiated__c = 'D020';
            cta2.CN_Reference_Day__c = 'Fapiao_Day';
            cta2.CN_Credit_Limit_Incl_VAT__c = 113.00;
            cta2.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta2);

            CN_Credit_Term_Application__c cta3 = new CN_Credit_Term_Application__c();
            cta3.CN_Account__c = accList_factory[num_name++].Id;
            cta3.CN_Company_Background__c = 'company background';
            cta3.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_REGULAR;
            cta3.CN_Payment_Term_Negotiated__c = 'M231';
            cta3.CN_Reference_Day__c = 'Delivery_Day';
            cta3.CN_Credit_Limit_Incl_VAT__c = 113.00;
            cta3.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta3);

            CN_Credit_Term_Application__c cta4 = new CN_Credit_Term_Application__c();
            cta4.CN_Account__c = accList_factory[num_name++].Id;
            cta4.CN_Company_Background__c = 'company background';
            cta4.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_TM1;
            cta4.CN_Payment_Term_Negotiated__c = 'D005';
            cta4.CN_Reference_Day__c = 'Delivery_Day';
            cta4.CN_Credit_Limit_Incl_VAT__c = 113.00;
            cta4.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta4);

            CN_Credit_Term_Application__c cta5 = new CN_Credit_Term_Application__c();
            cta5.CN_Account__c = accList_factory[num_name++].Id;
            cta5.CN_Company_Background__c = 'company background';
            cta5.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_TM1;
            cta5.CN_Payment_Term_Negotiated__c = 'D005';
            cta5.CN_Reference_Day__c = 'Delivery_Day';
            cta5.CN_Credit_Limit_Incl_VAT__c = 30000.00;
            cta5.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta5);

            CN_Credit_Term_Application__c cta6 = new CN_Credit_Term_Application__c();
            cta6.CN_Account__c = accList_factory[num_name++].Id;
            cta6.CN_Company_Background__c = 'company background';
            cta6.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_TM1;
            cta6.CN_Payment_Term_Negotiated__c = 'D005';
            cta6.CN_Reference_Day__c = 'Delivery_Day';
            cta6.CN_Credit_Limit_Incl_VAT__c = 130000.00;
            cta6.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta6);

            CN_Credit_Term_Application__c cta7 = new CN_Credit_Term_Application__c();
            cta7.CN_Account__c = accList_factory[num_name++].Id;
            cta7.CN_Company_Background__c = 'company background';
            cta7.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_TM1;
            cta7.CN_Payment_Term_Negotiated__c = 'D005';
            cta7.CN_Reference_Day__c = 'Delivery_Day';
            cta7.CN_Credit_Limit_Incl_VAT__c = 230000.00;
            cta7.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta7);

            CN_Credit_Term_Application__c cta8 = new CN_Credit_Term_Application__c();
            cta8.CN_Account__c = accList_factory[num_name++].Id;
            cta8.CN_Company_Background__c = 'company background';
            cta8.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_REGULAR;
            cta8.CN_Payment_Term_Negotiated__c = 'M231';
            cta8.CN_Reference_Day__c = 'Delivery_Day';
            cta8.CN_Credit_Limit_Incl_VAT__c = 113.00;
            cta8.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta8);

            //payment < 20 , TM2 , credit <= 10000
            CN_Credit_Term_Application__c cta9 = new CN_Credit_Term_Application__c();
            cta9.CN_Account__c = accList_factory[num_name++].Id;
            cta9.CN_Company_Background__c = 'company background';
            cta9.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_TM2;
            cta9.CN_Payment_Term_Negotiated__c = 'D005';
            cta9.CN_Reference_Day__c = 'Delivery_Day';
            cta9.CN_Credit_Limit_Incl_VAT__c = 113.00;
            cta9.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta9);

            //payment < 20 , TM2 , credit >= 10000
            CN_Credit_Term_Application__c cta17 = new CN_Credit_Term_Application__c();
            cta17.CN_Account__c = accList_factory[num_name++].Id;
            cta17.CN_Company_Background__c = 'company background';
            cta17.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_TM2;
            cta17.CN_Payment_Term_Negotiated__c = 'D005';
            cta17.CN_Reference_Day__c = 'Delivery_Day';
            cta17.CN_Credit_Limit_Incl_VAT__c = 200113.00;
            cta17.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta17);

            //payment > 60  TM1
            CN_Credit_Term_Application__c cta10 = new CN_Credit_Term_Application__c();
            cta10.CN_Account__c = accList_factory[num_name++].Id;
            cta10.CN_Company_Background__c = 'company background';
            cta10.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_TM1;
            cta10.CN_Payment_Term_Negotiated__c = 'M231';
            cta10.CN_Reference_Day__c = 'Delivery_Day';
            cta10.CN_Credit_Limit_Incl_VAT__c = 113.00;
            cta10.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta10);

            //payment > 60,TM2 , credit < 10000
            CN_Credit_Term_Application__c cta11 = new CN_Credit_Term_Application__c();
            cta11.CN_Account__c = accList_factory[num_name++].Id;
            cta11.CN_Company_Background__c = 'company background';
            cta11.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_TM2;
            cta11.CN_Payment_Term_Negotiated__c = 'M231';
            cta11.CN_Reference_Day__c = 'Delivery_Day';
            cta11.CN_Credit_Limit_Incl_VAT__c = 113.00;
            cta11.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta11);

            //payment > 60,TM2 , credit > 10000
            CN_Credit_Term_Application__c cta12 = new CN_Credit_Term_Application__c();
            cta12.CN_Account__c = accList_factory[num_name++].Id;
            cta12.CN_Company_Background__c = 'company background';
            cta12.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_TM2;
            cta12.CN_Payment_Term_Negotiated__c = 'M231';
            cta12.CN_Reference_Day__c = 'Delivery_Day';
            cta12.CN_Credit_Limit_Incl_VAT__c = 30000.00;
            cta12.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta12);

            //payment > 60,NO CONTRACT
            CN_Credit_Term_Application__c cta13 = new CN_Credit_Term_Application__c();
            cta13.CN_Account__c = accList_factory[num_name++].Id;
            cta13.CN_Company_Background__c = 'company background';
            cta13.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_NOC;
            cta13.CN_Payment_Term_Negotiated__c = 'M231';
            cta13.CN_Reference_Day__c = 'Delivery_Day';
            cta13.CN_Credit_Limit_Incl_VAT__c = 30000.00;
            cta13.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta13);

            //payment <= 60,NO CONTRACT , credit > 10000
            CN_Credit_Term_Application__c cta14 = new CN_Credit_Term_Application__c();
            cta14.CN_Account__c = accList_factory[num_name++].Id;
            cta14.CN_Company_Background__c = 'company background';
            cta14.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_NOC;
            cta14.CN_Payment_Term_Negotiated__c = 'D005';
            cta14.CN_Reference_Day__c = 'Delivery_Day';
            cta14.CN_Credit_Limit_Incl_VAT__c = 30000.00;
            cta14.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta14);

            //payment <= 60,NO CONTRACT , credit > 100000
            CN_Credit_Term_Application__c cta15 = new CN_Credit_Term_Application__c();
            cta15.CN_Account__c = accList_factory[num_name++].Id;
            cta15.CN_Company_Background__c = 'company background';
            cta15.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_NOC;
            cta15.CN_Payment_Term_Negotiated__c = 'D005';
            cta15.CN_Reference_Day__c = 'Delivery_Day';
            cta15.CN_Credit_Limit_Incl_VAT__c = 160000.00;
            cta15.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta15);

            //payment <= 60,NO CONTRACT , 100000 > credit > 60000
            CN_Credit_Term_Application__c cta16 = new CN_Credit_Term_Application__c();
            cta16.CN_Account__c = accList_factory[num_name++].Id;
            cta16.CN_Company_Background__c = 'company background';
            cta16.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_NOC;
            cta16.CN_Payment_Term_Negotiated__c = 'D005';
            cta16.CN_Reference_Day__c = 'Delivery_Day';
            cta16.CN_Credit_Limit_Incl_VAT__c = 60000.00;
            cta16.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            ctaList.add(cta16);

            //CTA_CTA_Populate_Fields_Handler
            CN_Credit_Term_Application__c cta18 = new CN_Credit_Term_Application__c();
            cta18.CN_Account__c = accList_factory[num_name++].Id;
            cta18.CN_Company_Background__c = 'company background';
            cta18.CN_Nature_Of_Request__c = Constants.CN_CTA_NATURE_OF_REQUEST_NOC;
            cta18.CN_Payment_Term_Negotiated__c = 'D005';
            cta18.CN_Reference_Day__c = 'Delivery_Day';
            cta18.CN_Credit_Limit_Incl_VAT__c = 60000.00;
            cta18.CN_Reasons_For_Applying_For_Credit_Term__c = 'Reason';
            insert cta18;

            Test.startTest();

            insert ctaList;

            List<CN_Credit_Term_Application__c> ctaList_update = new List<CN_Credit_Term_Application__c>();
            for(CN_Credit_Term_Application__c cta_source : ctaList){
                CN_Credit_Term_Application__c cta_update = new CN_Credit_Term_Application__c();
                cta_update.Id = cta_source.Id;
                cta_update.CN_Status__c = Constants.CN_CTA_STATUS_READY_FOR_APPROVAL;
                ctaList_update.add(cta_update);
            }
            update ctaList_update;

            ctaList_update = new List<CN_Credit_Term_Application__c>();
            for(CN_Credit_Term_Application__c cta_source : ctaList){
                CN_Credit_Term_Application__c cta_update = new CN_Credit_Term_Application__c();
                cta_update.Id = cta_source.Id;
                cta_update.CN_Approve_Step__c = 'step1';
                cta_update.CN_Status__c = Constants.CN_CTA_STATUS_SUBMITTED_FOR_APPROVAL;
                ctaList_update.add(cta_update);
            }
            update ctaList_update;

            ctaList_update = new List<CN_Credit_Term_Application__c>();
            for(CN_Credit_Term_Application__c cta_source : ctaList){
                CN_Credit_Term_Application__c cta_update = new CN_Credit_Term_Application__c();
                cta_update.Id = cta_source.Id;
                cta_update.CN_Status__c = Constants.CN_CTA_STATUS_APPROVALED;
                ctaList_update.add(cta_update);
            }
            update ctaList_update;

            CN_Credit_Term_Application__c cta_update = new CN_Credit_Term_Application__c();
            cta_update.Id = cta18.Id;
            cta_update.CN_Status__c = Constants.CN_CTA_STATUS_CANCEL;
            update cta_update;

            Test.stopTest();

        }
    }
}