objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Bank_Account_Name__c</fullName>
        <label>Bank Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Bank_Account__c</fullName>
        <label>Bank Account</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Billing_Block__c</fullName>
        <label>Billing Block</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>01    Calculation Missing</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>02    Compl Confirm Missng</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>03    Prices Incomplete</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>04    Check Terms of Paymt</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>05    Check Terms of Dlv</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>08    Check Credit Memo</label>
                </value>
                <value>
                    <fullName>09</fullName>
                    <label>09    Check Debit Memo</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10-YH Rejected by Customer</label>
                </value>
                <value>
                    <fullName>S0</fullName>
                    <label>S0-Overdue Payment</label>
                </value>
                <value>
                    <fullName>S1</fullName>
                    <label>S1-Credit Limit</label>
                </value>
                <value>
                    <fullName>S2</fullName>
                    <label>S2-Food License Lack</label>
                </value>
                <value>
                    <fullName>S3</fullName>
                    <label>S3-Addr. certif. Lack</label>
                </value>
                <value>
                    <fullName>S4</fullName>
                    <label>S4-Others License Lack</label>
                </value>
                <value>
                    <fullName>S5</fullName>
                    <label>S5-Missing Order</label>
                </value>
                <value>
                    <fullName>S6</fullName>
                    <label>S6-Obsolete</label>
                </value>
                <value>
                    <fullName>S7</fullName>
                    <label>S7-Inactive SF</label>
                </value>
                <value>
                    <fullName>S8</fullName>
                    <label>S8-Legal Case</label>
                </value>
                <value>
                    <fullName>YH</fullName>
                    <isActive>false</isActive>
                    <label>YH Rejected by Customer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Invoice_Type__c</fullName>
        <label>Invoice Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VAT Invoice</fullName>
                </value>
                <value>
                    <fullName>General Invoice</fullName>
                </value>
                <value>
                    <fullName>Electronic General Invoice</fullName>
                </value>
                <value>
                    <fullName>Electronic VAT Invoice</fullName>
                </value>
                <value>
                    <fullName>No need Invoice</fullName>
                    <isActive>false</isActive>
                    <label>No need invoice</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Invoicing_Address_and_Phone__c</fullName>
        <inlineHelpText>address and phone</inlineHelpText>
        <label>Invoicing Address and Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Payment_Bank_Account__c</fullName>
        <label>Payment Bank Account</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Payment_Bank_Name__c</fullName>
        <label>Payment Bank Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CIA</fullName>
                    <label>CIA-Payment in advance</label>
                </value>
                <value>
                    <fullName>D000</fullName>
                    <label>D000-Cash on delivery</label>
                </value>
                <value>
                    <fullName>D005</fullName>
                    <label>D005-D05/5 days after delivery</label>
                </value>
                <value>
                    <fullName>D010</fullName>
                    <label>D010-D10/10 days after delivery</label>
                </value>
                <value>
                    <fullName>D015</fullName>
                    <label>D015-15 days after delivery</label>
                </value>
                <value>
                    <fullName>D020</fullName>
                    <label>D020-20 days, due net</label>
                </value>
                <value>
                    <fullName>D030</fullName>
                    <label>D030-30 days, due net</label>
                </value>
                <value>
                    <fullName>D045</fullName>
                    <label>D045-45 days, due net</label>
                </value>
                <value>
                    <fullName>D060</fullName>
                    <label>D060-60days, due net</label>
                </value>
                <value>
                    <fullName>D090</fullName>
                    <label>D090-90days, due net</label>
                </value>
                <value>
                    <fullName>M110</fullName>
                    <label>M110-10 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M115</fullName>
                    <label>M115-15 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M131</fullName>
                    <label>M131-30 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M145</fullName>
                    <label>M145-Before 15th in 2 months, due net</label>
                </value>
                <value>
                    <fullName>M231</fullName>
                    <label>M231-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>D003</fullName>
                    <label>D003-Pay immediately with Invoice</label>
                </value>
                <value>
                    <fullName>D120</fullName>
                    <label>D120-120 days, due net</label>
                </value>
                <value>
                    <fullName>M120</fullName>
                    <label>M120-20 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M23</fullName>
                    <label>M23-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M031</fullName>
                </value>
                <value>
                    <fullName>D007</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sales_Office__c</fullName>
        <label>Sales Office</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>K010</fullName>
                    <label>K010-ShangHai</label>
                </value>
                <value>
                    <fullName>K020</fullName>
                    <label>K020-BeiJing</label>
                </value>
                <value>
                    <fullName>K030</fullName>
                    <label>K030-ShenZhen</label>
                </value>
                <value>
                    <fullName>K040</fullName>
                    <label>K040-GuangZhou</label>
                </value>
                <value>
                    <fullName>K050</fullName>
                    <label>K050-ChengDu</label>
                </value>
                <value>
                    <fullName>K060</fullName>
                    <isActive>false</isActive>
                    <label>K060-DaLian</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sales_Person_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person Name</label>
        <referenceTo>CN_Internal_Employee__c</referenceTo>
        <relationshipLabel>Accounts (Sales Person Name)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Sales_Team_UI__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Please search for KA/DS/WS.</inlineHelpText>
        <label>Sales Team</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>2 OR (1 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.CN_Business_Unit_UI__c</field>
                <operation>equals</operation>
                <valueField>CN_Sales_Team__c.CN_Business_Unit__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>CN_Sales_Team__c.CN_Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CN_Sales_Team__c</referenceTo>
        <relationshipLabel>SalesTeams</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Store_Name_CN__c</fullName>
        <label>Commercial Name (CN)</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Store_Name_EN__c</fullName>
        <label>Commercial Name (EN)</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Tax_Registration_No__c</fullName>
        <label>Tax Registration No.</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Internal_Employee__c.object
<CustomObject>
    <fields>
        <fullName>CN_User_Email__c</fullName>
        <label>User Email</label>
        <type>Email</type>
    </fields>
    <label>Internal Employee</label>
    <nameField>
        <label>Internal Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CN_Sales_Office__c</fullName>
        <label>Sales Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CN_Account_Send_MG_Mark_Batch.cls
/*
 * ************************************************************************************************
 * Name : CN_Account_Send_MG_Mark_Batch
 * Object :
 * Requirement :AC-017 | AC-018
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2023/4/24
 * Modify History :
 * ************************************************************************************************
 */
public class CN_Account_Send_MG_Mark_Batch implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful{

	public Iterable<SObject> start(Database.BatchableContext bc) {
		List<Account> accountList = [SELECT
			ID,
			Name,
			CN_License_Name_EN__c,
			CN_Store_Name_CN__c,
			CN_Store_Name_EN__c,
			CN_Customer_Code__c,
//			CN_Sales_Person_Name__r.Name,
//			CN_Sales_Person_Name__r.CN_User_Email__c,
			Owner.Email,
			Owner.Name,
			CN_MG_Account_ID__c,
			CN_Sales_Team_UI__r.Name,
			CN_Payment_Terms__c,
			CN_Inactive__c,
			CN_Invoice_Type__c,
			CN_Bank_Account_Name__c,
			CN_Tax_Registration_No__c,
			CN_Bank_Account__c,
			CN_Payment_Bank_Account__c,
			CN_Payment_Bank_Name__c,
			CN_Invoicing_Address_and_Phone__c,
			CN_Sales_Office__c,
			CN_Billing_Block__c,
			CN_Delivery_Block__c,
			CN_Order_Block__c,
			CN_Block_Sales_Support__c,
			CN_Closed__c,
			CN_Need_Send_MG_Flag__c,
			CN_Invoicing_Name_Bill_To_Party__c,
			CN_Sales_Org__c,
			CN_Sales_District__c,
			CN_Finance_AR__r.Username
		FROM Account
		WHERE ( CN_Need_Send_MG_Flag__c != 0 and CN_Need_Send_MG_Flag__c != null )
		AND (CN_Customer_Code__c != null OR CN_Inactive__c = true)
		AND CN_Account_Source__c = :Constants.CN_ACCOUNT_SOURCE_ECOMMERCE
		ORDER BY LastModifiedDate DESC ];

		return accountList;
	}

	public void execute(Database.BatchableContext bc, List<SObject> accountList){

		List<Account> inactiveList = new List<Account>();
		List<Account> setCustomerList = new List<Account>();

		for(Account account:(List<Account>) accountList){
			if(((Integer)account.CN_Need_Send_MG_Flag__c & 1) == 1){
				inactiveList.add(account);
			}
			if (((Integer)account.CN_Need_Send_MG_Flag__c & 1 << 1) == 1 << 1){
				setCustomerList.add(account);
			}
		}

		System.debug(JSON.serialize(inactiveList));
		System.debug(JSON.serialize(setCustomerList));

		List<CN_API_Call_Logger__c> listLog = new List<CN_API_Call_Logger__c>();

		Map<String,Account> sendSuccessInactiveId =  CN_Account_Inactive_To_Mg_Callout.upsertInactiveToMg(inactiveList,listLog);
		Map<String,Account> sendSuccessSetCustomerId =  CN_Account_Customer_Code_To_Mg_Callout.upsertCustomerCodeToMg(setCustomerList,listLog);

		List<Account> needUpdateList = new List<Account>();

		for(Account account:(List<Account>) accountList){
			String id = account.Id;
			Integer old = (Integer)account.CN_Need_Send_MG_Flag__c;
			if(sendSuccessInactiveId.containsKey(id)){
				account.CN_Need_Send_MG_Flag__c = (Integer)account.CN_Need_Send_MG_Flag__c ^ 1;
			}
			if(sendSuccessSetCustomerId.containsKey(id)){
				account.CN_Need_Send_MG_Flag__c = (Integer)account.CN_Need_Send_MG_Flag__c ^ 1 << 1;
			}

			if(account.CN_Need_Send_MG_Flag__c == old){
				continue;
			}

			Account needUpdate =  new Account();
			needUpdate.Id = id;
			needUpdate.CN_Need_Send_MG_Flag__c = account.CN_Need_Send_MG_Flag__c;
			needUpdateList.add(needUpdate);

		}
		insert listLog;
		update needUpdateList;

	}

	public void finish(Database.BatchableContext bc) {

	}
}