objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_City_CN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City(CN)</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>CN_City__c.CN_Province__c</field>
                <operation>equals</operation>
                <valueField>$Source.CN_Province_CN__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_City__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_City_Code__c</fullName>
        <formula>CN_City_CN__r.CN_City_Code__c</formula>
        <label>City Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Delivery_Plant__c</fullName>
        <label>Delivery Plant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P011</fullName>
                    <label>P011-SINODIS ShangHai External-西诺迪斯（上海） 外部</label>
                </value>
                <value>
                    <fullName>P020</fullName>
                    <label>P020-SINODIS BeiJing-西诺迪斯（北京）</label>
                </value>
                <value>
                    <fullName>P040</fullName>
                    <label>P040-SINODIS GuangZhou-西诺迪斯（广州）</label>
                </value>
                <value>
                    <fullName>P050</fullName>
                    <label>P050-SINODIS Chengdu-西诺迪斯（成都）</label>
                </value>
                <value>
                    <fullName>P060</fullName>
                    <label>P060-SINODIS Dalian-西诺迪斯（大连）</label>
                </value>
                <value>
                    <fullName>P010</fullName>
                    <isActive>false</isActive>
                    <label>P010-SINODIS ShangHai-西诺迪斯（上海）</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Post_Code__c</fullName>
        <label>Post Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Province_CN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province(CN)</label>
        <referenceTo>CN_Province__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_API_Call_Logger__c.object
<CustomObject>
    <description>API Call Log</description>
    <label>API Call Logger</label>
    <nameField>
        <displayFormat>INF-{YYYYMMDD}{0000}</displayFormat>
        <label>API Call Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Call Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_City__c.object
<CustomObject>
    <fields>
        <fullName>CN_City_CN__c</fullName>
        <label>City(CN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_City_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>City Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Citys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Province__c.object
<CustomObject>
    <fields>
        <fullName>CN_Province_CN__c</fullName>
        <label>Province(CN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Province Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Province</label>
    <nameField>
        <label>Province Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provinces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Ship_to_Party__c.object
<CustomObject>
    <fields>
        <fullName>CN_City_CN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City(CN)</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>CN_City__c.CN_Province__c</field>
                <operation>equals</operation>
                <valueField>$Source.CN_Province_CN__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_City__c</referenceTo>
        <relationshipLabel>Ship to Parties</relationshipLabel>
        <relationshipName>Ship_to_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Customer_Name_EN__c</fullName>
        <label>Ship To Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Customer_Name__c</fullName>
        <inlineHelpText>Please input license name + store name.</inlineHelpText>
        <label>Ship To Name(CN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Delivery_Address_CN__c</fullName>
        <label>Delivery Address(CN)</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Delivery_Address_EN__c</fullName>
        <label>Delivery Address (EN)</label>
        <length>220</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Delivery_Plant__c</fullName>
        <label>Delivery Plant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P011</fullName>
                    <label>P011-SINODIS ShangHai External-西诺迪斯（上海） 外部</label>
                </value>
                <value>
                    <fullName>P020</fullName>
                    <label>P020-SINODIS BeiJing-西诺迪斯（北京）</label>
                </value>
                <value>
                    <fullName>P040</fullName>
                    <label>P040-SINODIS GuangZhou-西诺迪斯（广州）</label>
                </value>
                <value>
                    <fullName>P050</fullName>
                    <label>P050-SINODIS Chengdu-西诺迪斯（成都）</label>
                </value>
                <value>
                    <fullName>P060</fullName>
                    <label>P060-SINODIS Dalian-西诺迪斯（大连）</label>
                </value>
                <value>
                    <fullName>P010</fullName>
                    <isActive>false</isActive>
                    <label>P010-SINODIS ShangHai-西诺迪斯（上海）</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Indirect_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Indirect Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship to Parties (Indirect Account)</relationshipLabel>
        <relationshipName>Ship_to_Parties1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Mobile_Phone__c</fullName>
        <inlineHelpText>Please enter the number in the format of 1XXXXXXXXXX or XXX-XXXXXXXX or XXXX-XXXXXXXX-XXX (X is number).</inlineHelpText>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CN_Post_Code__c</fullName>
        <formula>CN_Sold_To_Party_Customer__r.CN_Post_Code__c</formula>
        <label>Post Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Province_CN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province(CN)</label>
        <referenceTo>CN_Province__c</referenceTo>
        <relationshipLabel>Ship to Parties (Province(CN))</relationshipLabel>
        <relationshipName>Ship_to_Parties1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Sold_To_Party_Customer__c</fullName>
        <label>Sold-to Party Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5 AND 6) OR 7</booleanFilter>
            <errorMessage>You can only select Account whose Status is New.</errorMessage>
            <filterItems>
                <field>Account.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>New</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship to Party</value>
            </filterItems>
            <filterItems>
                <field>$Source.CN_Change_Request__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.CN_Change_Request__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship to Party</value>
            </filterItems>
            <filterItems>
                <field>Account.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship to Parties</relationshipLabel>
        <relationshipName>Ship_to_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Telephone__c</fullName>
        <inlineHelpText>Please enter the number in the format of 1XXXXXXXXXX or XXX-XXXXXXXX or XXXX-XXXXXXXX-XXX (X is number).</inlineHelpText>
        <label>Telephone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CN_UP_Code__c</fullName>
        <externalId>true</externalId>
        <label>UP code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Ship to Party</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Ship to Party Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ship to Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Talend_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Talend Setting</label>
</CustomObject>

classes/CN_ShipTo_Upsert_To_Mg_Callout.cls
/*
 * ************************************************************************************************
 * Name : CN_ShipTo_Upsert_To_Mg_Callout
 * Object :
 * Requirement : AC-009
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2023/4/4
 * Modify History :
 * ************************************************************************************************
 */
public class CN_ShipTo_Upsert_To_Mg_Callout {

	public static List<CN_Ship_to_Party__c> upsertShipToAddress(List<CN_Ship_to_Party__c> shipToList){

		//handleDataList
		List<Map<String, Object>> maps = handleData(shipToList);

		//Necessary parameters for assembly request
		Talend_Setting__c setting = Talend_Setting__c.getInstance();
		Http http = new Http();
		HttpRequest request = CN_HelperClass_WS.createHttpRequestHelper(
				setting.Sandbox_MG_Update_Shipping_Address__c,
				setting.MG_Update_Shipping_Address__c);

		List<CN_Ship_to_Party__c> sendSuccess = new List<CN_Ship_to_Party__c>();
		List<CN_API_Call_Logger__c> listLog = new List<CN_API_Call_Logger__c>();
		for(Map<String,Object> item:maps){
			CN_HelperClass_WS.WS_Log log = new CN_HelperClass_WS.WS_Log();
			try {
				String body = JSON.serialize(item);
				log.SetRequest(body);
				System.debug(body);
				String id = String.valueOf(item.get('MAP_ID'));

				String errorMessage = '';
				request.setBody(body);

				HttpResponse response = http.send(request);
				String data = response.getBody();
				log.SetResponse(data);

				System.debug(data);


				Integer resCode = response.getStatusCode();
				String errorMsg = '';

				if(resCode == 200) {
					CN_HelperClass_WS.Message  cs = CN_HelperClass_WS.getRetData(data);
					System.debug(JSON.serialize(cs));


					if(cs != null && cs.code == 1){

						Map<String,Object> retData = cs.retData;
						if (retData != null && retData.containsKey('address_id')){
							CN_Ship_to_Party__c cnShipToParty = new CN_Ship_to_Party__c();
							cnShipToParty.ID = id;
							cnShipToParty.CN_Need_Send_MG__c = false;
							cnShipToParty.CN_ShipTo_Address_ID__c = String.valueOf(retData.get('address_id'));
							sendSuccess.add(cnShipToParty);
						}

					}

				}else  {
					if(resCode == 503) {
						errorMessage = 'Service Unavailable';
					}else if(resCode == 500) {
						errorMessage = 'Server Error';
					} else if(resCode == 404) {
						errorMessage = 'API Path Error';
					}
				}
				errorMsg = resCode + ':' + errorMessage + ':' + data;

				log.SetResult(resCode, data, errorMsg);
				listLog.add(log.getLog());
			} catch (Exception e){
				System.debug(e.getLineNumber() + ' : ' + e.getCause());
				System.debug(e.getMessage());
				System.debug(e.getStackTraceString());
				log.SetResult(0,'Error',e.getMessage());
				listLog.add(log.getLog());
			}

		}
		insert listLog;

		return sendSuccess;
	}

	private static List<Map<String, Object>> handleData(List<CN_Ship_to_Party__c> shipToList) {

		List<Map<String,Object>> maps = new List<Map<String,Object>>();
		for(CN_Ship_to_Party__c shipTo : shipToList){
			Map<String,Object> mapItem= new Map<String,Object>();

			mapItem.put('MAP_ID',shipTo.Id); //转换后获得Map的Key，用于返回sendSuccess

			mapItem.put('ship_to_address_id',shipTo.CN_ShipTo_Address_ID__c);
			mapItem.put('city',shipTo.CN_City_CN__r.CN_City_Code__c);
			mapItem.put('contact_name',shipTo.CN_Contact_Name__c);
			mapItem.put('delivery_address_en',shipTo.CN_Delivery_Address_EN__c);
			mapItem.put('delivery_address_cn',shipTo.CN_Delivery_Address_CN__c);
			mapItem.put('delivery_plant',shipTo.CN_Delivery_Plant__c);
			mapItem.put('indirect_account',shipTo.CN_Indirect_Account__r.CN_MG_Account_ID__c);
			mapItem.put('mobile_phone',shipTo.CN_Mobile_Phone__c);
			mapItem.put('province_cn',shipTo.CN_Province_CN__r.Province_Code__c);
			mapItem.put('ship_to_name_cn',shipTo.CN_Customer_Name__c);
			mapItem.put('ship_to_name_en',shipTo.CN_Customer_Name_EN__c);
			mapItem.put('sold_to_party_customer',shipTo.CN_Sold_To_Party_Customer__r.CN_MG_Account_ID__c);
			mapItem.put('contact_id',shipTo.CN_Sold_To_Party_Customer__r.CN_Lead_MG_Contact_Id__c);
			mapItem.put('telephone',shipTo.CN_Telephone__c);
			mapItem.put('up_code',shipTo.CN_UP_Code__c);
			mapItem.put('post_code',shipTo.CN_Post_Code__c);
			mapItem.put('inactive',shipTo.CN_Inactive__c?'1':'0');
			maps.add(mapItem);
		}
		return maps;
	}


}