objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sales_Office__c</fullName>
        <label>Sales Office</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>K010</fullName>
                    <label>K010-ShangHai</label>
                </value>
                <value>
                    <fullName>K020</fullName>
                    <label>K020-BeiJing</label>
                </value>
                <value>
                    <fullName>K030</fullName>
                    <label>K030-ShenZhen</label>
                </value>
                <value>
                    <fullName>K040</fullName>
                    <label>K040-GuangZhou</label>
                </value>
                <value>
                    <fullName>K050</fullName>
                    <label>K050-ChengDu</label>
                </value>
                <value>
                    <fullName>K060</fullName>
                    <isActive>false</isActive>
                    <label>K060-DaLian</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Promotion__c.object
<CustomObject>
    <fields>
        <fullName>CN_End_Date__c</fullName>
        <label>End Date(Planned End Date)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Promotion_Type__c</fullName>
        <label>Promotion Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>Bundle sells</fullName>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                </value>
                <value>
                    <fullName>Gifting</fullName>
                </value>
                <value>
                    <fullName>买满就减</fullName>
                    <isActive>false</isActive>
                    <label>买满就减</label>
                </value>
                <value>
                    <fullName>买送</fullName>
                    <isActive>false</isActive>
                    <label>买送</label>
                </value>
                <value>
                    <fullName>会员促销</fullName>
                    <isActive>false</isActive>
                    <label>会员促销</label>
                </value>
                <value>
                    <fullName>免费试吃</fullName>
                    <isActive>false</isActive>
                    <label>免费试吃</label>
                </value>
                <value>
                    <fullName>免费送</fullName>
                    <isActive>false</isActive>
                    <label>免费送</label>
                </value>
                <value>
                    <fullName>凭**换取</fullName>
                    <isActive>false</isActive>
                    <label>凭**换取</label>
                </value>
                <value>
                    <fullName>加***元多一件</fullName>
                    <isActive>false</isActive>
                    <label>加***元多一件</label>
                </value>
                <value>
                    <fullName>打折</fullName>
                    <isActive>false</isActive>
                    <label>打折</label>
                </value>
                <value>
                    <fullName>折上折</fullName>
                    <isActive>false</isActive>
                    <label>折上折</label>
                </value>
                <value>
                    <fullName>抽奖</fullName>
                    <isActive>false</isActive>
                    <label>抽奖</label>
                </value>
                <value>
                    <fullName>换购</fullName>
                    <isActive>false</isActive>
                    <label>换购</label>
                </value>
                <value>
                    <fullName>特价</fullName>
                    <isActive>false</isActive>
                    <label>特价</label>
                </value>
                <value>
                    <fullName>秒杀</fullName>
                    <isActive>false</isActive>
                    <label>秒杀</label>
                </value>
                <value>
                    <fullName>送券</fullName>
                    <isActive>false</isActive>
                    <label>送券</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sales_Office__c</fullName>
        <label>Sales Office</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>K010</fullName>
                    <label>K010-ShangHai</label>
                </value>
                <value>
                    <fullName>K020</fullName>
                    <label>K020-BeiJing</label>
                </value>
                <value>
                    <fullName>K030</fullName>
                    <label>K030-ShenZhen</label>
                </value>
                <value>
                    <fullName>K040</fullName>
                    <label>K040-GuangZhou</label>
                </value>
                <value>
                    <fullName>K050</fullName>
                    <label>K050-ChengDu</label>
                </value>
                <value>
                    <fullName>K060</fullName>
                    <label>K060-DaLian</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Start_Date__c</fullName>
        <label>Start Date(Planned Start Date)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KA</fullName>
                </value>
                <value>
                    <fullName>DS</fullName>
                </value>
                <value>
                    <fullName>WS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <label>Customer Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BAPA</fullName>
                </value>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Coffee/Tea Shop</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
                <value>
                    <fullName>Retailor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Promotion_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CN_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Promotion Line Items</relationshipLabel>
        <relationshipName>Promotion_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Promotion_Price__c</fullName>
        <label>Promotion Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Promotion__c</fullName>
        <label>Promotion</label>
        <referenceTo>CN_Promotion__c</referenceTo>
        <relationshipLabel>Promotion Line Items</relationshipLabel>
        <relationshipName>Promotion_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promotion Line Item</label>
    <nameField>
        <displayFormat>PLI-{0000000000}</displayFormat>
        <label>Promotion Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Promotion_Member__c.object
<CustomObject>
    <fields>
        <fullName>CN_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotion Members</relationshipLabel>
        <relationshipName>Promotion_Members1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>CN_Promotion__c</referenceTo>
        <relationshipLabel>Promotion Members</relationshipLabel>
        <relationshipName>Promotion_Members2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion Member</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Promotion Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Quote_To_Promotion__c.object
<CustomObject>
    <fields>
        <fullName>CN_Promotion_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promotion Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CN_Promotion_Member__c.CN_IsPublished__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CN_Promotion_Member__c</referenceTo>
        <relationshipLabel>Quote To Promotions</relationshipLabel>
        <relationshipName>Quote_To_Promotions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote To Promotions</relationshipLabel>
        <relationshipName>Quote_To_Promotions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote To Promotion</label>
    <nameField>
        <displayFormat>QTP-{000000}</displayFormat>
        <label>Quote To Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote To Promotions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>CN_Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>CN_Promotion_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Member</label>
        <referenceTo>CN_Promotion_Member__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Promotion_Price__c</fullName>
        <label>Promotion Price</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CN_Sales_Office__c</fullName>
        <label>Sales Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CN_Quote_Accept_All_Items_LC_Ctrl_Test.cls
/**************************************************************************************************
 * Name           : CN_Quote_Accept_All_Items_LC_Ctrl_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Du Dezheng
 * Create Date    : 2021-10-13
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_Quote_Accept_All_Items_LC_Ctrl_Test {

    static List<Account> accList_factory = null;
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }
    @isTest
    private static void handleTest() {
        TestDataFactory testDataFactory = new TestDataFactory();
        List<Account> accFactroy_List = TestDataFactory.makeFactoryAccount();

        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, User> lastNameUserMap = new Map<String, User>();
        for(User usr: userList) {
            lastNameUserMap.put(usr.LastName, usr);
        }

        User cce = lastNameUserMap.get('CCE1_KA');
        User salesRep = lastNameUserMap.get('Sales1');
        Account acc_factory = [SELECT Id,Name FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];
        Id cnQuoteRTId = Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get(Constants.CN_Quote_RT_API_NAME_NEW).getRecordTypeId();
        List<Product2> productList = [Select Id,name From Product2 LIMIT 1];
        PricebookEntry pbEntry = [Select Id,Product2Id From PricebookEntry Where Pricebook2Id =: Test.getStandardPricebookId() And Product2Id  =: productList[0].Id];

        CN_Promotion__c promotion = new CN_Promotion__c(
            Name = 'TestPromotion',
            CN_Start_Date__c = Date.today().addMonths(3),
            CN_End_Date__c = Date.today().addMonths(3).addDays(13),
            CN_Promotion_Type__c = 'Discount',
            Channel__c = 'KA',
            CN_Status__c = 'Planned',
            Customer_Category__c = 'BAPA',
            CN_Sales_Office__c = 'K010'
        );

        CN_Promotion_Member__c pm = new CN_Promotion_Member__c ();
        Opportunity opp = new Opportunity();
        Quote q = new Quote();

        System.runAs(cce) {
            insert promotion;

            promotion.CN_Status__c = Constants.CN_PROMOTION_STATUS_READY;
            try {
                update promotion;
            } catch (Exception e) {}

            CN_Promotion_Line_Item__c pli = new CN_Promotion_Line_Item__c(
                CN_Promotion__c = promotion.Id,
                CN_Product__c = productList[0].Id,
                CN_Promotion_Price__c = 99.9
            );
            insert pli;

            CN_Promotion_Generate_ProMember_LC_Ctrl.generateProMember(promotion.Id);

            pm = new CN_Promotion_Member__c(
                CN_Promotion__c = promotion.Id,
                CN_Account__c = acc_factory.Id
            );
            insert pm;

            promotion.CN_Status__c = Constants.CN_PROMOTION_STATUS_READY;
            update promotion;
            CN_Promotion_Publish_LC_Ctrl.prmtPublish(promotion.Id);
        }

        System.runAs(salesRep) {
            opp = testDataFactory.makeOpp(acc_factory);
            insert opp;

            Opportunity opp_update = new Opportunity();
            opp_update.Id = opp.Id;
            opp_update.Pricebook2Id = Test.getStandardPricebookId();
            update opp_update;

            q = new Quote(
                Name = 'Quote Name',
                CN_Effective_Date__c = Date.Today()+1,
                ExpirationDate = Date.Today() + 7,
                OpportunityId = opp.Id
            );
            insert q;
        }

        CN_Quote_To_Promotion__c quoteToPromo = new CN_Quote_To_Promotion__c(
            CN_Quote__c = q.Id,
            CN_Promotion_Member__c = pm.Id
        );
        insert quoteToPromo;

        QuoteLineItem quoteItem = new QuoteLineItem(
            QuoteId = q.Id,
            Product2Id = productList[0].Id,
            Quantity = 2,
            UnitPrice = 12,
            PricebookEntryId = pbEntry.Id
        );
        insert quoteItem;

        Test.startTest();
        try {
            CN_Quote_AcceptORDeny_All_Items_LC_Ctrl.getIfAcceptedAllItems(q.Id);
        } catch (Exception e) {}
        try {
            CN_Quote_AcceptORDeny_All_Items_LC_Ctrl.acceptOrDenyAllQuoteItems(q.Id,false);
        } catch (Exception e) {}

        Quote q_update = new Quote(
            Id = q.Id,
            Status = Constants.CN_QUOTE_STATUS_APPROVED
        );
        update q_update;

        CN_Quote_AcceptORDeny_All_Items_LC_Ctrl.getIfAcceptedAllItems(q.Id);
        CN_Quote_AcceptORDeny_All_Items_LC_Ctrl.acceptOrDenyAllQuoteItems(q.Id,false);

        try {
            CN_Quote_AcceptORDeny_All_Items_LC_Ctrl.getIfAcceptedAllItems('');
        } catch (Exception e) {}

        try {
            CN_Quote_AcceptORDeny_All_Items_LC_Ctrl.getIfAcceptedAllItems('001000000000000');
        } catch (Exception e) {}

        try {
            CN_Quote_AcceptORDeny_All_Items_LC_Ctrl.acceptOrDenyAllQuoteItems('',false);
        } catch (Exception e) {}

        try {
            CN_Quote_AcceptORDeny_All_Items_LC_Ctrl.acceptOrDenyAllQuoteItems('001000000000000',false);
        } catch (Exception e) {}


        CN_Quote_To_Promotion__c quoteToPromo2 = new CN_Quote_To_Promotion__c(
            CN_Quote__c = q.Id,
            CN_Promotion_Member__c = pm.Id
        );
        try {
            insert quoteToPromo2;
        } catch (Exception e) {}

        CN_Quote_To_Promotion__c quoteToPromo_delete = new CN_Quote_To_Promotion__c(
            Id = quoteToPromo.Id
        );
        try {
            delete quoteToPromo_delete;
        } catch (Exception e) {}

        Test.stopTest();
    }
    

}