objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Billing_Block__c</fullName>
        <label>Billing Block</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>01    Calculation Missing</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>02    Compl Confirm Missng</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>03    Prices Incomplete</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>04    Check Terms of Paymt</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>05    Check Terms of Dlv</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>08    Check Credit Memo</label>
                </value>
                <value>
                    <fullName>09</fullName>
                    <label>09    Check Debit Memo</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10-YH Rejected by Customer</label>
                </value>
                <value>
                    <fullName>S0</fullName>
                    <label>S0-Overdue Payment</label>
                </value>
                <value>
                    <fullName>S1</fullName>
                    <label>S1-Credit Limit</label>
                </value>
                <value>
                    <fullName>S2</fullName>
                    <label>S2-Food License Lack</label>
                </value>
                <value>
                    <fullName>S3</fullName>
                    <label>S3-Addr. certif. Lack</label>
                </value>
                <value>
                    <fullName>S4</fullName>
                    <label>S4-Others License Lack</label>
                </value>
                <value>
                    <fullName>S5</fullName>
                    <label>S5-Missing Order</label>
                </value>
                <value>
                    <fullName>S6</fullName>
                    <label>S6-Obsolete</label>
                </value>
                <value>
                    <fullName>S7</fullName>
                    <label>S7-Inactive SF</label>
                </value>
                <value>
                    <fullName>S8</fullName>
                    <label>S8-Legal Case</label>
                </value>
                <value>
                    <fullName>YH</fullName>
                    <isActive>false</isActive>
                    <label>YH Rejected by Customer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Change_Request__c</fullName>
        <label>Change Request</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_City_Code__c</fullName>
        <formula>CN_City_CN__r.CN_City_Code__c</formula>
        <label>City Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Order_Block__c</fullName>
        <label>Order Block</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>01    Overall block</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>02    All free of charge</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>03    Test block</label>
                </value>
                <value>
                    <fullName>99</fullName>
                    <label>99    test (e)</label>
                </value>
                <value>
                    <fullName>S0</fullName>
                    <label>S0-Overdue Payment</label>
                </value>
                <value>
                    <fullName>S1</fullName>
                    <label>S1-Credit Limit</label>
                </value>
                <value>
                    <fullName>S2</fullName>
                    <label>S2-Food License Lack</label>
                </value>
                <value>
                    <fullName>S3</fullName>
                    <label>S3-Addr. certif. Lack</label>
                </value>
                <value>
                    <fullName>S4</fullName>
                    <label>S4-Others License Lack</label>
                </value>
                <value>
                    <fullName>S5</fullName>
                    <label>S5-Missing Order</label>
                </value>
                <value>
                    <fullName>S6</fullName>
                    <label>S6-Obsolete</label>
                </value>
                <value>
                    <fullName>S7</fullName>
                    <label>S7-Inactive SF</label>
                </value>
                <value>
                    <fullName>S8</fullName>
                    <label>S8-Legal Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>CN_Billing_Block__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing Block</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Order_Block__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Block</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship to Party</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <errorMessage>The associated Account should be Approved and Synchronized.</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Update Account Request, Update Contact Request, New Contact Request, Update Ship-to Request, New Ship-to Request</value>
            </filterItems>
            <filterItems>
                <field>CN_Ship_to_Party__c.CN_Sold_To_Party_Customer__r.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>CN_Ship_to_Party__c.CN_Sold_To_Party_Customer__r.CN_Synchronized__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Update Account Request, Update Contact Request, New Contact Request, Update Ship-to Request, New Ship-to Request</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_Ship_to_Party__c</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Change_Requests_Shipto</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_City__c.object
<CustomObject>
    <fields>
        <fullName>CN_City_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>City Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Province__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province</label>
        <referenceTo>CN_Province__c</referenceTo>
        <relationshipLabel>Citys (Province)</relationshipLabel>
        <relationshipName>Citys1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Citys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Province__c.object
<CustomObject>
    <fields>
        <fullName>Province_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Province Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Province</label>
    <nameField>
        <label>Province Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provinces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Ship_to_Party__c.object
<CustomObject>
    <fields>
        <fullName>CN_Change_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change Request</label>
        <referenceTo>CN_Change_Request__c</referenceTo>
        <relationshipLabel>Ship to Parties</relationshipLabel>
        <relationshipName>Ship_to_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Sold_To_Party_Customer__c</fullName>
        <label>Sold-to Party Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5 AND 6) OR 7</booleanFilter>
            <errorMessage>You can only select Account whose Status is New.</errorMessage>
            <filterItems>
                <field>Account.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>New</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship to Party</value>
            </filterItems>
            <filterItems>
                <field>$Source.CN_Change_Request__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.CN_Change_Request__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship to Party</value>
            </filterItems>
            <filterItems>
                <field>Account.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship to Parties</relationshipLabel>
        <relationshipName>Ship_to_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ship to Party</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Ship to Party Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ship to Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CN_Change_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change Request</label>
        <referenceTo>CN_Change_Request__c</referenceTo>
        <relationshipLabel>Change Request</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Account_TM_REPORT_Handler_Test.cls
/**************************************************************************************************
 * Name           : CN_Account_TM_REPORT_Handler_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Dezheng Du
 * Create Date    : 2021-09-28
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_Account_TM_REPORT_Handler_Test {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }

    @isTest
    private static void handleBeforeUpdate() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();

        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }
        
        User salesRep = [SELECT Id FROM User WHERE lastName = 'Sales1'][0];
        Account acc_factory = [SELECT Id FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];
        Contact con = [Select Id From Contact Where AccountId =: acc_factory.Id][0];
        CN_Ship_to_Party__c sh = [Select Id From CN_Ship_to_Party__c Where CN_Sold_To_Party_Customer__c =:acc_factory.Id][0];
        CN_Province__c province = [SELECT Id FROM CN_Province__c WHERE Province_Code__c = '010'][0];
        CN_City__c city = [SELECT Id FROM CN_City__c WHERE CN_City_Code__c = '010'][0];


        System.runAs(salesRep) {
            Id updateAccountRTId = Schema.SObjectType.CN_Change_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CR_RT_API_NAME_UPDATE_ACCOUNT).getRecordTypeId();
            Id updateContactRTId = Schema.SObjectType.CN_Change_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CR_RT_API_NAME_UPDATE_CONTACT).getRecordTypeId();
            Id updateShiptoRTId = Schema.SObjectType.CN_Change_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CR_RT_API_NAME_UPDATE_SHIPTO).getRecordTypeId();
            Id newContactRTId = Schema.SObjectType.CN_Change_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CR_RT_API_NAME_NEW_CONTACT).getRecordTypeId();
            Id newShiptoRTId = Schema.SObjectType.CN_Change_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CR_RT_API_NAME_NEW_SHIPTO).getRecordTypeId();

            List<Account> accList = testFactory.makeAccounts(3,false);
            List<Account> accList_Update = new List<Account>();

            Test.startTest();
            for(Account acc : accList){
                Account acc_update = new Account();
                acc_update.Id = acc.Id;
                acc_update.Name = 'TM_' + acc.Name;
                acc_update.CN_Billing_Block__c = '01';
                acc_update.CN_Order_Block__c = '01';
                acc_update.CN_Delivery_Block__c = '01';
                accList_Update.add(acc_update);
            }
            update accList_Update;

            Account acc_update1 = new Account();
            acc_update1.Id = accList[1].Id;
            acc_update1.Name = 'TM_' + accList[1].Name;
            acc_update1.CN_Billing_Block__c = null;
            acc_update1.CN_Order_Block__c = null;
            acc_update1.CN_Delivery_Block__c = null;
            update acc_update1;

            Account acc_update2 = new Account();
            acc_update1.Id = accList[2].Id;
            acc_update1.Name = 'TM_' + accList[2].Name;
            acc_update1.CN_Billing_Block__c = null;
            acc_update1.CN_Order_Block__c = null;
            acc_update1.CN_Delivery_Block__c = null;
            update acc_update1;

            testFactory.approveAccount(accList);
            
            Test.stopTest();
        }
    }
}