objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Source__c</fullName>
        <label>Account Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Recommend</fullName>
                </value>
                <value>
                    <fullName>Cold Visit</fullName>
                </value>
                <value>
                    <fullName>Public Demo</fullName>
                </value>
                <value>
                    <fullName>Brand Activity</fullName>
                </value>
                <value>
                    <fullName>Expositions</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Social Media Network</fullName>
                </value>
                <value>
                    <fullName>Marketing Campaign</fullName>
                </value>
                <value>
                    <fullName>Digital Campaign</fullName>
                </value>
                <value>
                    <fullName>Bakery China</fullName>
                </value>
                <value>
                    <fullName>CIIE</fullName>
                </value>
                <value>
                    <fullName>FHC</fullName>
                </value>
                <value>
                    <fullName>Other Trade show</fullName>
                </value>
                <value>
                    <fullName>Sponsorship Event</fullName>
                </value>
                <value>
                    <fullName>Customer Service Hotline</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Ship_to_Party__c.object
<CustomObject>
    <fields>
        <fullName>CN_Sold_To_Party_Customer__c</fullName>
        <label>Sold-to Party Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5 AND 6) OR 7</booleanFilter>
            <errorMessage>You can only select Account whose Status is New.</errorMessage>
            <filterItems>
                <field>Account.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>New</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship to Party</value>
            </filterItems>
            <filterItems>
                <field>$Source.CN_Change_Request__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.CN_Change_Request__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship to Party</value>
            </filterItems>
            <filterItems>
                <field>Account.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship to Parties</relationshipLabel>
        <relationshipName>Ship_to_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ship to Party</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Ship to Party Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ship to Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_ShipTo_Send_Mg_Handler.cls
/*
 * ************************************************************************************************
 * Name : CN_ShipTo_Send_Mg_Handler
 * Description :
 * Object :
 * Requirement : AC-007 | AC-009
 * Target :
 * Refer classes : 
 * Author : Leo Dicaprio
 * Create Date : 2023/8/7
 * Modify History :
 * ************************************************************************************************
 */
public without sharing class CN_ShipTo_Send_Mg_Handler implements Triggers.Handler{

	public void handle() {
		List<CN_Ship_to_Party__c> newList = (List<CN_Ship_to_Party__c>)Trigger.new;
		List<String> accountIds = new List<String>();
		for (CN_Ship_to_Party__c next : newList) {
			System.debug('next.CN_Sold_To_Party_Customer__c==>'+next.CN_Sold_To_Party_Customer__c);
			accountIds.add(next.CN_Sold_To_Party_Customer__c);
		}

		List<Account> accountList = [SELECT ID,CN_Account_Source__c FROM Account WHERE ID in : accountIds];
		Map<String,Account> accountMap = new Map<String, Account>();
		for (Account next : accountList) {
			System.debug('next.Id==>'+next.Id);
			accountMap.put(next.Id,next);
		} 

		for (CN_Ship_to_Party__c next : newList) {
			Account acc =  accountMap.get(next.CN_Sold_To_Party_Customer__c);
 			if(acc != null){
				next.CN_Sold_To_Party_Customer__r =  acc;
				System.debug('next.CN_Sold_To_Party_Customer__r=>'+next.CN_Sold_To_Party_Customer__r);
			}

		}


		if(Trigger.isBefore && Trigger.isUpdate) {
			handleBeforeUpdate();
		}else if(Trigger.isBefore && Trigger.isInsert){
			handleBeforeInsert();
		}
	}

	private void handleBeforeInsert() {
		for(CN_Ship_to_Party__c shipTo:(List<CN_Ship_to_Party__c>)Trigger.new){

			if(shipTo.CN_Sold_To_Party_Customer__r == null
					|| shipTo.CN_Sold_To_Party_Customer__r.CN_Account_Source__c == null
					|| shipTo.CN_Sold_To_Party_Customer__r.CN_Account_Source__c != Constants.CN_ACCOUNT_SOURCE_ECOMMERCE  ){
				continue;
			}

			shipTo.CN_Need_Send_MG__c = true;
		}
	}

	private void handleBeforeUpdate() {
		for(CN_Ship_to_Party__c shipTo:(List<CN_Ship_to_Party__c>)Trigger.new){

			if(shipTo.CN_Sold_To_Party_Customer__r == null
					|| shipTo.CN_Sold_To_Party_Customer__r.CN_Account_Source__c == null
					|| shipTo.CN_Sold_To_Party_Customer__r.CN_Account_Source__c != Constants.CN_ACCOUNT_SOURCE_ECOMMERCE  ){
				continue;
			}

			CN_Ship_to_Party__c old = (CN_Ship_to_Party__c)Trigger.oldMap.get(shipTo.Id);
			System.debug('old.CN_Need_Send_MG__c==>'+old.CN_Need_Send_MG__c);
			System.debug('shipTo.CN_Need_Send_MG__c==>'+shipTo.CN_Need_Send_MG__c);
			if(old.CN_Need_Send_MG__c == shipTo.CN_Need_Send_MG__c){
				shipTo.CN_Need_Send_MG__c = true;
			}
		}
	}

}