objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Contract__c.object
<CustomObject>
    <fields>
        <fullName>CN_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Direct_Account_Name__c</fullName>
        <label>Direct Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>Contract-{000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Contract_Number_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CN_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_DateTime__c</fullName>
        <label>CN_DateTime__c</label>
        <type>DateTime</type>
    </fields>
    <label>CN Contract Number Setting</label>
</CustomObject>

classes/CN_Contract_Populate_Fields_Handler_Test.cls
/**************************************************************************************************
 * Name           : CN_Contract_Populate_Fields_Handler_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Kealsalas Qiu
 * Create Date    : 2021-10-12
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_Contract_Populate_Fields_Handler_Test {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }

    @isTest
    private static void CN_Contract_Populate_Fields_Handler_Test() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();

        Account acc_factory = [SELECT Id FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];

        CN_Contract_Number_Setting__c setting = new CN_Contract_Number_Setting__c(
            CN_Contract_Number__c = 0,
            CN_DateTime__c = Datetime.now()
        );
        
        insert setting;

        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }

        CN_Contract__c con = new CN_Contract__c();
        con.CN_Direct_Account_Name__c = acc_factory.Id;
        insert con;
    }


    @isTest
    private static void CN_Contract_Populate_Fields_Handler_Test_1() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();
        
        Account acc_factory = [SELECT Id FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];

        CN_Contract_Number_Setting__c setting = new CN_Contract_Number_Setting__c(
            CN_Contract_Number__c = 0,
            CN_DateTime__c = Datetime.now().addYears(-1)
        );
        
        insert setting;

        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }

        CN_Contract__c con = new CN_Contract__c();
        con.CN_Direct_Account_Name__c = acc_factory.Id;
        insert con;
    }
}