objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Source__c</fullName>
        <label>Account Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Recommend</fullName>
                </value>
                <value>
                    <fullName>Cold Visit</fullName>
                </value>
                <value>
                    <fullName>Public Demo</fullName>
                </value>
                <value>
                    <fullName>Brand Activity</fullName>
                </value>
                <value>
                    <fullName>Expositions</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Social Media Network</fullName>
                </value>
                <value>
                    <fullName>Marketing Campaign</fullName>
                </value>
                <value>
                    <fullName>Digital Campaign</fullName>
                </value>
                <value>
                    <fullName>Bakery China</fullName>
                </value>
                <value>
                    <fullName>CIIE</fullName>
                </value>
                <value>
                    <fullName>FHC</fullName>
                </value>
                <value>
                    <fullName>Other Trade show</fullName>
                </value>
                <value>
                    <fullName>Sponsorship Event</fullName>
                </value>
                <value>
                    <fullName>Customer Service Hotline</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CN_UP_Code__c</fullName>
        <label>UP code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Contact_Upsert_To_Mg_Test.cls
/*
 * ************************************************************************************************
 * Name : CN_Contact_Upsert_To_Mg_Test
 * Description :
 * Object :
 * Requirement :
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2023/12/31
 * Modify History :
 * ************************************************************************************************
 */
@IsTest
public class CN_Contact_Upsert_To_Mg_Test {

	@TestSetup
	static void makeData(){
		TestDataFactory.makeBaseData();
	}

	@IsTest
	private static void handleUpdate() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		testFactory.makeTalendSetting();
		Account account = [SELECT Id FROM Account WHERE CN_MG_Account_ID__c = '1'];
		account.CN_Account_Source__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		account.CN_Customer_Code__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		update account;
		Contact contact = [SELECT Id FROM Contact WHERE CN_MG_Contact_ID__c = '1'];
		contact.CN_Need_Send_MG__c = true;
		contact.CN_UP_Code__c = 'UPTEST';
		update contact;

		Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
		Database.executeBatch(new CN_Contact_Send_Mg_Batch());
	}

	@IsTest
	private static void handleUpdate503() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		testFactory.makeTalendSetting();
		Account account = [SELECT Id FROM Account WHERE CN_MG_Account_ID__c = '1'];
		account.CN_Account_Source__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		account.CN_Customer_Code__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		update account;
		Contact contact = [SELECT Id FROM Contact WHERE CN_MG_Contact_ID__c = '1'];
		contact.CN_Need_Send_MG__c = true;
		contact.CN_MG_Contact_ID__c = '503';
		contact.CN_UP_Code__c = 'UPTEST';
		update contact;

		Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
		Database.executeBatch(new CN_Contact_Send_Mg_Batch());
	}

	@IsTest
	private static void handleUpdate500() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		testFactory.makeTalendSetting();
		Account account = [SELECT Id FROM Account WHERE CN_MG_Account_ID__c = '1'];
		account.CN_Account_Source__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		account.CN_Customer_Code__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		update account;
		Contact contact = [SELECT Id FROM Contact WHERE CN_MG_Contact_ID__c = '1'];
		contact.CN_Need_Send_MG__c = true;
		contact.CN_UP_Code__c = 'UPTEST';
		contact.CN_MG_Contact_ID__c = '500';
		update contact;

		Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
		Database.executeBatch(new CN_Contact_Send_Mg_Batch());
	}

	@IsTest
	private static void handleUpdate404() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		testFactory.makeTalendSetting();
		Account account = [SELECT Id FROM Account WHERE CN_MG_Account_ID__c = '1'];
		account.CN_Account_Source__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		account.CN_Customer_Code__c = Constants.CN_ACCOUNT_SOURCE_ECOMMERCE;
		update account;
		Contact contact = [SELECT Id FROM Contact WHERE CN_MG_Contact_ID__c = '1'];
		contact.CN_Need_Send_MG__c = true;
		contact.CN_UP_Code__c = 'UPTEST';
		contact.CN_MG_Contact_ID__c = '404';
		update contact;

		Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
		Database.executeBatch(new CN_Contact_Send_Mg_Batch());
	}

}