objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Change_Request__c</fullName>
        <label>Change Request</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sync_Status__c</fullName>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>CN_Change_Request_Status__c</fullName>
        <label>Change Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Is_Generate_From_Action__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Generate From Action</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship to Party</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <errorMessage>The associated Account should be Approved and Synchronized.</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Update Account Request, Update Contact Request, New Contact Request, Update Ship-to Request, New Ship-to Request</value>
            </filterItems>
            <filterItems>
                <field>CN_Ship_to_Party__c.CN_Sold_To_Party_Customer__r.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>CN_Ship_to_Party__c.CN_Sold_To_Party_Customer__r.CN_Synchronized__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Update Account Request, Update Contact Request, New Contact Request, Update Ship-to Request, New Ship-to Request</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_Ship_to_Party__c</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Change_Requests_Shipto</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Sync_Status__c</fullName>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>No Need To Sync</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_CN_Contact_CN_Last_Name__c</fullName>
        <label>New Contact Name(CN))-Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_CN_ShipTo_Customer_Name__c</fullName>
        <inlineHelpText>Please input license name + store name.</inlineHelpText>
        <label>New Ship To Name(CN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Ship_to_Party__c.object
<CustomObject>
    <fields>
        <fullName>CN_Change_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change Request</label>
        <referenceTo>CN_Change_Request__c</referenceTo>
        <relationshipLabel>Ship to Parties</relationshipLabel>
        <relationshipName>Ship_to_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Sync_Status__c</fullName>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ship to Party</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Ship to Party Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ship to Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Trigger_Switcher_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EnableFlow__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EnableFlow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnableTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EnableTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnableValidationRule__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EnableValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Switcher Setting</label>
</CustomObject>

classes/CN_CR_Populate_Approver_Handler_Test.cls
/*
 * ************************************************************************************************
 * Name : CN_CR_Populate_Approver_Handler_Test
 * Description :
 * Object :
 * Requirement :
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2024/1/3
 * Modify History :
 * ************************************************************************************************
 */
@IsTest
public class CN_CR_Populate_Approver_Handler_Test {
	@TestSetup
	static void makeData(){
		TestDataFactory.makeBaseData();
	}
	@isTest
	private static void handleInactiveShiptoTest() {
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeAccounts(10,false);
		User salesRep = [SELECT Id FROM User WHERE lastName = 'Sales1'][0];
		Account acc = [SELECT Id FROM Account WHERE CN_MG_Account_ID__c = '1'];
		acc.CN_Sync_Status__c = Constants.CN_ACCOUNT_SYNC_STATUS_SUCCESS;
		update acc;

		CN_Ship_to_Party__c shipToParty = [SELECT Id FROM CN_Ship_to_Party__c WHERE CN_ShipTo_Address_ID__c = '1'];
		Id inactiveShiptoRTId = Schema.SObjectType.CN_Change_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CR_RT_API_NAME_INACTIVE_SHIPTO).getRecordTypeId();
		Test.startTest();
		System.runAs(salesRep){
			CN_Change_Request__c cr = new CN_Change_Request__c();

			Map<String, Object> cR_LC_Ctrl_ResultMap = CN_SHIPTO_CHANGE_REQUEST_LC_CTRL.getShipTo(shipToParty.Id);
			for(String field : ((Map<String, String>)cR_LC_Ctrl_ResultMap.get('fieldMap')).keySet()){
				CN_Ship_to_Party__c con_source = (CN_Ship_to_Party__c)cR_LC_Ctrl_ResultMap.get('sourceShipTo');
				cr.put(field,con_source.get(((Map<String, String>)cR_LC_Ctrl_ResultMap.get('fieldMap')).get(field)));
			}
			cr.CN_ShipTo_Address_ID__c = '1';
			cr.CN_Is_Generate_From_Action__c = true;
			cr.New_CN_Contact_CN_Last_Name__c = 'Test CR_update';
			cr.New_CN_ShipTo_Customer_Name__c = 'Test CR_update';
			cr.RecordTypeId = inactiveShiptoRTId;
			cr.OwnerId = salesRep.Id;
			insert cr;

			Trigger_Switcher_Setting__c setting = new Trigger_Switcher_Setting__c(
					SetupOwnerId = UserInfo.getOrganizationId(),
					EnableFlow__c = true,
					EnableTrigger__c = true,
					EnableValidationRule__c = false
			);
			insert setting;

			try {
				cr.CN_Change_Request_Status__c = Constants.CN_CR_STATUS_READY_FOR_APPROVAL;
				update cr;
			} catch (Exception e) {

			}
		}
		Test.stopTest();
	}
}