objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>2 OR (1 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.CN_Group_Name__c</field>
                <operation>equals</operation>
                <valueField>CN_Brand__c.CN_Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>CN_Brand__c.CN_Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CN_Brand__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BAPA</fullName>
                </value>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Coffee/Tea Shop</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
                <value>
                    <fullName>Retailor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Customer_Group__c</fullName>
        <formula>CASE(CN_Category__c, 
&quot;Hotel&quot;,&quot;01&quot;,
&quot;Restaurant&quot;,&quot;02&quot;,
&quot;Catering&quot;,&quot;03&quot;,
&quot;International Chain&quot;,&quot;04&quot;,
&quot;Local Chain&quot;,&quot;05&quot;,
&quot;Department Stores&quot;,&quot;06&quot;,
&quot;Pastry/Bakery/Ice cr&quot;,&quot;07&quot;,
&quot;Expat Stores&quot;,&quot;08&quot;,
&quot;Convenient stores&quot;,&quot;09&quot;,
&quot;Distributor Retail&quot;,&quot;10&quot;,
&quot;Distributor Corporat&quot;,&quot;11&quot;,
&quot;Wholesale Market&quot;,&quot;12&quot;,
&quot;Employee&quot;,&quot;13&quot;,
&quot;Internet sales&quot;,&quot;14&quot;,
&quot;Personal sales&quot;,&quot;15&quot;,
&quot;Distributor Food Ser&quot;,&quot;16&quot;,
&quot;Supply Chain&quot;,&quot;17&quot;,
&quot;Food Logistic Servic&quot;,&quot;18&quot;,
&quot;Supply Chain and Foo&quot;,&quot;19&quot;,
&quot;Key Account&quot;,&quot;20&quot;,
&quot;Distributor Retail &amp;&quot;,&quot;21&quot;,
&quot;Gourmet Shop&quot;,&quot;22&quot;,
&quot;Other&quot;,&quot;23&quot;,
&quot;FS1&quot;,&quot;24&quot;,
&quot;FS2&quot;,&quot;25&quot;,
&quot;FS3&quot;,&quot;26&quot;,
&quot;DEPARTMENT STORES &amp;&quot;,&quot;27&quot;,
&quot;BAPA&quot;,&quot;30&quot;,
&quot;Coffee/Tea Shop&quot;,&quot;31&quot;,
&quot;OEM&quot;,&quot;32&quot;,
&quot;EC&quot;,&quot;33&quot;,
&quot;Wholesaler&quot;,&quot;34&quot;,
&quot;Retailor&quot;,&quot;35&quot;,
&quot;&quot;)</formula>
        <label>Customer Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Group_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>2 OR (1 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.CN_Sales_Team_UI__c</field>
                <operation>equals</operation>
                <valueField>CN_Group__c.CN_Sales_Team__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>CN_Group__c.CN_Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CN_Group__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Sales_Office__c</fullName>
        <label>Sales Office</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>K010</fullName>
                    <label>K010-ShangHai</label>
                </value>
                <value>
                    <fullName>K020</fullName>
                    <label>K020-BeiJing</label>
                </value>
                <value>
                    <fullName>K030</fullName>
                    <label>K030-ShenZhen</label>
                </value>
                <value>
                    <fullName>K040</fullName>
                    <label>K040-GuangZhou</label>
                </value>
                <value>
                    <fullName>K050</fullName>
                    <label>K050-ChengDu</label>
                </value>
                <value>
                    <fullName>K060</fullName>
                    <isActive>false</isActive>
                    <label>K060-DaLian</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sales_Team_Name__c</fullName>
        <formula>CN_Sales_Team_UI__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Team Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Brand__c.object
<CustomObject>
    <fields>
        <fullName>CN_Group_Name__c</fullName>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Promotion__c.object
<CustomObject>
    <fields>
        <fullName>CN_Customer_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Brand</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CN_Brand__c.CN_Group__c</field>
                <operation>equals</operation>
                <valueField>$Source.CN_Customer_Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>CN_Brand__c.CN_Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_Brand__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Customer_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CN_Group__c.CN_Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_Group__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Sales_Office__c</fullName>
        <label>Sales Office</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>K010</fullName>
                    <label>K010-ShangHai</label>
                </value>
                <value>
                    <fullName>K020</fullName>
                    <label>K020-BeiJing</label>
                </value>
                <value>
                    <fullName>K030</fullName>
                    <label>K030-ShenZhen</label>
                </value>
                <value>
                    <fullName>K040</fullName>
                    <label>K040-GuangZhou</label>
                </value>
                <value>
                    <fullName>K050</fullName>
                    <label>K050-ChengDu</label>
                </value>
                <value>
                    <fullName>K060</fullName>
                    <label>K060-DaLian</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KA</fullName>
                </value>
                <value>
                    <fullName>DS</fullName>
                </value>
                <value>
                    <fullName>WS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <label>Customer Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BAPA</fullName>
                </value>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Coffee/Tea Shop</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
                <value>
                    <fullName>Retailor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Promotion_Member__c.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Promotion_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotion Members</relationshipLabel>
        <relationshipName>Promotion_Members1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Category__c</fullName>
        <formula>TEXT(CN_Account__r.CN_Category__c)</formula>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>CN_Promotion__c</referenceTo>
        <relationshipLabel>Promotion Members</relationshipLabel>
        <relationshipName>Promotion_Members2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion Member</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Promotion Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CN_Promotion_Generate_ProMember_LC_Ctrl.cls
/**************************************************************************************************
 * Name           : CN_Promotion_Generate_ProMember_LC_Ctrl
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Dezheng Du
 * Create Date    : 2021-09-10
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_Promotion_Generate_ProMember_LC_Ctrl {

    @AuraEnabled 
    public static Map<String, Object> generateProMember(Id recordId){
        
        List<Profile> profileList = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
        String myProflieName = profileList[0].Name;
        String errorMessage = '';

        if(String.isBlank(recordId)) {
            throw new AuraHandledException(System.Label.CN_Promotion_Not_Found);
        }
        Boolean hasCreatePermission = Untils.checkObjectCreatePermission('CN_Promotion_Member__c');
        if(!hasCreatePermission) {
            throw new AuraHandledException(System.Label.CN_PromotionMember_No_Permission);
        }

        List<CN_Promotion__c> promoList = [SELECT Id,
                                        CN_Status__c,
                                        Channel__c,
                                        Customer_Category__c,
                                        CN_Sales_Office__c,
                                        CN_Customer_Group__c,
                                        CN_Customer_Brand__c
                                   FROM CN_Promotion__c
                                   WHERE Id = :recordId];
        if(promoList.size() > 0) {
            createPromotionMember(promoList[0]);
        }

        return new Map<String, Object>{
            'errorMessage' => errorMessage
        };
    }

    public static void createPromotionMember(CN_Promotion__c promo){
        Integer resultNum = 0;

        List<CN_Promotion_Member__c> promoMemberList_delete = [SELECT Id 
                                   FROM CN_Promotion_Member__c 
                                   WHERE CN_Promotion__c = :promo.Id];

        String queryString = 'SELECT Id,OwnerId FROM Account ';
        List<String> conditionList = new List<String>();

        if(promo.CN_Customer_Group__c != null){
            conditionList.add('CN_Group_Name__c = \'' + promo.CN_Customer_Group__c + '\'');
        }
        if(promo.CN_Customer_Brand__c != null){
            conditionList.add('CN_Brand__c = \'' + promo.CN_Customer_Brand__c + '\'');
        }
        conditionList.add('CN_Sales_Team_Name__c IN (\''+String.join(promo.Channel__c.split(';'), '\',\'')+'\')');
        conditionList.add('CN_Sales_Office__c IN (\''+String.join(promo.CN_Sales_Office__c.split(';'), '\',\'')+'\')');
        conditionList.add('CN_Category__c IN (\''+String.join(promo.Customer_Category__c.split(';'), '\',\'')+'\')');

        if(conditionList.size()>0){
            queryString = queryString + 'WHERE ' + String.join(conditionList , ' AND ');
        }

        List<Account> accList = Database.query(queryString);

        List<CN_Promotion_Member__c> promoMemberList_Generate = new List<CN_Promotion_Member__c>();
        for(Account acc : accList){
            promoMemberList_generate.add(new CN_Promotion_Member__c(CN_Account__c = acc.Id,CN_Account_Owner__c=acc.OwnerId,CN_Promotion__c=promo.Id));
        }
        
        if(promoMemberList_delete.size()>0){
            delete promoMemberList_delete;
        }

        if(promoMemberList_generate.size()>0){
            insert promoMemberList_generate;
        }

    }

}