objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BAPA</fullName>
                </value>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Coffee/Tea Shop</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
                <value>
                    <fullName>Retailor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Customer_Status__c</fullName>
        <formula>IF( 
  ISBLANK(CN_Latest_Order_Create_Date__c) ,
  NULL,
  IF(
    TODAY() &lt; ADDMONTHS(CN_Latest_Order_Create_Date__c,1) ,
    &quot;Active&quot; ,
    IF(TODAY() &lt;  ADDMONTHS(CN_Latest_Order_Create_Date__c,3),&quot;Sleep&quot;,&quot;Dead&quot;)
  )

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sales_Person_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person Name</label>
        <referenceTo>CN_Internal_Employee__c</referenceTo>
        <relationshipLabel>Accounts (Sales Person Name)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Subcategory__c</fullName>
        <label>Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CN_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Access Bakery</fullName>
                </value>
                <value>
                    <fullName>Access Pastry</fullName>
                </value>
                <value>
                    <fullName>Access Ice cream</fullName>
                </value>
                <value>
                    <fullName>Core Bakery</fullName>
                </value>
                <value>
                    <fullName>Core Pastry</fullName>
                </value>
                <value>
                    <fullName>Core Ice cream</fullName>
                </value>
                <value>
                    <fullName>Premium Bakery</fullName>
                </value>
                <value>
                    <fullName>Premium Pastry</fullName>
                </value>
                <value>
                    <fullName>Premium Ice cream</fullName>
                </value>
                <value>
                    <fullName>Casual Dining - Western</fullName>
                </value>
                <value>
                    <fullName>Casual Dining - Asian excl CH</fullName>
                </value>
                <value>
                    <fullName>Casual Dining - Chinese</fullName>
                </value>
                <value>
                    <fullName>Fine Dining - Western</fullName>
                </value>
                <value>
                    <fullName>Fine Dining - Asian excl CH</fullName>
                </value>
                <value>
                    <fullName>Fine Dining - Chinese</fullName>
                </value>
                <value>
                    <fullName>Central Kitchen</fullName>
                </value>
                <value>
                    <fullName>Airline</fullName>
                </value>
                <value>
                    <fullName>Cruise</fullName>
                </value>
                <value>
                    <fullName>Corporate Sales</fullName>
                </value>
                <value>
                    <fullName>Hospital</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Access Coffee Shop</fullName>
                </value>
                <value>
                    <fullName>Access Tea Shop</fullName>
                </value>
                <value>
                    <fullName>Core Coffee Shop</fullName>
                </value>
                <value>
                    <fullName>Core Tea Shop</fullName>
                </value>
                <value>
                    <fullName>Premium Coffee Shop</fullName>
                </value>
                <value>
                    <fullName>Premium Tea Shop</fullName>
                </value>
                <value>
                    <fullName>BAPA OEM</fullName>
                </value>
                <value>
                    <fullName>HORECA OEM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Customer_Status_Trend__c.object
<CustomObject>
    <fields>
        <fullName>CN_Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Customer_Status__c</fullName>
        <label>Customer Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Execution_Time__c</fullName>
        <label>Execution Time</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_License_Name_CN__c</fullName>
        <label>License Name CN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name EN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Subcategory__c</fullName>
        <label>Subcategory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Status Trend</label>
    <nameField>
        <displayFormat>CST-{0000000000}</displayFormat>
        <label>Customer Status Trend No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Status Trend</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CN_Customer_Status_Trend_Batch.cls
/**************************************************************************************************
 * Name           : CN_Customer_Status_Trend_Batch
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Kealsalas Qiu
 * Create Date    : 2021-11-15
 * Modify History : 
 **************************************************************************************************/
global class CN_Customer_Status_Trend_Batch implements Database.Batchable<SObject> {

    global String queryString = '';

    public CN_Customer_Status_Trend_Batch() {
        this.queryString = 'SELECT Id, Name, CN_Customer_Status__c, CN_Category__c, CN_Subcategory__c, CN_Sales_Person_Name__c, CN_License_Name_EN__c, Owner.Name, OwnerId FROM Account';
    }

    public CN_Customer_Status_Trend_Batch(String queryString) {
        this.queryString = queryString;
    }

    global Database.QueryLocator start(Database.BatchableContext ctx) {
		return Database.getQueryLocator(queryString);
	}

    global void execute(Database.BatchableContext bc, List<sObject> scope) {
        Savepoint sp = Database.setSavePoint();
        List<Account> scopeList = (List<Account>)scope;
        List<CN_Customer_Status_Trend__c> cstList = new List<CN_Customer_Status_Trend__c>();
		try{
            for(Account acc : scopeList){
                CN_Customer_Status_Trend__c cst = new CN_Customer_Status_Trend__c();
                cst.CN_Category__c = acc.CN_Category__c;
                cst.CN_Customer_Owner__c = acc.OwnerId;
                cst.CN_Customer_Status__c = acc.CN_Customer_Status__c;
                cst.CN_Execution_Time__c = Date.today();
                cst.CN_License_Name_CN__c = acc.Name;
                cst.CN_License_Name_EN__c = acc.CN_License_Name_EN__c;
                cst.CN_Subcategory__c = acc.CN_Subcategory__c;
                cstList.add(cst);
            }
            if (cstList.size() > 0) {
                insert cstList;
            }				
		} catch (Exception e) {
			Database.rollback(sp);
			throw e;
		} finally {

		}
	}

	global void finish(Database.BatchableContext BC) {

	}
}