objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Source__c</fullName>
        <label>Account Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Recommend</fullName>
                </value>
                <value>
                    <fullName>Cold Visit</fullName>
                </value>
                <value>
                    <fullName>Public Demo</fullName>
                </value>
                <value>
                    <fullName>Brand Activity</fullName>
                </value>
                <value>
                    <fullName>Expositions</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Social Media Network</fullName>
                </value>
                <value>
                    <fullName>Marketing Campaign</fullName>
                </value>
                <value>
                    <fullName>Digital Campaign</fullName>
                </value>
                <value>
                    <fullName>Bakery China</fullName>
                </value>
                <value>
                    <fullName>CIIE</fullName>
                </value>
                <value>
                    <fullName>FHC</fullName>
                </value>
                <value>
                    <fullName>Other Trade show</fullName>
                </value>
                <value>
                    <fullName>Sponsorship Event</fullName>
                </value>
                <value>
                    <fullName>Customer Service Hotline</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Invoicing_Name_Bill_To_Party__c</fullName>
        <label>Invoicing Name (Bill to party)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CIA</fullName>
                    <label>CIA-Payment in advance</label>
                </value>
                <value>
                    <fullName>D000</fullName>
                    <label>D000-Cash on delivery</label>
                </value>
                <value>
                    <fullName>D005</fullName>
                    <label>D005-D05/5 days after delivery</label>
                </value>
                <value>
                    <fullName>D010</fullName>
                    <label>D010-D10/10 days after delivery</label>
                </value>
                <value>
                    <fullName>D015</fullName>
                    <label>D015-15 days after delivery</label>
                </value>
                <value>
                    <fullName>D020</fullName>
                    <label>D020-20 days, due net</label>
                </value>
                <value>
                    <fullName>D030</fullName>
                    <label>D030-30 days, due net</label>
                </value>
                <value>
                    <fullName>D045</fullName>
                    <label>D045-45 days, due net</label>
                </value>
                <value>
                    <fullName>D060</fullName>
                    <label>D060-60days, due net</label>
                </value>
                <value>
                    <fullName>D090</fullName>
                    <label>D090-90days, due net</label>
                </value>
                <value>
                    <fullName>M110</fullName>
                    <label>M110-10 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M115</fullName>
                    <label>M115-15 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M131</fullName>
                    <label>M131-30 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M145</fullName>
                    <label>M145-Before 15th in 2 months, due net</label>
                </value>
                <value>
                    <fullName>M231</fullName>
                    <label>M231-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>D003</fullName>
                    <label>D003-Pay immediately with Invoice</label>
                </value>
                <value>
                    <fullName>D120</fullName>
                    <label>D120-120 days, due net</label>
                </value>
                <value>
                    <fullName>M120</fullName>
                    <label>M120-20 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M23</fullName>
                    <label>M23-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M031</fullName>
                </value>
                <value>
                    <fullName>D007</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CN_Account_Send_MG_Mark_Handler.cls
/*
 * ************************************************************************************************
 * Name : CN_Account_Send_MG_Mark_Handler
 * Object :
 * Requirement :  Insert and Update Mark (Use To AC-017 AND AC-018)
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2023/4/24
 * Modify History :
 * ************************************************************************************************
 */
public class CN_Account_Send_MG_Mark_Handler implements Triggers.Handler{
	public void handle() {
		if (Trigger.isBefore && Trigger.isInsert) {
			handleBeforeInsert();
		} else if (Trigger.isBefore && Trigger.isUpdate) {
			handleBeforeUpdate(); //get Customer or Inactive
		}
	}

	private void handleBeforeInsert() {
		for (Account newAcc : (List<Account>)Trigger.new) {
			//only handle EC Record
			if(newAcc.CN_Account_Source__c != Constants.CN_ACCOUNT_SOURCE_ECOMMERCE){
				continue;
			}
			newAcc.CN_Need_Send_MG_Flag__c = (Integer)newAcc.CN_Need_Send_MG_Flag__c | 1 << 1;
		}
	}

	private void handleBeforeUpdate() {
		Map<Id, Account> oldMap = (Map<Id, Account>)Trigger.oldMap;
		for (Account newAcc : (List<Account>)Trigger.new) {
			if(newAcc.CN_Account_Source__c != Constants.CN_ACCOUNT_SOURCE_ECOMMERCE){
				continue;
			}
			Account oldAcc = oldMap.get(newAcc.Id);
			if (newAcc.CN_Inactive__c != oldAcc.CN_Inactive__c) {
				newAcc.CN_Need_Send_MG_Flag__c = (Integer)newAcc.CN_Need_Send_MG_Flag__c | 1;
			}


			if (newAcc.CN_Customer_Code__c != oldAcc.CN_Customer_Code__c) {
				newAcc.CN_Need_Send_MG_Flag__c = (Integer)newAcc.CN_Need_Send_MG_Flag__c | 1 << 1;
				continue;
			} else if (newAcc.CN_MG_Account_ID__c != oldAcc.CN_MG_Account_ID__c) {
				newAcc.CN_Need_Send_MG_Flag__c = (Integer)newAcc.CN_Need_Send_MG_Flag__c | 1 << 1;
				continue;
			} else if (newAcc.CN_Payment_Terms__c != oldAcc.CN_Payment_Terms__c) {
				newAcc.CN_Need_Send_MG_Flag__c = (Integer)newAcc.CN_Need_Send_MG_Flag__c | 1 << 1;
				continue;
			}
			//add by ZhangZhiHao owner changes to push to EC
			
			else if (newAcc.OwnerId != oldAcc.OwnerId) {
				newAcc.CN_Need_Send_MG_Flag__c = (Integer)newAcc.CN_Need_Send_MG_Flag__c | 1 << 1;
				continue;
			}
			//add by ZhangZhiHao owner changes to push to EC

			//add by ZhangZhiHao owner changes to push to EC 2024/4/14
			else if (newAcc.CN_Invoicing_Name_Bill_To_Party__c != oldAcc.CN_Invoicing_Name_Bill_To_Party__c) {
				newAcc.CN_Need_Send_MG_Flag__c = (Integer)newAcc.CN_Need_Send_MG_Flag__c | 1 << 1;
				continue;
			}
			//add by ZhangZhiHao owner changes to push to EC 2024/4/14

		}

	}

}