objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Change_Request__c</fullName>
        <label>Change Request</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Reference_Day__c</fullName>
        <label>Reference Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery_Day</fullName>
                    <label>Delivery Day</label>
                </value>
                <value>
                    <fullName>Fapiao_Day</fullName>
                    <label>Fapiao Day</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>CN_Is_Generate_From_Action__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Generate From Action</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_CN_Account_Payment_Terms__c</fullName>
        <label>New Account Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CIA</fullName>
                    <label>CIA-Payment in advance</label>
                </value>
                <value>
                    <fullName>D000</fullName>
                    <label>D000-Cash on delivery</label>
                </value>
                <value>
                    <fullName>D003</fullName>
                    <label>D003-Pay immediately with Invoice</label>
                </value>
                <value>
                    <fullName>D005</fullName>
                    <label>D005-D05/5 days after delivery</label>
                </value>
                <value>
                    <fullName>D010</fullName>
                    <label>D010-D10/10 days after delivery</label>
                </value>
                <value>
                    <fullName>D015</fullName>
                    <label>D015-15 days after delivery</label>
                </value>
                <value>
                    <fullName>D020</fullName>
                    <label>D020-20 days, due net</label>
                </value>
                <value>
                    <fullName>D030</fullName>
                    <label>D030-30 days, due net</label>
                </value>
                <value>
                    <fullName>D045</fullName>
                    <label>D045-45 days, due net</label>
                </value>
                <value>
                    <fullName>D060</fullName>
                    <label>D060-60days, due net</label>
                </value>
                <value>
                    <fullName>D090</fullName>
                    <label>D090-90days, due net</label>
                </value>
                <value>
                    <fullName>D120</fullName>
                    <label>D120-120 days, due net</label>
                </value>
                <value>
                    <fullName>M110</fullName>
                    <label>M110-10 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M115</fullName>
                    <label>M115-15 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M120</fullName>
                    <label>M120-20 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M131</fullName>
                    <label>M131-30 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M145</fullName>
                    <label>M145-Before 15th in 2 months, due net</label>
                </value>
                <value>
                    <fullName>M231</fullName>
                    <label>M231-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>D007</fullName>
                </value>
                <value>
                    <fullName>M031</fullName>
                </value>
                <value>
                    <fullName>M23</fullName>
                    <label>M23-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M331</fullName>
                    <isActive>false</isActive>
                    <label>M331-90 days end of month, due net</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_CN_Account_Reference_Day__c</fullName>
        <label>New Account Reference Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery_Day</fullName>
                    <label>Delivery Day</label>
                </value>
                <value>
                    <fullName>Fapiao_Day</fullName>
                    <label>Fapiao Day</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_CN_Account_Require_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Require Contract</label>
        <type>Checkbox</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Change_Request_Fields_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>CN_Change_Request_Field_Name__c</fullName>
        <label>Change Request Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CN_Change_Request_Fields_Mapping</label>
    <pluralLabel>CN_Change_Request_Fields_Mapping</pluralLabel>
</CustomObject>

objects/CN_Credit_Term_Application__c.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Sync_Status__c</fullName>
        <formula>TEXT(CN_Account__r.CN_Sync_Status__c)</formula>
        <label>Account Sync Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Account__c</fullName>
        <label>Sold-to Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Term Applications</relationshipLabel>
        <relationshipName>Credit_Term_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Nature_Of_Request__c</fullName>
        <label>Nature of Request</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Regular Customer</fullName>
                </value>
                <value>
                    <fullName>TM1 (Hotel-3month rule)</fullName>
                </value>
                <value>
                    <fullName>TM2 (BAPA-3month rule)</fullName>
                    <label>TM2(Excluding Hotel-3month rule)</label>
                </value>
                <value>
                    <fullName>NO CONTRACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Payment_Term_Negotiated__c</fullName>
        <label>Payment Term Negotiated</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>D005</fullName>
                    <label>D005-D05/5 days after delivery</label>
                </value>
                <value>
                    <fullName>D010</fullName>
                    <label>D010-D10/10 days after delivery</label>
                </value>
                <value>
                    <fullName>D015</fullName>
                    <label>D015-15 days after delivery</label>
                </value>
                <value>
                    <fullName>D020</fullName>
                    <label>D020-20 days, due net</label>
                </value>
                <value>
                    <fullName>D030</fullName>
                    <label>D030-30 days, due net</label>
                </value>
                <value>
                    <fullName>D045</fullName>
                    <label>D045-45 days, due net</label>
                </value>
                <value>
                    <fullName>D060</fullName>
                    <label>D060-60days, due net</label>
                </value>
                <value>
                    <fullName>D090</fullName>
                    <label>D090-90days, due net</label>
                </value>
                <value>
                    <fullName>M110</fullName>
                    <label>M110-10 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M115</fullName>
                    <label>M115-15 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M131</fullName>
                    <label>M131-30 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M145</fullName>
                    <label>M145-Before 15th in 2 months, due net</label>
                </value>
                <value>
                    <fullName>M231</fullName>
                    <label>M231-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>D000</fullName>
                    <isActive>false</isActive>
                    <label>D000-Payment in advance</label>
                </value>
                <value>
                    <fullName>D003-Pay immediately with Invoice</fullName>
                    <isActive>false</isActive>
                    <label>D003-Pay immediately with Invoice</label>
                </value>
                <value>
                    <fullName>D120-120 days, due net</fullName>
                    <isActive>false</isActive>
                    <label>D120-120 days, due net</label>
                </value>
                <value>
                    <fullName>M120-20 th of next month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M120-20 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M23-60 days end of month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M23-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M331-90 days end of month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M331-90 days end of month, due net</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Reference_Day__c</fullName>
        <label>Reference Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery_Day</fullName>
                    <label>Delivery Day</label>
                </value>
                <value>
                    <fullName>Fapiao_Day</fullName>
                    <label>Fapiao Day</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Credit Term Application</label>
    <nameField>
        <displayFormat>CA{0000000000}</displayFormat>
        <label>Credit Term Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Term Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_CTA_Generate_CR_Handler.cls
/**************************************************************************************************
 * Name           : CN_CTA_Generate_CR_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Du Dezheng
 * Create Date    : 2021-05-21
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_CTA_Generate_CR_Handler implements Triggers.Handler{
    
	public void handle() {
        if(Trigger.isAfter && Trigger.IsUpdate) {
            handleAfterUpdate();
        }
    }
    
    public void handleAfterUpdate() {
        Id ctaRTId = Schema.SObjectType.CN_Credit_Term_Application__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CTA_RT_API_NAME).getRecordTypeId();
        List<CN_Credit_Term_Application__c> ctaList = new List<CN_Credit_Term_Application__c>();
        Map<Id,Id> ctaIdaccIdMap = new Map<Id,Id>();
        for(CN_Credit_Term_Application__c cta : (List<CN_Credit_Term_Application__c>)Trigger.New) {          
            if(Constants.CN_CTA_STATUS_APPROVALED.equals(cta.CN_Status__c) && cta.CN_Status__c <> ((CN_Credit_Term_Application__c)Trigger.oldMap.get(cta.Id)).CN_Status__c 
            && Constants.CN_ACCOUNT_SYNC_STATUS_SUCCESS.equals(cta.CN_Account_Sync_Status__c)){
                ctaList.add(cta);
                ctaIdaccIdMap.put(cta.Id, cta.CN_Account__c);
            }
        }
        if(ctaList.size() > 0){
            generateChangeRequest(ctaList,ctaIdaccIdMap);
        }
    }

    public void generateChangeRequest(List<CN_Credit_Term_Application__c> ctaList,Map<Id,Id> ctaIdaccIdMap){
        Set<String> accIdStringSet = new Set<String>();
        for(Id accId : ctaIdaccIdMap.values()){
            accIdStringSet.add('\'' + String.valueOf(accId) + '\'');
        }
        Set<String> fieldNameStringSet = new Set<String>();
        
        Map<String, String> fieldNamefieldNameOldMap = new Map<String, String>();
        List<CN_Change_Request__c> crList = new List<CN_Change_Request__c>();
        for(CN_Credit_Term_Application__c cta : ctaList){
            Map<String, CN_Change_Request_Fields_Mapping__mdt> crmSettingMap = CN_Change_Request_Fields_Mapping__mdt.getAll();  
            for(String crmSettingId : crmSettingMap.keyset()) {
                if('Account'.equalsIgnoreCase(crmSettingMap.get(crmSettingId).CN_Object_Name__c) == False){
                    continue;
                }
                CN_Change_Request_Fields_Mapping__mdt crmSetting = crmSettingMap.get(crmSettingId);
                String fieldName = crmSetting.CN_Field_Name__c;
                String fieldNameOld = crmSetting.CN_Change_Request_Field_Name__c;    
                fieldNamefieldNameOldMap.put(fieldName, fieldNameOld);
                fieldNameStringSet.add(fieldName); 
            }
        }
    
        String selectFields = String.join(new List<String>(fieldNameStringSet), ',');
        String accIds = String.join(new List<String>(accIdStringSet), ',');
        String soql = 'SELECT ' + selectFields + ' FROM Account WHERE Id IN (' + accIds + ')';
        List<Account> accList = Database.query(soql);
        Map<Id,Account> accIdAccountMap = new Map<Id,Account>();
        for (Account acc : accList) {
            accIdAccountMap.put(acc.Id,acc);
        }

        for(CN_Credit_Term_Application__c cta : ctaList){
            CN_Change_Request__c cr = new CN_Change_Request__c();
            cr.recordTypeId = Schema.SObjectType.CN_Change_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CR_RT_API_NAME_APPD_UPDATE_ACCOUNT).getRecordTypeId();
            for(String fieldName : fieldNameStringSet) {
                String fieldNameOld = fieldNamefieldNameOldMap.get(fieldName);
                String fieldNameNew = 'New_' + fieldNameOld;
                cr.put(fieldNameOld,accIdAccountMap.get( ctaIdaccIdMap.get(cta.Id)).get(fieldName) );
                cr.put(fieldNameNew,accIdAccountMap.get( ctaIdaccIdMap.get(cta.Id)).get(fieldName) );
            }
            cr.New_CN_Account_Reference_Day__c = cta.CN_Reference_Day__c;
            cr.New_CN_Account_Payment_Terms__c = cta.CN_Payment_Term_Negotiated__c;
            cr.CN_Is_Generate_From_Action__c = True;
            if(Constants.CN_CTA_NATURE_OF_REQUEST_REGULAR.equals(cta.CN_Nature_Of_Request__c) 
                || Constants.CN_CTA_NATURE_OF_REQUEST_TM1.equals(cta.CN_Nature_Of_Request__c) 
                || Constants.CN_CTA_NATURE_OF_REQUEST_TM2.equals(cta.CN_Nature_Of_Request__c) ){
                    cr.New_CN_Account_Require_Contract__c = TRUE;
            }
            crList.add(cr);
        }
        insert crList;

    }
}