objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Visit_Addr_CN__c</fullName>
        <inlineHelpText>Please fill with city and street</inlineHelpText>
        <label>Visit Address(CN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CN_Account_Gaode_Geolocation_Batch_Test.cls
/**************************************************************************************************
 * Name           : CN_Account_Gaode_Geolocation_Batch_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Kealsalas Qiu
 * Create Date    : 2021-10-12
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_Account_Gaode_Geolocation_Batch_Test {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }

    @isTest
    private static void CN_Account_Gaode_Geolocation_Batch_Test() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.makeFactoryAccount();

        Account acc_factory = [SELECT Id FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];
        acc_factory.CN_Visit_Addr_CN__c = 'CN_Visit_Addr_CN__c';
        update acc_factory;

        Test.startTest();
        Test.setMock(HTTPCalloutMock.class, new TestHttpMock());

        CN_Account_Gaode_Geolocation_Batch batch = new CN_Account_Gaode_Geolocation_Batch();
        System.schedule('CN_Account_Gaode_Geolocation_Batch' + Datetime.now(), '20 30 8 10 2 ?', batch);

        Test.stopTest();
    }
}