objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Change_Request__c</fullName>
        <label>Change Request</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>CN_Change_Request_Status__c</fullName>
        <label>Change Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4 OR 5</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Update Account Request, Update Contact Request, New Contact Request, Update Ship-to Request, New Ship-to Request</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.CN_Account_Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.CN_Synchronized__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Update Account Request, Update Contact Request, New Contact Request, Update Ship-to Request, New Ship-to Request</value>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Change Requests (Contact)</relationshipLabel>
        <relationshipName>Change_Requests_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Is_Generate_From_Action__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Generate From Action</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_CN_Contact_Billing_To_Address__c</fullName>
        <label>New Contact Billing To Address</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_CN_Contact_CN_First_Name__c</fullName>
        <label>New Contact Name(CN))-First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_CN_Contact_CN_Last_Name__c</fullName>
        <label>New Contact Name(CN))-Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_CN_Contact_Dept_Of_Contact_Person__c</fullName>
        <label>New Department of Contact person</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0001</fullName>
                    <label>0001-Purchasing Dept</label>
                </value>
                <value>
                    <fullName>0002</fullName>
                    <label>0002-Sales Dept</label>
                </value>
                <value>
                    <fullName>0003</fullName>
                    <label>0003-Administration Dept</label>
                </value>
                <value>
                    <fullName>0004</fullName>
                    <label>0004-Production Dept</label>
                </value>
                <value>
                    <fullName>0005</fullName>
                    <label>0005-QA Dept</label>
                </value>
                <value>
                    <fullName>0006</fullName>
                    <label>0006-Secretary&apos;s Office</label>
                </value>
                <value>
                    <fullName>0007</fullName>
                    <label>0007-Financial Dept</label>
                </value>
                <value>
                    <fullName>0008</fullName>
                    <label>0008-Legal Dept</label>
                </value>
                <value>
                    <fullName>0009</fullName>
                    <label>0009-Human Resources Dept</label>
                </value>
                <value>
                    <fullName>0010</fullName>
                    <label>0010-General Affairs Dept</label>
                </value>
                <value>
                    <fullName>0011</fullName>
                    <label>0011-Sales Promotion Dept</label>
                </value>
                <value>
                    <fullName>0012</fullName>
                    <label>0012-International Dept</label>
                </value>
                <value>
                    <fullName>0013</fullName>
                    <label>0013-Export Dept</label>
                </value>
                <value>
                    <fullName>0014</fullName>
                    <label>0014-Import Dept</label>
                </value>
                <value>
                    <fullName>0015</fullName>
                    <label>0015-Public Relation Dept</label>
                </value>
                <value>
                    <fullName>0016</fullName>
                    <label>0016-Advertising Dept</label>
                </value>
                <value>
                    <fullName>0017</fullName>
                    <label>0017-Planning Dept</label>
                </value>
                <value>
                    <fullName>0018</fullName>
                    <label>0018-R&amp;D Dept</label>
                </value>
                <value>
                    <fullName>0019</fullName>
                    <label>0019-Product Dev. Dept</label>
                </value>
                <value>
                    <fullName>0020</fullName>
                    <label>0020-Food &amp; Beverage Dept</label>
                </value>
                <value>
                    <fullName>0021</fullName>
                    <label>0021-Service Dept</label>
                </value>
                <value>
                    <fullName>0022</fullName>
                    <label>0022-Technical Support</label>
                </value>
                <value>
                    <fullName>0023</fullName>
                    <label>0023-IT Dept</label>
                </value>
                <value>
                    <fullName>0024</fullName>
                    <label>0024-Logistics Dept</label>
                </value>
                <value>
                    <fullName>0025</fullName>
                    <label>0025-Cold Kitchen</label>
                </value>
                <value>
                    <fullName>0026</fullName>
                    <label>0026-Hot Kitchen</label>
                </value>
                <value>
                    <fullName>0027</fullName>
                    <label>0027-Banquet Kitchen</label>
                </value>
                <value>
                    <fullName>0028</fullName>
                    <label>0028-Pastry</label>
                </value>
                <value>
                    <fullName>0029</fullName>
                    <label>0029-Backery</label>
                </value>
                <value>
                    <fullName>0030</fullName>
                    <label>0030-Bar</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_CN_Contact_Mobile__c</fullName>
        <inlineHelpText>Please enter the number in the format of 1XXXXXXXXXX or XXX-XXXXXXXX or XXXX-XXXXXXXX-XXX (X is number).</inlineHelpText>
        <label>New Contact Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>New_CN_Contact_Name_EN__c</fullName>
        <label>New Contact Name(EN)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_CN_Contact_Title__c</fullName>
        <label>New Contact Title</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_CN_Contact_Type__c</fullName>
        <label>New Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>01-Billing</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>02-Business</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>04-Others</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CN_Change_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change Request</label>
        <referenceTo>CN_Change_Request__c</referenceTo>
        <relationshipLabel>Change Request</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_CR_Contact_Billing_Upsert_Rest_Test.cls
/*
 * ************************************************************************************************
 * Name : CN_CR_Contact_Billing_Upsert_Rest_Test
 * Description :
 * Object :
 * Requirement :
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2023/12/28
 * Modify History :
 * ************************************************************************************************
 */
@isTest
public class CN_CR_Contact_Billing_Upsert_Rest_Test {
	@TestSetup
	static void makeData(){
		TestDataFactory.makeBaseData();
	}

    @IsTest
	private static void handleContact(){
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		RestResponse res = new RestResponse();
		RestRequest request = new RestRequest();
		request.requestURI = '/services/apexrest/BillingAddressUpsert';
		request.httpMethod = 'POST';
		String body = '{"datas":[{"newContactTitle":"Title","newContactNameCNLastName":"example2-1213V2","newContactNameCNFirstName":"U1692156286-1213","newContactNameEN":"EN name","newContactLicenseName":"1","newContactType":"01;02","newDepartmentOfContactPerson":"0015","newContactPhoneNumber":"18516071021","newContactMobile":"15202121020","newContactWechatID":"15202121020","newContactEmail":"peggy.liu@savencia-test.com","mgContactID":"1","newContactBillingToAddress":"\u5317\u4eac\u4e07\u53e4\u79d1\u6280\u80a1\u4efd\u6709\u9650\u516c\u53f8test1455","newContactBirthday":"2000-01-01","newContactReportsTo":"","newContactFamilyInfo":"","newContactOpenFieldToComment":"","mgBillingToAddressID":"1","billingToAddressId":"1","newShipToIndirectAccount":""}]}';
		request.requestBody = Blob.valueOf(body);
		RestContext.request = request;
		RestContext.response= res;
		Test.startTest();
		CN_CR_Contact_Billing_Upsert_Rest.post();
		Test.stopTest();
	}

	@IsTest
	private static void handleContactFieldError(){
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		RestResponse res = new RestResponse();
		RestRequest request = new RestRequest();
		request.requestURI = '/services/apexrest/BillingAddressUpsert';
		request.httpMethod = 'POST';
		String body = '{"datas":[{"newContactMobile":"15202121020","newContactWechatID":"15202121020","newContactEmail":"peggy.liu@savencia-test.com","mgContactID":"1","newContactBillingToAddress":"\u5317\u4eac\u4e07\u53e4\u79d1\u6280\u80a1\u4efd\u6709\u9650\u516c\u53f8test1455","newContactBirthday":"2000-01-01","newContactReportsTo":"","newContactFamilyInfo":"","newContactOpenFieldToComment":"","mgBillingToAddressID":"1","billingToAddressId":"1","newShipToIndirectAccount":""}]}';
		request.requestBody = Blob.valueOf(body);
		RestContext.request = request;
		RestContext.response= res;
		Test.startTest();
		CN_CR_Contact_Billing_Upsert_Rest.post();
		Test.stopTest();
	}

	@IsTest
	private static void handleContacNoneData(){
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		RestResponse res = new RestResponse();
		RestRequest request = new RestRequest();
		request.requestURI = '/services/apexrest/BillingAddressUpsert';
		request.httpMethod = 'POST';
		String body = '{}';
		request.requestBody = Blob.valueOf(body);
		RestContext.request = request;
		RestContext.response= res;
		Test.startTest();
		CN_CR_Contact_Billing_Upsert_Rest.post();
		Test.stopTest();
	}

	@IsTest
	private static void handleContactInsertError(){
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		RestResponse res = new RestResponse();
		RestRequest request = new RestRequest();
		request.requestURI = '/services/apexrest/BillingAddressUpsert';
		request.httpMethod = 'POST';
		String body = '{"datas":[{"newContactTitle":"Title","newContactNameCNLastName":"example2-1213V2","newContactNameCNFirstName":"U1692156286-1213","newContactNameEN":"EN name","newContactLicenseName":"1","newContactType":"01;02","newDepartmentOfContactPerson":"0015","newContactPhoneNumber":"18516071021","newContactMobile":"15202121020","newContactWechatID":"15202121020","newContactEmail":"com","newContactBillingToAddress":"\u5317\u4eac\u4e07\u53e4\u79d1\u6280\u80a1\u4efd\u6709\u9650\u516c\u53f8test1455","newContactBirthday":"2000-01-01","newContactReportsTo":"","newContactFamilyInfo":"","newContactOpenFieldToComment":"","mgBillingToAddressID":"1","billingToAddressId":"1","newShipToIndirectAccount":""}]}';
		request.requestBody = Blob.valueOf(body);
		RestContext.request = request;
		RestContext.response= res;
		Test.startTest();
		CN_CR_Contact_Billing_Upsert_Rest.post();
		Test.stopTest();
	}

	@IsTest
	private static void handleContactNoneMgContactId(){
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		RestResponse res = new RestResponse();
		RestRequest request = new RestRequest();
		request.requestURI = '/services/apexrest/BillingAddressUpsert';
		request.httpMethod = 'POST';
		String body = '{"datas":[{"newContactTitle":"Title","newContactNameCNLastName":"example2-1213V2","newContactNameCNFirstName":"U1692156286-1213","newContactNameEN":"EN name","newContactLicenseName":"1","newContactType":"01;02","newDepartmentOfContactPerson":"0015","newContactPhoneNumber":"18516071021","newContactMobile":"15202121020","newContactWechatID":"15202121020","newContactEmail":"peggy.liu@savencia-test.com","mgContactID":"1000","newContactBillingToAddress":"\u5317\u4eac\u4e07\u53e4\u79d1\u6280\u80a1\u4efd\u6709\u9650\u516c\u53f8test1455","newContactBirthday":"2000-01-01","newContactReportsTo":"","newContactFamilyInfo":"","newContactOpenFieldToComment":"","mgBillingToAddressID":"1","billingToAddressId":"1","newShipToIndirectAccount":""}]}';
		request.requestBody = Blob.valueOf(body);
		RestContext.request = request;
		RestContext.response= res;
		Test.startTest();
		CN_CR_Contact_Billing_Upsert_Rest.post();
		Test.stopTest();
	}



	@IsTest
	private static void handleWithAutoSubmit(){
		TestDataFactory testFactory = new TestDataFactory();
		testFactory.makeFactoryAccount();
		Account acc_factory = [SELECT Id FROM Account WHERE CN_License_Name_EN__c = 'TestAccount_Factory'][0];
		Contact contactId = [SELECT Id FROM Contact WHERE CN_MG_Contact_ID__c = '1'][0];

		CN_Change_Request__c cr = new CN_Change_Request__c();
		RecordType recordTypeAPPD = [SELECT ID FROM RecordType WHERE DeveloperName = :Constants.CN_CR_RT_API_NAME_APPD_UPDATE_CONTACT].get(0);
		cr.recordtypeId = recordTypeAPPD.id;
		cr.CN_CR_Source__c = 'E-Commerce';
		cr.New_CN_Contact_Type__c = '04';
		cr.New_CN_Contact_Title__c = 'contact title';
		cr.CN_Is_Generate_From_Action__c = true;
		cr.New_CN_Contact_CN_First_Name__c = 'Test';
		cr.New_CN_Contact_CN_Last_Name__c = 'Test CR_update';
		cr.New_CN_Contact_Dept_Of_Contact_Person__c = '0001';
		cr.New_CN_Contact_Name_EN__c = 'Contact Name EN';
		cr.New_CN_Contact_Mobile__c = '15755555555';
		cr.New_CN_Contact_Billing_To_Address__c = '1';
		cr.CN_Change_Request_Status__c = 'Approved' ;
		cr.CN_External_Id__c  = contactId.id ;
		cr.CN_Contact__c=contactId.id;
            
        insert cr;

		RestResponse res = new RestResponse();
		RestRequest request = new RestRequest();
		request.requestURI = '/services/apexrest/BillingAddressUpsert';
		request.httpMethod = 'POST';
		String body = '{"datas":[{"newContactTitle":"Title","newContactNameCNLastName":"example2-1213V2","newContactNameCNFirstName":"U1692156286-1213","newContactNameEN":"EN name","newContactLicenseName":"1","newContactType":"01;02","newDepartmentOfContactPerson":"0015","newContactPhoneNumber":"18516071021","newContactMobile":"15202121020","newContactWechatID":"15202121020","newContactEmail":"peggy.liu@savencia-test.com","mgContactID":"1","newContactBillingToAddress":"\u5317\u4eac\u4e07\u53e4\u79d1\u6280\u80a1\u4efd\u6709\u9650\u516c\u53f8test1455","newContactBirthday":"2000-01-01","newContactReportsTo":"","newContactFamilyInfo":"","newContactOpenFieldToComment":"","mgBillingToAddressID":"1","billingToAddressId":"1","newShipToIndirectAccount":""}]}';
		request.requestBody = Blob.valueOf(body);
		RestContext.request = request;
		RestContext.response= res;
		Test.startTest();
		CN_CR_Contact_Billing_Upsert_Rest.post();
		Test.stopTest();
	}

	
}