objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Latest_Credit_Term_App_Status__c</fullName>
        <label>Latest Credit Term App Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Nature__c</fullName>
        <label>Nature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CIA</fullName>
                    <label>CIA-Payment in advance</label>
                </value>
                <value>
                    <fullName>D000</fullName>
                    <label>D000-Cash on delivery</label>
                </value>
                <value>
                    <fullName>D005</fullName>
                    <label>D005-D05/5 days after delivery</label>
                </value>
                <value>
                    <fullName>D010</fullName>
                    <label>D010-D10/10 days after delivery</label>
                </value>
                <value>
                    <fullName>D015</fullName>
                    <label>D015-15 days after delivery</label>
                </value>
                <value>
                    <fullName>D020</fullName>
                    <label>D020-20 days, due net</label>
                </value>
                <value>
                    <fullName>D030</fullName>
                    <label>D030-30 days, due net</label>
                </value>
                <value>
                    <fullName>D045</fullName>
                    <label>D045-45 days, due net</label>
                </value>
                <value>
                    <fullName>D060</fullName>
                    <label>D060-60days, due net</label>
                </value>
                <value>
                    <fullName>D090</fullName>
                    <label>D090-90days, due net</label>
                </value>
                <value>
                    <fullName>M110</fullName>
                    <label>M110-10 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M115</fullName>
                    <label>M115-15 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M131</fullName>
                    <label>M131-30 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M145</fullName>
                    <label>M145-Before 15th in 2 months, due net</label>
                </value>
                <value>
                    <fullName>M231</fullName>
                    <label>M231-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>D003</fullName>
                    <label>D003-Pay immediately with Invoice</label>
                </value>
                <value>
                    <fullName>D120</fullName>
                    <label>D120-120 days, due net</label>
                </value>
                <value>
                    <fullName>M120</fullName>
                    <label>M120-20 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M23</fullName>
                    <label>M23-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M031</fullName>
                </value>
                <value>
                    <fullName>D007</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Require_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Require Contract</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Credit_Term_Application__c.object
<CustomObject>
    <fields>
        <fullName>CN_Account__c</fullName>
        <label>Sold-to Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Term Applications</relationshipLabel>
        <relationshipName>Credit_Term_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Nature_Of_Request__c</fullName>
        <label>Nature of Request</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Regular Customer</fullName>
                </value>
                <value>
                    <fullName>TM1 (Hotel-3month rule)</fullName>
                </value>
                <value>
                    <fullName>TM2 (BAPA-3month rule)</fullName>
                    <label>TM2(Excluding Hotel-3month rule)</label>
                </value>
                <value>
                    <fullName>NO CONTRACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Payment_Term_Negotiated__c</fullName>
        <label>Payment Term Negotiated</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>D005</fullName>
                    <label>D005-D05/5 days after delivery</label>
                </value>
                <value>
                    <fullName>D010</fullName>
                    <label>D010-D10/10 days after delivery</label>
                </value>
                <value>
                    <fullName>D015</fullName>
                    <label>D015-15 days after delivery</label>
                </value>
                <value>
                    <fullName>D020</fullName>
                    <label>D020-20 days, due net</label>
                </value>
                <value>
                    <fullName>D030</fullName>
                    <label>D030-30 days, due net</label>
                </value>
                <value>
                    <fullName>D045</fullName>
                    <label>D045-45 days, due net</label>
                </value>
                <value>
                    <fullName>D060</fullName>
                    <label>D060-60days, due net</label>
                </value>
                <value>
                    <fullName>D090</fullName>
                    <label>D090-90days, due net</label>
                </value>
                <value>
                    <fullName>M110</fullName>
                    <label>M110-10 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M115</fullName>
                    <label>M115-15 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M131</fullName>
                    <label>M131-30 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M145</fullName>
                    <label>M145-Before 15th in 2 months, due net</label>
                </value>
                <value>
                    <fullName>M231</fullName>
                    <label>M231-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>D000</fullName>
                    <isActive>false</isActive>
                    <label>D000-Payment in advance</label>
                </value>
                <value>
                    <fullName>D003-Pay immediately with Invoice</fullName>
                    <isActive>false</isActive>
                    <label>D003-Pay immediately with Invoice</label>
                </value>
                <value>
                    <fullName>D120-120 days, due net</fullName>
                    <isActive>false</isActive>
                    <label>D120-120 days, due net</label>
                </value>
                <value>
                    <fullName>M120-20 th of next month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M120-20 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M23-60 days end of month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M23-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M331-90 days end of month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M331-90 days end of month, due net</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Credit Term Application</label>
    <nameField>
        <displayFormat>CA{0000000000}</displayFormat>
        <label>Credit Term Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Term Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_CTA_Populate_Account_Handler.cls
/**************************************************************************************************
 * Name           : CN_CTA_Populate_Account_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Du Dezheng
 * Create Date    : 2021-05-12
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_CTA_Populate_Account_Handler implements Triggers.Handler{
    public void handle() {
        // if(Trigger.isAfter && Trigger.isUpdate) {
        //     handleAfterUpdate();
        // }
        // if(Trigger.isAfter && Trigger.isInsert) {
        //     handleAfterInsert();
        // }
    }
    
    // public void handleAfterInsert() {
    //     Set<Id> accIdSet = new Set<Id>();
    //     Id ctaRTId = Schema.SObjectType.CN_Credit_Term_Application__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CTA_RT_API_NAME).getRecordTypeId();
    //     for(CN_Credit_Term_Application__c cta : (List<CN_Credit_Term_Application__c>)Trigger.New){
    //         if(ctaRTId == cta.RecordTypeId){
    //             accIdSet.add(cta.CN_Account__c);
    //         }
    //         if(accIdSet.size()>0){
    //             populateAccountField_New(accIdSet);
    //         }
    //     }
    // }
    
    // public void handleAfterUpdate() {	
    //     Id ctaRTId = Schema.SObjectType.CN_Credit_Term_Application__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CTA_RT_API_NAME).getRecordTypeId();
    //     List<CN_Credit_Term_Application__c> ctaList_Status = new List<CN_Credit_Term_Application__c>();
    //     List<CN_Credit_Term_Application__c> ctaList_Approved = new List<CN_Credit_Term_Application__c>();
    //     List<CN_Credit_Term_Application__c> ctaList_ChangedToCancel = new List<CN_Credit_Term_Application__c>();
    //     List<Account> accList = new List<Account>();
    //     for(CN_Credit_Term_Application__c cta : (List<CN_Credit_Term_Application__c>)Trigger.New){
    //         if(ctaRTId == cta.RecordTypeId && cta.CN_Status__c <> ((CN_Credit_Term_Application__c)Trigger.oldMap.get(cta.Id)).CN_Status__c){
    //             if(cta.CN_Status__c == Constants.CN_CTA_STATUS_APPROVALED){
    //                 system.debug('handleAfterUpdate if1');
    //                 ctaList_Approved.add(cta);
    //             }else if(cta.CN_Status__c == Constants.CN_CTA_STATUS_CANCEL){
    //                 ctaList_ChangedToCancel.add(cta);
    //                 system.debug('handleAfterUpdate if2');
    //             }else{
    //                 ctaList_Status.add(cta);
    //                 system.debug('handleAfterUpdate if3');
    //             }
    //         }
    //     }
    //     if(ctaList_Status.size()>0){
    //         accList.addAll(populateAccountField_Status(ctaList_Status));
    //     }
    //     system.debug('accList1:' + accList);
    //     if(ctaList_ChangedToCancel.size()>0){
    //         accList.addAll(populateAccountField_ChangedToCancel(ctaList_ChangedToCancel));
    //     }
    //     system.debug('accList2:' + accList);
    //     if(ctaList_Approved.size()>0){
    //         accList.addAll(populateAccountField_Approved(ctaList_Approved));
    //     }
    //     system.debug('update accList:' + accList);
    //     if(accList.size()>0){
    //         Constants.ACCOUNT_TRIGGER_ON = false;
    //    		update accList;
    //     	Constants.ACCOUNT_TRIGGER_ON = true;
    //     }
    // }
    
    // public List<Account> populateAccountField_Status(List<CN_Credit_Term_Application__c> ctaList) {
    //     List<Account> accList = new List<Account>();
    //     for(CN_Credit_Term_Application__c cta : ctaList){
    //         accList.add(new Account(Id = cta.CN_Account__c,
    //                                 CN_Latest_Credit_Term_App_Status__c = cta.CN_Status__c));
    //     }
    //     return accList;
    // }
    // public List<Account> populateAccountField_Approved(List<CN_Credit_Term_Application__c> ctaList) {
    //     List<Account> accList = new List<Account>();
    //     Set<Id> ctaId = new Set<Id>();
    //     for(CN_Credit_Term_Application__c cta : ctaList){
    //         ctaId.add(cta.Id);
    //     }
    //     List<CN_Credit_Term_Application__c> ctaList_Qurey_CtaId = [Select Id,CN_Account__c,CN_Nature_Of_Request__c,CN_Payment_Term_Negotiated__c From CN_Credit_Term_Application__c Where Id IN :ctaId];
    //     if(ctaList_Qurey_CtaId.size()>0){
    //         for(CN_Credit_Term_Application__c cta : ctaList_Qurey_CtaId){
    //             accList.add(new Account(Id = cta.CN_Account__c,
    //                                     CN_Nature__c = cta.CN_Nature_Of_Request__c,
    //                                     CN_Payment_Terms__c = cta.CN_Payment_Term_Negotiated__c,
    //                                     CN_Latest_Credit_Term_App_Status__c = constants.CN_CTA_STATUS_APPROVALED,
    //                                     CN_Require_Contract__c = TRUE));
    //         }  
            
    //     }
    //     return accList;
    // }
    // public List<Account> populateAccountField_ChangedToCancel(List<CN_Credit_Term_Application__c> ctaList) {
	// 	List<Account> accList = new List<Account>();
    //     Set<Id> ctaId = new Set<Id>();
    //     Map<Id,Id> catIdaccIdMap = new Map<Id,Id>();
    //     for(CN_Credit_Term_Application__c cta : ctaList){
    //         ctaId.add(cta.Id);
    //     }
    //     List<CN_Credit_Term_Application__c> ctaList_Qurey_CtaId = [Select Id,CN_Account__c From CN_Credit_Term_Application__c Where Id IN :ctaId];
    //     if(ctaList_Qurey_CtaId.size()>0){
    //         for(CN_Credit_Term_Application__c cta : ctaList_Qurey_CtaId){
    //             catIdaccIdMap.put(cta.CN_Account__c,cta.Id);
    //         }
    //         List<CN_Credit_Term_Application__c> ctaList_Qurey_AccId = [Select Id,CN_Account__c,CN_Status__c From CN_Credit_Term_Application__c 
    //                                                                 Where CN_Account__c IN :catIdaccIdMap.keySet() AND CN_Status__c <> :Constants.CN_CTA_STATUS_CANCEL];
    //         if(ctaList_Qurey_AccId.size()>0){
    //             for(CN_Credit_Term_Application__c cta : ctaList_Qurey_AccId){
    //                 if(catIdaccIdMap.get(cta.CN_Account__c) <> NULL){
    //                     accList.add(new Account(Id = cta.CN_Account__c,CN_Latest_Credit_Term_App_Status__c = Constants.CN_CTA_STATUS_APPROVALED));
    //                 }else{
    //                     accList.add(new Account(Id = cta.CN_Account__c,CN_Latest_Credit_Term_App_Status__c = NULL));
    //                 }
    //             }
    //         }
    //     }
    //     return accList;
    // }
    // public void populateAccountField_New(Set<Id> accIdSet) {
    //     List<Account> accList = new List<Account>();
    //     for(Id accId : accIdSet){
    //         accList.add(new Account(Id = accId,
    //                                 CN_Latest_Credit_Term_App_Status__c = Constants.CN_CTA_STATUS_NEW));
    //     }
    //     if(accList.size()>0){
    //         Constants.ACCOUNT_TRIGGER_ON = false;
    //    		update accList;
    //     	Constants.ACCOUNT_TRIGGER_ON = true;
    //     }
    // }
}