objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Bank_Account_Name__c</fullName>
        <label>Bank Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Bank_Account__c</fullName>
        <label>Bank Account</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Finance_AR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance AR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Invoice_Type__c</fullName>
        <label>Invoice Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VAT Invoice</fullName>
                </value>
                <value>
                    <fullName>General Invoice</fullName>
                </value>
                <value>
                    <fullName>Electronic General Invoice</fullName>
                </value>
                <value>
                    <fullName>Electronic VAT Invoice</fullName>
                </value>
                <value>
                    <fullName>No need Invoice</fullName>
                    <isActive>false</isActive>
                    <label>No need invoice</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Invoicing_Address_and_Phone__c</fullName>
        <inlineHelpText>address and phone</inlineHelpText>
        <label>Invoicing Address and Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Invoicing_Name_Bill_To_Party__c</fullName>
        <label>Invoicing Name (Bill to party)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CIA</fullName>
                    <label>CIA-Payment in advance</label>
                </value>
                <value>
                    <fullName>D000</fullName>
                    <label>D000-Cash on delivery</label>
                </value>
                <value>
                    <fullName>D005</fullName>
                    <label>D005-D05/5 days after delivery</label>
                </value>
                <value>
                    <fullName>D010</fullName>
                    <label>D010-D10/10 days after delivery</label>
                </value>
                <value>
                    <fullName>D015</fullName>
                    <label>D015-15 days after delivery</label>
                </value>
                <value>
                    <fullName>D020</fullName>
                    <label>D020-20 days, due net</label>
                </value>
                <value>
                    <fullName>D030</fullName>
                    <label>D030-30 days, due net</label>
                </value>
                <value>
                    <fullName>D045</fullName>
                    <label>D045-45 days, due net</label>
                </value>
                <value>
                    <fullName>D060</fullName>
                    <label>D060-60days, due net</label>
                </value>
                <value>
                    <fullName>D090</fullName>
                    <label>D090-90days, due net</label>
                </value>
                <value>
                    <fullName>M110</fullName>
                    <label>M110-10 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M115</fullName>
                    <label>M115-15 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M131</fullName>
                    <label>M131-30 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M145</fullName>
                    <label>M145-Before 15th in 2 months, due net</label>
                </value>
                <value>
                    <fullName>M231</fullName>
                    <label>M231-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>D003</fullName>
                    <label>D003-Pay immediately with Invoice</label>
                </value>
                <value>
                    <fullName>D120</fullName>
                    <label>D120-120 days, due net</label>
                </value>
                <value>
                    <fullName>M120</fullName>
                    <label>M120-20 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M23</fullName>
                    <label>M23-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M031</fullName>
                </value>
                <value>
                    <fullName>D007</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sales_District__c</fullName>
        <label>Sales District</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>020</fullName>
                    <label>020-Out of ShangHai</label>
                </value>
                <value>
                    <fullName>001</fullName>
                    <label>001-SH-HuangPu</label>
                </value>
                <value>
                    <fullName>002</fullName>
                    <label>002-SH-LuWan</label>
                </value>
                <value>
                    <fullName>003</fullName>
                    <label>003-SH-XuHui</label>
                </value>
                <value>
                    <fullName>004</fullName>
                    <label>004-SH-ChangNing</label>
                </value>
                <value>
                    <fullName>005</fullName>
                    <label>005-SH-JingAn</label>
                </value>
                <value>
                    <fullName>006</fullName>
                    <label>006-SH-PuTuo</label>
                </value>
                <value>
                    <fullName>007</fullName>
                    <label>007-SH-ZhaBei</label>
                </value>
                <value>
                    <fullName>008</fullName>
                    <label>008-SH-HongKou</label>
                </value>
                <value>
                    <fullName>009</fullName>
                    <label>009-SH-YangPu</label>
                </value>
                <value>
                    <fullName>010</fullName>
                    <label>010-SH-MingHang</label>
                </value>
                <value>
                    <fullName>011</fullName>
                    <label>011-SH-BaoShan</label>
                </value>
                <value>
                    <fullName>012</fullName>
                    <label>012-SH-JiaDing</label>
                </value>
                <value>
                    <fullName>013</fullName>
                    <label>013-SH-PuDong new Distr</label>
                </value>
                <value>
                    <fullName>014</fullName>
                    <label>014-SH-JinShan</label>
                </value>
                <value>
                    <fullName>015</fullName>
                    <label>015-SH-SongJiang</label>
                </value>
                <value>
                    <fullName>016</fullName>
                    <label>016-SH-QingPu</label>
                </value>
                <value>
                    <fullName>017</fullName>
                    <label>017-SH-NanHui</label>
                </value>
                <value>
                    <fullName>018</fullName>
                    <label>018-SH-FengXian</label>
                </value>
                <value>
                    <fullName>019</fullName>
                    <label>019-SH-CongMing</label>
                </value>
                <value>
                    <fullName>021</fullName>
                    <label>021-HangZhou</label>
                </value>
                <value>
                    <fullName>022</fullName>
                    <label>022-SuZhou</label>
                </value>
                <value>
                    <fullName>023</fullName>
                    <label>023-Nanjing</label>
                </value>
                <value>
                    <fullName>024</fullName>
                    <label>024-BeiJing</label>
                </value>
                <value>
                    <fullName>025</fullName>
                    <label>025-ShenZhen</label>
                </value>
                <value>
                    <fullName>026</fullName>
                    <label>026-GuangZhou</label>
                </value>
                <value>
                    <fullName>B01</fullName>
                    <isActive>false</isActive>
                    <label>B01-North Area</label>
                </value>
                <value>
                    <fullName>B02</fullName>
                    <isActive>false</isActive>
                    <label>B02-East Area</label>
                </value>
                <value>
                    <fullName>B03</fullName>
                    <isActive>false</isActive>
                    <label>B03-South Area</label>
                </value>
                <value>
                    <fullName>B04</fullName>
                    <isActive>false</isActive>
                    <label>B04-e-commerce</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sales_Office__c</fullName>
        <label>Sales Office</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>K010</fullName>
                    <label>K010-ShangHai</label>
                </value>
                <value>
                    <fullName>K020</fullName>
                    <label>K020-BeiJing</label>
                </value>
                <value>
                    <fullName>K030</fullName>
                    <label>K030-ShenZhen</label>
                </value>
                <value>
                    <fullName>K040</fullName>
                    <label>K040-GuangZhou</label>
                </value>
                <value>
                    <fullName>K050</fullName>
                    <label>K050-ChengDu</label>
                </value>
                <value>
                    <fullName>K060</fullName>
                    <isActive>false</isActive>
                    <label>K060-DaLian</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sales_Org__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>S010</fullName>
                    <default>true</default>
                    <label>S010-Sinodis Sales Org</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sales_Team_UI__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Please search for KA/DS/WS.</inlineHelpText>
        <label>Sales Team</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>2 OR (1 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.CN_Business_Unit_UI__c</field>
                <operation>equals</operation>
                <valueField>CN_Sales_Team__c.CN_Business_Unit__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.CN_Is_Integration_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>CN_Sales_Team__c.CN_Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CN_Sales_Team__c</referenceTo>
        <relationshipLabel>SalesTeams</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Store_Name_CN__c</fullName>
        <label>Commercial Name (CN)</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Store_Name_EN__c</fullName>
        <label>Commercial Name (EN)</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Tax_Registration_No__c</fullName>
        <label>Tax Registration No.</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_API_Call_Logger__c.object
<CustomObject>
    <description>API Call Log</description>
    <label>API Call Logger</label>
    <nameField>
        <displayFormat>INF-{YYYYMMDD}{0000}</displayFormat>
        <label>API Call Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Call Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Sales_Team__c.object
<CustomObject>
    <label>Sales Team</label>
    <nameField>
        <label>Sales Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Talend_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Talend Setting</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CN_Sales_Office__c</fullName>
        <label>Sales Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CN_Account_Customer_Code_To_Mg_Callout.cls
/*
 * ************************************************************************************************
 * Name : CN_Account_Customer_Code_To_Mg_Callout
 * Object :
 * Requirement : AC-017
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2023/4/7
 * Modify History :
 * ************************************************************************************************
 */
public class CN_Account_Customer_Code_To_Mg_Callout {

	public static Map<String,Account> upsertCustomerCodeToMg(List<Account> accounts,List<CN_API_Call_Logger__c> listLog){

		//handleDataList
		List<Map<String, Object>> maps = handleData(accounts);

		//Necessary parameters for assembly request
		Talend_Setting__c setting = Talend_Setting__c.getInstance();
		Http http = new Http();
		HttpRequest request = CN_HelperClass_WS.createHttpRequestHelper(
				setting.Sandbox_MG_Save_Customer_Code__c,
				setting.MG_Save_Customer_Code__c);

		Map<String,Account> sendSuccessMap = new Map<String,Account>();
		for(Map<String,Object> param:maps){
			CN_HelperClass_WS.WS_Log log = new CN_HelperClass_WS.WS_Log();
			try {
				String body = JSON.serialize(param);
				log.SetRequest(body);

				request.setBody(body);
				System.debug(body);
				HttpResponse response = http.send(request);
				log.SetResponse(response.getBody());

				// Parse the JSON response
				Integer resCode = response.getStatusCode();
				String errorMsg = '';
				String errorMessage = '';
				if(resCode == 200) {
					System.debug(response.getBody());
					Integer  cs = CN_HelperClass_WS.getRetDataCode(response.getBody());
					if(cs != null &&cs == 1) {
						Account account = new Account();
						account.Id = String.valueOf(param.get('MAP_ID'));
						sendSuccessMap.put(account.Id, account);
					}
				}else if(resCode == 503) {
					System.debug(resCode + ':' + Json.serialize(response.getBody()));
					errorMessage = 'Server Error';
				}else {
					if(resCode == 500) {
						errorMessage = 'Server Error';
					} else if(resCode == 404) {
						errorMessage = 'API Path Error';
					}
				}
				errorMsg = resCode + ':' + errorMessage + ':' +  Json.serialize(response.getBody());
				log.SetResult(resCode, Json.serialize(response.getBody()), errorMessage);
				listLog.add(log.getLog());
			} catch (Exception e){
				System.debug(e.getMessage());
				System.debug(e.getCause());
				System.debug(e.getStackTraceString());
				log.SetResult(0, '', e.getStackTraceString());
				listLog.add(log.getLog());
			}

		}
		return sendSuccessMap;

	}

	private static List<Map<String, Object>> handleData(List<Account> accounts) {
		List<Map<String,Object>> maps = new List<Map<String,Object>>();
		for(Account account : accounts){
			Map<String,Object> mapItem= new Map<String,Object>();
			mapItem.put('MAP_ID',account.Id);
			mapItem.put('license_name_cn',account.Name);
			mapItem.put('license_name_en',account.CN_License_Name_EN__c);
			mapItem.put('commercial_name_cn',account.CN_Store_Name_CN__c);
			mapItem.put('commercial_name_en',account.CN_Store_Name_EN__c);
			mapItem.put('customer_code',account.CN_Customer_Code__c);
			mapItem.put('owner',account.Owner.Name);
			mapItem.put('email',account.Owner.Email);
			mapItem.put('mg_account_id',account.CN_MG_Account_ID__c);
			mapItem.put('sales_team',account.CN_Sales_Team_UI__r.Name);
			mapItem.put('payment_terms',account.CN_Payment_Terms__c);
			mapItem.put('invoice_type',account.CN_Invoice_Type__c);
			mapItem.put('bank_account_name',account.CN_Bank_Account_Name__c);
			mapItem.put('tax_registration_no',account.CN_Tax_Registration_No__c);
			mapItem.put('invoicing_address_and_phone',account.CN_Invoicing_Address_and_Phone__c);
			mapItem.put('bank_account',account.CN_Bank_Account__c);
			mapItem.put('sales_office',account.CN_Sales_Office__c);
			mapItem.put('sales_org',account.CN_Sales_Org__c);
			mapItem.put('sales_district',account.CN_Sales_District__c);
			mapItem.put('finance_ar',account.CN_Finance_AR__r.Username);

			mapItem.put('bill_to',account.CN_Invoicing_Name_Bill_To_Party__c);
			
			maps.add(mapItem);
		}
		return maps;
	}
}