objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Business_Unit__c</fullName>
        <formula>CN_Business_Unit_UI__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BAPA</fullName>
                </value>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Coffee/Tea Shop</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
                <value>
                    <fullName>Retailor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_City_Code__c</fullName>
        <formula>CN_City_CN__r.CN_City_Code__c</formula>
        <label>City Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Customer_Group__c</fullName>
        <formula>CASE(CN_Category__c, 
&quot;Hotel&quot;,&quot;01&quot;,
&quot;Restaurant&quot;,&quot;02&quot;,
&quot;Catering&quot;,&quot;03&quot;,
&quot;International Chain&quot;,&quot;04&quot;,
&quot;Local Chain&quot;,&quot;05&quot;,
&quot;Department Stores&quot;,&quot;06&quot;,
&quot;Pastry/Bakery/Ice cr&quot;,&quot;07&quot;,
&quot;Expat Stores&quot;,&quot;08&quot;,
&quot;Convenient stores&quot;,&quot;09&quot;,
&quot;Distributor Retail&quot;,&quot;10&quot;,
&quot;Distributor Corporat&quot;,&quot;11&quot;,
&quot;Wholesale Market&quot;,&quot;12&quot;,
&quot;Employee&quot;,&quot;13&quot;,
&quot;Internet sales&quot;,&quot;14&quot;,
&quot;Personal sales&quot;,&quot;15&quot;,
&quot;Distributor Food Ser&quot;,&quot;16&quot;,
&quot;Supply Chain&quot;,&quot;17&quot;,
&quot;Food Logistic Servic&quot;,&quot;18&quot;,
&quot;Supply Chain and Foo&quot;,&quot;19&quot;,
&quot;Key Account&quot;,&quot;20&quot;,
&quot;Distributor Retail &amp;&quot;,&quot;21&quot;,
&quot;Gourmet Shop&quot;,&quot;22&quot;,
&quot;Other&quot;,&quot;23&quot;,
&quot;FS1&quot;,&quot;24&quot;,
&quot;FS2&quot;,&quot;25&quot;,
&quot;FS3&quot;,&quot;26&quot;,
&quot;DEPARTMENT STORES &amp;&quot;,&quot;27&quot;,
&quot;BAPA&quot;,&quot;30&quot;,
&quot;Coffee/Tea Shop&quot;,&quot;31&quot;,
&quot;OEM&quot;,&quot;32&quot;,
&quot;EC&quot;,&quot;33&quot;,
&quot;Wholesaler&quot;,&quot;34&quot;,
&quot;Retailor&quot;,&quot;35&quot;,
&quot;&quot;)</formula>
        <label>Customer Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_License_Name_EN__c</fullName>
        <label>License Name(EN)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sales_District__c</fullName>
        <label>Sales District</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>020</fullName>
                    <label>020-Out of ShangHai</label>
                </value>
                <value>
                    <fullName>001</fullName>
                    <label>001-SH-HuangPu</label>
                </value>
                <value>
                    <fullName>002</fullName>
                    <label>002-SH-LuWan</label>
                </value>
                <value>
                    <fullName>003</fullName>
                    <label>003-SH-XuHui</label>
                </value>
                <value>
                    <fullName>004</fullName>
                    <label>004-SH-ChangNing</label>
                </value>
                <value>
                    <fullName>005</fullName>
                    <label>005-SH-JingAn</label>
                </value>
                <value>
                    <fullName>006</fullName>
                    <label>006-SH-PuTuo</label>
                </value>
                <value>
                    <fullName>007</fullName>
                    <label>007-SH-ZhaBei</label>
                </value>
                <value>
                    <fullName>008</fullName>
                    <label>008-SH-HongKou</label>
                </value>
                <value>
                    <fullName>009</fullName>
                    <label>009-SH-YangPu</label>
                </value>
                <value>
                    <fullName>010</fullName>
                    <label>010-SH-MingHang</label>
                </value>
                <value>
                    <fullName>011</fullName>
                    <label>011-SH-BaoShan</label>
                </value>
                <value>
                    <fullName>012</fullName>
                    <label>012-SH-JiaDing</label>
                </value>
                <value>
                    <fullName>013</fullName>
                    <label>013-SH-PuDong new Distr</label>
                </value>
                <value>
                    <fullName>014</fullName>
                    <label>014-SH-JinShan</label>
                </value>
                <value>
                    <fullName>015</fullName>
                    <label>015-SH-SongJiang</label>
                </value>
                <value>
                    <fullName>016</fullName>
                    <label>016-SH-QingPu</label>
                </value>
                <value>
                    <fullName>017</fullName>
                    <label>017-SH-NanHui</label>
                </value>
                <value>
                    <fullName>018</fullName>
                    <label>018-SH-FengXian</label>
                </value>
                <value>
                    <fullName>019</fullName>
                    <label>019-SH-CongMing</label>
                </value>
                <value>
                    <fullName>021</fullName>
                    <label>021-HangZhou</label>
                </value>
                <value>
                    <fullName>022</fullName>
                    <label>022-SuZhou</label>
                </value>
                <value>
                    <fullName>023</fullName>
                    <label>023-Nanjing</label>
                </value>
                <value>
                    <fullName>024</fullName>
                    <label>024-BeiJing</label>
                </value>
                <value>
                    <fullName>025</fullName>
                    <label>025-ShenZhen</label>
                </value>
                <value>
                    <fullName>026</fullName>
                    <label>026-GuangZhou</label>
                </value>
                <value>
                    <fullName>B01</fullName>
                    <isActive>false</isActive>
                    <label>B01-North Area</label>
                </value>
                <value>
                    <fullName>B02</fullName>
                    <isActive>false</isActive>
                    <label>B02-East Area</label>
                </value>
                <value>
                    <fullName>B03</fullName>
                    <isActive>false</isActive>
                    <label>B03-South Area</label>
                </value>
                <value>
                    <fullName>B04</fullName>
                    <isActive>false</isActive>
                    <label>B04-e-commerce</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sales_Team__c</fullName>
        <formula>CN_Sales_Team_UI__r.CN_Sales_Team_Code__c</formula>
        <label>Sales Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Store_Name_CN__c</fullName>
        <label>Commercial Name (CN)</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Store_Name_EN__c</fullName>
        <label>Commercial Name (EN)</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Approve_Process_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CN_CEO_UserId__c</fullName>
        <label>CEO User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_CFO_UserId__c</fullName>
        <label>CFO User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Finance_AR_UserId__c</fullName>
        <label>Finance AR User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Finance_MDM_UserId__c</fullName>
        <label>Finance MDM User ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sales_MDM_UserId__c</fullName>
        <label>Sales MDM User ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CN Approve Process Settings</label>
</CustomObject>

objects/CN_Business_Unit__c.object
<CustomObject>
    <fields>
        <fullName>CN_Business_Unit_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Business Unit Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_City__c.object
<CustomObject>
    <fields>
        <fullName>CN_City_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>City Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Province__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province</label>
        <referenceTo>CN_Province__c</referenceTo>
        <relationshipLabel>Citys (Province)</relationshipLabel>
        <relationshipName>Citys1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Citys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Province__c.object
<CustomObject>
    <fields>
        <fullName>Province_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Province Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Province</label>
    <nameField>
        <label>Province Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provinces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Sales_Team__c.object
<CustomObject>
    <fields>
        <fullName>CN_Business_Unit_Code__c</fullName>
        <formula>CN_Business_Unit__r.CN_Business_Unit_Code__c</formula>
        <label>Business Unit Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Business_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Unit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The business unit you choose must have business unit Code.</errorMessage>
            <filterItems>
                <field>CN_Business_Unit__c.CN_Business_Unit_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_Business_Unit__c</referenceTo>
        <relationshipLabel>Sales Teams</relationshipLabel>
        <relationshipName>Sales_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Sales_Team_Code__c</fullName>
        <externalId>true</externalId>
        <label>Sales Team Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <label>Sales Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trigger_Switcher_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EnableFlow__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EnableFlow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnableTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EnableTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnableValidationRule__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EnableValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Switcher Setting</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CN_Sales_Team__c</fullName>
        <label>Sales Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CN_CONTACT_POPULATE_FIELD_HANDLER_Test.cls
/**************************************************************************************************
 * Name           : CN_CONTACT_POPULATE_FIELD_HANDLER_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Qiu Chen
 * Create Date    : 2021-06-07
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_CONTACT_POPULATE_FIELD_HANDLER_Test {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }
    @isTest
    private static void contact_Populate_Test() {
        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }
        Trigger_Switcher_Setting__c setting = new Trigger_Switcher_Setting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            EnableFlow__c = true,
            EnableTrigger__c = true,
            EnableValidationRule__c = true
        );
        insert setting;

        CN_Approve_Process_Settings__c approveSetting = new CN_Approve_Process_Settings__c(
            CN_CEO_UserId__c = lastNameUserIdMap.get('CEO'),
            CN_CFO_UserId__c = lastNameUserIdMap.get('CFO'),
            CN_Finance_AR_UserId__c = lastNameUserIdMap.get('FinanceAR'),
            CN_Finance_MDM_UserId__c = lastNameUserIdMap.get('FinanceMDM'),
            CN_Sales_MDM_UserId__c = lastNameUserIdMap.get('SalesMDM'),
			CN_WholeSales_Development_Supervisor__c = lastNameUserIdMap.get('WholeSalesDevelopmentSupervisor')
        );
        insert approveSetting;

        User salesRep = [SELECT Id FROM User WHERE lastName = 'Sales1'][0];
        CN_Province__c province = [SELECT Id FROM CN_Province__c WHERE Province_Code__c = '010'][0];
        CN_City__c city = [SELECT Id FROM CN_City__c WHERE CN_City_Code__c = '010'][0];
        CN_Business_Unit__c businessUnit = [SELECT Id FROM CN_Business_Unit__c WHERE CN_Business_Unit_Code__c = '0000900001'][0];
        CN_Sales_Team__c salesTeam = [SELECT Id FROM CN_Sales_Team__c WHERE CN_Sales_Team_Code__c = '0000901001'][0];
        
        System.runAs(salesRep) {
            Id newDirectRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.CN_Account_RT_API_NAME_NEW_DIRECT).getRecordTypeId();
            Id editDirectRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.CN_Account_RT_API_NAME_EDIT_DIRECT).getRecordTypeId();
            Id newInDirectRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.CN_Account_RT_API_NAME_NEW_INDIRECT).getRecordTypeId();
            Account acc = new Account();
            acc.RecordTypeId = newDirectRTId;
            acc.Name = 'TestAccount';
            acc.CN_License_Name_EN__c = 'TestAccount';
            acc.CN_Store_Name_EN__c = 'TestAccount';
            acc.CN_Store_Name_CN__c = 'TestAccount';
            acc.CN_Sales_District__c = '001';
            //acc.CN_Customer_Group__c = '01';
            acc.CN_Category__c = 'BAPA';
            acc.CN_Subcategory__c = 'Access Bakery';
            acc.CN_Province_CN__c = province.Id;
            acc.CN_City_CN__c = city.Id;
            acc.CN_Post_Code__c = '100000';
            acc.CN_Delivery_Plant__c = 'P011';
            acc.CN_Payment_Terms__c = 'D000';
            acc.CN_Invoicing_Name_Bill_To_Party__c = 'D000';
            acc.CN_Tax_Registration_No__c = '10000000';
            acc.CN_Invoice_Type__c = 'General Invoice';
            acc.CN_Invoicing_Address_EN__c = 'ABCDEF';
            acc.CN_Reference_Day__c = 'Delivery_Day';
            acc.CN_Business_Unit_UI__c = businessUnit.Id;
            acc.CN_Sales_Team_UI__c = salesTeam.Id;
            insert acc;

            CN_Document__c doc_b = new CN_Document__c();
            doc_b.CN_Account__c = acc.Id;
            doc_b.CN_Document_Type__c = Constants.CN_DOCUMENT_TYPE_BUSINESS_LICENSE;
            doc_b.CN_Is_File_Upload__c = true;
            insert doc_b;

            CN_Document__c doc_f = new CN_Document__c();
            doc_f.CN_Account__c = acc.Id;
            doc_f.CN_Document_Type__c = Constants.CN_DOCUMENT_TYPE_FAPIAO_INFORMATION;
            doc_f.CN_Is_File_Upload__c = true;
            insert doc_f;

            Contact con = new Contact();
            con.AccountId = acc.Id;
            con.CN_Contact_Type__c = '01;02';
            con.Title = 'CEO';
            con.CN_Department_Of_Contact_Person__c = '0001';
            con.CN_Contact_Name_EN__c = 'Test Contact';
            con.LastName = 'Contact';
            con.MobilePhone = '13013001300';
            con.CN_Bill_To_Address__c = 'ABCDE';
            insert con;

            Contact con2 = new Contact();
            con2.AccountId = acc.Id;
            con2.CN_Contact_Type__c = '02';
            con2.Title = 'CEO';
            con2.CN_Department_Of_Contact_Person__c = '0002';
            con2.CN_Contact_Name_EN__c = 'Test Contact1';
            con2.LastName = 'Contact1';
            con2.MobilePhone = '13013801300';
            con2.CN_Bill_To_Address__c = 'ABCDEF';
            insert con2;

            con.CN_Contact_Type__c = '01;02;04';
            update con;

            delete con2;

            undelete con2;
        }
    }
}