objects/Account.object
<CustomObject>
    <fields>
        <fullName>CN_Contact_Name_EN__c</fullName>
        <label>Contact Name(EN)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Department_of_Contact_Person__c</fullName>
        <label>Department of Contact Person</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0001-Purchasing Dept</fullName>
                </value>
                <value>
                    <fullName>0002-Sales Dept</fullName>
                </value>
                <value>
                    <fullName>0003-Administration Dept</fullName>
                </value>
                <value>
                    <fullName>0004-Production Dept</fullName>
                </value>
                <value>
                    <fullName>0005-QA Dept</fullName>
                </value>
                <value>
                    <fullName>0006-Secretary&apos;s Office</fullName>
                </value>
                <value>
                    <fullName>0007-Financial Dept</fullName>
                </value>
                <value>
                    <fullName>0008-Legal Dept</fullName>
                </value>
                <value>
                    <fullName>0009-Human Resources Dept</fullName>
                </value>
                <value>
                    <fullName>0010-General Affairs Dept</fullName>
                </value>
                <value>
                    <fullName>0011-Sales Promotion Dept</fullName>
                </value>
                <value>
                    <fullName>0012-International Dept</fullName>
                </value>
                <value>
                    <fullName>0013-Export Dept</fullName>
                </value>
                <value>
                    <fullName>0014-Import Dept</fullName>
                </value>
                <value>
                    <fullName>0015-Public Relation Dept</fullName>
                </value>
                <value>
                    <fullName>0016-Advertising Dept</fullName>
                </value>
                <value>
                    <fullName>0017-Planning Dept</fullName>
                </value>
                <value>
                    <fullName>0018-R&amp;D Dept</fullName>
                </value>
                <value>
                    <fullName>0019-Product Dev. Dept</fullName>
                </value>
                <value>
                    <fullName>0020-Food &amp; Beverage Dept</fullName>
                </value>
                <value>
                    <fullName>0021-Service Dept</fullName>
                </value>
                <value>
                    <fullName>0022-Technical Support</fullName>
                </value>
                <value>
                    <fullName>0023-IT Dept</fullName>
                </value>
                <value>
                    <fullName>0024-Logistics Dept</fullName>
                </value>
                <value>
                    <fullName>0025-Cold Kitchen</fullName>
                </value>
                <value>
                    <fullName>0026-Hot Kitchen</fullName>
                </value>
                <value>
                    <fullName>0027-Banquet Kitchen</fullName>
                </value>
                <value>
                    <fullName>0028-Pastry</fullName>
                </value>
                <value>
                    <fullName>0029-Backery</fullName>
                </value>
                <value>
                    <fullName>0030-Bar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_API_Call_Logger__c.object
<CustomObject>
    <description>API Call Log</description>
    <label>API Call Logger</label>
    <nameField>
        <displayFormat>INF-{YYYYMMDD}{0000}</displayFormat>
        <label>API Call Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Call Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CN_Bill_To_Address__c</fullName>
        <label>Bill To Address</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Contact_Name_EN__c</fullName>
        <label>Contact Name(EN)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>01-Billing</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>02-Business</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>04-Others</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <isActive>false</isActive>
                    <label>03-Receiving</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Department_Of_Contact_Person__c</fullName>
        <label>Department of Contact Person</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0001</fullName>
                    <label>0001-Purchasing Dept</label>
                </value>
                <value>
                    <fullName>0002</fullName>
                    <label>0002-Sales Dept</label>
                </value>
                <value>
                    <fullName>0003</fullName>
                    <label>0003-Administration Dept</label>
                </value>
                <value>
                    <fullName>0004</fullName>
                    <label>0004-Production Dept</label>
                </value>
                <value>
                    <fullName>0005</fullName>
                    <label>0005-QA Dept</label>
                </value>
                <value>
                    <fullName>0006</fullName>
                    <label>0006-Secretary&apos;s Office</label>
                </value>
                <value>
                    <fullName>0007</fullName>
                    <label>0007-Financial Dept</label>
                </value>
                <value>
                    <fullName>0008</fullName>
                    <label>0008-Legal Dept</label>
                </value>
                <value>
                    <fullName>0009</fullName>
                    <label>0009-Human Resources Dept</label>
                </value>
                <value>
                    <fullName>0010</fullName>
                    <label>0010-General Affairs Dept</label>
                </value>
                <value>
                    <fullName>0011</fullName>
                    <label>0011-Sales Promotion Dept</label>
                </value>
                <value>
                    <fullName>0012</fullName>
                    <label>0012-International Dept</label>
                </value>
                <value>
                    <fullName>0013</fullName>
                    <label>0013-Export Dept</label>
                </value>
                <value>
                    <fullName>0014</fullName>
                    <label>0014-Import Dept</label>
                </value>
                <value>
                    <fullName>0015</fullName>
                    <label>0015-Public Relation Dept</label>
                </value>
                <value>
                    <fullName>0016</fullName>
                    <label>0016-Advertising Dept</label>
                </value>
                <value>
                    <fullName>0017</fullName>
                    <label>0017-Planning Dept</label>
                </value>
                <value>
                    <fullName>0018</fullName>
                    <label>0018-R&amp;D Dept</label>
                </value>
                <value>
                    <fullName>0019</fullName>
                    <label>0019-Product Dev. Dept</label>
                </value>
                <value>
                    <fullName>0020</fullName>
                    <label>0020-Food &amp; Beverage Dept</label>
                </value>
                <value>
                    <fullName>0021</fullName>
                    <label>0021-Service Dept</label>
                </value>
                <value>
                    <fullName>0022</fullName>
                    <label>0022-Technical Support</label>
                </value>
                <value>
                    <fullName>0023</fullName>
                    <label>0023-IT Dept</label>
                </value>
                <value>
                    <fullName>0024</fullName>
                    <label>0024-Logistics Dept</label>
                </value>
                <value>
                    <fullName>0025</fullName>
                    <label>0025-Cold Kitchen</label>
                </value>
                <value>
                    <fullName>0026</fullName>
                    <label>0026-Hot Kitchen</label>
                </value>
                <value>
                    <fullName>0027</fullName>
                    <label>0027-Banquet Kitchen</label>
                </value>
                <value>
                    <fullName>0028</fullName>
                    <label>0028-Pastry</label>
                </value>
                <value>
                    <fullName>0029</fullName>
                    <label>0029-Backery</label>
                </value>
                <value>
                    <fullName>0030</fullName>
                    <label>0030-Bar</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Family_Info__c</fullName>
        <label>Family Info</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Open_Field_To_Comment__c</fullName>
        <label>Open Field to Comment</label>
        <length>3200</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_UP_Code__c</fullName>
        <label>UP code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Wechat_ID__c</fullName>
        <label>Wechat ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Talend_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Talend Setting</label>
</CustomObject>

classes/CN_Contact_Upsert_To_Mg_Callout.cls
/*
 * ************************************************************************************************
 * Name : CN_Contact_Upsert_To_Mg_Callout
 * Object :
 * Requirement :CT-014
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2023/4/6
 * Modify History :
 * ************************************************************************************************
 */
public class CN_Contact_Upsert_To_Mg_Callout {

	public static Map<String, Contact> upsertContact(List<Contact> lists) {

		//handleDataList
		List<Map<String, Object>> maps = handleData(lists);

		//Necessary parameters for assembly request
		Talend_Setting__c setting = Talend_Setting__c.getInstance();
		Http http = new Http();
		HttpRequest request = CN_HelperClass_WS.createHttpRequestHelper(
				setting.Sandbox_MG_Save_Company_Contact__c,
				setting.MG_Save_Company_Contact__c);

		//Successful Requests Records
		Map<String, Contact> needUpdateMap = new Map<String, Contact>();

		//logs
		List<CN_API_Call_Logger__c> listLog = new List<CN_API_Call_Logger__c>();

		//Loop processing requests
		for (Map<String, Object> item : maps) {
			CN_HelperClass_WS.WS_Log log = new CN_HelperClass_WS.WS_Log();
			try {
				String body = JSON.serialize(item);
				String id = String.valueOf(item.get('MAP_ID'));
				request.setBody(body);
				log.SetRequest(request.getBody());

				HttpResponse response = http.send(request);
				log.SetResponse(response.getBody());

				Integer resCode = response.getStatusCode();

				String errorMsg = '';
				String errorMessage = '';
				if (resCode == 200) {
					System.debug(response.getBody());
					//成功调用
					CN_HelperClass_WS.Message  cs = CN_HelperClass_WS.getRetData(response.getBody());
					System.debug(JSON.serialize(cs));

					if(cs != null && cs.code == 1){

						Map<String,Object> retData = cs.retData;
						if (retData != null && retData.containsKey('mg_billing_id')){

							String contact_id = String.valueOf(retData.get('contact_id'));
							String mg_billing_id = String.valueOf(retData.get('mg_billing_id'));

							//handle successful record
							Contact contact = new Contact();
							contact.Id = id;
							contact.CN_MG_Contact_ID__c = contact_id;
							contact.CN_MG_Billing_To_Address_ID__c = mg_billing_id;
							contact.CN_Need_Send_MG__c = false;
							needUpdateMap.put(id, contact);
						}

					}

				}else {
					if(resCode == 500) {
						errorMessage = 'Server Error';
					} else if(resCode == 404) {
						errorMessage = 'API Path Error';
					} else if(resCode == 503) {
						errorMessage = 'Server Error';
					}
					errorMsg = resCode + ':' + errorMessage + ':' + response.getBody();
				}

				log.SetResult(resCode, response.getBody(), errorMessage);
				listLog.add(log.getLog());
			} catch (Exception e) {

				log.SetResult(0,'',e.getMessage());
				listLog.add(log.getLog());
			}
		}

		insert listLog;
		return needUpdateMap;
	}

	private static List<Map<String, Object>> handleData(List<Contact> lists) {
		List<Map<String, Object>> maps = new List<Map<String, Object>>();
		for (Contact contact : lists) {
			Map<String, Object> mapItem = new Map<String, Object>();
			mapItem.put('MAP_ID', contact.Id);
			mapItem.put('birthday', contact.Birthdate);
			mapItem.put('contact_person_address', contact.CN_Bill_To_Address__c);
			mapItem.put('id', contact.Id);
			mapItem.put('lastname', contact.LastName);
			mapItem.put('firstname', contact.FirstName);
			mapItem.put('contact_person', contact.CN_Department_Of_Contact_Person__c);
			mapItem.put('email', contact.Email);
			mapItem.put('mobile', contact.MobilePhone);
			mapItem.put('telephone', contact.Phone);
			mapItem.put('reports_to', contact.ReportsTo.CN_MG_Contact_ID__c);
			mapItem.put('contact_name', contact.CN_Contact_Name_EN__c);
			mapItem.put('prefix', contact.Title);
			mapItem.put('contact_type', contact.CN_Contact_Type__c);
			mapItem.put('wechat_id', contact.CN_Wechat_ID__c);
			mapItem.put('family_info', contact.CN_Family_Info__c);
			mapItem.put('open_field_to_comment', contact.CN_Open_Field_To_Comment__c);
			mapItem.put('decision_maker', contact.CN_Decision_Maker__c);
			mapItem.put('contact_license_name', contact.Account.CN_MG_Account_ID__c);
			mapItem.put('company', contact.Account.CN_MG_Account_ID__c);
			mapItem.put('contact_id', contact.CN_MG_Contact_ID__c);
			mapItem.put('mg_billing_id', contact.CN_MG_Billing_To_Address_ID__c);
			mapItem.put('sf_billing_to_address_id', contact.CN_Billing_To_Address_ID__c);
			mapItem.put('lead_mg_account_id', contact.CN_Lead_MG_Account_ID__c);
			mapItem.put('customer_code', contact.Account.CN_Customer_Code__c);
			mapItem.put('used_mg_account_id', contact.Account.CN_MG_Account_ID__c);
			mapItem.put('up_code', contact.CN_UP_Code__c);
			maps.add(mapItem);
		}
		return maps;
	}

}