objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CN_Brand__c</fullName>
        <label>Brand</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>5J</fullName>
                </value>
                <value>
                    <fullName>Adamance</fullName>
                </value>
                <value>
                    <fullName>ANTICHICOLLI</fullName>
                </value>
                <value>
                    <fullName>BARNIER OLIVES</fullName>
                </value>
                <value>
                    <fullName>BASTIDES</fullName>
                </value>
                <value>
                    <fullName>BEAUFOR</fullName>
                </value>
                <value>
                    <fullName>Beillevaire</fullName>
                </value>
                <value>
                    <fullName>BERETTA</fullName>
                </value>
                <value>
                    <fullName>BEYONG MEAT</fullName>
                </value>
                <value>
                    <fullName>Cabrifin</fullName>
                </value>
                <value>
                    <fullName>CAPRICE DES DIEUX</fullName>
                </value>
                <value>
                    <fullName>CAVIAR &amp; TRADITIONS</fullName>
                </value>
                <value>
                    <fullName>Chateau d&apos;Estoublon</fullName>
                </value>
                <value>
                    <fullName>Chef Studio OIL</fullName>
                </value>
                <value>
                    <fullName>Chef Studio Pastry</fullName>
                </value>
                <value>
                    <fullName>COEUR DE LION</fullName>
                </value>
                <value>
                    <fullName>CORMAN</fullName>
                </value>
                <value>
                    <fullName>DOBLA</fullName>
                </value>
                <value>
                    <fullName>DODONI</fullName>
                </value>
                <value>
                    <fullName>Elle &amp; Vire</fullName>
                </value>
                <value>
                    <fullName>FERMES DE LA TREMBLAYE</fullName>
                </value>
                <value>
                    <fullName>Giovanni Ferrari</fullName>
                </value>
                <value>
                    <fullName>ILE DE FRANCE</fullName>
                </value>
                <value>
                    <fullName>IRCA</fullName>
                </value>
                <value>
                    <fullName>Joyhana</fullName>
                </value>
                <value>
                    <fullName>LE RUSTIQUE</fullName>
                </value>
                <value>
                    <fullName>Lescure</fullName>
                </value>
                <value>
                    <fullName>Liberty Lane</fullName>
                </value>
                <value>
                    <fullName>LOSTE TRADI-FRANCE</fullName>
                </value>
                <value>
                    <fullName>Milkana</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Channel__c</fullName>
        <label>Channel</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KA</fullName>
                </value>
                <value>
                    <fullName>WS</fullName>
                </value>
                <value>
                    <fullName>DS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Customer_Category__c</fullName>
        <label>Customer Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BAPA</fullName>
                </value>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Coffee/Tea Shop</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
                <value>
                    <fullName>Retailor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Execution_Type__c</fullName>
        <label>Execution Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public Demonstration</fullName>
                </value>
                <value>
                    <fullName>VIP Class</fullName>
                </value>
                <value>
                    <fullName>1on1</fullName>
                </value>
                <value>
                    <fullName>VIP Dinner</fullName>
                </value>
                <value>
                    <fullName>Tasting</fullName>
                </value>
                <value>
                    <fullName>On-Site Order</fullName>
                </value>
                <value>
                    <fullName>Livestreaming</fullName>
                </value>
                <value>
                    <fullName>Solution Development</fullName>
                </value>
                <value>
                    <fullName>Short Video</fullName>
                </value>
                <value>
                    <fullName>WeChat</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_New_Product_Launch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Product Launch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Number_of_Audiences__c</fullName>
        <inlineHelpText>For Live Streaming Only</inlineHelpText>
        <label>Number of Audiences</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>GOURMET &amp; GROCERY</fullName>
                </value>
                <value>
                    <fullName>PASTRY</fullName>
                </value>
                <value>
                    <fullName>Chef Studio Pastry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Product_Type__c</fullName>
        <label>Product Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CHEESE</fullName>
                </value>
                <value>
                    <fullName>BUTTER</fullName>
                </value>
                <value>
                    <fullName>CREAM</fullName>
                </value>
                <value>
                    <fullName>COLD CUTS &amp; MEAT</fullName>
                </value>
                <value>
                    <fullName>FOIS GRAS</fullName>
                </value>
                <value>
                    <fullName>GROCERY</fullName>
                </value>
                <value>
                    <fullName>CHOCOLATE &amp; DECORATION</fullName>
                </value>
                <value>
                    <fullName>PUREE</fullName>
                </value>
                <value>
                    <fullName>PRE MIX</fullName>
                </value>
                <value>
                    <fullName>VALUE - ADDED</fullName>
                </value>
                <value>
                    <fullName>FROZEN PASTRY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_API_Call_Logger__c.object
<CustomObject>
    <description>API Call Log</description>
    <label>API Call Logger</label>
    <nameField>
        <displayFormat>INF-{YYYYMMDD}{0000}</displayFormat>
        <label>API Call Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Call Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Talend_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Talend Setting</label>
</CustomObject>

classes/CN_Campaign_Upsert_To_Mg_Callout.cls
/*
 * ************************************************************************************************
 * Name : CN_Campaign_Upsert_To_Mg_Callout
 * Object :
 * Requirement : ET-001
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2023/10/1
 * Modify History :
 * ************************************************************************************************
 */
public class CN_Campaign_Upsert_To_Mg_Callout {

    public static Map<String,Campaign> sendMgCampaign(List<Campaign> ltCampaigns,List<CN_API_Call_Logger__c> listLog){
        //handleDataList
        List<Map<String, Object>> maps = handleData(ltCampaigns);

        //Necessary parameters for assembly request
        Talend_Setting__c setting = Talend_Setting__c.getInstance();
        Http http = new Http();
        HttpRequest request = CN_HelperClass_WS.createHttpRequestHelper(
                setting.Sandbox_MG_Update_Campaign__c,
                setting.MG_Update_Campaign__c);

        Map<String,Campaign> sendSuccessMap = new Map<String,Campaign>();

        for(Map<String,Object> param:maps) {
            CN_HelperClass_WS.WS_Log log = new CN_HelperClass_WS.WS_Log();

            try {


                String body = JSON.serialize(param);
                log.SetRequest(body);
                System.debug(body);

                request.setBody(body);
                HttpResponse response = http.send(request);
                System.debug(response.getStatus());
                System.debug(response.getBody());
                // Parse the JSON response
                String data = Json.serialize(response.getBody());
                log.SetResponse(data);
                Integer resCode = response.getStatusCode();
                String errorMsg = '';
                String errorMessage = '';
                if (resCode == 200) {
                    Campaign campaign = new Campaign();
                    campaign.Id = String.valueOf(param.get('sf_campaign_id'));
                    campaign.CN_Need_Send_MG_Flag__c = 0;
                    sendSuccessMap.put(campaign.Id, campaign);
                } else {
                    if (resCode == 503) {
                        errorMessage = 'Service Unavailable';
                    } else if (resCode == 500) {
                        errorMessage = 'Server Error';
                    } else if (resCode == 404) {
                        errorMessage = 'API Path Error';
                    } else {
                        errorMessage = 'Others Error';
                    }
                }
                errorMsg = resCode + ':' + errorMessage + ':' + data;

                log.SetResult(1, 'success', 'success');
                listLog.add(log.getLog());
            } catch (Exception e) {
                log.SetResult(0, 'error', e.getMessage());
                listLog.add(log.getLog());
            }
        }
        return sendSuccessMap;
    }

    private static List<Map<String, Object>> handleData(List<Campaign> campaigns) {
        List<Map<String,Object>> maps = new List<Map<String,Object>>();
        for(Campaign campaign : campaigns){
            Map<String,Object> mapItem= new Map<String,Object>();
            mapItem.put('sf_campaign_id',campaign.Id);
            mapItem.put('brand',multiSelectToList(campaign.CN_Brand__c));
            mapItem.put('product_type',multiSelectToList(campaign.CN_Product_Type__c));
            mapItem.put('product_category',multiSelectToList(campaign.CN_Product_Category__c));
            mapItem.put('event_type',campaign.Type);
            mapItem.put('campaign_name',campaign.Name);
            mapItem.put('start_date',campaign.StartDate);
            mapItem.put('end_date',campaign.EndDate);
            mapItem.put('status',campaign.Status);
            mapItem.put('description',campaign.Description);
            mapItem.put('new_product_launch',campaign.CN_New_Product_Launch__c?1:0);
            mapItem.put('number_audiences',campaign.CN_Number_of_Audiences__c);
            mapItem.put('parent_campaign',campaign.ParentId);
            mapItem.put('channel',multiSelectToList(campaign.CN_Channel__c));
            mapItem.put('number_of_audiences',campaign.CN_Number_of_Audiences__c);
            mapItem.put('campaign_owner',campaign.OwnerId);
            mapItem.put('customer_category',multiSelectToList(campaign.CN_Customer_Category__c));
            mapItem.put('execution_type',multiSelectToList(campaign.CN_Execution_Type__c));
            mapItem.put('publish_date_enable','0');
            mapItem.put('registration_type','1');

            maps.add(mapItem);
        }
        return maps;
    }

    @Future(callout=true)
    public static void sendMgCampaignRealTime(String args){
        System.debug(args);
        List<Campaign> ltCampaigns = (List<Campaign>)JSON.deserialize(args,List<Campaign>.class);
        List<CN_API_Call_Logger__c> loggerList = new List<CN_API_Call_Logger__c>();
        Map<String,Campaign> res = sendMgCampaign(ltCampaigns,loggerList);
        update res.values();
        insert loggerList;
    }


    private static List<Object> multiSelectToList(String args){
        if(args == null || String.isEmpty(args)){
            return null;
        }
        return args.split(';');
    }



}