objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CN_New_Product_Launch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Product Launch</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Campaign_Product__c.object
<CustomObject>
    <fields>
        <fullName>CN_Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Products</relationshipLabel>
        <relationshipName>Campaign_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Campaign Products</relationshipLabel>
        <relationshipName>Campaign_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Product</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Campaign Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>CN_Sold_To_Account_Name__c</fullName>
        <label>Sold-To Party</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Order</relationshipLabel>
        <relationshipName>Sales_Order</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Up_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Sales Order Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Sales_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>CN_Material_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sales Order Item</relationshipLabel>
        <relationshipName>Sales_Order_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Order_Number__c</fullName>
        <label>Sales Order Number</label>
        <referenceTo>CN_Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Item</relationshipLabel>
        <relationshipName>Sales_Order_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Up_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Item Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Order Item</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Sales Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_SOItem_Populate_CampaignP_Batch_Test.cls
/**************************************************************************************************
 * Name           : CN_SOItem_Populate_CampaignP_Batch_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Dezheng Du
 * Create Date    : 2021-10-14
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_SOItem_Populate_CampaignP_Batch_Test {
    
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }

    @isTest
    private static void CN_SOItem_Populate_CampaignP_Batch_Test() {
        TestDataFactory testFactory = new TestDataFactory();
        List<Account> accListFactory = testFactory.makeFactoryAccount();
        //add by Zhangzhihao  Create a TalendSetting 2024/4/6
        testFactory.makeTalendSetting();    
        //add by Zhangzhihao  Create a TalendSetting 2024/4/6

        List<User> userList = [SELECT Id, LastName FROM User WHERE lastName in ('Sales1', 'Sales3', 'ChefManager', 'Chef', 'CCE1_KA')];
        Map<String, User> lastNameUserMap = new Map<String, User>();
        for(User usr: userList) {
            lastNameUserMap.put(usr.LastName, usr);
        }

        User salesRep = lastNameUserMap.get('Sales1');
        Account acc_factory = accListFactory[0];
        List<Product2> SKUList = [SELECT Id, Name FROM Product2];

        campaign cam = testFactory.makeCampaign();
        cam.CN_New_Product_Launch__c = true;
        cam.StartDate = Date.today().addMonths(-5);
        cam.EndDate = Date.today().addMonths(-5).addDays(13);
        insert cam;

        CN_Campaign_Product__c cp = new CN_Campaign_Product__c();
        cp.CN_Campaign__c = cam.Id;
        cp.CN_Product__c = SKUList[0].Id;
        insert cp;

        List<CN_Sales_Order_Item__c> orderItemList = new List<CN_Sales_Order_Item__c>();
        System.runAs(salesRep) {
            CN_Sales_Order__c  order = new CN_Sales_Order__c();
            order.CN_Sold_To_Account_Name__c = acc_factory.Id;
            order.CN_Up_Code__c = '0000' + 1;
            insert order;

            CN_Sales_Order_Item__c orderItem1 = new CN_Sales_Order_Item__c();
            orderItem1.CN_Order_Number__c = order.Id;
            orderItem1.CN_Material_Number__c = SKUList[0].Id;
            orderItem1.CN_Up_Code__c = '0000' + 1 + '1';
            orderItemList.add(orderItem1);
        
            insert orderItemList;

        }

        Test.setCreatedDate(orderItemList[0].Id, Date.today().addDays(-1));
        test.startTest();
        
        CN_SOItem_Populate_CampaignPro_SCH sch = new CN_SOItem_Populate_CampaignPro_SCH();
        System.schedule('CN_SOItem_Populate_CampaignPro_SCH' + Datetime.now(), '20 30 8 10 2 ?', sch);

        CN_SOItem_Populate_CampaignPro_Batch batch = new CN_SOItem_Populate_CampaignPro_Batch();
        Database.executeBatch(batch);
        CN_SOItem_Populate_CampaignPro_Batch batch2 = new CN_SOItem_Populate_CampaignPro_Batch('Select  Id,CN_Material_Number__c From CN_Sales_Order_Item__c Where CN_Is_Created_Yesterday__c = TRUE');
        Database.executeBatch(batch2);
        
        test.stopTest();
    }
}