objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CN_Brand__c</fullName>
        <label>Brand</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>5J</fullName>
                </value>
                <value>
                    <fullName>Adamance</fullName>
                </value>
                <value>
                    <fullName>ANTICHICOLLI</fullName>
                </value>
                <value>
                    <fullName>BARNIER OLIVES</fullName>
                </value>
                <value>
                    <fullName>BASTIDES</fullName>
                </value>
                <value>
                    <fullName>BEAUFOR</fullName>
                </value>
                <value>
                    <fullName>Beillevaire</fullName>
                </value>
                <value>
                    <fullName>BERETTA</fullName>
                </value>
                <value>
                    <fullName>BEYONG MEAT</fullName>
                </value>
                <value>
                    <fullName>Cabrifin</fullName>
                </value>
                <value>
                    <fullName>CAPRICE DES DIEUX</fullName>
                </value>
                <value>
                    <fullName>CAVIAR &amp; TRADITIONS</fullName>
                </value>
                <value>
                    <fullName>Chateau d&apos;Estoublon</fullName>
                </value>
                <value>
                    <fullName>Chef Studio OIL</fullName>
                </value>
                <value>
                    <fullName>Chef Studio Pastry</fullName>
                </value>
                <value>
                    <fullName>COEUR DE LION</fullName>
                </value>
                <value>
                    <fullName>CORMAN</fullName>
                </value>
                <value>
                    <fullName>DOBLA</fullName>
                </value>
                <value>
                    <fullName>DODONI</fullName>
                </value>
                <value>
                    <fullName>Elle &amp; Vire</fullName>
                </value>
                <value>
                    <fullName>FERMES DE LA TREMBLAYE</fullName>
                </value>
                <value>
                    <fullName>Giovanni Ferrari</fullName>
                </value>
                <value>
                    <fullName>ILE DE FRANCE</fullName>
                </value>
                <value>
                    <fullName>IRCA</fullName>
                </value>
                <value>
                    <fullName>Joyhana</fullName>
                </value>
                <value>
                    <fullName>LE RUSTIQUE</fullName>
                </value>
                <value>
                    <fullName>Lescure</fullName>
                </value>
                <value>
                    <fullName>Liberty Lane</fullName>
                </value>
                <value>
                    <fullName>LOSTE TRADI-FRANCE</fullName>
                </value>
                <value>
                    <fullName>Milkana</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Channel__c</fullName>
        <label>Channel</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KA</fullName>
                </value>
                <value>
                    <fullName>WS</fullName>
                </value>
                <value>
                    <fullName>DS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Customer_Category__c</fullName>
        <label>Customer Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BAPA</fullName>
                </value>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Coffee/Tea Shop</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
                <value>
                    <fullName>Retailor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Execution_Type__c</fullName>
        <label>Execution Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public Demonstration</fullName>
                </value>
                <value>
                    <fullName>VIP Class</fullName>
                </value>
                <value>
                    <fullName>1on1</fullName>
                </value>
                <value>
                    <fullName>VIP Dinner</fullName>
                </value>
                <value>
                    <fullName>Tasting</fullName>
                </value>
                <value>
                    <fullName>On-Site Order</fullName>
                </value>
                <value>
                    <fullName>Livestreaming</fullName>
                </value>
                <value>
                    <fullName>Solution Development</fullName>
                </value>
                <value>
                    <fullName>Short Video</fullName>
                </value>
                <value>
                    <fullName>WeChat</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_New_Product_Launch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Product Launch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Number_of_Audiences__c</fullName>
        <inlineHelpText>For Live Streaming Only</inlineHelpText>
        <label>Number of Audiences</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>GOURMET &amp; GROCERY</fullName>
                </value>
                <value>
                    <fullName>PASTRY</fullName>
                </value>
                <value>
                    <fullName>Chef Studio Pastry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Product_Type__c</fullName>
        <label>Product Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CHEESE</fullName>
                </value>
                <value>
                    <fullName>BUTTER</fullName>
                </value>
                <value>
                    <fullName>CREAM</fullName>
                </value>
                <value>
                    <fullName>COLD CUTS &amp; MEAT</fullName>
                </value>
                <value>
                    <fullName>FOIS GRAS</fullName>
                </value>
                <value>
                    <fullName>GROCERY</fullName>
                </value>
                <value>
                    <fullName>CHOCOLATE &amp; DECORATION</fullName>
                </value>
                <value>
                    <fullName>PUREE</fullName>
                </value>
                <value>
                    <fullName>PRE MIX</fullName>
                </value>
                <value>
                    <fullName>VALUE - ADDED</fullName>
                </value>
                <value>
                    <fullName>FROZEN PASTRY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_API_Call_Logger__c.object
<CustomObject>
    <description>API Call Log</description>
    <label>API Call Logger</label>
    <nameField>
        <displayFormat>INF-{YYYYMMDD}{0000}</displayFormat>
        <label>API Call Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Call Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CN_Campaign_Upsert_To_Mg_Batch.cls
/*
 * ************************************************************************************************
 * Name : CN_Campaign_Upsert_To_Mg_Batch
 * Description :
 * Object :
 * Requirement :
 * Target :
 * Refer classes :
 * Author : Leo Dicaprio
 * Create Date : 2023/10/17
 * Modify History :
 * ************************************************************************************************
 */
public class CN_Campaign_Upsert_To_Mg_Batch implements Database.batchable<SObject>, Database.AllowsCallouts{

	public Iterable<SObject> start(Database.BatchableContext bc) {
		return [
				SELECT
						Id,CN_Product_Type__c,
						CN_Brand__c,CN_Product_Category__c,
						Type,Name,StartDate,EndDate,Status,CN_Execution_Type__c,
						Description,CN_New_Product_Launch__c,
						CN_Number_of_Audiences__c,ParentId,CN_Channel__c,CN_Customer_Category__c,
						OwnerId
				FROM Campaign
				WHERE CN_Need_Send_MG_Flag__c != 0
				ORDER BY LastModifiedDate ASC ];
	}

	public void execute(Database.BatchableContext bc, List<SObject> batchObjects) {
		List<CN_API_Call_Logger__c> listLog = new List<CN_API_Call_Logger__c>();
		Map<String,Campaign> ltCampaigns = CN_Campaign_Upsert_To_Mg_Callout.sendMgCampaign((List<Campaign>)batchObjects,listLog );
		// add by Zhange ZhiHao Insert log 2024/4/2
        //update listLog;
        upsert listLog;
        // add by Zhange ZhiHao Insert log 2024/4/2
		update ltCampaigns.values();
	}

	public void finish(Database.BatchableContext bc) {
	}

}