objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CN_Is_Within_6_Months__c</fullName>
        <formula>StartDate  &gt;= ADDMONTHS(ToDay(),-6) &amp;&amp; StartDate &lt;= ToDay()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CN_Is_Within_6_Months</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_New_Product_Launch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Product Launch</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Campaign_Product__c.object
<CustomObject>
    <fields>
        <fullName>CN_Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Products</relationshipLabel>
        <relationshipName>Campaign_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Campaign Products</relationshipLabel>
        <relationshipName>Campaign_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Product</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Campaign Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Sales_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>CN_Material_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sales Order Item</relationshipLabel>
        <relationshipName>Sales_Order_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Item</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Sales Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_SOItem_Populate_CampaignPro_Batch.cls
/**************************************************************************************************
 * Name           : CN_SOItem_Populate_CampaignPro_Batch
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Dezheng
 * Create Date    : 2021-09-22
 * Modify History : 
 **************************************************************************************************/
global class CN_SOItem_Populate_CampaignPro_Batch implements Database.Batchable<SObject>,Database.Stateful{

    global String queryString = '';
    List<CN_Campaign_Product__c> campProduct = new List<CN_Campaign_Product__c>();
    Map<Id,Id> productIdCampaignProductIdMap = new Map<Id,Id>();
    
    public CN_SOItem_Populate_CampaignPro_Batch() {
        queryString = 
            'Select  Id,CN_Material_Number__c From CN_Sales_Order_Item__c Where CN_Is_Created_Yesterday__c = TRUE';
    }
    public CN_SOItem_Populate_CampaignPro_Batch(String queryString) {
        this.queryString = queryString;
    }

    global Database.QueryLocator start(Database.BatchableContext ctx) {
        List<CN_Campaign_Product__c> cpList = [Select Id,CN_Product__c,CN_Campaign__c 
                                                From CN_Campaign_Product__c 
                                                Where CN_Campaign__r.CN_New_Product_Launch__c = TRUE And CN_Campaign__r.CN_Is_Within_6_Months__c = TRUE
                                                ORDER BY CN_Campaign__r.StartDate ];
        for(CN_Campaign_Product__c cp : cpList){
            productIdCampaignProductIdMap.put(cp.CN_Product__c,cp.Id);
        }
        Set<Id> productIdSet = productIdCampaignProductIdMap.keySet();
		return Database.getQueryLocator(queryString + ' AND CN_Material_Number__c IN :productIdSet');
	}

    global void execute(Database.BatchableContext bc, List<sObject> scope) {
        Savepoint sp = Database.setSavePoint();
        List<CN_Sales_Order_Item__c> scopeList = (List<CN_Sales_Order_Item__c>)scope;
        List<CN_Sales_Order_Item__c> soiList_update = new List<CN_Sales_Order_Item__c>();
		try{
            for(CN_Sales_Order_Item__c soi : scopeList){
                if(productIdCampaignProductIdMap.containsKey(soi.CN_Material_Number__c)){
                    CN_Sales_Order_Item__c soi_update = new CN_Sales_Order_Item__c();
                    soi_update.Id = soi.Id;
                    soi_update.CN_Campaign_Product__c = productIdCampaignProductIdMap.get(soi.CN_Material_Number__c);
                    soiList_update.add(soi_update);
                }
            }
            if (soiList_update.size() > 0) {
                update soiList_update;
            }				
		} catch (Exception e) {
			Database.rollback(sp);
			throw e;
		} finally {

		}
	}

	global void finish(Database.BatchableContext BC) {

	}

}