objects/CN_Approve_Process_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CN_CEO_UserId__c</fullName>
        <label>CEO User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_CFO_UserId__c</fullName>
        <label>CFO User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Finance_AR_UserId__c</fullName>
        <label>Finance AR User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>CN Approve Process Settings</label>
</CustomObject>

objects/CN_Credit_Term_Application__c.object
<CustomObject>
    <fields>
        <fullName>CN_Account_OwnerId__c</fullName>
        <formula>CASESAFEID(CN_Account__r.OwnerId )</formula>
        <label>Account OwnerId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance AR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Credit_Term_Applications_Approver1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Credit_Term_Applications_Approver2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Credit_Term_Applications_Approver3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Credit_Limit_Incl_VAT__c</fullName>
        <label>Credit Limit (incl VAT)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Nature_Of_Request__c</fullName>
        <label>Nature of Request</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Regular Customer</fullName>
                </value>
                <value>
                    <fullName>TM1 (Hotel-3month rule)</fullName>
                </value>
                <value>
                    <fullName>TM2 (BAPA-3month rule)</fullName>
                    <label>TM2(Excluding Hotel-3month rule)</label>
                </value>
                <value>
                    <fullName>NO CONTRACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Payment_Term_Negotiated__c</fullName>
        <label>Payment Term Negotiated</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>D005</fullName>
                    <label>D005-D05/5 days after delivery</label>
                </value>
                <value>
                    <fullName>D010</fullName>
                    <label>D010-D10/10 days after delivery</label>
                </value>
                <value>
                    <fullName>D015</fullName>
                    <label>D015-15 days after delivery</label>
                </value>
                <value>
                    <fullName>D020</fullName>
                    <label>D020-20 days, due net</label>
                </value>
                <value>
                    <fullName>D030</fullName>
                    <label>D030-30 days, due net</label>
                </value>
                <value>
                    <fullName>D045</fullName>
                    <label>D045-45 days, due net</label>
                </value>
                <value>
                    <fullName>D060</fullName>
                    <label>D060-60days, due net</label>
                </value>
                <value>
                    <fullName>D090</fullName>
                    <label>D090-90days, due net</label>
                </value>
                <value>
                    <fullName>M110</fullName>
                    <label>M110-10 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M115</fullName>
                    <label>M115-15 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M131</fullName>
                    <label>M131-30 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M145</fullName>
                    <label>M145-Before 15th in 2 months, due net</label>
                </value>
                <value>
                    <fullName>M231</fullName>
                    <label>M231-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>D000</fullName>
                    <isActive>false</isActive>
                    <label>D000-Payment in advance</label>
                </value>
                <value>
                    <fullName>D003-Pay immediately with Invoice</fullName>
                    <isActive>false</isActive>
                    <label>D003-Pay immediately with Invoice</label>
                </value>
                <value>
                    <fullName>D120-120 days, due net</fullName>
                    <isActive>false</isActive>
                    <label>D120-120 days, due net</label>
                </value>
                <value>
                    <fullName>M120-20 th of next month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M120-20 th of next month, due net</label>
                </value>
                <value>
                    <fullName>M23-60 days end of month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M23-60 days end of month, due net</label>
                </value>
                <value>
                    <fullName>M331-90 days end of month, due net</fullName>
                    <isActive>false</isActive>
                    <label>M331-90 days end of month, due net</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Reference_Day__c</fullName>
        <label>Reference Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery_Day</fullName>
                    <label>Delivery Day</label>
                </value>
                <value>
                    <fullName>Fapiao_Day</fullName>
                    <label>Fapiao Day</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Credit Term Application</label>
    <nameField>
        <displayFormat>CA{0000000000}</displayFormat>
        <label>Credit Term Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Term Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Payment_Term_Check__mdt.object
<CustomObject>
    <fields>
        <fullName>CN_Payment_Days__c</fullName>
        <label>Payment Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment Term Check</label>
    <pluralLabel>Payment Term Checks</pluralLabel>
</CustomObject>

classes/CN_CTA_Populate_Approver_Hander.cls
/**************************************************************************************************
 * Name           : CN_CTA_Populate_Approver_Hander
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Qiu Chen
 * Create Date    : 2021-05-12
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_CTA_Populate_Approver_Hander implements Triggers.Handler {
    public void handle() {
        if(Trigger.isBefore && Trigger.isUpdate) {
            handleBeforeUpdate();
        }
    }
    public void handleBeforeUpdate() {
        Id ctaRTId = Schema.SObjectType.CN_Credit_Term_Application__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CTA_RT_API_NAME).getRecordTypeId();
        List<CN_Credit_Term_Application__c> ctaList = new List<CN_Credit_Term_Application__c>();
        for(CN_Credit_Term_Application__c cta : (List<CN_Credit_Term_Application__c>)Trigger.new) {
            CN_Credit_Term_Application__c oldCta = (CN_Credit_Term_Application__c)((Map<Id, CN_Credit_Term_Application__c>)Trigger.OldMap).get(cta.Id);
            if(ctaRTId.equals(cta.recordTypeId) && cta.CN_Status__c != oldCta.CN_Status__c && Constants.CN_CTA_STATUS_READY_FOR_APPROVAL.equals(cta.CN_Status__c)) {
                ctaList.add(cta);
            }
        }
        if(ctaList.size() > 0) {
            populateApprover(ctaList);
        }
    }

    public void populateApprover(List<CN_Credit_Term_Application__c> ctaList) {
        CN_Approve_Process_Settings__c settings = CN_Approve_Process_Settings__c.getInstance();
        Set<String> ownerIdSet = new Set<String>();
        for(CN_Credit_Term_Application__c cta : ctaList) {
            ownerIdSet.add(cta.CN_Account_OwnerId__c);
        }
		List<User> ownerList = [SELECT Id,
                                		Title,
                                		ManagerId,
                                		Manager.Title,
                                		Manager.ManagerId,
                                		Manager.Manager.Title,
                                		Manager.Manager.ManagerId,
                                		Manager.Manager.Manager.Title,
                                		Manager.Manager.Manager.ManagerId,
                                		Manager.Manager.Manager.Manager.Title,
                                		Manager.Manager.Manager.Manager.ManagerId,
                                		Manager.Manager.Manager.Manager.Manager.Title
                               FROM User
                               WHERE Id in: ownerIdSet];
        Map<Id, User> ownerMap = new Map<Id, User>(ownerList);
        for(CN_Credit_Term_Application__c cta : ctaList) {
            
            cta.CN_Approver_2__c = null;
            cta.CN_Approver_1__c = null;
            cta.CN_Approver_3__c = null;

            User owner = ownerMap.get(cta.CN_Account_OwnerId__c);
            Map<String, String> titleUserIdMap = new Map<String, String>();
            if(String.isNotBlank(owner.ManagerId)) {
                titleUserIdMap.put(owner.Manager.Title, owner.ManagerId);
            }
            if(String.isNotBlank(owner.Manager.ManagerId)) {
                titleUserIdMap.put(owner.Manager.Manager.Title, owner.Manager.ManagerId);
            }
            if(String.isNotBlank(owner.Manager.Manager.ManagerId)) {
                titleUserIdMap.put(owner.Manager.Manager.Manager.Title, owner.Manager.Manager.ManagerId);
            }
            if(String.isNotBlank(owner.Manager.Manager.Manager.ManagerId)) {
                titleUserIdMap.put(owner.Manager.Manager.Manager.Manager.Title, owner.Manager.Manager.Manager.ManagerId);
            }
            if(String.isNotBlank(owner.Manager.Manager.Manager.Manager.ManagerId)) {
                titleUserIdMap.put(owner.Manager.Manager.Manager.Manager.Manager.Title, owner.Manager.Manager.Manager.Manager.ManagerId);
            }
            titleUserIdMap.put(Constants.CN_USER_TITLE_CEO, settings.CN_CEO_UserID__c);
            titleUserIdMap.put(Constants.CN_USER_TITLE_CFO, settings.CN_CFO_UserID__c);

            String ManagerUserId = titleUserIdMap.get(Constants.CN_USER_TITLE_MANAGER);
            String ARMUserId = titleUserIdMap.get(Constants.CN_USER_TITLE_ARM);
            String RMUserId = titleUserIdMap.get(Constants.CN_USER_TITLE_RM);
            String CMUserId = titleUserIdMap.get(Constants.CN_USER_TITLE_CM);
            String CDUserId = titleUserIdMap.get(Constants.CN_USER_TITLE_CD);

            Map<String, Integer> levelMap = new Map<String, Integer>();
            levelMap.put(Constants.CN_USER_TITLE_MANAGER, 0);
            levelMap.put(Constants.CN_USER_TITLE_ARM, 1);
            levelMap.put(Constants.CN_USER_TITLE_RM, 2);
            levelMap.put(Constants.CN_USER_TITLE_CM, 3);
            levelMap.put(Constants.CN_USER_TITLE_CD, 4);

            List<String> levelList = new List<String>();
            levelList.add(ManagerUserId);
            levelList.add(ARMUserId);
            levelList.add(RMUserId);
            levelList.add(CMUserId);
            levelList.add(CDUserId);
            
            String nature = cta.CN_Nature_Of_Request__c;
            Decimal paymentDays = CN_Payment_Term_Check__mdt.getInstance(cta.CN_Payment_Term_Negotiated__c + '_' + cta.CN_Reference_Day__c).CN_Payment_Days__c;
            Decimal creditLimit = cta.CN_Credit_Limit_Incl_VAT__c;
            String approver2Ttile = '';
            Boolean hasApprover3 = false;

            if(Constants.CN_CTA_NATURE_OF_REQUEST_REGULAR.equals(nature)) {
                if(paymentDays <= 30) {
                    approver2Ttile = Constants.CN_USER_TITLE_CM;
                } else if(30 < paymentDays && paymentDays <= 60) {
                    approver2Ttile = Constants.CN_USER_TITLE_CD;
                    hasApprover3 = true;
                } else if(60 < paymentDays) {
                    approver2Ttile = Constants.CN_USER_TITLE_CEO;
                }
            } else if(Constants.CN_CTA_NATURE_OF_REQUEST_TM1.equals(nature)) {
                if(paymentDays <= 60) {
                    if(creditLimit <= 20000) {
                        approver2Ttile = Constants.CN_USER_TITLE_RM;
                    } else if(20000 < creditLimit && creditLimit <= 100000) {
                        approver2Ttile = Constants.CN_USER_TITLE_CM;
                    } else if(100000 < creditLimit && creditLimit <= 200000) {
                        approver2Ttile = Constants.CN_USER_TITLE_CD;
                    } else if(200000 < creditLimit) {
                        approver2Ttile = Constants.CN_USER_TITLE_CEO;
                    }
                } else if(60 < paymentDays) {
                    approver2Ttile = Constants.CN_USER_TITLE_CEO;
                }
            } else if(Constants.CN_CTA_NATURE_OF_REQUEST_TM2.equals(nature)) {
                if(paymentDays <= 20) {
                    if(creditLimit <= 10000) {
                        approver2Ttile = Constants.CN_USER_TITLE_RM;
                    } else if(10000 < creditLimit) {
                        approver2Ttile = Constants.CN_USER_TITLE_CD;
                    }
                } else if(20 < paymentDays) {
                    approver2Ttile = Constants.CN_USER_TITLE_CEO;
                }
            } else if(Constants.CN_CTA_NATURE_OF_REQUEST_NOC.equals(nature)) {
                if(paymentDays <= 30) {
                    if(creditLimit <= 50000) {
                        approver2Ttile = Constants.CN_USER_TITLE_CM;
                    } else if(50000 < creditLimit && creditLimit <= 100000) {
                        approver2Ttile = Constants.CN_USER_TITLE_CD;
                    } else if(10000 < creditLimit) {
                        approver2Ttile = Constants.CN_USER_TITLE_CEO;
                    }
                } else if(30 < paymentDays) {
                    approver2Ttile = Constants.CN_USER_TITLE_CEO;
                }
            }

            cta.CN_Approver_1__c = settings.CN_Finance_AR_UserId__c;
            if(String.isNotBlank(owner.Title)) {
                cta.CN_Approver_2__c = titleUserIdMap.get(approver2Ttile);
            }
            if(hasApprover3) {
                cta.CN_Approver_3__c = titleUserIdMap.get(Constants.CN_USER_TITLE_CFO);
            }
            // Set The Last Stand Approver
            if(cta.CN_Approver_2__c == null) {
                cta.CN_Approver_2__c = getLatestApprover(approver2Ttile, levelMap, levelList);
            }
        }
    }
    public String getLatestApprover(String title, Map<String, Integer> levelMap, List<String> levelList) {
        String latestApproverId = null;
        if(levelMap.containsKey(title)) {
            if(levelMap.get(title) <= levelList.size()) {
                if(String.isBlank(levelList[levelMap.get(title)])) {
                    for(Integer i = levelMap.get(title); i < levelList.size(); i++) {
                        if(String.isNotBlank(levelList[i])) {
                            latestApproverId = levelList[i];
                            break;
                        }
                    }
                } else {
                    latestApproverId = levelList[levelMap.get(title)];
                }
            }
        }
        return latestApproverId;
    }
}