objects/CN_Approval_Aging_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>CN_Approval_Aging_Setting_Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_Approval_Aging_Setting_Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Approval_Aging_Setting_Step__c</fullName>
        <label>Step</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approval Aging Setting</label>
    <pluralLabel>Approval Aging Settings</pluralLabel>
</CustomObject>

objects/CN_Credit_Term_Application__c.object
<CustomObject>
    <fields>
        <fullName>CN_Approve_Aging_Trigger_Datetime__c</fullName>
        <label>Approve Aging Trigger Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CN_Approve_Step__c</fullName>
        <label>Approve Step</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Step1</fullName>
                </value>
                <value>
                    <fullName>Step2</fullName>
                </value>
                <value>
                    <fullName>Step3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance AR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Credit_Term_Applications_Approver1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Credit_Term_Applications_Approver2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Credit_Term_Applications_Approver3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Current_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Credit_Term_Applications_Current_Apporve</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Credit Term Application</label>
    <nameField>
        <displayFormat>CA{0000000000}</displayFormat>
        <label>Credit Term Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Term Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_CTA_Approve_Aging_Handler.cls
/**************************************************************************************************
 * Name           : CN_CTA_Approve_Aging_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Du Dezheng
 * Create Date    : 2021-05-13
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_CTA_Approve_Aging_Handler implements Triggers.Handler{
    
	public void handle() {
        if(Trigger.isBefore && Trigger.IsUpdate) {
            handleBeforeUpdate();
        }
    }
    
    public void handleBeforeUpdate() {
        Id ctaRTId = Schema.SObjectType.CN_Credit_Term_Application__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CTA_RT_API_NAME).getRecordTypeId();
        List<CN_Credit_Term_Application__c> ctaList = new List<CN_Credit_Term_Application__c>();
        for(CN_Credit_Term_Application__c cta : (List<CN_Credit_Term_Application__c>)Trigger.New) {          
            if(Constants.CN_CTA_STATUS_SUBMITTED_FOR_APPROVAL.equals(cta.CN_Status__c) && String.isNotBlank(cta.CN_Approve_Step__c) && cta.CN_Approve_Step__c <> ((CN_Credit_Term_Application__c)Trigger.oldMap.get(cta.Id)).CN_Approve_Step__c ){
                ctaList.add(cta);
            }
        }
        if(ctaList.size() > 0){
            updateTriggerTimeAndApprover(ctaList);
        }        
    }
    
    public void updateTriggerTimeAndApprover(List<CN_Credit_Term_Application__c> ctaList){
        for(CN_Credit_Term_Application__c cta : ctaList){
            Integer hours = NUll;
            
            Map<String,Id> ApproveStepStringApproverIdMap = new Map<String,Id>();
            ApproveStepStringApproverIdMap.put('step1',cta.CN_Approver_1__c);
            ApproveStepStringApproverIdMap.put('step2',cta.CN_Approver_2__c);
            ApproveStepStringApproverIdMap.put('step3',cta.CN_Approver_3__c);
            Integer str_Approve_Step_num = Integer.valueOf(cta.CN_Approve_Step__c.Right(1));
            for(Integer n=str_Approve_Step_num;n<=3;n++){
                if(String.isNotBlank(ApproveStepStringApproverIdMap.get('step'+n))){
                    cta.CN_Current_Approver__c = ApproveStepStringApproverIdMap.get('step'+ n);
                    cta.CN_Approve_Step__c = 'step'+n;
                    break;
                }else if(n==3){
                    return;
                }
            }
            
            List<CN_Approval_Aging_Setting__mdt> approvalAgingSettings =  CN_Approval_Aging_Setting__mdt.getAll().values();
            for(CN_Approval_Aging_Setting__mdt approvalAgingSetting : approvalAgingSettings){
                if(approvalAgingSetting.CN_Approval_Aging_Setting_Step__c == cta.CN_Approve_Step__c && approvalAgingSetting.CN_Approval_Aging_Setting_Object__c == 'CN_Credit_Term_Application__c'){
                    hours = (Integer)approvalAgingSetting.CN_Approval_Aging_Setting_Hours__c;
                    break;
                }
            }
            
            if(hours <> null){
                cta.CN_Approve_Aging_Trigger_Datetime__c = Untils.calculateBusinessTime(DateTime.now(),hours,Constants.CN_BUSINESS_HOURS_NAME);
            }else{
                cta.AddError(system.Label.CN_CTA_CustomLabel_Hour_Is_NULL);
            }
        }
    }
}