objects/CN_Approve_Process_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CN_CEO_UserId__c</fullName>
        <label>CEO User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_CFO_UserId__c</fullName>
        <label>CFO User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Finance_AR_UserId__c</fullName>
        <label>Finance AR User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Finance_MDM_UserId__c</fullName>
        <label>Finance MDM User ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sales_MDM_UserId__c</fullName>
        <label>Sales MDM User ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CN Approve Process Settings</label>
</CustomObject>

objects/CN_Business_Unit__c.object
<CustomObject>
    <fields>
        <fullName>CN_Business_Unit_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Business Unit Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_City_API__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_City__c.object
<CustomObject>
    <fields>
        <fullName>CN_City_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>City Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Province__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province</label>
        <referenceTo>CN_Province__c</referenceTo>
        <relationshipLabel>Citys (Province)</relationshipLabel>
        <relationshipName>Citys1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Citys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Group__c.object
<CustomObject>
    <fields>
        <fullName>CN_City_API__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Group_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Group Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Sales_Team_Code__c</fullName>
        <formula>CN_Sales_Team__r.CN_Sales_Team_Code__c</formula>
        <label>Sales Team Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sales_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The sales team you choose must have sales team Code.</errorMessage>
            <filterItems>
                <field>CN_Sales_Team__c.CN_Sales_Team_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_Sales_Team__c</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Province__c.object
<CustomObject>
    <fields>
        <fullName>Province_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Province Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Province</label>
    <nameField>
        <label>Province Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provinces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Sales_Team__c.object
<CustomObject>
    <fields>
        <fullName>CN_Business_Unit_Code__c</fullName>
        <formula>CN_Business_Unit__r.CN_Business_Unit_Code__c</formula>
        <label>Business Unit Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Business_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Unit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The business unit you choose must have business unit Code.</errorMessage>
            <filterItems>
                <field>CN_Business_Unit__c.CN_Business_Unit_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CN_Business_Unit__c</referenceTo>
        <relationshipLabel>Sales Teams</relationshipLabel>
        <relationshipName>Sales_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_City_API__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sales_Team_Code__c</fullName>
        <externalId>true</externalId>
        <label>Sales Team Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <label>Sales Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Talend_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Change_Request_Endpoint__c</fullName>
        <label>Change Request Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Update_Endpoint__c</fullName>
        <label>Sales Order Update Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Sanbox_Change_Request_Endpoint__c</fullName>
        <label>Sanbox Change Request Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Sanbox_Sales_Order_Update_Endpoint__c</fullName>
        <label>Sanbox Sales Order Update Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Sandbox_Password__c</fullName>
        <label>Sandbox Password</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sandbox_Send_To_Account_Endpoint__c</fullName>
        <label>Sandbox Send to Account Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Sandbox_User_Name__c</fullName>
        <label>Sandbox User Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Account_Endpoint__c</fullName>
        <label>Send to Account Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Talend Setting</label>
</CustomObject>

objects/Trigger_Switcher_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EnableFlow__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EnableFlow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnableTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EnableTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnableValidationRule__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EnableValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Switcher Setting</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CN_Sales_Team__c</fullName>
        <label>Sales Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CN_ST_Send_To_SAP_LC_Ctrl_Test.cls
/**************************************************************************************************
 * Name           : CN_ST_Send_To_SAP_LC_Ctrl_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Dezheng Du
 * Create Date    : 2021-06-18
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_ST_Send_To_SAP_LC_Ctrl_Test {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }

    @isTest
    private static void handleBeforeDelete_500() {
        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }
        Trigger_Switcher_Setting__c setting = new Trigger_Switcher_Setting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            EnableFlow__c = true,
            EnableTrigger__c = true,
            EnableValidationRule__c = true
        );
        insert setting;
        CN_Approve_Process_Settings__c approveSetting = new CN_Approve_Process_Settings__c(
            CN_CEO_UserId__c = lastNameUserIdMap.get('CEO'),
            CN_CFO_UserId__c = lastNameUserIdMap.get('CFO'),
            CN_Finance_AR_UserId__c = lastNameUserIdMap.get('FinanceAR'),
            CN_Finance_MDM_UserId__c = lastNameUserIdMap.get('FinanceMDM'),
            CN_Sales_MDM_UserId__c = lastNameUserIdMap.get('SalesMDM'),
			CN_WholeSales_Development_Supervisor__c = lastNameUserIdMap.get('WholeSalesDevelopmentSupervisor')
        );
        insert approveSetting;

        Talend_Setting__c talendSetting = new Talend_Setting__c();
        talendSetting.Change_Request_Endpoint__c = 'http://127.0.0.1/CR/500';
        talendSetting.Password__c = 'password';
        talendSetting.Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/500';
        talendSetting.Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/500';
        talendSetting.Sandbox_Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/500';
        talendSetting.Sanbox_Change_Request_Endpoint__c = 'http://127.0.0.1/CR/500';
        talendSetting.Sanbox_Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/500';
        talendSetting.Sandbox_Password__c = 'password';
        talendSetting.Sandbox_Send_To_Account_Endpoint__c = 'http://127.0.0.1/ACC/500';
        talendSetting.Sandbox_User_Name__c = 'Name';
        talendSetting.Send_to_Account_Endpoint__c = 'http://127.0.0.1/ACC/500';
        talendSetting.User_Name__c = 'Name';
        talendSetting.Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        talendSetting.Sandbox_Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        insert talendSetting;

        User salesMDM = [SELECT Id FROM User WHERE lastName = 'salesMDM'][0];
        CN_Province__c province = [SELECT Id FROM CN_Province__c WHERE Province_Code__c = '010'][0];
        CN_City__c city = [SELECT Id FROM CN_City__c WHERE CN_City_Code__c = '010'][0];
        CN_Business_Unit__c businessUnit = [SELECT Id FROM CN_Business_Unit__c WHERE CN_Business_Unit_Code__c = '0000900001'][0];
        CN_Sales_Team__c salesTeam = [SELECT Id FROM CN_Sales_Team__c WHERE CN_Sales_Team_Code__c = '0000901001'][0];
        CN_Group__c gr = [SELECT Id FROM CN_Group__c WHERE CN_Group_Code__c = 'drink group'][0];
        

        System.runAs(salesMDM) {

            CN_Business_Unit__c bu = new CN_Business_Unit__c();
            bu.Name = 'Test BusinessUnit';
            bu.CN_Business_Unit_Code__c = '00001';
            bu.CN_City_API__c = 'Shanghai';
            bu.CurrencyIsoCode = 'CNY';
            insert bu;
            
            CN_Sales_Team__c st = new CN_Sales_Team__c();
            st.Name = 'Test SalesTeam';
            st.CN_Sales_Team_Code__c = '00001';
            st.CN_City_API__c = 'Shanghai';
            st.CN_Business_Unit__c = bu.Id;
            insert st;
            
            test.startTest();

            try{
                CN_ST_Send_To_SAP_LC_Ctrl.getBUInfoAndCheckEditPermisison(st.id);
                Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
                CN_ST_Send_To_SAP_LC_Ctrl.sendSalesTeam(st.id);
            }catch(Exception e){}
            
            test.stopTest();
        }
    }

    @isTest
    private static void handleBeforeDelete_200_Sync_Success() {
        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }
        Trigger_Switcher_Setting__c setting = new Trigger_Switcher_Setting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            EnableFlow__c = true,
            EnableTrigger__c = true,
            EnableValidationRule__c = true
        );
        insert setting;
        CN_Approve_Process_Settings__c approveSetting = new CN_Approve_Process_Settings__c(
            CN_CEO_UserId__c = lastNameUserIdMap.get('CEO'),
            CN_CFO_UserId__c = lastNameUserIdMap.get('CFO'),
            CN_Finance_AR_UserId__c = lastNameUserIdMap.get('FinanceAR'),
            CN_Finance_MDM_UserId__c = lastNameUserIdMap.get('FinanceMDM'),
            CN_Sales_MDM_UserId__c = lastNameUserIdMap.get('SalesMDM'),
			CN_WholeSales_Development_Supervisor__c = lastNameUserIdMap.get('WholeSalesDevelopmentSupervisor')
        );
        insert approveSetting;

        Talend_Setting__c talendSetting = new Talend_Setting__c();
        talendSetting.Change_Request_Endpoint__c = 'http://127.0.0.1/CR/200';
        talendSetting.Password__c = 'password';
        talendSetting.Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/200';
        talendSetting.Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CHS/200';
        talendSetting.Sandbox_Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CHS/200';
        talendSetting.Sanbox_Change_Request_Endpoint__c = 'http://127.0.0.1/CR/200';
        talendSetting.Sanbox_Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/200';
        talendSetting.Sandbox_Password__c = 'password';
        talendSetting.Sandbox_Send_To_Account_Endpoint__c = 'http://127.0.0.1/ACC/200';
        talendSetting.Sandbox_User_Name__c = 'Name';
        talendSetting.Send_to_Account_Endpoint__c = 'http://127.0.0.1/ACC/200';
        talendSetting.User_Name__c = 'Name';
        talendSetting.Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        talendSetting.Sandbox_Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        insert talendSetting;

        User salesMDM = [SELECT Id FROM User WHERE lastName = 'salesMDM'][0];
        CN_Province__c province = [SELECT Id FROM CN_Province__c WHERE Province_Code__c = '010'][0];
        CN_City__c city = [SELECT Id FROM CN_City__c WHERE CN_City_Code__c = '010'][0];
        CN_Business_Unit__c businessUnit = [SELECT Id FROM CN_Business_Unit__c WHERE CN_Business_Unit_Code__c = '0000900001'][0];
        CN_Sales_Team__c salesTeam = [SELECT Id FROM CN_Sales_Team__c WHERE CN_Sales_Team_Code__c = '0000901001'][0];
        CN_Group__c gr = [SELECT Id FROM CN_Group__c WHERE CN_Group_Code__c = 'drink group'][0];
        

        System.runAs(salesMDM) {

            CN_Business_Unit__c bu = new CN_Business_Unit__c();
            bu.Name = 'Test BusinessUnit';
            bu.CN_Business_Unit_Code__c = '00001';
            bu.CurrencyIsoCode = 'CNY';
            bu.CN_City_API__c = 'Shanghai';
            insert bu;
            
            CN_Sales_Team__c st = new CN_Sales_Team__c();
            st.Name = 'Test SalesTeam';
            st.CN_Sales_Team_Code__c = '00001';
            st.CN_City_API__c = 'Shanghai';
            st.CN_Business_Unit__c = bu.Id;
            insert st;
            
            test.startTest();

            try{
                CN_ST_Send_To_SAP_LC_Ctrl.getBUInfoAndCheckEditPermisison(st.id);
                Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
                CN_ST_Send_To_SAP_LC_Ctrl.sendSalesTeam(st.id);
            }catch(Exception e){}
            try{
                CN_ST_Send_To_SAP_LC_Ctrl.getBUInfoAndCheckEditPermisison(null);
            }catch(Exception e){}
            try{
                CN_ST_Send_To_SAP_LC_Ctrl.sendSalesTeam(null);
            }catch(Exception e){}
            test.stopTest();
        }
    }

    @isTest
    private static void handleBeforeDelete_200_Sync_Fail() {
        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }
        Trigger_Switcher_Setting__c setting = new Trigger_Switcher_Setting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            EnableFlow__c = true,
            EnableTrigger__c = true,
            EnableValidationRule__c = true
        );
        insert setting;
        CN_Approve_Process_Settings__c approveSetting = new CN_Approve_Process_Settings__c(
            CN_CEO_UserId__c = lastNameUserIdMap.get('CEO'),
            CN_CFO_UserId__c = lastNameUserIdMap.get('CFO'),
            CN_Finance_AR_UserId__c = lastNameUserIdMap.get('FinanceAR'),
            CN_Finance_MDM_UserId__c = lastNameUserIdMap.get('FinanceMDM'),
            CN_Sales_MDM_UserId__c = lastNameUserIdMap.get('SalesMDM'),
			CN_WholeSales_Development_Supervisor__c = lastNameUserIdMap.get('WholeSalesDevelopmentSupervisor')
        );
        insert approveSetting;

        Talend_Setting__c talendSetting = new Talend_Setting__c();
        talendSetting.Change_Request_Endpoint__c = 'http://127.0.0.1/CR/200';
        talendSetting.Password__c = 'password';
        talendSetting.Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/200';
        talendSetting.Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CHE/200';
        talendSetting.Sandbox_Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CHE/200';
        talendSetting.Sanbox_Change_Request_Endpoint__c = 'http://127.0.0.1/CR/200';
        talendSetting.Sanbox_Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/200';
        talendSetting.Sandbox_Password__c = 'password';
        talendSetting.Sandbox_Send_To_Account_Endpoint__c = 'http://127.0.0.1/ACC/200';
        talendSetting.Sandbox_User_Name__c = 'Name';
        talendSetting.Send_to_Account_Endpoint__c = 'http://127.0.0.1/ACC/200';
        talendSetting.User_Name__c = 'Name';
        talendSetting.Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        talendSetting.Sandbox_Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        insert talendSetting;

        User salesMDM = [SELECT Id FROM User WHERE lastName = 'salesMDM'][0];
        CN_Province__c province = [SELECT Id FROM CN_Province__c WHERE Province_Code__c = '010'][0];
        CN_City__c city = [SELECT Id FROM CN_City__c WHERE CN_City_Code__c = '010'][0];
        CN_Business_Unit__c businessUnit = [SELECT Id FROM CN_Business_Unit__c WHERE CN_Business_Unit_Code__c = '0000900001'][0];
        CN_Sales_Team__c salesTeam = [SELECT Id FROM CN_Sales_Team__c WHERE CN_Sales_Team_Code__c = '0000901001'][0];
        CN_Group__c gr = [SELECT Id FROM CN_Group__c WHERE CN_Group_Code__c = 'drink group'][0];
        

        System.runAs(salesMDM) {

            CN_Business_Unit__c bu = new CN_Business_Unit__c();
            bu.Name = 'Test BusinessUnit';
            bu.CN_Business_Unit_Code__c = '00001';
            bu.CurrencyIsoCode = 'CNY';
            bu.CN_City_API__c = 'Shanghai';
            insert bu;

            CN_Sales_Team__c st = new CN_Sales_Team__c();
            st.Name = 'Test SalesTeam';
            st.CN_Sales_Team_Code__c = '00001';
            st.CN_City_API__c = 'Shanghai';
            st.CN_Business_Unit__c = bu.Id;
            insert st;
            
            test.startTest();

            try{
                CN_ST_Send_To_SAP_LC_Ctrl.getBUInfoAndCheckEditPermisison(st.id);
                Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
                CN_ST_Send_To_SAP_LC_Ctrl.sendSalesTeam(st.id);
            }catch(Exception e){}
            
            test.stopTest();
        }
    }

    @isTest
    private static void handleBeforeDelete_200_Sent() {
        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }
        Trigger_Switcher_Setting__c setting = new Trigger_Switcher_Setting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            EnableFlow__c = true,
            EnableTrigger__c = true,
            EnableValidationRule__c = true
        );
        insert setting;
        CN_Approve_Process_Settings__c approveSetting = new CN_Approve_Process_Settings__c(
            CN_CEO_UserId__c = lastNameUserIdMap.get('CEO'),
            CN_CFO_UserId__c = lastNameUserIdMap.get('CFO'),
            CN_Finance_AR_UserId__c = lastNameUserIdMap.get('FinanceAR'),
            CN_Finance_MDM_UserId__c = lastNameUserIdMap.get('FinanceMDM'),
            CN_Sales_MDM_UserId__c = lastNameUserIdMap.get('SalesMDM'),
			CN_WholeSales_Development_Supervisor__c = lastNameUserIdMap.get('WholeSalesDevelopmentSupervisor')
        );
        insert approveSetting;

        Talend_Setting__c talendSetting = new Talend_Setting__c();
        talendSetting.Change_Request_Endpoint__c = 'http://127.0.0.1/CR/200';
        talendSetting.Password__c = 'password';
        talendSetting.Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/200';
        talendSetting.Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/200';
        talendSetting.Sandbox_Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/200';
        talendSetting.Sanbox_Change_Request_Endpoint__c = 'http://127.0.0.1/CR/200';
        talendSetting.Sanbox_Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/200';
        talendSetting.Sandbox_Password__c = 'password';
        talendSetting.Sandbox_Send_To_Account_Endpoint__c = 'http://127.0.0.1/ACC/200';
        talendSetting.Sandbox_User_Name__c = 'Name';
        talendSetting.Send_to_Account_Endpoint__c = 'http://127.0.0.1/ACC/200';
        talendSetting.User_Name__c = 'Name';
        talendSetting.Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        talendSetting.Sandbox_Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        insert talendSetting;

        User salesMDM = [SELECT Id FROM User WHERE lastName = 'salesMDM'][0];
        CN_Province__c province = [SELECT Id FROM CN_Province__c WHERE Province_Code__c = '010'][0];
        CN_City__c city = [SELECT Id FROM CN_City__c WHERE CN_City_Code__c = '010'][0];
        CN_Business_Unit__c businessUnit = [SELECT Id FROM CN_Business_Unit__c WHERE CN_Business_Unit_Code__c = '0000900001'][0];
        CN_Sales_Team__c salesTeam = [SELECT Id FROM CN_Sales_Team__c WHERE CN_Sales_Team_Code__c = '0000901001'][0];
        CN_Group__c gr = [SELECT Id FROM CN_Group__c WHERE CN_Group_Code__c = 'drink group'][0];
        

        System.runAs(salesMDM) {

            CN_Business_Unit__c bu = new CN_Business_Unit__c();
            bu.Name = 'Test BusinessUnit';
            bu.CN_Business_Unit_Code__c = '00001';
            bu.CurrencyIsoCode = 'CNY';
            bu.CN_City_API__c = 'Shanghai';
            insert bu;
            
            CN_Sales_Team__c st = new CN_Sales_Team__c();
            st.Name = 'Test SalesTeam';
            st.CN_Sales_Team_Code__c = '00001';
            st.CN_City_API__c = 'Shanghai';
            st.CN_Business_Unit__c = bu.Id;
            insert st;
            
            test.startTest();

            try{
                CN_ST_Send_To_SAP_LC_Ctrl.getBUInfoAndCheckEditPermisison(st.id);
                Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
                CN_ST_Send_To_SAP_LC_Ctrl.sendSalesTeam(st.id);
            }catch(Exception e){}
            
            test.stopTest();
        }
    }

    @isTest
    private static void handleBeforeDelete_400() {
        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }
        Trigger_Switcher_Setting__c setting = new Trigger_Switcher_Setting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            EnableFlow__c = true,
            EnableTrigger__c = true,
            EnableValidationRule__c = true
        );
        insert setting;
        CN_Approve_Process_Settings__c approveSetting = new CN_Approve_Process_Settings__c(
            CN_CEO_UserId__c = lastNameUserIdMap.get('CEO'),
            CN_CFO_UserId__c = lastNameUserIdMap.get('CFO'),
            CN_Finance_AR_UserId__c = lastNameUserIdMap.get('FinanceAR'),
            CN_Finance_MDM_UserId__c = lastNameUserIdMap.get('FinanceMDM'),
            CN_Sales_MDM_UserId__c = lastNameUserIdMap.get('SalesMDM'),
			CN_WholeSales_Development_Supervisor__c = lastNameUserIdMap.get('WholeSalesDevelopmentSupervisor')
        );
        insert approveSetting;

        Talend_Setting__c talendSetting = new Talend_Setting__c();
        talendSetting.Change_Request_Endpoint__c = 'http://127.0.0.1/CR/500';
        talendSetting.Password__c = 'password';
        talendSetting.Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/500';
        talendSetting.Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/400';
        talendSetting.Sandbox_Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/400';
        talendSetting.Sanbox_Change_Request_Endpoint__c = 'http://127.0.0.1/CR/500';
        talendSetting.Sanbox_Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/500';
        talendSetting.Sandbox_Password__c = 'password';
        talendSetting.Sandbox_Send_To_Account_Endpoint__c = 'http://127.0.0.1/ACC/500';
        talendSetting.Sandbox_User_Name__c = 'Name';
        talendSetting.Send_to_Account_Endpoint__c = 'http://127.0.0.1/ACC/500';
        talendSetting.User_Name__c = 'Name';
        talendSetting.Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        talendSetting.Sandbox_Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        insert talendSetting;

        User salesMDM = [SELECT Id FROM User WHERE lastName = 'salesMDM'][0];
        CN_Province__c province = [SELECT Id FROM CN_Province__c WHERE Province_Code__c = '010'][0];
        CN_City__c city = [SELECT Id FROM CN_City__c WHERE CN_City_Code__c = '010'][0];
        CN_Business_Unit__c businessUnit = [SELECT Id FROM CN_Business_Unit__c WHERE CN_Business_Unit_Code__c = '0000900001'][0];
        CN_Sales_Team__c salesTeam = [SELECT Id FROM CN_Sales_Team__c WHERE CN_Sales_Team_Code__c = '0000901001'][0];
        CN_Group__c gr = [SELECT Id FROM CN_Group__c WHERE CN_Group_Code__c = 'drink group'][0];
        

        System.runAs(salesMDM) {

            CN_Business_Unit__c bu = new CN_Business_Unit__c();
            bu.Name = 'Test BusinessUnit';
            bu.CN_Business_Unit_Code__c = '00001';
            bu.CurrencyIsoCode = 'CNY';
            bu.CN_City_API__c = 'Shanghai';
            insert bu;
            
            CN_Sales_Team__c st = new CN_Sales_Team__c();
            st.Name = 'Test SalesTeam';
            st.CN_Sales_Team_Code__c = '00001';
            st.CN_City_API__c = 'Shanghai';
            st.CN_Business_Unit__c = bu.Id;
            insert st;
            
            test.startTest();

            try{
                CN_ST_Send_To_SAP_LC_Ctrl.getBUInfoAndCheckEditPermisison(st.id);
                Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
                CN_ST_Send_To_SAP_LC_Ctrl.sendSalesTeam(st.id);
            }catch(Exception e){}
            
            test.stopTest();
        }
    }

    @isTest
    private static void handleBeforeDelete_401() {
        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }
        Trigger_Switcher_Setting__c setting = new Trigger_Switcher_Setting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            EnableFlow__c = true,
            EnableTrigger__c = true,
            EnableValidationRule__c = true
        );
        insert setting;
        CN_Approve_Process_Settings__c approveSetting = new CN_Approve_Process_Settings__c(
            CN_CEO_UserId__c = lastNameUserIdMap.get('CEO'),
            CN_CFO_UserId__c = lastNameUserIdMap.get('CFO'),
            CN_Finance_AR_UserId__c = lastNameUserIdMap.get('FinanceAR'),
            CN_Finance_MDM_UserId__c = lastNameUserIdMap.get('FinanceMDM'),
            CN_Sales_MDM_UserId__c = lastNameUserIdMap.get('SalesMDM'),
			CN_WholeSales_Development_Supervisor__c = lastNameUserIdMap.get('WholeSalesDevelopmentSupervisor')
        );
        insert approveSetting;

        Talend_Setting__c talendSetting = new Talend_Setting__c();
        talendSetting.Change_Request_Endpoint__c = 'http://127.0.0.1/CR/500';
        talendSetting.Password__c = 'password';
        talendSetting.Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/500';
        talendSetting.Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/401';
        talendSetting.Sandbox_Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/401';
        talendSetting.Sanbox_Change_Request_Endpoint__c = 'http://127.0.0.1/CR/500';
        talendSetting.Sanbox_Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/500';
        talendSetting.Sandbox_Password__c = 'password';
        talendSetting.Sandbox_Send_To_Account_Endpoint__c = 'http://127.0.0.1/ACC/500';
        talendSetting.Sandbox_User_Name__c = 'Name';
        talendSetting.Send_to_Account_Endpoint__c = 'http://127.0.0.1/ACC/500';
        talendSetting.User_Name__c = 'Name';
        talendSetting.Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        talendSetting.Sandbox_Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        insert talendSetting;

        User salesMDM = [SELECT Id FROM User WHERE lastName = 'salesMDM'][0];
        CN_Province__c province = [SELECT Id FROM CN_Province__c WHERE Province_Code__c = '010'][0];
        CN_City__c city = [SELECT Id FROM CN_City__c WHERE CN_City_Code__c = '010'][0];
        CN_Business_Unit__c businessUnit = [SELECT Id FROM CN_Business_Unit__c WHERE CN_Business_Unit_Code__c = '0000900001'][0];
        CN_Sales_Team__c salesTeam = [SELECT Id FROM CN_Sales_Team__c WHERE CN_Sales_Team_Code__c = '0000901001'][0];
        CN_Group__c gr = [SELECT Id FROM CN_Group__c WHERE CN_Group_Code__c = 'drink group'][0];
        

        System.runAs(salesMDM) {

            CN_Business_Unit__c bu = new CN_Business_Unit__c();
            bu.Name = 'Test BusinessUnit';
            bu.CN_Business_Unit_Code__c = '00001';
            bu.CurrencyIsoCode = 'CNY';
            bu.CN_City_API__c = 'Shanghai';
            insert bu;
            
            CN_Sales_Team__c st = new CN_Sales_Team__c();
            st.Name = 'Test SalesTeam';
            st.CN_Sales_Team_Code__c = '00001';
            st.CN_City_API__c = 'Shanghai';
            st.CN_Business_Unit__c = bu.Id;
            insert st;
            
            test.startTest();

            try{
                CN_ST_Send_To_SAP_LC_Ctrl.getBUInfoAndCheckEditPermisison(st.id);
                Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
                CN_ST_Send_To_SAP_LC_Ctrl.sendSalesTeam(st.id);
            }catch(Exception e){}
            
            test.stopTest();
        }
    }

    @isTest
    private static void handleBeforeDelete_404() {
        List<User> userList = [SELECT Id, LastName FROM User];
        Map<String, Id> lastNameUserIdMap = new Map<String, Id>();
        for(User usr: userList) {
            lastNameUserIdMap.put(usr.LastName, usr.Id);
        }
        Trigger_Switcher_Setting__c setting = new Trigger_Switcher_Setting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            EnableFlow__c = true,
            EnableTrigger__c = true,
            EnableValidationRule__c = true
        );
        insert setting;
        CN_Approve_Process_Settings__c approveSetting = new CN_Approve_Process_Settings__c(
            CN_CEO_UserId__c = lastNameUserIdMap.get('CEO'),
            CN_CFO_UserId__c = lastNameUserIdMap.get('CFO'),
            CN_Finance_AR_UserId__c = lastNameUserIdMap.get('FinanceAR'),
            CN_Finance_MDM_UserId__c = lastNameUserIdMap.get('FinanceMDM'),
            CN_Sales_MDM_UserId__c = lastNameUserIdMap.get('SalesMDM'),
			CN_WholeSales_Development_Supervisor__c = lastNameUserIdMap.get('WholeSalesDevelopmentSupervisor')
        );
        insert approveSetting;

        Talend_Setting__c talendSetting = new Talend_Setting__c();
        talendSetting.Change_Request_Endpoint__c = 'http://127.0.0.1/CR/500';
        talendSetting.Password__c = 'password';
        talendSetting.Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/500';
        talendSetting.Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/404';
        talendSetting.Sandbox_Customer_Hierarchy_Endpoint__c = 'http://127.0.0.1/CH/404';
        talendSetting.Sanbox_Change_Request_Endpoint__c = 'http://127.0.0.1/CR/500';
        talendSetting.Sanbox_Sales_Order_Update_Endpoint__c = 'http://127.0.0.1/SO/500';
        talendSetting.Sandbox_Password__c = 'password';
        talendSetting.Sandbox_Send_To_Account_Endpoint__c = 'http://127.0.0.1/ACC/500';
        talendSetting.Sandbox_User_Name__c = 'Name';
        talendSetting.Send_to_Account_Endpoint__c = 'http://127.0.0.1/ACC/500';
        talendSetting.User_Name__c = 'Name';
        talendSetting.Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        talendSetting.Sandbox_Quote_Endpoint__c = 'http://127.0.0.1/Quote/200';
        insert talendSetting;

        User salesMDM = [SELECT Id FROM User WHERE lastName = 'salesMDM'][0];
        CN_Province__c province = [SELECT Id FROM CN_Province__c WHERE Province_Code__c = '010'][0];
        CN_City__c city = [SELECT Id FROM CN_City__c WHERE CN_City_Code__c = '010'][0];
        CN_Business_Unit__c businessUnit = [SELECT Id FROM CN_Business_Unit__c WHERE CN_Business_Unit_Code__c = '0000900001'][0];
        CN_Sales_Team__c salesTeam = [SELECT Id FROM CN_Sales_Team__c WHERE CN_Sales_Team_Code__c = '0000901001'][0];
        CN_Group__c gr = [SELECT Id FROM CN_Group__c WHERE CN_Group_Code__c = 'drink group'][0];
        

        System.runAs(salesMDM) {

            CN_Business_Unit__c bu = new CN_Business_Unit__c();
            bu.Name = 'Test BusinessUnit';
            bu.CN_Business_Unit_Code__c = '00001';
            bu.CurrencyIsoCode = 'CNY';
            bu.CN_City_API__c = 'Shanghai';
            insert bu;
            
            CN_Sales_Team__c st = new CN_Sales_Team__c();
            st.Name = 'Test SalesTeam';
            st.CN_Sales_Team_Code__c = '00001';
            st.CN_City_API__c = 'Shanghai';
            st.CN_Business_Unit__c = bu.Id;
            insert st;
            
            test.startTest();


            try{
                CN_ST_Send_To_SAP_LC_Ctrl.getBUInfoAndCheckEditPermisison(st.id);
                Test.setMock(HTTPCalloutMock.class, new TestHttpMock());
                CN_ST_Send_To_SAP_LC_Ctrl.sendSalesTeam(st.id);
            }catch(Exception e){}
            
            test.stopTest();
        }
    }

    
}