objects/CN_Approve_Process_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CN_Finance_MDM_UserId__c</fullName>
        <label>Finance MDM User ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CN Approve Process Settings</label>
</CustomObject>

objects/CN_Credit_Term_Application__c.object
<CustomObject>
    <fields>
        <fullName>CN_Finance_MDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance MDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Credit_Term_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit Term Application</label>
    <nameField>
        <displayFormat>CA{0000000000}</displayFormat>
        <label>Credit Term Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Term Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_CTA_Populate_FinanceMDM_Handler.cls
/**************************************************************************************************
 * Name           : CN_CTA_Populate_FinanceMDM_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Du Dezheng
 * Create Date    : 2021-06-09
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_CTA_Populate_FinanceMDM_Handler implements Triggers.Handler{
    Id ctaRTId = Schema.SObjectType.CN_Credit_Term_Application__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CTA_RT_API_NAME).getRecordTypeId();
	public void handle() {
        if(Trigger.isBefore && Trigger.isInsert) {
            handleBeforeInsert();
        }
        if(Trigger.isBefore && Trigger.isUpdate) {
            handleBeforeUpdate();
        }
    }
    
    public void handleBeforeInsert() {
        List<CN_Credit_Term_Application__c> CTAList = new List<CN_Credit_Term_Application__c>();
        for(CN_Credit_Term_Application__c cta : (List<CN_Credit_Term_Application__c>)Trigger.New) {
            if(cta.RecordTypeId == ctaRTId) {
                CTAList.add(cta);
            }
        }
        if(CTAList.size() > 0) {
            populateFinanceMDM(CTAList);
        }
    }

    public void handleBeforeUpdate() {
        List<CN_Credit_Term_Application__c> CTAList = new List<CN_Credit_Term_Application__c>();
        for(CN_Credit_Term_Application__c cta : (List<CN_Credit_Term_Application__c>)Trigger.New) {
            if(cta.RecordTypeId == ctaRTId) {
                CTAList.add(cta);
            }
        }
        if(CTAList.size() > 0) {
            populateFinanceMDM(CTAList);
        }
    }

    public void populateFinanceMDM(List<CN_Credit_Term_Application__c> CTAList) {
        for(CN_Credit_Term_Application__c cta : CTAList){
            cta.CN_Finance_MDM__c = CN_Approve_Process_Settings__c.getInstance().CN_Finance_MDM_UserId__c;
        }
    }

}