objects/CN_Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Brand_Owner_Control__c.object
<CustomObject>
    <fields>
        <fullName>CN_Brand_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Brand_Owner_Control_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Brands__c</fullName>
        <label>Brands</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Brand Owner Control</label>
    <nameField>
        <displayFormat>BOC-{0000000000}</displayFormat>
        <label>Brand Owner Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Owner Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CN_Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_SKU_Description_EN__c</fullName>
        <label>SKU Description EN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trigger_Switcher_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EnableFlow__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EnableFlow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnableTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EnableTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EnableValidationRule__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EnableValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Switcher Setting</label>
</CustomObject>

classes/CN_Product_Description_Check_HandlerTest.cls
@isTest
public class CN_Product_Description_Check_HandlerTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();

        Trigger_Switcher_Setting__c setting = new Trigger_Switcher_Setting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            EnableFlow__c = true,
            EnableTrigger__c = true,
            EnableValidationRule__c = true
        );
        insert setting;
    }

    @isTest
    private static void handleBeforeUpdate1(){
        User cceUser = [Select Id from User Where Profile.Name = 'CN CCE' and LastName = 'CCE2_DS' limit 1];
        CN_Brand_Owner_Control__c boc = new CN_Brand_Owner_Control__c();
        boc.CN_Brands__c = 'AA';
        boc.CN_Brand_Owner__c = cceUser.Id;
        insert boc;

        Product2 prd = [Select Id From Product2 Where Name = 'TestProduct00001' limit 1];
        prd.CN_Brand__c = 'AA';
        update prd;
        User cceUser2 = [Select Id from User Where Profile.Name = 'CN CCE' and LastName = 'CCE1_KA' limit 1];
        system.runAs(cceUser2){
            Product2 prd2 = [Select Id From Product2 Where Name = 'TestProduct00001' limit 1];
            prd2.CN_SKU_Description_EN__c = 'AA';
            try{
                update prd2;
            }catch(Exception ex){

            }
            
        }
    }

    @isTest
    private static void handleBeforeUpdate2(){
        User cceUser = [Select Id from User Where Profile.Name = 'CN CCE' and LastName = 'CCE2_DS' limit 1];
        CN_Brand_Owner_Control__c boc = new CN_Brand_Owner_Control__c();
        boc.CN_Brands__c = 'AA';
        boc.CN_Brand_Owner__c = cceUser.Id;
        insert boc;

        Product2 prd = [Select Id From Product2 Where Name = 'TestProduct00001' limit 1];
        prd.CN_Brand__c = 'BB';
        update prd;        
        system.runAs(cceUser){
            Product2 prd2 = [Select Id From Product2 Where Name = 'TestProduct00001' limit 1];
            prd2.CN_SKU_Description_EN__c = 'AA';
            try{
                update prd2;
            }catch(Exception ex){

            }
            
        }
    }
}