objects/CN_Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CN_Brand_Owner_Control__c.object
<CustomObject>
    <fields>
        <fullName>CN_Brand_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Brand_Owner_Control_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Brands__c</fullName>
        <label>Brands</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Brand Owner Control</label>
    <nameField>
        <displayFormat>BOC-{0000000000}</displayFormat>
        <label>Brand Owner Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Owner Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CN_Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_SKU_Description_CN__c</fullName>
        <label>SKU Description CN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_SKU_Description_EN__c</fullName>
        <label>SKU Description EN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CN_Product_Description_Check_Handler.cls
public without sharing class CN_Product_Description_Check_Handler implements Triggers.Handler{
        
    Map<Id,Profile> systemProfiles = new Map<Id,Profile>([Select Id from Profile Where name in ( 'System Integration','System Administrator')]);
    public void handle(){
        
        if(systemProfiles.containskey(userinfo.getProfileId())){
            return;
        }
        
        Map<Id,String> userBrandsMap = new Map<Id,String>();
        for(CN_Brand_Owner_Control__c boc:[Select Id,CN_Brand_Owner__c,CN_Brands__c From CN_Brand_Owner_Control__c Limit 20000]){
            userBrandsMap.put(boc.CN_Brand_Owner__c,boc.CN_Brands__c);
        }        
        system.debug('userBrandsMap==>'+userBrandsMap);

        for(Product2 prd:(List<Product2>)trigger.new){
            Product2 oldPrd = (Product2) trigger.oldMap.get(prd.Id);
            if(prd.CN_SKU_Description_CN__c != oldPrd.CN_SKU_Description_CN__c || prd.CN_SKU_Description_EN__c != oldPrd.CN_SKU_Description_EN__c){
                if(userBrandsMap.containskey(userinfo.getUserId())){
                    if(!userBrandsMap.get(userinfo.getUserId()).contains(prd.CN_Brand__c)){
                        system.debug('here1==>'+prd.CN_Brand__c);
                        prd.addError(system.Label.CN_Product_Desc_Change);
                    }
                }else{
                    system.debug('here2==>'+prd.CN_Brand__c);
                    prd.addError(system.Label.CN_Product_Desc_Change);
                }
            }
        }
        
    }
}