objects/CN_Chef_UT_Item__c.object
<CustomObject>
    <fields>
        <fullName>CN_Chefs_Assigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chefs Assigned</label>
        <referenceTo>CN_Chefs_Assigned__c</referenceTo>
        <relationshipLabel>Chef UT Items</relationshipLabel>
        <relationshipName>Chef_UT_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chef UT Item</label>
    <nameField>
        <displayFormat>CUI-{0000000000}</displayFormat>
        <label>Chef UT Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chef UT Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Chefs_Assigned__c.object
<CustomObject>
    <fields>
        <fullName>CN_Chef_Work_End_Date__c</fullName>
        <label>Chef Work End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Chef_Work_Start_Date__c</fullName>
        <label>Chef Work Start Date</label>
        <type>Date</type>
    </fields>
    <label>Chefs Assigned</label>
    <nameField>
        <displayFormat>CA-{0000000000}</displayFormat>
        <label>Chefs Assigned ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chefs Assigneds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Chefs_Assigned_Chef_UT_Item_Handler.cls
/**************************************************************************************************
 * Name           : CN_Chefs_Assigned_Chef_UT_Item_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Qiu Chen
 * Create Date    : 2021-12-28
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_Chefs_Assigned_Chef_UT_Item_Handler implements Triggers.Handler {
    public void handle() {
        if(Trigger.isAfter && Trigger.isInsert) {
            handleAfterInsert();
        }
        if(Trigger.isAfter && Trigger.isUpdate) {
            handleAfterUpdate();
        }
        if(Trigger.isBefore && Trigger.isDelete) {
            handleBeforeDelete();
        }
        if(Trigger.isAfter && Trigger.isUndelete) {
            handleAfterInsert();
        }
    }

    public void handleBeforeDelete() {
        CN_Chefs_Assigned_Chef_UT_Item_Biz biz = new CN_Chefs_Assigned_Chef_UT_Item_Biz();
        List<CN_Chefs_Assigned__c> caList = new List<CN_Chefs_Assigned__c>();
        for(CN_Chefs_Assigned__c ca: (List<CN_Chefs_Assigned__c>)Trigger.old) {
            if(!'OFF'.equals(ca.CN_Self_Work_Type__c)) {
                caList.add(ca);
            }
        }
        if(caList.size() > 0) {
            biz.cleanChefUTItems(caList);
        }
    }

    public void handleAfterInsert() {
        CN_Chefs_Assigned_Chef_UT_Item_Biz biz = new CN_Chefs_Assigned_Chef_UT_Item_Biz();
        List<CN_Chefs_Assigned__c> caList = new List<CN_Chefs_Assigned__c>();
        for(CN_Chefs_Assigned__c ca: (List<CN_Chefs_Assigned__c>)Trigger.new) {
            if(!'OFF'.equals(ca.CN_Self_Work_Type__c)) {
                caList.add(ca);
            }
        }
        if(caList.size() > 0) {
            List<CN_Chef_UT_Item__c> cuiList = biz.generateChefUTItems(caList);
            if(cuiList.size() > 0) {
                insert cuiList;
            }
        }
    }

    public void handleAfterUpdate() {
        CN_Chefs_Assigned_Chef_UT_Item_Biz biz = new CN_Chefs_Assigned_Chef_UT_Item_Biz();
        List<CN_Chefs_Assigned__c> caList = new List<CN_Chefs_Assigned__c>();
        for(CN_Chefs_Assigned__c ca: (List<CN_Chefs_Assigned__c>)Trigger.new) {
            CN_Chefs_Assigned__c oldCa = (CN_Chefs_Assigned__c)Trigger.oldMap.get(ca.Id);
            if(!'OFF'.equals(ca.CN_Self_Work_Type__c) && (oldCa.CN_Chef_Work_Start_Date__c != ca.CN_Chef_Work_Start_Date__c || oldCa.CN_Chef_Work_End_Date__c != ca.CN_Chef_Work_End_Date__c)) {
                caList.add(ca);
            }
        }
        if(caList.size() > 0) {
            biz.cleanChefUTItems(caList);
            List<CN_Chef_UT_Item__c> cuiList = biz.generateChefUTItems(caList);
            if(cuiList.size() > 0) {
                insert cuiList;
            }
        }
    }
}