objects/CN_Chef_Request__c.object
<CustomObject>
    <fields>
        <fullName>CN_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Chef Request</label>
    <nameField>
        <displayFormat>CDR-{0000000000}</displayFormat>
        <label>Chef Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chef Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Chefs_Assigned__c.object
<CustomObject>
    <fields>
        <fullName>CN_Chef_Request__c</fullName>
        <label>Chef Request</label>
        <referenceTo>CN_Chef_Request__c</referenceTo>
        <relationshipLabel>Chefs Assigneds</relationshipLabel>
        <relationshipName>Chefs_Assigneds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Chef_Role__c</fullName>
        <label>Chef Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Leading Chef</fullName>
                </value>
                <value>
                    <fullName>Supporting Chef</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Chef_Self_Confirm_Time__c</fullName>
        <label>Chef Self Confirm Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CN_Chef_Work_End_Date__c</fullName>
        <label>Chef Work End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Chef_Work_Start_Date__c</fullName>
        <label>Chef Work Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Chef__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chef</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>CN Chef,CN Chef Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Chefs_Assigneds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Confirmed__c</fullName>
        <formula>CN_Chef_Request__r.CN_Confirmed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Chefs Assigned</label>
    <nameField>
        <displayFormat>CA-{0000000000}</displayFormat>
        <label>Chefs Assigned ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chefs Assigneds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Chef_Request_Chef_Assign_Handler.cls
/**************************************************************************************************
 * Name           : CN_Chef_Request_Chef_Assign_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Qiu Chen
 * Create Date    : 2021-07-27
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_Chef_Request_Chef_Assign_Handler implements Triggers.Handler {

    public void handle() {
        if(Trigger.isAfter && Trigger.isUpdate) {
            handleAfterUpdate();
        }
    }

    public void handleAfterUpdate() {

        List<CN_Chef_Request__c> confirmCRList = new List<CN_Chef_Request__c>();
        List<CN_Chef_Request__c> unConfirmCRList = new List<CN_Chef_Request__c>();

        Id chefRequestChefSelfRTId = Schema.SObjectType.CN_Chef_Request__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_CHEF_REQUEST_CHEF_SELF_RT_API_NAME).getRecordTypeId();
        for(CN_Chef_Request__c cr: (List<CN_Chef_Request__c>)Trigger.new) {
            if(cr.RecordTypeId == chefRequestChefSelfRTId) {
                CN_Chef_Request__c oldCr = (CN_Chef_Request__c)Trigger.oldMap.get(cr.Id);
                if(!oldCr.CN_Confirmed__c && cr.CN_Confirmed__c) {
                    confirmCRList.add(cr);
                } else if(oldCr.CN_Confirmed__c && !cr.CN_Confirmed__c) {
                    unConfirmCRList.add(cr);
                }
            }
        }

        if(confirmCRList.size() > 0) {
            List<CN_Chefs_Assigned__c> caList = generateChefAssignList(confirmCRList);
            if(caList.size() > 0) {
                upsert caList CN_External_Id__c;
            }
        }
        if(unConfirmCRList.size() > 0) {
            List<CN_Chefs_Assigned__c> caList = getDeleteChefAssignList(unConfirmCRList);
            if(caList.size() > 0) {
                delete caList;
            }
        }
    }

    public List<CN_Chefs_Assigned__c> generateChefAssignList(List<CN_Chef_Request__c> confirmCRList) {
        
        List<CN_Chefs_Assigned__c> caList = new List<CN_Chefs_Assigned__c>();

        if(confirmCRList.size() > 0) {
            for(CN_Chef_Request__c cr: confirmCRList) {
                CN_Chefs_Assigned__c ca = new CN_Chefs_Assigned__c();
                ca.CN_Chef_Request__c = cr.Id;
                ca.CN_Chef__c = cr.OwnerId;
                ca.CN_Chef_Role__c = 'Leading Chef';
                ca.CN_Chef_Work_Start_Date__c = cr.CN_Start_Date__c;
                ca.CN_Chef_Work_End_Date__c = cr.CN_End_Date__c;
                ca.CN_External_Id__c = cr.Id + '-' + cr.OwnerId;
                ca.CN_Chef_Self_Confirm_Time__c = Datetime.now();
                caList.add(ca);
            }
        }

        return caList;
    }

    public List<CN_Chefs_Assigned__c> getDeleteChefAssignList(List<CN_Chef_Request__c> unConfirmCRList) {
        
        List<CN_Chefs_Assigned__c> caList = new List<CN_Chefs_Assigned__c>();

        if(unConfirmCRList.size() > 0) {
            Set<Id> crIdSet = new Set<Id>();
            for(CN_Chef_Request__c cr: unConfirmCRList) {
                crIdSet.add(cr.Id);
            }
            if(crIdSet.size() > 0) {
                caList = [SELECT Id, CN_Chef_Request__c FROM CN_Chefs_Assigned__c WHERE CN_Chef_Request__c in: crIdSet];
            }
        }

        return caList;
    }
}