objects/CN_Chefs_Assigned__c.object
<CustomObject>
    <fields>
        <fullName>CN_Is_Chef_Request_Confirmed__c</fullName>
        <formula>CN_Chef_Request__r.CN_Confirmed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Chef Request Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <label>Chefs Assigned</label>
    <nameField>
        <displayFormat>CA-{0000000000}</displayFormat>
        <label>Chefs Assigned ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chefs Assigneds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Chefs_Assigned_Prevent_Delete_Handler.cls
/**************************************************************************************************
 * Name           : CN_Chefs_Assigned_Prevent_Delete_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Qiu Chen
 * Create Date    : 2021-07-28
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_Chefs_Assigned_Prevent_Delete_Handler implements Triggers.Handler{

	public void handle() {
        if(Trigger.isBefore && Trigger.isDelete) {
            handleBeforeDelete();
        }
    }
    public void handleBeforeDelete() {
        for(CN_Chefs_Assigned__c ca : (List<CN_Chefs_Assigned__c>)Trigger.old) {
            if(ca.CN_Is_Chef_Request_Confirmed__c) {
                ca.addError(System.label.CN_Chefs_Assigned_Prevent_Delete_Error_Message);
            }
        }
    }
}