objects/CN_Chef_Request__c.object
<CustomObject>
    <fields>
        <fullName>CN_Is_Deletable__c</fullName>
        <formula>OR(ISPICKVAL(CN_Status__c  , &apos;New&apos;), ISPICKVAL(CN_Status__c  , &apos;Rejected&apos;)) &amp;&amp;  CN_Assigned_Chefs_Count__c = 0 &amp;&amp;  CN_Demo_Report_Count__c = 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Deletable</label>
        <type>Checkbox</type>
    </fields>
    <label>Chef Request</label>
    <nameField>
        <displayFormat>CDR-{0000000000}</displayFormat>
        <label>Chef Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chef Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CN_Chef_Request_Prevent_Delete_Handler.cls
/**************************************************************************************************
 * Name           : CN_Chef_Request_Prevent_Delete_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Dezheng
 * Create Date    : 2021-08-06
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_Chef_Request_Prevent_Delete_Handler implements Triggers.Handler{
    
    public void handle() {
        if(Trigger.isBefore && Trigger.isDelete) {
            handleBeforeDelete();
        }
    }

    public void handleBeforeDelete() {
        for(CN_Chef_Request__c cr: (List<CN_Chef_Request__c>)Trigger.Old) {
            if(!cr.CN_Is_Deletable__c) {
                cr.addError(System.label.CN_Chef_Request_Delete_Error_Message);
            }
        }
    }
}