objects/CN_Document__c.object
<CustomObject>
    <fields>
        <fullName>CN_Account__c</fullName>
        <label>CN Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business License</fullName>
                </value>
                <value>
                    <fullName>Fapiao Information</fullName>
                </value>
                <value>
                    <fullName>Hygiene Certificate</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>New Address Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>D-{000000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Account_Generate_Documents_Handler.cls
/**************************************************************************************************
 * Name           : CN_Account_Generate_Documents_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Du Dezheng
 * Create Date    : 2021-06-09
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_Account_Generate_Documents_Handler implements Triggers.Handler{
	public void handle() {
        if(Trigger.isAfter && Trigger.isInsert) {
            handleAfterInsert();
        }
        if(Trigger.isAfter && Trigger.isUpdate) {
            handleAfterUpdate();
        }
    }
    
    public void handleAfterInsert() {
        Id newDirectRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.CN_Account_RT_API_NAME_NEW_DIRECT).getRecordTypeId();
        List<ID> directAccIDList = new List<ID>();
        for(Account acc : (List<Account>)Trigger.New) {
            if(acc.RecordTypeId == newDirectRTId) {
                directAccIDList.add(acc.Id);
            }
        }
        if(directAccIDList.size() > 0) {
            List<CN_Document__c> docList = new List<CN_Document__c>();
            for(ID accId : directAccIDList){
                docList.addAll(generateDocuments(accId));
            }
            if(docList.size() > 0) {
				insert docList;
            }
        }
    }

    public void handleAfterUpdate() {
        Id editProspectRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.CN_Account_RT_API_NAME_EDIT_Prospect).getRecordTypeId();
        Id editEditRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.CN_Account_RT_API_NAME_EDIT_DIRECT).getRecordTypeId();
        List<ID> directAccIDList = new List<ID>();
        
        for(Account acc : (List<Account>)Trigger.New) {
            Account oldAccount = (Account)Trigger.oldMap.get(acc.Id);
            if(oldAccount.RecordTypeId == editProspectRTId && acc.RecordTypeId == editEditRTId) {
                directAccIDList.add(acc.Id);
            }
        }
        if(directAccIDList.size() > 0) {
            List<CN_Document__c> docList = new List<CN_Document__c>();
            for(ID accId : directAccIDList){
                docList.addAll(generateDocuments(accId));
            }
            if(docList.size() > 0) {
				insert docList;
            }
        }
    }

    public List<CN_Document__c> generateDocuments(Id accId) {
        List<String> docTypeList = new List<String>();
        docTypeList.add(Constants.CN_DOCUMENT_TYPE_BUSINESS_LICENSE);
        docTypeList.add(Constants.CN_DOCUMENT_TYPE_FAPIAO_INFORMATION);
        docTypeList.add(Constants.CN_DOCUMENT_TYPE_HYGIENE_CERTIFICATE);
        docTypeList.add(Constants.CN_DOCUMENT_TYPE_CONTRACT);
        
        List<CN_Document__c> docList = new List<CN_Document__c>();
        for(String docType : docTypeList){
            CN_Document__c doc = new CN_Document__c();
            doc.CN_Account__c = accId;
            doc.CN_Document_Type__c = docType;
            docList.add(doc);
        }
        return docList;
    }
}