objects/CN_Promotion_Member__c.object
<CustomObject>
    <fields>
        <fullName>CN_Is_Promotion_Planned__c</fullName>
        <formula>CN_Promotion_Status__c = &quot;Planned&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Promotion Planned</label>
        <type>Checkbox</type>
    </fields>
    <label>Promotion Member</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Promotion Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CN_PromotionM_Prevent_Delete_Handler.cls
/**************************************************************************************************
 * Name           : CN_PromotionM_Prevent_Delete_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Qiu Chen
 * Create Date    : 2021-08-25
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_PromotionM_Prevent_Delete_Handler implements Triggers.Handler {
    
    public void handle() {
        if(Trigger.isBefore && Trigger.isDelete) {
            handleBeforeDelete();
        }
    }

    public void handleBeforeDelete() {
        for(CN_Promotion_Member__c promotionLMember: (List<CN_Promotion_Member__c>)Trigger.Old) {
            if(!promotionLMember.CN_Is_Promotion_Planned__c) {
                promotionLMember.addError(System.label.CN_Promotion_Prevent_Delete);
            }
        }
    }
}