objects/CN_Promotion_Member__c.object
<CustomObject>
    <fields>
        <fullName>CN_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Promotion Member</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Promotion Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Quote_To_Promotion__c.object
<CustomObject>
    <fields>
        <fullName>CN_Promotion_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promotion Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CN_Promotion_Member__c.CN_IsPublished__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CN_Promotion_Member__c</referenceTo>
        <relationshipLabel>Quote To Promotions</relationshipLabel>
        <relationshipName>Quote_To_Promotions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote To Promotions</relationshipLabel>
        <relationshipName>Quote_To_Promotions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote To Promotion</label>
    <nameField>
        <displayFormat>QTP-{000000}</displayFormat>
        <label>Quote To Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote To Promotions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>CN_Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>CN_Approval_Status_Required__c</fullName>
        <label>Approval Status Required</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reject</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Approve_Complete_Target__c</fullName>
        <label>Approve Complete Target</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_Approver_Id_List__c</fullName>
        <label>Approver Id List</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Approver_Required__c</fullName>
        <label>Approver Required</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Channel_Price__c</fullName>
        <label>ChannelPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Commets_for_Approver__c</fullName>
        <label>Comments for Approver</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Condition_Table_API__c</fullName>
        <defaultValue>&quot;A005&quot;</defaultValue>
        <label>Condition Table</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Condition_Type_API__c</fullName>
        <defaultValue>&quot;RB00&quot;</defaultValue>
        <label>Condition Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Customer_Acceptance__c</fullName>
        <label>Customer Acceptance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Denied_Reason__c</fullName>
        <label>Denied Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Discount_Price__c</fullName>
        <label>Discount Price</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Finance_Acceptance__c</fullName>
        <label>Finance Acceptance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_From_Splited__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CN From Splited</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Is_Approval_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Approval Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Max_Discount_Price__c</fullName>
        <label>Max Discount Price</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Minimum_Price__c</fullName>
        <label>Minimum Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Origin_PDF__c</fullName>
        <label>Orign/原产国</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Promo_Price_P1__c</fullName>
        <label>Promo Price P1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Promo_Price_P2__c</fullName>
        <label>Promo Price P2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Promo_Price_P3__c</fullName>
        <label>Promo Price P3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Promo_Price_P4__c</fullName>
        <label>Promo Price P4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Promotion_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Member</label>
        <referenceTo>CN_Promotion_Member__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Promotion_Price__c</fullName>
        <label>Promotion Price</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_QTY_PER_CTN_PDF__c</fullName>
        <label>QTY PER CTN/箱规</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Rate_Unit_API__c</fullName>
        <defaultValue>&quot;%&quot;</defaultValue>
        <label>Rate Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Tax__c</fullName>
        <label>Tax</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Quote_Split_LC_Ctrl.cls
public class CN_Quote_Split_LC_Ctrl {
    
    @AuraEnabled
    public static String splitQuote(String QuoteId){
        system.debug('QuoteId==>'+QuoteId);
        //clone(false,true,false,false)         
        //name,status??
        Quote Quote = [Select Id,Name,AccountId,OpportunityId,OwnerId,
                       CN_Effective_Date__c,ExpirationDate,Status,
                       GrandTotal,Pricebook2Id,RecordTypeId
                       From Quote Where Id = :QuoteId];
        List<QuoteLineItem> Items = [Select Id,
                                     CN_Approval_Status__c,CN_Approval_Status_Required__c,CN_Approve_Complete_Target__c,
                                     CN_Approver_Id_List__c,CN_Approver_Required__c,CN_Channel_Price__c,CN_Commets_for_Approver__c,
                                     CN_Condition_Table_API__c,CN_Condition_Type_API__c,CreatedById,
                                     CN_Customer_Acceptance__c,ServiceDate,CN_Denied_Reason__c,Discount,
                                     CN_Discount_Price__c,CN_Finance_Acceptance__c,
                                     CN_Is_Approval_Completed__c,LastModifiedById,Description,
                                     CN_List_Price__c,ListPrice,CN_Max_Discount_Price__c,CN_Minimum_Price__c,
                                     Product2Id,CN_Promo_Price_P1__c,CN_Promo_Price_P2__c,CN_Promo_Price_P3__c,
                                     CN_Promo_Price_P4__c,CN_Promotion_Member__c,CN_Promotion_Price__c,
                                     Quantity,QuoteId,CN_Rate_Unit_API__c,UnitPrice,Subtotal,CN_Tax__c,TotalPrice,
                                     PricebookEntryId,cn_qty_per_ctn_pdf__c,cn_origin_pdf__c                                     
                                     From QuoteLineItem 
                                     Where QuoteId = :QuoteId
                                     And CN_Is_Approval_Completed__c = true];
        if(Items.size() == 0){
            throw new AuraHandledException(System.Label.CN_Quote_No_items_Msg);
        }
        
        Savepoint sp = Database.setSavepoint();
        try{ 
            
            Quote newQuote = Quote.clone(false,true,false,false);
            newQuote.Name = '[Split] - '+Quote.Name;            
            newQuote.Status = 'Approved';
            newQuote.CN_Source_Quote__c = Quote.Id;                         
            insert newQuote;
            system.debug('newQuote==>'+newQuote);
                        
            List<QuoteLineItem> newItems = new List<QuoteLineItem>();
            for(QuoteLineItem item:Items){
                QuoteLineItem newItem = item.clone(false,true,false,false);
                newItem.QuoteId = newQuote.Id;               
                newItem.CN_External_Id__c = null;
                newItem.CN_From_Splited__c = true;
                newItems.add(newItem);
            }            
            system.debug('newItems==>'+newItems);
            insert newItems;
            
            List<CN_Quote_To_Promotion__c> newQTPs = new List<CN_Quote_To_Promotion__c>();
            for(CN_Quote_To_Promotion__c qtp :[SELECT Id,CN_Promotion_Member__c,CN_Quote__c FROM CN_Quote_To_Promotion__c WHERE CN_Quote__c =: QuoteId]){
                CN_Quote_To_Promotion__c newQTP = new CN_Quote_To_Promotion__c();
                newQTP.CN_Promotion_Member__c = qtp.CN_Promotion_Member__c;
                newQTP.CN_Quote__c = newQuote.Id;
                newQTPs.add(newQTP);
            }
            if(newQTPs.size()>0){
                insert newQTPs;
            }
            
            Constants.CN_QUOTEITEM_PREVENT_DELETE_HANDLER_TRIGGER_ON = false;
            delete Items;
            
            return URL.getSalesforceBaseURL().toExternalForm()+'/'+newQuote.Id;
        }catch(Exception ex){
            Database.rollback(sp);
            throw new AuraHandledException('Split error:'+ex.getMessage());
            
        }
        
    }
}