objects/CN_Promotion__c.object
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Promotion_Member__c.object
<CustomObject>
    <fields>
        <fullName>CN_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotion Members</relationshipLabel>
        <relationshipName>Promotion_Members1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_IsPublished__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPublished</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Promotion_End_Date__c</fullName>
        <formula>CN_Promotion__r.CN_End_Date__c</formula>
        <label>Promotion End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Promotion_Start_Date__c</fullName>
        <formula>CN_Promotion__r.CN_Start_Date__c</formula>
        <label>Promotion Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Promotion_Status__c</fullName>
        <formula>TEXT(CN_Promotion__r.CN_Status__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Promotion Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>CN_Promotion__c</referenceTo>
        <relationshipLabel>Promotion Members</relationshipLabel>
        <relationshipName>Promotion_Members2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion Member</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Promotion Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_Quote_To_Promotion__c.object
<CustomObject>
    <fields>
        <fullName>CN_Promotion_End_Date__c</fullName>
        <formula>CN_Promotion_Member__r.CN_Promotion_End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Promotion End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Promotion_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promotion Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CN_Promotion_Member__c.CN_IsPublished__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CN_Promotion_Member__c</referenceTo>
        <relationshipLabel>Quote To Promotions</relationshipLabel>
        <relationshipName>Quote_To_Promotions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Promotion_Start_Date__c</fullName>
        <formula>CN_Promotion_Member__r.CN_Promotion__r.CN_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Promotion Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CN_Promotion_Status__c</fullName>
        <formula>TEXT( CN_Promotion_Member__r.CN_Promotion__r.CN_Status__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Promotion Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote To Promotions</relationshipLabel>
        <relationshipName>Quote_To_Promotions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote To Promotion</label>
    <nameField>
        <displayFormat>QTP-{000000}</displayFormat>
        <label>Quote To Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote To Promotions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>CN_Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Quote_Generate_Quote_Prom_Handler.cls
/**************************************************************************************************
 * Name           : CN_Quote_Generate_Quote_Prom_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Kealsalas Qiu
 * Create Date    : 2021-10-29
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_Quote_Generate_Quote_Prom_Handler implements Triggers.Handler {
    public void handle() {
        if(Trigger.isAfter && Trigger.isInsert) {
            handleAfterInsert();
        }
    }
    public void handleAfterInsert() {
        Id newRTId = Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get(Constants.CN_QUOTE_RT_API_NAME_NEW).getRecordTypeId();

        List<Quote> quoList = new List<Quote>();
        for(Quote quo: (List<Quote>)Trigger.new) {
            if(newRTId == quo.RecordTypeId) {
                quoList.add(quo);
            }
        }
        if(quoList.size() > 0) {
            List<CN_Quote_To_Promotion__c> QTPList = generateQuoteToPromotion(quoList);
            if(QTPList.size() > 0) {
                insert QTPList;
            }
        }
    }

    public List<CN_Quote_To_Promotion__c> generateQuoteToPromotion(List<Quote> quoList) {

        Map<Id, Id> oppIdQuoteIdMap = new Map<Id, Id>();
        Map<Id, Id> accIdQuoteIdMap = new Map<Id, Id>();
        Map<Id, Id> accIdOppIdMap = new Map<Id, Id>();
        Map<Id, Date> quoteIdEffectiveDateMap = new Map<Id, Date>();
        Map<Id, Date> quoteIdExpirationDateMap = new Map<Id,Date>();
        List<CN_Quote_To_Promotion__c> qtpList = new List<CN_Quote_To_Promotion__c>();

        for(Quote quo: quoList) {
            oppIdQuoteIdMap.put(quo.OpportunityId, quo.Id);
            quoteIdEffectiveDateMap.put(quo.Id, quo.CN_Effective_Date__c);
            quoteIdExpirationDateMap.put(quo.Id, quo.ExpirationDate);
            //accIdQuoteIdMap.put(quo.AccountId, quo.Id);
        }

        List<Opportunity> oppList = [SELECT Id, AccountId FROM Opportunity WHERE Id IN: oppIdQuoteIdMap.keySet()];

        for(Opportunity opp: oppList) {
            accIdOppIdMap.put(opp.AccountId, opp.Id);
        }

        List<CN_Promotion_Member__c> promotionMemberList = [SELECT Id, 
                                                                CN_Promotion__c, 
                                                                CN_Promotion_Start_Date__c, 
                                                                CN_Promotion_End_Date__c, 
                                                                CN_Promotion_Status__c, 
                                                                CN_IsPublished__c,
                                                                CN_Account__c
                                                            FROM CN_Promotion_Member__c
                                                            WHERE CN_IsPublished__c = true
                                                                AND CN_Promotion_Status__c = 'Published'
                                                                AND CN_Account__c IN: accIdOppIdMap.keySet()
                                                            ORDER BY CN_Promotion_Start_Date__c DESC LIMIT 50000];
        if(promotionMemberList.size() > 0) {
            for(CN_Promotion_Member__c pm: promotionMemberList) {
                if(accIdOppIdMap.containsKey(pm.CN_Account__c)) {
                    Id OppId = accIdOppIdMap.get(pm.CN_Account__c);
                    if(oppIdQuoteIdMap.containsKey(OppId)) {
                        Id quoId = oppIdQuoteIdMap.get(OppId);
                        Date effectiveDate = quoteIdEffectiveDateMap.get(quoId);
                        Date expirationDate = quoteIdExpirationDateMap.get(quoId);
                        if(pm.CN_Promotion_Start_Date__c <= effectiveDate && expirationDate <= pm.CN_Promotion_End_Date__c) {
                            CN_Quote_To_Promotion__c qtp = new CN_Quote_To_Promotion__c();
                            qtp.CN_Promotion_Member__c = pm.Id;
                            qtp.CN_Quote__c = quoId;
                            qtpList.add(qtp);
                        }
                    }
                }

            }
        }
        return qtpList;
    }
}