objects/CN_Promotion_Member__c.object
<CustomObject>
    <fields>
        <fullName>CN_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Promotion Member</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Promotion Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>CN_Approval_Status_Required__c</fullName>
        <label>Approval Status Required</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reject</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Approve_Complete_Target__c</fullName>
        <label>Approve Complete Target</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_Approver_Id_List__c</fullName>
        <label>Approver Id List</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Approver_Required__c</fullName>
        <label>Approver Required</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Channel_Price__c</fullName>
        <label>ChannelPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Commets_for_Approver__c</fullName>
        <label>Comments for Approver</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Condition_Table_API__c</fullName>
        <defaultValue>&quot;A005&quot;</defaultValue>
        <label>Condition Table</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Condition_Type_API__c</fullName>
        <defaultValue>&quot;RB00&quot;</defaultValue>
        <label>Condition Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Customer_Acceptance__c</fullName>
        <label>Customer Acceptance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Denied_Reason__c</fullName>
        <label>Denied Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Discount_Price__c</fullName>
        <label>Discount Price</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CN_Finance_Acceptance__c</fullName>
        <label>Finance Acceptance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_From_Splited__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CN From Splited</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Is_Approval_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Approval Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CN_Latest_Ready_DateTime__c</fullName>
        <label>Latest Ready DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CN_Latest_Reject_Approve_DateTime__c</fullName>
        <label>Latest Reject/Approve DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CN_List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Max_Discount_Price__c</fullName>
        <label>Max Discount Price</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Promotion_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Member</label>
        <referenceTo>CN_Promotion_Member__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Quote_Status__c</fullName>
        <formula>TEXT(Quote.Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quote Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Rate_Unit_API__c</fullName>
        <defaultValue>&quot;%&quot;</defaultValue>
        <label>Rate Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sync_Error_Message__c</fullName>
        <label>Sync Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CN_Sync_Status__c</fullName>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_Sync_Time__c</fullName>
        <label>Sync Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CN_Unit_of_Measure__c</fullName>
        <label>UoM</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_QuoteItem_Validation_Handler.cls
/**************************************************************************************************
 * Name           : CN_QuoteItem_Validation_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Kealsalas QIu
 * Create Date    : 2021-11-10
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_QuoteItem_Validation_Handler implements Triggers.Handler {
    public void handle() {
        if(Trigger.isBefore && Trigger.isUpdate) {
            handleBeforeUpdate();
        }
    }

    public void handleBeforeUpdate() {
        Map<String, Schema.SObjectField> mfields = Schema.getGlobalDescribe().get('QuoteLineItem').getDescribe().fields.getMap();
        Set<String> allFields = new Set<String>();
        for(String fieldName: mfields.keySet()) {
            Schema.DescribeFieldResult fResult = mfields.get(fieldName).getDescribe();
            if(fResult.isCustom() && !fResult.isCalculated() && fResult.isUpdateable()) {
                allFields.add(fieldName);
            }
        }
        allfields.add('unitprice');
        //allfields.add('quantity');
        allFields.add('description');
        allfields.remove('cn_approval_status_required__c');
        allfields.remove('cn_approve_complete_target__c');
        allfields.remove('cn_approver_id_list__c');
        allfields.remove('cn_approver_required__c');
        allfields.remove('cn_channel_price__c');
        allfields.remove('cn_from_splited__c');
        allfields.remove('cn_commets_for_approver__c');
        allfields.remove('cn_condition_table_api__c');
        allfields.remove('cn_condition_type_api__c');
        allfields.remove('cn_discount_price__c');
        allfields.remove('cn_external_id__c');
        allfields.remove('cn_is_approval_completed__c');
        allfields.remove('cn_latest_ready_datetime__c');
        allfields.remove('cn_list_price__c');
        allfields.remove('cn_max_discount_price__c');
        allfields.remove('cn_rate_unit_api__c');
        allfields.remove('cn_sync_status__c');
        allfields.remove('cn_sync_time__c');
        allfields.remove('cn_sync_error_message__c');
        allfields.remove('cn_unit_of_measure__c');
        allfields.remove('cn_latest_reject_approve_datetime__c');

        for(QuoteLineItem qli: (List<QuoteLineItem>)Trigger.new) {
            Set<String> allFieldsForQli = new Set<String>();
            allFieldsForQli.addAll(allfields);

            Set<String> notAllowChangedFields = new Set<String>();
            QuoteLineItem oldQli = (QuoteLineItem)Trigger.oldMap.get(qli.Id);
            if(Constants.CN_QUOTE_STATUS_NEW.equals(qli.CN_Quote_Status__c)) {
                notAllowChangedFields.add('CN_Customer_Acceptance__c');
                notAllowChangedFields.add('CN_Denied_Reason__c');
                notAllowChangedFields.add('CN_Approval_Status__c');
                notAllowChangedFields.add('CN_Finance_Acceptance__c');
                notAllowChangedFields.add('quantity');
                if(checkFieldsChanged(notAllowChangedFields, qli, oldQli)) {
                    qli.addError(System.Label.CN_QuoteLineItem_Field_Changed_ErrMsg_Quote_New);
                }
            } else if(Constants.CN_QUOTE_STATUS_REJECTED.equals(qli.CN_Quote_Status__c)) {
                if(qli.CN_Latest_Reject_Approve_DateTime__c == oldQli.CN_Latest_Reject_Approve_DateTime__c) {
  
                    if(qli.CN_Approval_Status__c != oldQli.CN_Approval_Status__c && Constants.CN_QUOTEITEM_APPROVAL_STATUS_APPROVED.equals(qli.CN_Approval_Status__c)) {
                        qli.addError(System.Label.CN_QuoteLineItem_Approved_Item_Changed_Status_ErrMsg_Quote_Reject);
                    } else if(qli.CN_Approval_Status__c == oldQli.CN_Approval_Status__c) {
                        if(qli.UnitPrice != oldQli.UnitPrice || qli.CN_Promotion_Member__c != oldQli.CN_Promotion_Member__c) {
                            qli.CN_Approval_Status__c = '';
                            qli.CN_Is_Approval_Completed__c = false;
                        } else {
                            notAllowChangedFields.add('CN_Customer_Acceptance__c');
                            notAllowChangedFields.add('CN_Denied_Reason__c');
                            //notAllowChangedFields.add('CN_Approval_Status__c');
                            notAllowChangedFields.add('CN_Finance_Acceptance__c');
                            notAllowChangedFields.add('CN_Promotion_Member__c');
                           notAllowChangedFields.add('quantity');
                            if(checkFieldsChanged(notAllowChangedFields, qli, oldQli)) {
                                qli.addError(System.Label.CN_QuoteLineItem_Field_Changed_ErrMsg_Quote_Reject);
                            }
                        }
                    }
                }
            } else if(Constants.CN_QUOTE_STATUS_READY.equals(qli.CN_Quote_Status__c)) {
                if(qli.cn_latest_ready_datetime__c == oldQli.cn_latest_ready_datetime__c) {
                    if(checkFieldsChanged(allFieldsForQli, qli, oldQli)) {
                        qli.addError(System.Label.CN_QuoteLineItem_Field_Changed_ErrMsg_Quote_Ready);
                    }
                }
            } else if(Constants.CN_QUOTE_STATUS_SUBMITTED.equals(qli.CN_Quote_Status__c)) {
                allFieldsForQli.remove('cn_approval_status__c');
                if(checkFieldsChanged(allFieldsForQli, qli, oldQli)) {
                    qli.addError(System.Label.CN_QuoteLineItem_Field_Changed_ErrMsg_Quote_SUBMITTED);
                }
            } else if(Constants.CN_QUOTE_STATUS_APPROVED.equals(qli.CN_Quote_Status__c)) {
                if(qli.CN_Latest_Reject_Approve_DateTime__c == oldQli.CN_Latest_Reject_Approve_DateTime__c) {
                    allFieldsForQli.remove('cn_customer_acceptance__c');
                    allFieldsForQli.remove('cn_denied_reason__c');
                    allFieldsForQli.remove('cn_finance_acceptance__c');
                    if(checkFieldsChanged(allFieldsForQli, qli, oldQli)) {
                        qli.addError(System.Label.CN_QuoteLineItem_Field_Changed_ErrMsg_Quote_Approved);
                    }
                }
            }
            if(qli.CN_Is_Approval_Completed__c) {
                if(qli.CN_Latest_Reject_Approve_DateTime__c == oldQli.CN_Latest_Reject_Approve_DateTime__c) {
                    allFieldsForQli.remove('cn_customer_acceptance__c');
                    allFieldsForQli.remove('cn_denied_reason__c');
                    allFieldsForQli.remove('cn_is_approval_completed__c');
                    allFieldsForQli.remove('cn_finance_acceptance__c');
                    if(checkFieldsChanged(allFieldsForQli, qli, oldQli)) {
                        qli.addError(System.Label.CN_QuoteLineItem_Field_Changed_ErrMsg_Approval_Completed);
                    }
                }
            }
        }

    }

    public Boolean checkFieldsChanged(Set<String> fields, QuoteLineItem newQli, QuoteLineItem oldQli) {
        Boolean isChanged = false;
        for(String field: fields) {
            if(newQli.get(field) != oldQli.get(field)) {
                isChanged = true;
                break;
            }
        }
        return isChanged;
    }
}