objects/CN_Sales_Performance__c.object
<CustomObject>
    <fields>
        <fullName>CN_Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Performance</relationshipLabel>
        <relationshipName>Sales_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Material_SAP__c</fullName>
        <description>MATNR</description>
        <label>Material</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Performance</label>
    <nameField>
        <displayFormat>SP-{000000000}</displayFormat>
        <label>Sales Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Performance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CN_SKU_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CN_SP_Populate_Product_Handler_Test.cls
/**************************************************************************************************
 * Name           : CN_SP_Populate_Product_Handler_Test
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Qiu Chen
 * Create Date    : 2021-10-12
 * Modify History : 
 **************************************************************************************************/
@isTest
private class CN_SP_Populate_Product_Handler_Test {

    @TestSetup
    static void makeData(){
        TestDataFactory.makeBaseData();
    }

    @isTest
    private static void CN_SP_Populate_Product_Handler_Test() {
        TestDataFactory testFactory = new TestDataFactory();
        List<Account> accListFactory = testFactory.makeFactoryAccount();

        Id SalesPerforRTId = Schema.SObjectType.CN_Sales_Performance__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_SP_RT_API_NAME_PERFORMANCE).getRecordTypeId();
        List<Product2> SKUList = [SELECT Id, Name, CN_SKU_Code__c FROM Product2];

        Test.startTest();

        CN_Sales_Performance__c sp = new CN_Sales_Performance__c(
            CN_Material_SAP__c = SKUList[0].CN_SKU_Code__c,
            RecordTypeId = SalesPerforRTId,
            CN_Customer__c = accListFactory[0].Id
        );
        insert sp;

        sp.CN_Material_SAP__c = SKUList[1].CN_SKU_Code__c;
        update sp;

        Test.stopTest();
    }
}