objects/CN_Sales_Team__c.object
<CustomObject>
    <fields>
        <fullName>CN_Sync_Status__c</fullName>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <label>Sales Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CN_SalesTeam_Prevent_Delete_Handler.cls
/**************************************************************************************************
 * Name           : CN_SalesTeam_Prevent_Delete_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Du Dezheng
 * Create Date    : 2021-06-18
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_SalesTeam_Prevent_Delete_Handler implements Triggers.Handler{
    
	public void handle() {
        if(Trigger.isBefore && Trigger.isDelete) {
            handleBeforeDelete();
        }
    }
    
    public void handleBeforeDelete() {
        Id salesTeamRTId = Schema.SObjectType.CN_Sales_Team__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_ST_RT_API_NAME).getRecordTypeId();
        for(CN_Sales_Team__c st : (List<CN_Sales_Team__c>)Trigger.Old) {
            if(salesTeamRTId.equals(st.recordTypeId) &&  String.isNotBlank(st.CN_Sync_Status__c)
            ){
                st.addError(system.Label.CN_SalesTeam_Synced_Prevent_Delete);
            }
        }
    }
          
}