objects/CN_Sample_Product__c.object
<CustomObject>
    <fields>
        <fullName>CN_List_Price__c</fullName>
        <formula>IF( 
  
  CN_Sample_Request__r.RecordType.DeveloperName  = &apos;CN_Whole_Pack&apos;, 
  CN_Pricebook_Price__c,
  CN_Sample_Unit_List_Price__c 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>List Price</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Qty_per_Carton__c</fullName>
        <formula>CN_Product__r.CN_Qty_per_Carton__c</formula>
        <label>Qty per Carton</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Quantity_Needed__c</fullName>
        <label>Quantity Needed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CN_SKU_Chinese_Description__c</fullName>
        <formula>CN_Product__r.CN_SKU_Description_CN__c</formula>
        <label>SKU Chinese Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_SKU_English_Description__c</fullName>
        <formula>CN_Product__r.CN_SKU_Description_EN__c</formula>
        <label>SKU English Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sample_Cost__c</fullName>
        <label>Sample Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Sample_Request__c</fullName>
        <label>Sample Request</label>
        <referenceTo>CN_Sample_Request__c</referenceTo>
        <relationshipLabel>Sample Products</relationshipLabel>
        <relationshipName>Sample_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CN_Sample_SKU_Code__c</fullName>
        <formula>CN_Product__r.CN_SKU_Code__c</formula>
        <label>Sample SKU Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Sample_Unit_List_Price__c</fullName>
        <formula>CN_Product__r.CN_Sample_Unit_List_Price__c</formula>
        <label>Sample Unit List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Sample_Unit__c</fullName>
        <formula>CN_Product__r.CN_Standard_Sample_Unit__c</formula>
        <label>Sample Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Unit__c</fullName>
        <formula>if(  ISNULL(CN_Product__r.CN_Sales_Unit__c) || CN_Product__r.CN_Sales_Unit__c = &apos;&apos; ,  CN_Product__r.CN_Base_Unit_of_Measure__c , CN_Product__r.CN_Sales_Unit__c)</formula>
        <label>Unit</label>
        <type>Text</type>
    </fields>
    <label>Sample Product</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Sample Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CN_Sample_Request__c.object
<CustomObject>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>SR-{000000000}</displayFormat>
        <label>Sample Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CN_Sample_Product_Get_LC_Ctrl.cls
global without sharing class CN_Sample_Product_Get_LC_Ctrl {
    global Id sampleRequestId {get; set;}
    global List<CN_Sample_Product__c> spList {get
        {
            List<CN_Sample_Product__c> spList = [SELECT Name,
                                                    CN_Sample_SKU_Code__c,
                                                    CN_SKU_Chinese_Description__c,
                                                    CN_SKU_English_Description__c,
                                                    CN_Qty_per_Carton__c,
                                                    CN_Unit__c,
                                                    CN_List_Price__c,
                                                    CN_Sample_Unit_List_Price__c,
                                                    CN_Quantity_Needed__c,
                                                    CN_Sample_Cost__c,
                                                    CN_Sample_Unit__c
                                             FROM CN_Sample_Product__c
                                             WHERE CN_Sample_Request__c = :sampleRequestId];
        return spList;
        } 
        set;
    }
}