objects/CN_Sales_Performance__c.object
<CustomObject>
    <fields>
        <fullName>CN_Material_SAP__c</fullName>
        <description>MATNR</description>
        <label>Material</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sales Performance</relationshipLabel>
        <relationshipName>Sales_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Performance</label>
    <nameField>
        <displayFormat>SP-{000000000}</displayFormat>
        <label>Sales Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Performance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CN_SKU_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CN_SP_Populate_Product_Handler.cls
/**************************************************************************************************
 * Name           : CN_SP_Populate_Product_Handler
 * Object         : 
 * Requirement    : 
 * Target         : 
 * Refer classes  :
 * Author         : Du Dezheng
 * Create Date    : 2021-09-08
 * Modify History : 
 **************************************************************************************************/
public without sharing class CN_SP_Populate_Product_Handler implements Triggers.Handler{

    Id SalesPerforRTId = Schema.SObjectType.CN_Sales_Performance__c.getRecordTypeInfosByDeveloperName().get(Constants.CN_SP_RT_API_NAME_PERFORMANCE).getRecordTypeId();
    
	public void handle() {
        if(Trigger.isBefore && Trigger.isInsert) {
            handleBeforeInsert();
        }
        if(Trigger.isBefore && Trigger.isUpdate) {
            handleBeforeUpdate();
        }
    }
    
    public void handleBeforeInsert() {
        Set<String> productCodeSet = new Set<String>();
        for(CN_Sales_Performance__c sp : (List<CN_Sales_Performance__c>)Trigger.NEW){
            if(sp.recordTypeId==SalesPerforRTId && String.isNotBlank(sp.CN_Material_SAP__c)){
                productCodeSet.add(sp.CN_Material_SAP__c);
            }
        }
        if(productCodeSet.size()>0){
            populateProduct(productCodeSet);
        }
    }
    
    public void handleBeforeUpdate() {
		Set<String> productCodeSet = new Set<String>();
        for(CN_Sales_Performance__c sp : (List<CN_Sales_Performance__c>)Trigger.NEW){
            if(sp.recordTypeId==SalesPerforRTId && sp.CN_Material_SAP__c != ((CN_Sales_Performance__c)Trigger.OldMap.get(sp.Id)).CN_Material_SAP__c){
                productCodeSet.add(sp.CN_Material_SAP__c);
            }
        }
        if(productCodeSet.size()>0){
            populateProduct(productCodeSet);
        }        
    }

    public void populateProduct(Set<String> productCodeSet){
        Map<String,Id> proCodeProIdMap = new Map<String,Id>();
        List<Product2> proList = [SELECT Id,CN_SKU_Code__c FROM Product2 WHERE CN_SKU_Code__c IN: productCodeSet];
        for(Product2 pro : proList){
            proCodeProIdMap.put(pro.CN_SKU_Code__c,pro.Id);
        }
        for(CN_Sales_Performance__c sp : (List<CN_Sales_Performance__c>)Trigger.New){
            if(sp.recordTypeId==SalesPerforRTId && String.isNotBlank(sp.CN_Material_SAP__c)){
                Id productId = proCodeProIdMap.get(sp.CN_Material_SAP__c);
                sp.CN_Product__c = productId;
            }else if(sp.recordTypeId==SalesPerforRTId){
                sp.CN_Product__c = null;
            }
        } 
    }
}