objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>CN_Customer_Acceptance__c</fullName>
        <label>Customer Acceptance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_List_Price_VAT__c</fullName>
        <label>List Price(VAT)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CN_Product_Code__c</fullName>
        <formula>Product2.CN_SKU_Code__c</formula>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Rate_API__c</fullName>
        <formula>( UnitPrice /  ROUND((CN_List_Price__c*( 1 + VALUE(LEFT(CN_Tax__c,LEN(CN_Tax__c)-1))/100)) ,2)) - 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CN_SKU_Description_CN__c</fullName>
        <formula>Product2.CN_SKU_Description_CN__c</formula>
        <label>Product Description(CN)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_SKU_Description_EN__c</fullName>
        <formula>Product2.CN_SKU_Description_EN__c</formula>
        <label>Product Description(EN)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Selling_Unit__c</fullName>
        <formula>Text(CN_Pricing_Unit__c) &amp;&apos;-&apos; &amp; CN_Unit_of_Measure__c &amp; &apos;   Tax:&apos; &amp;  CN_Tax__c</formula>
        <label>Sales Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CN_Tax__c</fullName>
        <label>Tax</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CN_Quote_Notify_Finance_Template_Ctrl.cls
public class CN_Quote_Notify_Finance_Template_Ctrl {
    public Id QId{get;set;}
    
    public List<QuoteLineItem> getItems(){
        system.debug('QId==>'+QId);
        return [Select Id,CN_Product_Code__c,
                CN_SKU_Description_CN__c,CN_SKU_Description_EN__c,
                UnitPrice,CN_List_Price__c,CN_List_Price_VAT__c,CN_Rate_API__c,CN_Selling_Unit__c,CN_Tax__c      
                From QuoteLineItem 
                Where QuoteId = :QId
                And CN_Customer_Acceptance__c = 'Accepted'];
    }
    
    public String getQuoteURL(){
        String prefix = URL.getSalesforceBaseURL().toExternalForm().replace('https://', '').split('\\.')[0];
        prefix = prefix.removeEnd('--c');
        return 'https://' + prefix.toLowerCase() + '.lightning.force.com/'+QId;
    }
    
    
}